{
    This file is part of the MWA Software Pascal API for OpenSSL .

    The MWA Software Pascal API for OpenSSL is free software: you can redistribute it
    and/or modify it under the terms of the Apache License Version 2.0 (the "License"), and as
    a derived work of the OpenSSL Project (see below for the original licence text).

    You may not use this file except in compliance with the License.  You can obtain a copy
    in the file LICENSE.txt in the source distribution or at https://www.openssl.org/source/license.html.

    The MWA Software Pascal API for OpenSSL is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the License for more details.
}

{$include openssl_defines.inc}

unit openssl_crmferr;

{
  Generated from OpenSSL 3.0.20 Header File crmferr.h - Tue 19 May 14:15:43 BST 2026
}

{$IFNDEF FPC}
{$IFDEF OPENSSL_USE_STATIC_LIBRARY}
{$LINK openssl_crmferr.obj}
{$ENDIF}
{$ENDIF}

interface

uses OpenSSLAPI,openssl_symhacks,openssl_cryptoerr_legacy;


{* Generated by util/mkerr.pl DO NOT EDIT
* Copyright 1995-2021 The OpenSSL Project Authors. All Rights Reserved.
*
* Licensed under the Apache License 2.0 (the "License").  You may not use
* this file except in compliance with the License.  You can obtain a copy
* in the file LICENSE in the source distribution or at
* https://www.openssl.org/source/license.html
}
{$ifndef  OPENSSL_CRMFERR_H}
  {$define OPENSSL_CRMFERR_H}
  {$include openssl_opensslconf.inc}
  {$ifndef  OPENSSL_NO_CRMF}

const
    
    {* CRMF reason codes.
    }
  CRMF_R_BAD_PBM_ITERATIONCOUNT = 100;
  CRMF_R_CRMFERROR = 102;
  CRMF_R_ERROR = 103;
  CRMF_R_ERROR_DECODING_CERTIFICATE = 104;
  CRMF_R_ERROR_DECRYPTING_CERTIFICATE = 105;
  CRMF_R_ERROR_DECRYPTING_SYMMETRIC_KEY = 106;
  CRMF_R_FAILURE_OBTAINING_RANDOM = 107;
  CRMF_R_ITERATIONCOUNT_BELOW_100 = 108;
  CRMF_R_MALFORMED_IV = 101;
  CRMF_R_NULL_ARGUMENT = 109;
  CRMF_R_POPOSKINPUT_NOT_SUPPORTED = 113;
  CRMF_R_POPO_INCONSISTENT_PUBLIC_KEY = 117;
  CRMF_R_POPO_MISSING = 121;
  CRMF_R_POPO_MISSING_PUBLIC_KEY = 118;
  CRMF_R_POPO_MISSING_SUBJECT = 119;
  CRMF_R_POPO_RAVERIFIED_NOT_ACCEPTED = 120;
  CRMF_R_SETTING_MAC_ALGOR_FAILURE = 110;
  CRMF_R_SETTING_OWF_ALGOR_FAILURE = 111;
  CRMF_R_UNSUPPORTED_ALGORITHM = 112;
  CRMF_R_UNSUPPORTED_CIPHER = 114;
  CRMF_R_UNSUPPORTED_METHOD_FOR_CREATING_POPO = 115;
  CRMF_R_UNSUPPORTED_POPO_METHOD = 116;
  {$endif}
{$endif}

implementation

uses Sysutils, variants
  {$ifdef OPENSSL_INTERNAL_NEED_THREADS}
   {$IFNDEF FPC}
     ,System.SyncObjs
     {$IFDEF POSIX}
       ,Posix.Pthread
     {$ELSE}
       ,Windows
     {$ENDIF}
   {$ELSE}
     ,SyncObjs
   {$ENDIF}
  {$endif}
  ,Classes, OpenSSLExceptionHandlers;

  {$if not declared(__FILE__)}
  const
    {$ifdef FPC}
    __FILE__ = {$include %FILE%};
    {$else}
    __FILE__ = '$(INPUTFILENAME)';
    {$endif}
  {$ifend}
  {$if not declared(__LINE__)}
  const
    __LINE__ = 0;
  {$ifend}
  {$if not declared(OPENSSL_FILE)}
  const
    OPENSSL_FILE = __FILE__;
  {$ifend}
  {$if not declared(OPENSSL_LINE)}
  const
    OPENSSL_LINE  = 0;
  {$ifend}

{$ifndef OPENSSL_STATIC_LINK_MODEL}
procedure Load;
begin
  {$define EMPTY_LOAD_FUNCTION}
end;

procedure Unload;
begin
end;

{$endif} {OPENSSL_STATIC_LINK_MODEL}

initialization

{$ifndef OPENSSL_STATIC_LINK_MODEL}
{$ifndef EMPTY_LOAD_FUNCTION}
Register_SSLloader(@Load);
{$endif}
Register_SSLUnloader(@Unload);
{$endif}
{$if declared(LegacySupport_Initialization)}
LegacySupport_Initialization;
{$ifend}

finalization

{$if declared(LegacySupport_Finalization)}
LegacySupport_Finalization;
{$ifend}

end.



