{
    This file is part of the MWA Software Pascal API for OpenSSL .

    The MWA Software Pascal API for OpenSSL is free software: you can redistribute it
    and/or modify it under the terms of the Apache License Version 2.0 (the "License"), and as
    a derived work of the OpenSSL Project (see below for the original licence text).

    You may not use this file except in compliance with the License.  You can obtain a copy
    in the file LICENSE.txt in the source distribution or at https://www.openssl.org/source/license.html.

    The MWA Software Pascal API for OpenSSL is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the License for more details.
}

{$include openssl_defines.inc}

unit openssl_asn1t;

{
  Generated from OpenSSL 3.6.2 Header File asn1t.h - Tue 19 May 14:29:22 BST 2026
}

{$IFNDEF FPC}
{$IFDEF OPENSSL_USE_STATIC_LIBRARY}
{$LINK openssl_asn1t.obj}
{$ENDIF}
{$ENDIF}

interface

uses OpenSSLAPI,openssl_types,openssl_stack,openssl_e_os2,openssl_asn1;


{* WARNING: do not edit!
* Generated by Makefile from include/openssl/asn1t.h.in
*
* Copyright 2000-2021 The OpenSSL Project Authors. All Rights Reserved.
*
* Licensed under the Apache License 2.0 (the "License").  You may not use
* this file except in compliance with the License.  You can obtain a copy
* in the file LICENSE in the source distribution or at
* https://www.openssl.org/source/license.html
}
{ clang-format off }
{ clang-format on }
{$ifndef  OPENSSL_ASN1T_H}
  {$define OPENSSL_ASN1T_H}
  {$include openssl_macros.inc}
  {$ifndef  OPENSSL_NO_DEPRECATED_3_0}
    {$define HEADER_ASN1T_H}
  {$endif}
  {$ifdef OPENSSL_BUILD_SHLIBCRYPTO}
    {$undef  OPENSSL_EXTERN}

const
  OPENSSL_EXTERN = OPENSSL_EXPORT;
  {$endif}

const
  { ASN1 template defines, structures and functions }
  {-
  * These are the possible values for the itype field of the
  * ASN1_ITEM structure and determine how it is interpreted.
  *
  * For PRIMITIVE types the underlying type
  * determines the behaviour if items is NULL.
  *
  * Otherwise templates must contain a single
  * template and the type is treated in the
  * same way as the type specified in the template.
  *
  * For SEQUENCE types the templates field points
  * to the members, the size field is the
  * structure size.
  *
  * For CHOICE types the templates field points
  * to each possible member (typically a union)
  * and the 'size' field is the offset of the
  * selector.
  *
  * The 'funcs' field is used for application-specific
  * data and functions.
  *
  * The EXTERN type uses a new style d2i/i2d.
  * The new style should be used where possible
  * because it avoids things like the d2i IMPLICIT
  * hack.
  *
  * MSTRING is a multiple string type, it is used
  * for a CHOICE of character strings where the
  * actual strings all occupy an ASN1_STRING
  * structure. In this case the 'utype' field
  * has a special meaning, it is used as a mask
  * of acceptable types using the B_ASN1 constants.
  *
  * NDEF_SEQUENCE is the same as SEQUENCE except
  * that it will use indefinite length constructed
  * encoding if requested.
  *
  }
  ASN1_ITYPE_PRIMITIVE = $0;
  ASN1_ITYPE_SEQUENCE = $1;
  ASN1_ITYPE_CHOICE = $2;
  { unused value                          0x3 }
  ASN1_ITYPE_EXTERN = $4;
  ASN1_ITYPE_MSTRING = $5;
  ASN1_ITYPE_NDEF_SEQUENCE = $6;
  {# define  ASN1_ADB_ptr(iptr) ((const ASN1_ADB *)((iptr)()))}
  (*# define  ASN1_ITEM_start(itname) const ASN1_ITEM *itname ##_it(void) { static const ASN1_ITEM local_it = {*)
  {# define  static_ASN1_ITEM_start(itname) static ASN1_ITEM_start(itname)}
  (*# define  ASN1_ITEM_end(itname) } ; return &local_it; }*)
  {# define  ASN1_ITEM_TEMPLATE(tname) static const ASN1_TEMPLATE tname ##_item_tt}
  {# define  ASN1_ITEM_TEMPLATE_END(tname) ; ASN1_ITEM_start(tname) ASN1_ITYPE_PRIMITIVE, -1, &tname ##_item_tt, 0, NULL, 0, #tname 
ASN1_ITEM_end(tname)}
  {# define  static_ASN1_ITEM_TEMPLATE_END(tname) ; static_ASN1_ITEM_start(tname) ASN1_ITYPE_PRIMITIVE, -1, &tname ##_item_tt, 0, 
NULL, 0, #tname ASN1_ITEM_end(tname)}
  {# define  ASN1_SEQUENCE(tname) static const ASN1_TEMPLATE tname ##_seq_tt[]}
  {# define  ASN1_SEQUENCE_END(stname) ASN1_SEQUENCE_END_name(stname, stname)} { Blacklisted Macro}
  {# define  static_ASN1_SEQUENCE_END(stname) static_ASN1_SEQUENCE_END_name(stname, stname)} { Blacklisted Macro}
  {# define  ASN1_SEQUENCE_END_name(stname,tname) ; ASN1_ITEM_start(tname) ASN1_ITYPE_SEQUENCE, V_ASN1_SEQUENCE, tname ##_seq_tt, 
sizeof(tname ##_seq_tt) / sizeof(ASN1_TEMPLATE), NULL, sizeof(stname), #tname ASN1_ITEM_end(tname)}
  {# define  static_ASN1_SEQUENCE_END_name(stname,tname) ; static_ASN1_ITEM_start(tname) ASN1_ITYPE_SEQUENCE, V_ASN1_SEQUENCE, tname 
##_seq_tt, sizeof(tname ##_seq_tt) / sizeof(ASN1_TEMPLATE), NULL, sizeof(stname), #stname ASN1_ITEM_end(tname)}
  {# define  ASN1_NDEF_SEQUENCE(tname) ASN1_SEQUENCE(tname)} { Blacklisted Macro}
  {# define  ASN1_NDEF_SEQUENCE_cb(tname,cb) ASN1_SEQUENCE_cb(tname, cb)} { Blacklisted Macro}
  (*# define  ASN1_SEQUENCE_cb(tname,cb) static const ASN1_AUX tname ##_aux = { NULL, 0, 0, 0, cb, 0, NULL }; ASN1_SEQUENCE(tname)*)
  (*# define  ASN1_SEQUENCE_const_cb(tname,const_cb) static const ASN1_AUX tname ##_aux = { NULL, ASN1_AFLG_CONST_CB, 0, 0, NULL, 
0, const_cb }; ASN1_SEQUENCE(tname)*)
  (*# define  ASN1_SEQUENCE_cb_const_cb(tname,cb,const_cb) static const ASN1_AUX tname ##_aux = { NULL, ASN1_AFLG_CONST_CB, 0, 0, 
cb, 0, const_cb }; ASN1_SEQUENCE(tname)*)
  (*# define  ASN1_SEQUENCE_ref(tname,cb) static const ASN1_AUX tname ##_aux = { NULL, ASN1_AFLG_REFCOUNT, offsetof(tname, references),
 offsetof(tname, lock), cb, 0, NULL }; ASN1_SEQUENCE(tname)*)
  (*# define  ASN1_SEQUENCE_enc(tname,enc,cb) static const ASN1_AUX tname ##_aux = { NULL, ASN1_AFLG_ENCODING, 0, 0, cb, offsetof(tname,
 enc), NULL }; ASN1_SEQUENCE(tname)*)
  {# define  ASN1_NDEF_SEQUENCE_END(tname) ; ASN1_ITEM_start(tname) ASN1_ITYPE_NDEF_SEQUENCE, V_ASN1_SEQUENCE, tname ##_seq_tt, sizeof(tname 
##_seq_tt) / sizeof(ASN1_TEMPLATE), NULL, sizeof(tname), #tname ASN1_ITEM_end(tname)}
  {# define  static_ASN1_NDEF_SEQUENCE_END(tname) ; static_ASN1_ITEM_start(tname) ASN1_ITYPE_NDEF_SEQUENCE, V_ASN1_SEQUENCE, tname 
##_seq_tt, sizeof(tname ##_seq_tt) / sizeof(ASN1_TEMPLATE), NULL, sizeof(tname), #tname ASN1_ITEM_end(tname)}
  {# define  ASN1_SEQUENCE_END_enc(stname,tname) ASN1_SEQUENCE_END_ref(stname, tname)} { Blacklisted Macro}
  {# define  ASN1_SEQUENCE_END_cb(stname,tname) ASN1_SEQUENCE_END_ref(stname, tname)} { Blacklisted Macro}
  {# define  static_ASN1_SEQUENCE_END_cb(stname,tname) static_ASN1_SEQUENCE_END_ref(stname, tname)} { Blacklisted Macro}
  {# define  ASN1_SEQUENCE_END_ref(stname,tname) ; ASN1_ITEM_start(tname) ASN1_ITYPE_SEQUENCE, V_ASN1_SEQUENCE, tname ##_seq_tt, sizeof(tname 
##_seq_tt) / sizeof(ASN1_TEMPLATE), &tname ##_aux, sizeof(stname), #tname ASN1_ITEM_end(tname)}
  {# define  static_ASN1_SEQUENCE_END_ref(stname,tname) ; static_ASN1_ITEM_start(tname) ASN1_ITYPE_SEQUENCE, V_ASN1_SEQUENCE, tname 
##_seq_tt, sizeof(tname ##_seq_tt) / sizeof(ASN1_TEMPLATE), &tname ##_aux, sizeof(stname), #stname ASN1_ITEM_end(tname)}
  {# define  ASN1_NDEF_SEQUENCE_END_cb(stname,tname) ; ASN1_ITEM_start(tname) ASN1_ITYPE_NDEF_SEQUENCE, V_ASN1_SEQUENCE, tname ##_seq_tt,
 sizeof(tname ##_seq_tt) / sizeof(ASN1_TEMPLATE), &tname ##_aux, sizeof(stname), #stname ASN1_ITEM_end(tname)}
  {# define  ASN1_CHOICE(tname) static const ASN1_TEMPLATE tname ##_ch_tt[]}
  (*# define  ASN1_CHOICE_cb(tname,cb) static const ASN1_AUX tname ##_aux = { NULL, 0, 0, 0, cb, 0, NULL }; ASN1_CHOICE(tname)*)
  {# define  ASN1_CHOICE_END(stname) ASN1_CHOICE_END_name(stname, stname)} { Blacklisted Macro}
  {# define  static_ASN1_CHOICE_END(stname) static_ASN1_CHOICE_END_name(stname, stname)} { Blacklisted Macro}
  {# define  ASN1_CHOICE_END_name(stname,tname) ASN1_CHOICE_END_selector(stname, tname, type)} { Blacklisted Macro}
  {# define  static_ASN1_CHOICE_END_name(stname,tname) static_ASN1_CHOICE_END_selector(stname, tname, type)} { Blacklisted Macro}
  {# define  ASN1_CHOICE_END_selector(stname,tname,selname) ; ASN1_ITEM_start(tname) ASN1_ITYPE_CHOICE, offsetof(stname, selname),
 tname ##_ch_tt, sizeof(tname ##_ch_tt) / sizeof(ASN1_TEMPLATE), NULL, sizeof(stname), #stname ASN1_ITEM_end(tname)}
  {# define  static_ASN1_CHOICE_END_selector(stname,tname,selname) ; static_ASN1_ITEM_start(tname) ASN1_ITYPE_CHOICE, offsetof(stname,
 selname), tname ##_ch_tt, sizeof(tname ##_ch_tt) / sizeof(ASN1_TEMPLATE), NULL, sizeof(stname), #stname ASN1_ITEM_end(tname)}
  {# define  ASN1_CHOICE_END_cb(stname,tname,selname) ; ASN1_ITEM_start(tname) ASN1_ITYPE_CHOICE, offsetof(stname, selname), tname 
##_ch_tt, sizeof(tname ##_ch_tt) / sizeof(ASN1_TEMPLATE), &tname ##_aux, sizeof(stname), #stname ASN1_ITEM_end(tname)}
  (*# define  ASN1_EX_TEMPLATE_TYPE(flags,tag,name,type) { (flags), (tag), 0, #name, ASN1_ITEM_ref(type) }*)
  (*# define  ASN1_EX_TYPE(flags,tag,stname,field,type) { (flags), (tag), offsetof(stname, field), #field, ASN1_ITEM_ref(type) }*)
  {# define  ASN1_IMP_EX(stname,field,type,tag,ex) ASN1_EX_TYPE(ASN1_TFLG_IMPLICIT | (ex), tag, stname, field, type)} {Macro Return Type unknown at line no 243}
  {# define  ASN1_EXP_EX(stname,field,type,tag,ex) ASN1_EX_TYPE(ASN1_TFLG_EXPLICIT | (ex), tag, stname, field, type)} {Macro Return Type unknown at line no 246}
  (*# define  ASN1_ADB_OBJECT(tblname) { ASN1_TFLG_ADB_OID, -1, 0, #tblname, tblname ##_adb }*)
  (*# define  ASN1_ADB_INTEGER(tblname) { ASN1_TFLG_ADB_INT, -1, 0, #tblname, tblname ##_adb }*)
  {# define  ASN1_SIMPLE(stname,field,type) ASN1_EX_TYPE(0, 0, stname, field, type)} {Macro Return Type unknown at line no 255}
  {# define  ASN1_EMBED(stname,field,type) ASN1_EX_TYPE(ASN1_TFLG_EMBED, 0, stname, field, type)} {Macro Return Type unknown at line no 257}
  {# define  ASN1_OPT(stname,field,type) ASN1_EX_TYPE(ASN1_TFLG_OPTIONAL, 0, stname, field, type)} {Macro Return Type unknown at line no 260}
  {# define  ASN1_OPT_EMBED(stname,field,type) ASN1_EX_TYPE(ASN1_TFLG_OPTIONAL | ASN1_TFLG_EMBED, 0, stname, field, type)} {Macro Return Type unknown at line no 261}
  {# define  ASN1_IMP(stname,field,type,tag) ASN1_IMP_EX(stname, field, type, tag, 0)} {Macro Return Type unknown at line no 264}
  {# define  ASN1_IMP_EMBED(stname,field,type,tag) ASN1_IMP_EX(stname, field, type, tag, ASN1_TFLG_EMBED)} {Macro Return Type unknown at line no 265}
  {# define  ASN1_IMP_OPT(stname,field,type,tag) ASN1_IMP_EX(stname, field, type, tag, ASN1_TFLG_OPTIONAL)} {Macro Return Type unknown at line no 268}
  {# define  ASN1_IMP_OPT_EMBED(stname,field,type,tag) ASN1_IMP_EX(stname, field, type, tag, ASN1_TFLG_OPTIONAL | ASN1_TFLG_EMBED)} {Macro Return Type unknown at line no 269}
  {# define  ASN1_EXP(stname,field,type,tag) ASN1_EXP_EX(stname, field, type, tag, 0)} {Macro Return Type unknown at line no 273}
  {# define  ASN1_EXP_EMBED(stname,field,type,tag) ASN1_EXP_EX(stname, field, type, tag, ASN1_TFLG_EMBED)} {Macro Return Type unknown at line no 274}
  {# define  ASN1_EXP_OPT(stname,field,type,tag) ASN1_EXP_EX(stname, field, type, tag, ASN1_TFLG_OPTIONAL)} {Macro Return Type unknown at line no 275}
  {# define  ASN1_EXP_OPT_EMBED(stname,field,type,tag) ASN1_EXP_EX(stname, field, type, tag, ASN1_TFLG_OPTIONAL | ASN1_TFLG_EMBED)} {Macro Return Type unknown at line no 276}
  {# define  ASN1_SEQUENCE_OF(stname,field,type) ASN1_EX_TYPE(ASN1_TFLG_SEQUENCE_OF, 0, stname, field, type)} {Macro Return Type unknown at line no 279}
  {# define  ASN1_SEQUENCE_OF_OPT(stname,field,type) ASN1_EX_TYPE(ASN1_TFLG_SEQUENCE_OF | ASN1_TFLG_OPTIONAL, 0, stname, field, type)} {Macro Return Type unknown at line no 283}
  {# define  ASN1_SET_OF(stname,field,type) ASN1_EX_TYPE(ASN1_TFLG_SET_OF, 0, stname, field, type)} {Macro Return Type unknown at line no 288}
  {# define  ASN1_SET_OF_OPT(stname,field,type) ASN1_EX_TYPE(ASN1_TFLG_SET_OF | ASN1_TFLG_OPTIONAL, 0, stname, field, type)} {Macro Return Type unknown at line no 291}
  {# define  ASN1_IMP_SET_OF(stname,field,type,tag) ASN1_IMP_EX(stname, field, type, tag, ASN1_TFLG_SET_OF)} {Macro Return Type unknown at line no 296}
  {# define  ASN1_EXP_SET_OF(stname,field,type,tag) ASN1_EXP_EX(stname, field, type, tag, ASN1_TFLG_SET_OF)} {Macro Return Type unknown at line no 299}
  {# define  ASN1_IMP_SET_OF_OPT(stname,field,type,tag) ASN1_IMP_EX(stname, field, type, tag, ASN1_TFLG_SET_OF | ASN1_TFLG_OPTIONAL)} {Macro Return Type unknown at line no 302}
  {# define  ASN1_EXP_SET_OF_OPT(stname,field,type,tag) ASN1_EXP_EX(stname, field, type, tag, ASN1_TFLG_SET_OF | ASN1_TFLG_OPTIONAL)} {Macro Return Type unknown at line no 305}
  {# define  ASN1_IMP_SEQUENCE_OF(stname,field,type,tag) ASN1_IMP_EX(stname, field, type, tag, ASN1_TFLG_SEQUENCE_OF)} {Macro Return Type unknown at line no 308}
  {# define  ASN1_IMP_SEQUENCE_OF_OPT(stname,field,type,tag) ASN1_IMP_EX(stname, field, type, tag, ASN1_TFLG_SEQUENCE_OF | ASN1_TFLG_OPTIONAL)} {Macro Return Type unknown at line no 311}
  {# define  ASN1_EXP_SEQUENCE_OF(stname,field,type,tag) ASN1_EXP_EX(stname, field, type, tag, ASN1_TFLG_SEQUENCE_OF)} {Macro Return Type unknown at line no 314}
  {# define  ASN1_EXP_SEQUENCE_OF_OPT(stname,field,type,tag) ASN1_EXP_EX(stname, field, type, tag, ASN1_TFLG_SEQUENCE_OF | ASN1_TFLG_OPTIONAL)} {Macro Return Type unknown at line no 317}
  {# define  ASN1_NDEF_EXP(stname,field,type,tag) ASN1_EXP_EX(stname, field, type, tag, ASN1_TFLG_NDEF)} {Macro Return Type unknown at line no 321}
  {# define  ASN1_NDEF_EXP_OPT(stname,field,type,tag) ASN1_EXP_EX(stname, field, type, tag, ASN1_TFLG_OPTIONAL | ASN1_TFLG_NDEF)} {Macro Return Type unknown at line no 325}
  {# define  ASN1_ADB(name) static const ASN1_ADB_TABLE name ##_adbtbl[]}
  (*# define  ASN1_ADB_END(name,flags,field,adb_cb,def,none) ; static const ASN1_ITEM *name ##_adb(void) { static const ASN1_ADB internal_adb 
= { flags, offsetof(name, field), adb_cb, name ##_adbtbl, sizeof(name ##_adbtbl) / sizeof(ASN1_ADB_TABLE), def, none }; return (const 
ASN1_ITEM * )&internal_adb; } void dummy_function(void)*)
  (*# define  ADB_ENTRY(val,template) { val, template }*)
  {# define  ASN1_ADB_TEMPLATE(name) static const ASN1_TEMPLATE name ##_tt}

type
  {Auto-generated forward references}
  PASN1_TEMPLATE_st = ^TASN1_TEMPLATE_st;
  PPASN1_TEMPLATE_st = ^PASN1_TEMPLATE_st;
  {end of auto-generated forward references}

  { Macro to obtain ASN1_ADB pointer from a type (only used internally) }
  { Macros for start and end of ASN1_ITEM definition }
  { Macros to aid ASN1 template writing }
  { This is a ASN1 type which just embeds a template }
  (*-
  * This pair helps declare a SEQUENCE. We can do:
  *
  *      ASN1_SEQUENCE(stname) = {
  *              ... SEQUENCE components ...
  *      } ASN1_SEQUENCE_END(stname)
  *
  *      This will produce an ASN1_ITEM called stname_it
  *      for a structure called stname.
  *
  *      If you want the same structure but a different
  *      name then use:
  *
  *      ASN1_SEQUENCE(itname) = {
  *              ... SEQUENCE components ...
  *      } ASN1_SEQUENCE_END_name(stname, itname)
  *
  *      This will create an item called itname_it using
  *      a structure called stname.
  *)
  (*-
  * This pair helps declare a CHOICE type. We can do:
  *
  *      ASN1_CHOICE(chname) = {
  *              ... CHOICE options ...
  *      ASN1_CHOICE_END(chname)
  *
  *      This will produce an ASN1_ITEM called chname_it
  *      for a structure called chname. The structure
  *      definition must look like this:
  *      typedef struct {
  *              int type;
  *              union {
  *                      ASN1_SOMETHING *opt1;
  *                      ASN1_SOMEOTHER *opt2;
  *              } value;
  *      } chname;
  *
  *      the name of the selector must be 'type'.
  *      to use an alternative selector name use the
  *      ASN1_CHOICE_END_selector() version.
  *)
  { This helps with the template wrapper form of ASN1_ITEM }
  { These help with SEQUENCE or CHOICE components }
  { used to declare other types }
  { implicit and explicit helper macros }
  { Any defined by macros: the field used is in the table itself }
  { Plain simple type }
  { Embedded simple type }
  { OPTIONAL simple type }
  { IMPLICIT tagged simple type }
  { IMPLICIT tagged OPTIONAL simple type }
  { Same as above but EXPLICIT }
  { SEQUENCE OF type }
  { OPTIONAL SEQUENCE OF }
  { Same as above but for SET OF }
  { Finally compound types of SEQUENCE, SET, IMPLICIT, EXPLICIT and OPTIONAL }
  { EXPLICIT using indefinite length constructed form }
  { EXPLICIT OPTIONAL using indefinite length constructed form }
  { Macros for the ASN1_ADB structure }
  
  {* This is the ASN1 template structure that defines a wrapper round the
  * actual type. It determines the actual position of the field in the value
  * structure, various flags such as OPTIONAL and the field name.
  }
  TASN1_TEMPLATE_st = record 
    flags: TOpenSSL_C_UINT; { Various flags }
    tag: TOpenSSL_C_INT; { tag, not used if no tagging }
    offset: TOpenSSL_C_UINT; { Offset of this field in structure }
    field_name: PAnsiChar; { Field name }
    item: PASN1_ITEM_EXP; { Relevant ASN1_ITEM or ASN1_ADB }
  end;


  { Macro to extract ASN1_ITEM and ASN1_ADB pointer from ASN1_TEMPLATE }
  function ASN1_TEMPLATE_item(t: PASN1_TEMPLATE_st): PASN1_ITEM_EXP; inline;
  function ASN1_TEMPLATE_adb(t: PASN1_TEMPLATE_st): PASN1_ITEM_EXP; inline;

type
  {Auto-generated forward references}
  PASN1_ADB_TABLE_st = ^TASN1_ADB_TABLE_st;
  PPASN1_ADB_TABLE_st = ^PASN1_ADB_TABLE_st;
  PASN1_ADB_TABLE = ^TASN1_ADB_TABLE;
  PPASN1_ADB_TABLE = ^PASN1_ADB_TABLE;
  PASN1_ADB_st = ^TASN1_ADB_st;
  PPASN1_ADB_st = ^PASN1_ADB_st;
  PASN1_ADB = ^TASN1_ADB;
  PPASN1_ADB = ^PASN1_ADB;
  PFuncType000 = ^TFuncType000;
  PPFuncType000 = ^PFuncType000;
  {end of auto-generated forward references}

  TASN1_ADB_TABLE_st = record 
    value: TOpenSSL_C_INT; { NID for an object or value for an int }
    tt: TASN1_TEMPLATE; { item for this value }
  end;
  TASN1_ADB_TABLE = TASN1_ADB_TABLE_st;
  TASN1_ADB_st = record 
    flags: TOpenSSL_C_UINT; { Various flags }
    offset: TOpenSSL_C_UINT; { Offset of selector field }
    adb_cb: TFuncType000; { Application callback }
    tbl: PASN1_ADB_TABLE; { Table of possible types }
    tblcount: TOpenSSL_C_INT; { Number of entries in tbl }
    default_tt: PASN1_TEMPLATE; { Type to use if no match }
    null_tt: PASN1_TEMPLATE; { Type to use if selector is NULL }
  end;
  TASN1_ADB = TASN1_ADB_st;
  TFuncType000 = function(psel: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;

const
  { template flags }
  { Field is optional }
  ASN1_TFLG_OPTIONAL = $1;
  { Field is a SET OF }
  ASN1_TFLG_SET_OF = $1 shl 1;
  { Field is a SEQUENCE OF }
  ASN1_TFLG_SEQUENCE_OF = $2 shl 1;
  
  {* Special case: this refers to a SET OF that will be sorted into DER order
  * when encoded *and* the corresponding STACK will be modified to match the
  * new order.
  }
  ASN1_TFLG_SET_ORDER = $3 shl 1;
  { Mask for SET OF or SEQUENCE OF }
  ASN1_TFLG_SK_MASK = $3 shl 1;
  
  {* These flags mean the tag should be taken from the tag field. If EXPLICIT
  * then the underlying type is used for the inner tag.
  }
  { IMPLICIT tagging }
  ASN1_TFLG_IMPTAG = $1 shl 3;
  { EXPLICIT tagging, inner tag from underlying type }
  ASN1_TFLG_EXPTAG = $2 shl 3;
  ASN1_TFLG_TAG_MASK = $3 shl 3;
  
  {* If tagging is in force these determine the type of tag to use. Otherwise
  * the tag is determined by the underlying type. These values reflect the
  * actual octet format.
  }
  { Universal tag }
  ASN1_TFLG_UNIVERSAL = $0 shl 6;
  { Application tag }
  ASN1_TFLG_APPLICATION = $1 shl 6;
  { Context specific tag }
  ASN1_TFLG_CONTEXT = $2 shl 6;
  { Private tag }
  ASN1_TFLG_PRIVATE = $3 shl 6;
  ASN1_TFLG_TAG_CLASS = $3 shl 6;
  { context specific IMPLICIT }
  ASN1_TFLG_IMPLICIT = ASN1_TFLG_IMPTAG or ASN1_TFLG_CONTEXT;
  { context specific EXPLICIT }
  ASN1_TFLG_EXPLICIT = ASN1_TFLG_EXPTAG or ASN1_TFLG_CONTEXT;
  
  {* These are for ANY DEFINED BY type. In this case the 'item' field points to
  * an ASN1_ADB structure which contains a table of values to decode the
  * relevant type
  }
  ASN1_TFLG_ADB_MASK = $3 shl 8;
  ASN1_TFLG_ADB_OID = $1 shl 8;
  ASN1_TFLG_ADB_INT = $1 shl 9;
  
  {* This flag when present in a SEQUENCE OF, SET OF or EXPLICIT causes
  * indefinite length constructed encoding to be used if required.
  }
  ASN1_TFLG_NDEF = $1 shl 11;
  { Field is embedded and not a pointer }
  ASN1_TFLG_EMBED = $1 shl 12;

type
  {Auto-generated forward references}
  PASN1_ITEM_st = ^TASN1_ITEM_st;
  PPASN1_ITEM_st = ^PASN1_ITEM_st;
  PASN1_TLC_st = ^TASN1_TLC_st;
  PPASN1_TLC_st = ^PASN1_TLC_st;
  PASN1_ex_d2i = ^TASN1_ex_d2i;
  PPASN1_ex_d2i = ^PASN1_ex_d2i;
  PASN1_ex_d2i_ex = ^TASN1_ex_d2i_ex;
  PPASN1_ex_d2i_ex = ^PASN1_ex_d2i_ex;
  PASN1_ex_i2d = ^TASN1_ex_i2d;
  PPASN1_ex_i2d = ^PASN1_ex_i2d;
  PASN1_ex_new_func = ^TASN1_ex_new_func;
  PPASN1_ex_new_func = ^PASN1_ex_new_func;
  PASN1_ex_new_ex_func = ^TASN1_ex_new_ex_func;
  PPASN1_ex_new_ex_func = ^PASN1_ex_new_ex_func;
  PASN1_ex_free_func = ^TASN1_ex_free_func;
  PPASN1_ex_free_func = ^PASN1_ex_free_func;
  PASN1_ex_print_func = ^TASN1_ex_print_func;
  PPASN1_ex_print_func = ^PASN1_ex_print_func;
  PASN1_primitive_i2c = ^TASN1_primitive_i2c;
  PPASN1_primitive_i2c = ^PASN1_primitive_i2c;
  PASN1_primitive_c2i = ^TASN1_primitive_c2i;
  PPASN1_primitive_c2i = ^PASN1_primitive_c2i;
  PASN1_primitive_print = ^TASN1_primitive_print;
  PPASN1_primitive_print = ^PASN1_primitive_print;
  PASN1_EXTERN_FUNCS_st = ^TASN1_EXTERN_FUNCS_st;
  PPASN1_EXTERN_FUNCS_st = ^PASN1_EXTERN_FUNCS_st;
  PASN1_EXTERN_FUNCS = ^TASN1_EXTERN_FUNCS;
  PPASN1_EXTERN_FUNCS = ^PASN1_EXTERN_FUNCS;
  PASN1_PRIMITIVE_FUNCS_st = ^TASN1_PRIMITIVE_FUNCS_st;
  PPASN1_PRIMITIVE_FUNCS_st = ^PASN1_PRIMITIVE_FUNCS_st;
  PASN1_PRIMITIVE_FUNCS = ^TASN1_PRIMITIVE_FUNCS;
  PPASN1_PRIMITIVE_FUNCS = ^PASN1_PRIMITIVE_FUNCS;
  PASN1_aux_cb = ^TASN1_aux_cb;
  PPASN1_aux_cb = ^PASN1_aux_cb;
  PASN1_aux_const_cb = ^TASN1_aux_const_cb;
  PPASN1_aux_const_cb = ^PASN1_aux_const_cb;
  PASN1_AUX_st = ^TASN1_AUX_st;
  PPASN1_AUX_st = ^PASN1_AUX_st;
  PASN1_AUX = ^TASN1_AUX;
  PPASN1_AUX = ^PASN1_AUX;
  PASN1_PRINT_ARG_st = ^TASN1_PRINT_ARG_st;
  PPASN1_PRINT_ARG_st = ^PASN1_PRINT_ARG_st;
  PASN1_PRINT_ARG = ^TASN1_PRINT_ARG;
  PPASN1_PRINT_ARG = ^PASN1_PRINT_ARG;
  PASN1_STREAM_ARG_st = ^TASN1_STREAM_ARG_st;
  PPASN1_STREAM_ARG_st = ^PASN1_STREAM_ARG_st;
  PASN1_STREAM_ARG = ^TASN1_STREAM_ARG;
  PPASN1_STREAM_ARG = ^PASN1_STREAM_ARG;
  {end of auto-generated forward references}

  { This is the actual ASN1 item itself }
  TASN1_ITEM_st = record 
    itype: ansichar; { The item type, primitive, SEQUENCE, CHOICE
    * or extern }
    utype: TOpenSSL_C_INT; { underlying type }
    templates: PASN1_TEMPLATE; { If SEQUENCE or CHOICE this contains
    * the contents }
    tcount: TOpenSSL_C_INT; { Number of templates if SEQUENCE or CHOICE }
    funcs: pointer; { further data and type-specific functions }{ funcs can be ASN1_PRIMITIVE_FUNCS*, ASN1_EXTERN_FUNCS*, or ASN1_AUX* }
    size: TOpenSSL_C_INT; { Structure size (usually) }
    sname: PAnsiChar; { Structure name }
  end;
  
  {* Cache for ASN1 tag and length, so we don't keep re-reading it for things
  * like CHOICE
  }
  TASN1_TLC_st = record 
    valid: ansichar; { Values below are valid }
    ret: TOpenSSL_C_INT; { return value }
    plen: TOpenSSL_C_INT; { length }
    ptag: TOpenSSL_C_INT; { class value }
    pclass: TOpenSSL_C_INT; { class value }
    hdrlen: TOpenSSL_C_INT; { header length }
  end;
  { Typedefs for ASN1 function pointers }
  TASN1_ex_d2i = function(pval: PPASN1_VALUE; in_: PPbyte; len: TOpenSSL_C_INT; it: PASN1_ITEM; tag: TOpenSSL_C_INT; aclass: TOpenSSL_C_INT; opt: ansichar; ctx: PASN1_TLC): TOpenSSL_C_INT; cdecl;
  TASN1_ex_d2i_ex = function(pval: PPASN1_VALUE; in_: PPbyte; len: TOpenSSL_C_INT; it: PASN1_ITEM; tag: TOpenSSL_C_INT; aclass: TOpenSSL_C_INT; opt: ansichar; ctx: PASN1_TLC; libctx: POSSL_LIB_CTX; propq: PAnsiChar): TOpenSSL_C_INT; cdecl;
  TASN1_ex_i2d = function(pval: PPASN1_VALUE; out_: PPbyte; it: PASN1_ITEM; tag: TOpenSSL_C_INT; aclass: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  TASN1_ex_new_func = function(pval: PPASN1_VALUE; it: PASN1_ITEM): TOpenSSL_C_INT; cdecl;
  TASN1_ex_new_ex_func = function(pval: PPASN1_VALUE; it: PASN1_ITEM; libctx: POSSL_LIB_CTX; propq: PAnsiChar): TOpenSSL_C_INT; cdecl;
  TASN1_ex_free_func = procedure(pval: PPASN1_VALUE; it: PASN1_ITEM); cdecl;
  TASN1_ex_print_func = function(out_: PBIO; pval: PPASN1_VALUE; indent: TOpenSSL_C_INT; fname: PAnsiChar; pctx: PASN1_PCTX): TOpenSSL_C_INT; cdecl;
  TASN1_primitive_i2c = function(pval: PPASN1_VALUE; cont: Pbyte; putype: POpenSSL_C_INT; it: PASN1_ITEM): TOpenSSL_C_INT; cdecl;
  TASN1_primitive_c2i = function(pval: PPASN1_VALUE; cont: Pbyte; len: TOpenSSL_C_INT; utype: TOpenSSL_C_INT; free_cont: PAnsiChar; it: PASN1_ITEM): TOpenSSL_C_INT; cdecl;
  TASN1_primitive_print = function(out_: PBIO; pval: PPASN1_VALUE; it: PASN1_ITEM; indent: TOpenSSL_C_INT; pctx: PASN1_PCTX): TOpenSSL_C_INT; cdecl;
  TASN1_EXTERN_FUNCS_st = record 
    app_data: pointer;
    asn1_ex_new: PASN1_ex_new_func;
    asn1_ex_free: PASN1_ex_free_func;
    asn1_ex_clear: PASN1_ex_free_func;
    asn1_ex_d2i: PASN1_ex_d2i;
    asn1_ex_i2d: PASN1_ex_i2d;
    asn1_ex_print: PASN1_ex_print_func;
    asn1_ex_new_ex: PASN1_ex_new_ex_func;
    asn1_ex_d2i_ex: PASN1_ex_d2i_ex;
  end;
  TASN1_EXTERN_FUNCS = TASN1_EXTERN_FUNCS_st;
  TASN1_PRIMITIVE_FUNCS_st = record 
    app_data: pointer;
    flags: TOpenSSL_C_UINT;
    prim_new: PASN1_ex_new_func;
    prim_free: PASN1_ex_free_func;
    prim_clear: PASN1_ex_free_func;
    prim_c2i: PASN1_primitive_c2i;
    prim_i2c: PASN1_primitive_i2c;
    prim_print: PASN1_primitive_print;
  end;
  TASN1_PRIMITIVE_FUNCS = TASN1_PRIMITIVE_FUNCS_st;
  
  {* This is the ASN1_AUX structure: it handles various miscellaneous
  * requirements. For example the use of reference counts and an informational
  * callback. The "informational callback" is called at various points during
  * the ASN1 encoding and decoding. It can be used to provide minor
  * customisation of the structures used. This is most useful where the
  * supplied routines *almost* do the right thing but need some extra help at
  * a few points. If the callback returns zero then it is assumed a fatal
  * error has occurred and the main operation should be abandoned. If major
  * changes in the default behaviour are required then an external type is
  * more appropriate.
  * For the operations ASN1_OP_I2D_PRE, ASN1_OP_I2D_POST, ASN1_OP_PRINT_PRE, and
  * ASN1_OP_PRINT_POST, meanwhile a variant of the callback with const parameter
  * 'in' is provided to make clear statically that its input is not modified. If
  * and only if this variant is in use the flag ASN1_AFLG_CONST_CB must be set.
  }
  TASN1_aux_cb = function(operation: TOpenSSL_C_INT; in_: PPASN1_VALUE; it: PASN1_ITEM; exarg: pointer): TOpenSSL_C_INT; cdecl;
  TASN1_aux_const_cb = function(operation: TOpenSSL_C_INT; in_: PPASN1_VALUE; it: PASN1_ITEM; exarg: pointer): TOpenSSL_C_INT; cdecl;
  TASN1_AUX_st = record 
    app_data: pointer;
    flags: TOpenSSL_C_INT;
    ref_offset: TOpenSSL_C_INT; { Offset of reference value }
    ref_lock: TOpenSSL_C_INT; { Offset of lock value }
    asn1_cb: PASN1_aux_cb;
    enc_offset: TOpenSSL_C_INT; { Offset of ASN1_ENCODING structure }
    asn1_const_cb: PASN1_aux_const_cb; { for ASN1_OP_I2D_ and ASN1_OP_PRINT_ }
  end;
  TASN1_AUX = TASN1_AUX_st;
  { For print related callbacks exarg points to this structure }
  TASN1_PRINT_ARG_st = record 
    out_: PBIO;
    indent: TOpenSSL_C_INT;
    pctx: PASN1_PCTX;
  end;
  TASN1_PRINT_ARG = TASN1_PRINT_ARG_st;
  { For streaming related callbacks exarg points to this structure }
  TASN1_STREAM_ARG_st = record 
 { BIO to stream through }
    out_: PBIO; { BIO with filters appended }
    ndef_bio: PBIO; { Streaming I/O boundary }
    boundary: PPbyte;
  end;
  TASN1_STREAM_ARG = TASN1_STREAM_ARG_st;

const
  { Flags in ASN1_AUX }
  { Use a reference count }
  ASN1_AFLG_REFCOUNT = 1;
  { Save the encoding of structure (useful for signatures) }
  ASN1_AFLG_ENCODING = 2;
  { The Sequence length is invalid }
  ASN1_AFLG_BROKEN = 4;
  { Use the new asn1_const_cb }
  ASN1_AFLG_CONST_CB = 8;
  { operation values for asn1_cb }
  ASN1_OP_NEW_PRE = 0;
  ASN1_OP_NEW_POST = 1;
  ASN1_OP_FREE_PRE = 2;
  ASN1_OP_FREE_POST = 3;
  ASN1_OP_D2I_PRE = 4;
  ASN1_OP_D2I_POST = 5;
  ASN1_OP_I2D_PRE = 6;
  ASN1_OP_I2D_POST = 7;
  ASN1_OP_PRINT_PRE = 8;
  ASN1_OP_PRINT_POST = 9;
  ASN1_OP_STREAM_PRE = 10;
  ASN1_OP_STREAM_POST = 11;
  ASN1_OP_DETACHED_PRE = 12;
  ASN1_OP_DETACHED_POST = 13;
  ASN1_OP_DUP_PRE = 14;
  ASN1_OP_DUP_POST = 15;
  ASN1_OP_GET0_LIBCTX = 16;
  ASN1_OP_GET0_PROPQ = 17;
  {# define  IMPLEMENT_ASN1_TYPE(stname) IMPLEMENT_ASN1_TYPE_ex(stname, stname, 0)} { Blacklisted Macro}
  {# define  IMPLEMENT_ASN1_TYPE_ex(itname,vname,ex) ASN1_ITEM_start(itname) ASN1_ITYPE_PRIMITIVE, V_ ##vname, NULL, 0, NULL, ex, 
#itname ASN1_ITEM_end(itname)}
  {# define  IMPLEMENT_ASN1_MSTRING(itname,mask) ASN1_ITEM_start(itname) ASN1_ITYPE_MSTRING, mask, NULL, 0, NULL, sizeof(ASN1_STRING),
 #itname ASN1_ITEM_end(itname)}
  {# define  IMPLEMENT_EXTERN_ASN1(sname,tag,fptrs) ASN1_ITEM_start(sname) ASN1_ITYPE_EXTERN, tag, NULL, 0, &fptrs, 0, #sname ASN1_ITEM_end(sname)}
  {# define  IMPLEMENT_ASN1_FUNCTIONS(stname) IMPLEMENT_ASN1_FUNCTIONS_fname(stname, stname, stname)} { Blacklisted Macro}
  {# define  IMPLEMENT_ASN1_FUNCTIONS_name(stname,itname) IMPLEMENT_ASN1_FUNCTIONS_fname(stname, itname, itname)} { Blacklisted Macro}
  {# define  IMPLEMENT_ASN1_FUNCTIONS_ENCODE_name(stname,itname) IMPLEMENT_ASN1_FUNCTIONS_ENCODE_fname(stname, itname, itname)} {Macro Return Type unknown at line no 641}
  {# define  IMPLEMENT_STATIC_ASN1_ALLOC_FUNCTIONS(stname) IMPLEMENT_ASN1_ALLOC_FUNCTIONS_pfname(static, stname, stname, stname)} { Blacklisted Macro}
  {# define  IMPLEMENT_ASN1_ALLOC_FUNCTIONS(stname) IMPLEMENT_ASN1_ALLOC_FUNCTIONS_fname(stname, stname, stname)} { Blacklisted Macro}
  (*# define  IMPLEMENT_ASN1_ALLOC_FUNCTIONS_pfname(pre,stname,itname,fname) pre stname *fname ##_new(void) { return (stname * )ASN1_item_new(ASN1_ITEM_rptr(itname)); 
} pre void fname ##_free(stname *a) { ASN1_item_free((ASN1_VALUE * )a, ASN1_ITEM_rptr(itname)); }*)
  (*# define  IMPLEMENT_ASN1_ALLOC_FUNCTIONS_fname(stname,itname,fname) stname *fname ##_new(void) { return (stname * )ASN1_item_new(ASN1_ITEM_rptr(itname)); 
} void fname ##_free(stname *a) { ASN1_item_free((ASN1_VALUE * )a, ASN1_ITEM_rptr(itname)); }*)
  {# define  IMPLEMENT_ASN1_FUNCTIONS_fname(stname,itname,fname) IMPLEMENT_ASN1_ENCODE_FUNCTIONS_fname(stname, itname, fname) IMPLEMENT_ASN1_ALLOC_FUNCTIONS_fname(stname,
 itname, fname)}
  (*# define  IMPLEMENT_ASN1_ENCODE_FUNCTIONS_fname(stname,itname,fname) stname *d2i_ ##fname(stname **a, const unsigned char **in,
 long len) { return (stname * )ASN1_item_d2i((ASN1_VALUE ** )a, in, len, ASN1_ITEM_rptr(itname)); } int i2d_ ##fname(const stname 
*a, unsigned char **out) { return ASN1_item_i2d((const ASN1_VALUE * )a, out, ASN1_ITEM_rptr(itname)); }*)
  (*# define  IMPLEMENT_ASN1_NDEF_FUNCTION(stname) int i2d_ ##stname ##_NDEF(const stname *a, unsigned char **out) { return ASN1_item_ndef_i2d((const 
ASN1_VALUE * )a, out, ASN1_ITEM_rptr(stname)); }*)
  (*# define  IMPLEMENT_STATIC_ASN1_ENCODE_FUNCTIONS(stname) static stname *d2i_ ##stname(stname **a, const unsigned char **in, long 
len) { return (stname * )ASN1_item_d2i((ASN1_VALUE ** )a, in, len, ASN1_ITEM_rptr(stname)); } static int i2d_ ##stname(const stname 
*a, unsigned char **out) { return ASN1_item_i2d((const ASN1_VALUE * )a, out, ASN1_ITEM_rptr(stname)); }*)
  (*# define  IMPLEMENT_ASN1_DUP_FUNCTION(stname) stname *stname ##_dup(const stname *x) { return ASN1_item_dup(ASN1_ITEM_rptr(stname),
 x); }*)
  {# define  IMPLEMENT_ASN1_PRINT_FUNCTION(stname) IMPLEMENT_ASN1_PRINT_FUNCTION_fname(stname, stname, stname)} { Blacklisted Macro}
  (*# define  IMPLEMENT_ASN1_PRINT_FUNCTION_fname(stname,itname,fname) int fname ##_print_ctx(BIO *out, const stname *x, int indent,
 const ASN1_PCTX *pctx) { return ASN1_item_print(out, (const ASN1_VALUE * )x, indent, ASN1_ITEM_rptr(itname), pctx); }*)


  { Macro to implement a primitive type }
  { Macro to implement a multi string type }
  { Macro to implement standard functions in terms of ASN1_ITEM structures }
  { external definitions for primitive types }
  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function ASN1_BOOLEAN_it: PASN1_ITEM; cdecl; external CLibCrypto name 'ASN1_BOOLEAN_it';
  function ASN1_TBOOLEAN_it: PASN1_ITEM; cdecl; external CLibCrypto name 'ASN1_TBOOLEAN_it';
  function ASN1_FBOOLEAN_it: PASN1_ITEM; cdecl; external CLibCrypto name 'ASN1_FBOOLEAN_it';
  function ASN1_SEQUENCE_it: PASN1_ITEM; cdecl; external CLibCrypto name 'ASN1_SEQUENCE_it';
  function CBIGNUM_it: PASN1_ITEM; cdecl; external CLibCrypto name 'CBIGNUM_it';
  function BIGNUM_it: PASN1_ITEM; cdecl; external CLibCrypto name 'BIGNUM_it';
  function INT32_it: PASN1_ITEM; cdecl; external CLibCrypto name 'INT32_it';
  function ZINT32_it: PASN1_ITEM; cdecl; external CLibCrypto name 'ZINT32_it';
  function UINT32_it: PASN1_ITEM; cdecl; external CLibCrypto name 'UINT32_it';
  function ZUINT32_it: PASN1_ITEM; cdecl; external CLibCrypto name 'ZUINT32_it';
  function INT64_it: PASN1_ITEM; cdecl; external CLibCrypto name 'INT64_it';
  function ZINT64_it: PASN1_ITEM; cdecl; external CLibCrypto name 'ZINT64_it';
  function UINT64_it: PASN1_ITEM; cdecl; external CLibCrypto name 'UINT64_it';
  function ZUINT64_it: PASN1_ITEM; cdecl; external CLibCrypto name 'ZUINT64_it';
  {$else}
  { The EXTERNALSYM directive is ignored by FPC, however, it is used by Delphi as follows:

  The EXTERNALSYM directive prevents the specified Delphi symbol from appearing in header
  files generated for C++. }
  {$EXTERNALSYM ASN1_BOOLEAN_it}
  {$EXTERNALSYM ASN1_TBOOLEAN_it}
  {$EXTERNALSYM ASN1_FBOOLEAN_it}
  {$EXTERNALSYM ASN1_SEQUENCE_it}
  {$EXTERNALSYM CBIGNUM_it}
  {$EXTERNALSYM BIGNUM_it}
  {$EXTERNALSYM INT32_it}
  {$EXTERNALSYM ZINT32_it}
  {$EXTERNALSYM UINT32_it}
  {$EXTERNALSYM ZUINT32_it}
  {$EXTERNALSYM INT64_it}
  {$EXTERNALSYM ZINT64_it}
  {$EXTERNALSYM UINT64_it}
  {$EXTERNALSYM ZUINT64_it}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_ASN1_BOOLEAN_it: PASN1_ITEM; cdecl;
  function Load_ASN1_TBOOLEAN_it: PASN1_ITEM; cdecl;
  function Load_ASN1_FBOOLEAN_it: PASN1_ITEM; cdecl;
  function Load_ASN1_SEQUENCE_it: PASN1_ITEM; cdecl;
  function Load_CBIGNUM_it: PASN1_ITEM; cdecl;
  function Load_BIGNUM_it: PASN1_ITEM; cdecl;
  function Load_INT32_it: PASN1_ITEM; cdecl;
  function Load_ZINT32_it: PASN1_ITEM; cdecl;
  function Load_UINT32_it: PASN1_ITEM; cdecl;
  function Load_ZUINT32_it: PASN1_ITEM; cdecl;
  function Load_INT64_it: PASN1_ITEM; cdecl;
  function Load_ZINT64_it: PASN1_ITEM; cdecl;
  function Load_UINT64_it: PASN1_ITEM; cdecl;
  function Load_ZUINT64_it: PASN1_ITEM; cdecl;

var
  ASN1_BOOLEAN_it: function: PASN1_ITEM; cdecl = Load_ASN1_BOOLEAN_it;
  ASN1_TBOOLEAN_it: function: PASN1_ITEM; cdecl = Load_ASN1_TBOOLEAN_it;
  ASN1_FBOOLEAN_it: function: PASN1_ITEM; cdecl = Load_ASN1_FBOOLEAN_it;
  ASN1_SEQUENCE_it: function: PASN1_ITEM; cdecl = Load_ASN1_SEQUENCE_it;
  CBIGNUM_it: function: PASN1_ITEM; cdecl = Load_CBIGNUM_it;
  BIGNUM_it: function: PASN1_ITEM; cdecl = Load_BIGNUM_it;
  INT32_it: function: PASN1_ITEM; cdecl = Load_INT32_it;
  ZINT32_it: function: PASN1_ITEM; cdecl = Load_ZINT32_it;
  UINT32_it: function: PASN1_ITEM; cdecl = Load_UINT32_it;
  ZUINT32_it: function: PASN1_ITEM; cdecl = Load_ZUINT32_it;
  INT64_it: function: PASN1_ITEM; cdecl = Load_INT64_it;
  ZINT64_it: function: PASN1_ITEM; cdecl = Load_ZINT64_it;
  UINT64_it: function: PASN1_ITEM; cdecl = Load_UINT64_it;
  ZUINT64_it: function: PASN1_ITEM; cdecl = Load_ZUINT64_it;
  {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$ifndef  OPENSSL_NO_DEPRECATED_3_0}


    
    {* LONG and ZLONG are strongly discouraged for use as stored data, as the
    * underlying C type (long) differs in size depending on the architecture.
    * They are designed with 32-bit longs in mind.
    }
    {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function LONG_it: PASN1_ITEM; cdecl; external CLibCrypto name 'LONG_it';
  function ZLONG_it: PASN1_ITEM; cdecl; external CLibCrypto name 'ZLONG_it';
    {$else}
  {$EXTERNALSYM LONG_it}
  {$EXTERNALSYM ZLONG_it}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_LONG_it: PASN1_ITEM; cdecl;
  function Load_ZLONG_it: PASN1_ITEM; cdecl;

var
  LONG_it: function: PASN1_ITEM; cdecl = Load_LONG_it;
  ZLONG_it: function: PASN1_ITEM; cdecl = Load_ZLONG_it;
    {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$endif}

type
  {Auto-generated forward references}
  Pstack_st_ASN1_VALUE = ^Tstack_st_ASN1_VALUE;
  PPstack_st_ASN1_VALUE = ^Pstack_st_ASN1_VALUE;
  Psk_ASN1_VALUE_compfunc = ^Tsk_ASN1_VALUE_compfunc;
  PPsk_ASN1_VALUE_compfunc = ^Psk_ASN1_VALUE_compfunc;
  Psk_ASN1_VALUE_freefunc = ^Tsk_ASN1_VALUE_freefunc;
  PPsk_ASN1_VALUE_freefunc = ^Psk_ASN1_VALUE_freefunc;
  Psk_ASN1_VALUE_copyfunc = ^Tsk_ASN1_VALUE_copyfunc;
  PPsk_ASN1_VALUE_copyfunc = ^Psk_ASN1_VALUE_copyfunc;
  {end of auto-generated forward references}

  { clang-format off }
  Tstack_st_ASN1_VALUE = record 
  end;
  Tsk_ASN1_VALUE_compfunc = function(a: PPASN1_VALUE; b: PPASN1_VALUE): TOpenSSL_C_INT; cdecl;
  Tsk_ASN1_VALUE_freefunc = procedure(a: PASN1_VALUE); cdecl;
  Tsk_ASN1_VALUE_copyfunc = function(a: PASN1_VALUE): PASN1_VALUE; cdecl;


  procedure sk_ASN1_VALUE_freefunc_thunk(freefunc_arg: TOPENSSL_sk_freefunc; ptr: pointer); inline;
  function ossl_check_ASN1_VALUE_type(ptr: PASN1_VALUE): PASN1_VALUE{Has C Attribute: unused}; inline;
  function ossl_check_const_ASN1_VALUE_sk_type(sk: Pstack_st_ASN1_VALUE): POPENSSL_STACK{Has C Attribute: unused}; inline;
  function ossl_check_ASN1_VALUE_sk_type(sk: Pstack_st_ASN1_VALUE): POPENSSL_STACK{Has C Attribute: unused}; inline;
  function ossl_check_ASN1_VALUE_compfunc_type(cmp: Tsk_ASN1_VALUE_compfunc): TOPENSSL_sk_compfunc{Has C Attribute: unused}; inline;
  function ossl_check_ASN1_VALUE_copyfunc_type(cpy: Tsk_ASN1_VALUE_copyfunc): TOPENSSL_sk_copyfunc{Has C Attribute: unused}; inline;
  function ossl_check_ASN1_VALUE_freefunc_type(fr: Tsk_ASN1_VALUE_freefunc): TOPENSSL_sk_freefunc{Has C Attribute: unused}; inline;
  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function sk_ASN1_VALUE_num(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_num';
  function sk_ASN1_VALUE_value(_para: Pstack_st_ASN1_VALUE; _para2: TOpenSSL_C_INT): Pstack_st_ASN1_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_value';
  function sk_ASN1_VALUE_new(cmp: Tsk_ASN1_VALUE_compfunc): Pstack_st_ASN1_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_new';
  function sk_ASN1_VALUE_new_null: Pstack_st_ASN1_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_new_null';
  function sk_ASN1_VALUE_new_reserve(cmp: Tsk_ASN1_VALUE_compfunc; n: TOpenSSL_C_INT): Pstack_st_ASN1_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_new_reserve';
  function sk_ASN1_VALUE_reserve(_para: Pstack_st_ASN1_VALUE; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_reserve';
  function sk_ASN1_VALUE_free(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_free';
  function sk_ASN1_VALUE_zero(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_zero';
  function sk_ASN1_VALUE_delete(st: Pstack_st_ASN1_VALUE; loc: TOpenSSL_C_INT): Pstack_st_ASN1_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_delete';
  function sk_ASN1_VALUE_delete_ptr(st: Pstack_st_ASN1_VALUE; ptr: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_delete_ptr';
  function sk_ASN1_VALUE_push(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_push';
  function sk_ASN1_VALUE_unshift(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_unshift';
  function sk_ASN1_VALUE_pop(_para: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_pop';
  function sk_ASN1_VALUE_shift(_para: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_shift';
  procedure sk_ASN1_VALUE_pop_free(st: Pstack_st_ASN1_VALUE; func: Tsk_ASN1_VALUE_freefunc); cdecl; external CLibCrypto name 'OPENSSL_sk_pop_free';
  function sk_ASN1_VALUE_insert(st: Pstack_st_ASN1_VALUE; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_insert';
  function sk_ASN1_VALUE_set(st: Pstack_st_ASN1_VALUE; i: TOpenSSL_C_INT; data: pointer): Pstack_st_ASN1_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_set';
  function sk_ASN1_VALUE_find(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find';
  function sk_ASN1_VALUE_find_ex(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find_ex';
  function sk_ASN1_VALUE_find_all(st: Pstack_st_ASN1_VALUE; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find_all';
  function sk_ASN1_VALUE_sort(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_sort';
  function sk_ASN1_VALUE_is_sorted(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_is_sorted';
  function sk_ASN1_VALUE_dup(st: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_dup';
  function sk_ASN1_VALUE_deep_copy(st: Pstack_st_ASN1_VALUE; c: Tsk_ASN1_VALUE_compfunc; f: Tsk_ASN1_VALUE_freefunc): Pstack_st_ASN1_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_deep_copy';
  function sk_ASN1_VALUE_set_cmp_func(st: Pstack_st_ASN1_VALUE; cmp: Tsk_ASN1_VALUE_compfunc): Tsk_ASN1_VALUE_compfunc; cdecl; external CLibCrypto name 'OPENSSL_sk_set_cmp_func';
  { clang-format on }
  { Functions used internally by the ASN1 code }
  function ASN1_item_ex_new(pval: PPASN1_VALUE; it: PASN1_ITEM): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'ASN1_item_ex_new';
  procedure ASN1_item_ex_free(pval: PPASN1_VALUE; it: PASN1_ITEM); cdecl; external CLibCrypto name 'ASN1_item_ex_free';
  function ASN1_item_ex_d2i(pval: PPASN1_VALUE; in_: PPbyte; len: TOpenSSL_C_INT; it: PASN1_ITEM; tag: TOpenSSL_C_INT; aclass: TOpenSSL_C_INT; opt: ansichar; ctx: PASN1_TLC): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'ASN1_item_ex_d2i';
  function ASN1_item_ex_i2d(pval: PPASN1_VALUE; out_: PPbyte; it: PASN1_ITEM; tag: TOpenSSL_C_INT; aclass: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'ASN1_item_ex_i2d';
  { Legacy compatibility }
  {$else}
  {$EXTERNALSYM sk_ASN1_VALUE_num}
  {$EXTERNALSYM sk_ASN1_VALUE_value}
  {$EXTERNALSYM sk_ASN1_VALUE_new}
  {$EXTERNALSYM sk_ASN1_VALUE_new_null}
  {$EXTERNALSYM sk_ASN1_VALUE_new_reserve}
  {$EXTERNALSYM sk_ASN1_VALUE_reserve}
  {$EXTERNALSYM sk_ASN1_VALUE_free}
  {$EXTERNALSYM sk_ASN1_VALUE_zero}
  {$EXTERNALSYM sk_ASN1_VALUE_delete}
  {$EXTERNALSYM sk_ASN1_VALUE_delete_ptr}
  {$EXTERNALSYM sk_ASN1_VALUE_push}
  {$EXTERNALSYM sk_ASN1_VALUE_unshift}
  {$EXTERNALSYM sk_ASN1_VALUE_pop}
  {$EXTERNALSYM sk_ASN1_VALUE_shift}
  {$EXTERNALSYM sk_ASN1_VALUE_pop_free}
  {$EXTERNALSYM sk_ASN1_VALUE_insert}
  {$EXTERNALSYM sk_ASN1_VALUE_set}
  {$EXTERNALSYM sk_ASN1_VALUE_find}
  {$EXTERNALSYM sk_ASN1_VALUE_find_ex}
  {$EXTERNALSYM sk_ASN1_VALUE_find_all}
  {$EXTERNALSYM sk_ASN1_VALUE_sort}
  {$EXTERNALSYM sk_ASN1_VALUE_is_sorted}
  {$EXTERNALSYM sk_ASN1_VALUE_dup}
  {$EXTERNALSYM sk_ASN1_VALUE_deep_copy}
  {$EXTERNALSYM sk_ASN1_VALUE_set_cmp_func}
  {$EXTERNALSYM ASN1_item_ex_new}
  {$EXTERNALSYM ASN1_item_ex_free}
  {$EXTERNALSYM ASN1_item_ex_d2i}
  {$EXTERNALSYM ASN1_item_ex_i2d}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_sk_ASN1_VALUE_num(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl;
  function Load_sk_ASN1_VALUE_value(_para: Pstack_st_ASN1_VALUE; _para2: TOpenSSL_C_INT): Pstack_st_ASN1_VALUE; cdecl;
  function Load_sk_ASN1_VALUE_new(cmp: Tsk_ASN1_VALUE_compfunc): Pstack_st_ASN1_VALUE; cdecl;
  function Load_sk_ASN1_VALUE_new_null: Pstack_st_ASN1_VALUE; cdecl;
  function Load_sk_ASN1_VALUE_new_reserve(cmp: Tsk_ASN1_VALUE_compfunc; n: TOpenSSL_C_INT): Pstack_st_ASN1_VALUE; cdecl;
  function Load_sk_ASN1_VALUE_reserve(_para: Pstack_st_ASN1_VALUE; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_ASN1_VALUE_free(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl;
  function Load_sk_ASN1_VALUE_zero(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl;
  function Load_sk_ASN1_VALUE_delete(st: Pstack_st_ASN1_VALUE; loc: TOpenSSL_C_INT): Pstack_st_ASN1_VALUE; cdecl;
  function Load_sk_ASN1_VALUE_delete_ptr(st: Pstack_st_ASN1_VALUE; ptr: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl;
  function Load_sk_ASN1_VALUE_push(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_ASN1_VALUE_unshift(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_ASN1_VALUE_pop(_para: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl;
  function Load_sk_ASN1_VALUE_shift(_para: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl;
  procedure Load_sk_ASN1_VALUE_pop_free(st: Pstack_st_ASN1_VALUE; func: Tsk_ASN1_VALUE_freefunc); cdecl;
  function Load_sk_ASN1_VALUE_insert(st: Pstack_st_ASN1_VALUE; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_ASN1_VALUE_set(st: Pstack_st_ASN1_VALUE; i: TOpenSSL_C_INT; data: pointer): Pstack_st_ASN1_VALUE; cdecl;
  function Load_sk_ASN1_VALUE_find(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_ASN1_VALUE_find_ex(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_ASN1_VALUE_find_all(st: Pstack_st_ASN1_VALUE; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_ASN1_VALUE_sort(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl;
  function Load_sk_ASN1_VALUE_is_sorted(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl;
  function Load_sk_ASN1_VALUE_dup(st: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl;
  function Load_sk_ASN1_VALUE_deep_copy(st: Pstack_st_ASN1_VALUE; c: Tsk_ASN1_VALUE_compfunc; f: Tsk_ASN1_VALUE_freefunc): Pstack_st_ASN1_VALUE; cdecl;
  function Load_sk_ASN1_VALUE_set_cmp_func(st: Pstack_st_ASN1_VALUE; cmp: Tsk_ASN1_VALUE_compfunc): Tsk_ASN1_VALUE_compfunc; cdecl;
  function Load_ASN1_item_ex_new(pval: PPASN1_VALUE; it: PASN1_ITEM): TOpenSSL_C_INT; cdecl;
  procedure Load_ASN1_item_ex_free(pval: PPASN1_VALUE; it: PASN1_ITEM); cdecl;
  function Load_ASN1_item_ex_d2i(pval: PPASN1_VALUE; in_: PPbyte; len: TOpenSSL_C_INT; it: PASN1_ITEM; tag: TOpenSSL_C_INT; aclass: TOpenSSL_C_INT; opt: ansichar; ctx: PASN1_TLC): TOpenSSL_C_INT; cdecl;
  function Load_ASN1_item_ex_i2d(pval: PPASN1_VALUE; out_: PPbyte; it: PASN1_ITEM; tag: TOpenSSL_C_INT; aclass: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;

var
  sk_ASN1_VALUE_num: function(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl = Load_sk_ASN1_VALUE_num;
  sk_ASN1_VALUE_value: function(_para: Pstack_st_ASN1_VALUE; _para2: TOpenSSL_C_INT): Pstack_st_ASN1_VALUE; cdecl = Load_sk_ASN1_VALUE_value;
  sk_ASN1_VALUE_new: function(cmp: Tsk_ASN1_VALUE_compfunc): Pstack_st_ASN1_VALUE; cdecl = Load_sk_ASN1_VALUE_new;
  sk_ASN1_VALUE_new_null: function: Pstack_st_ASN1_VALUE; cdecl = Load_sk_ASN1_VALUE_new_null;
  sk_ASN1_VALUE_new_reserve: function(cmp: Tsk_ASN1_VALUE_compfunc; n: TOpenSSL_C_INT): Pstack_st_ASN1_VALUE; cdecl = Load_sk_ASN1_VALUE_new_reserve;
  sk_ASN1_VALUE_reserve: function(_para: Pstack_st_ASN1_VALUE; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_ASN1_VALUE_reserve;
  sk_ASN1_VALUE_free: function(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl = Load_sk_ASN1_VALUE_free;
  sk_ASN1_VALUE_zero: function(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl = Load_sk_ASN1_VALUE_zero;
  sk_ASN1_VALUE_delete: function(st: Pstack_st_ASN1_VALUE; loc: TOpenSSL_C_INT): Pstack_st_ASN1_VALUE; cdecl = Load_sk_ASN1_VALUE_delete;
  sk_ASN1_VALUE_delete_ptr: function(st: Pstack_st_ASN1_VALUE; ptr: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl = Load_sk_ASN1_VALUE_delete_ptr;
  sk_ASN1_VALUE_push: function(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_ASN1_VALUE_push;
  sk_ASN1_VALUE_unshift: function(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_ASN1_VALUE_unshift;
  sk_ASN1_VALUE_pop: function(_para: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl = Load_sk_ASN1_VALUE_pop;
  sk_ASN1_VALUE_shift: function(_para: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl = Load_sk_ASN1_VALUE_shift;
  sk_ASN1_VALUE_pop_free: procedure(st: Pstack_st_ASN1_VALUE; func: Tsk_ASN1_VALUE_freefunc); cdecl = Load_sk_ASN1_VALUE_pop_free;
  sk_ASN1_VALUE_insert: function(st: Pstack_st_ASN1_VALUE; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_ASN1_VALUE_insert;
  sk_ASN1_VALUE_set: function(st: Pstack_st_ASN1_VALUE; i: TOpenSSL_C_INT; data: pointer): Pstack_st_ASN1_VALUE; cdecl = Load_sk_ASN1_VALUE_set;
  sk_ASN1_VALUE_find: function(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_ASN1_VALUE_find;
  sk_ASN1_VALUE_find_ex: function(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_ASN1_VALUE_find_ex;
  sk_ASN1_VALUE_find_all: function(st: Pstack_st_ASN1_VALUE; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_ASN1_VALUE_find_all;
  sk_ASN1_VALUE_sort: function(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl = Load_sk_ASN1_VALUE_sort;
  sk_ASN1_VALUE_is_sorted: function(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl = Load_sk_ASN1_VALUE_is_sorted;
  sk_ASN1_VALUE_dup: function(st: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl = Load_sk_ASN1_VALUE_dup;
  sk_ASN1_VALUE_deep_copy: function(st: Pstack_st_ASN1_VALUE; c: Tsk_ASN1_VALUE_compfunc; f: Tsk_ASN1_VALUE_freefunc): Pstack_st_ASN1_VALUE; cdecl = Load_sk_ASN1_VALUE_deep_copy;
  sk_ASN1_VALUE_set_cmp_func: function(st: Pstack_st_ASN1_VALUE; cmp: Tsk_ASN1_VALUE_compfunc): Tsk_ASN1_VALUE_compfunc; cdecl = Load_sk_ASN1_VALUE_set_cmp_func;
  { clang-format on }
  { Functions used internally by the ASN1 code }
  ASN1_item_ex_new: function(pval: PPASN1_VALUE; it: PASN1_ITEM): TOpenSSL_C_INT; cdecl = Load_ASN1_item_ex_new;
  ASN1_item_ex_free: procedure(pval: PPASN1_VALUE; it: PASN1_ITEM); cdecl = Load_ASN1_item_ex_free;
  ASN1_item_ex_d2i: function(pval: PPASN1_VALUE; in_: PPbyte; len: TOpenSSL_C_INT; it: PASN1_ITEM; tag: TOpenSSL_C_INT; aclass: TOpenSSL_C_INT; opt: ansichar; ctx: PASN1_TLC): TOpenSSL_C_INT; cdecl = Load_ASN1_item_ex_d2i;
  ASN1_item_ex_i2d: function(pval: PPASN1_VALUE; out_: PPbyte; it: PASN1_ITEM; tag: TOpenSSL_C_INT; aclass: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_ASN1_item_ex_i2d;
  { Legacy compatibility }
  {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {# define  IMPLEMENT_ASN1_FUNCTIONS_const(name) IMPLEMENT_ASN1_FUNCTIONS(name)} { Blacklisted Macro}
  {# define  IMPLEMENT_ASN1_ENCODE_FUNCTIONS_const_fname(stname,itname,fname) IMPLEMENT_ASN1_ENCODE_FUNCTIONS_fname(stname, itname,
 fname)} { Blacklisted Macro}
{$endif}

implementation

uses Sysutils, variants
  {$ifdef OPENSSL_INTERNAL_NEED_THREADS}
   {$IFNDEF FPC}
     ,System.SyncObjs
     {$IFDEF POSIX}
       ,Posix.Pthread
     {$ELSE}
       ,Windows
     {$ENDIF}
   {$ELSE}
     ,SyncObjs
   {$ENDIF}
  {$endif}
  ,Classes, OpenSSLExceptionHandlers;

  {$if not declared(__FILE__)}
  const
    {$ifdef FPC}
    __FILE__ = {$include %FILE%};
    {$else}
    __FILE__ = '$(INPUTFILENAME)';
    {$endif}
  {$ifend}
  {$if not declared(__LINE__)}
  const
    __LINE__ = 0;
  {$ifend}
  {$if not declared(OPENSSL_FILE)}
  const
    OPENSSL_FILE = __FILE__;
  {$ifend}
  {$if not declared(OPENSSL_LINE)}
  const
    OPENSSL_LINE  = 0;
  {$ifend}


{# define  ASN1_TEMPLATE_item(t) (t->item)}

function ASN1_TEMPLATE_item(t: PASN1_TEMPLATE_st): PASN1_ITEM_EXP;
begin
  Result := PASN1_ITEM_EXP(t^.item);
end;

{# define  ASN1_TEMPLATE_adb(t) (t->item)}

function ASN1_TEMPLATE_adb(t: PASN1_TEMPLATE_st): PASN1_ITEM_EXP;
begin
  Result := PASN1_ITEM_EXP(t^.item);
end;
procedure sk_ASN1_VALUE_freefunc_thunk(freefunc_arg: TOPENSSL_sk_freefunc; ptr: pointer); inline;
begin
  raise Exception.Create('Unable to translate C Function "sk_ASN1_VALUE_freefunc_thunk"');

{Error: Line 709: Syntax Error parsing " sk_ASN1_VALUE_freefunc freefunc = (sk_ASN1_VALUE_freefunc)freefunc_arg; freefunc((ASN1_VALUE 
*)ptr); "

 sk_ASN1_VALUE_freefunc freefunc = (sk_ASN1_VALUE_freefunc)freefunc_arg; freefunc((ASN1_VALUE *)ptr); }
end;

function ossl_check_ASN1_VALUE_type(ptr: PASN1_VALUE): PASN1_VALUE{Has C Attribute: unused}; inline;
begin
   Result := ptr;
end;

function ossl_check_const_ASN1_VALUE_sk_type(sk: Pstack_st_ASN1_VALUE): POPENSSL_STACK{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_STACK(sk);
end;

function ossl_check_ASN1_VALUE_sk_type(sk: Pstack_st_ASN1_VALUE): POPENSSL_STACK{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_STACK(sk);
end;

function ossl_check_ASN1_VALUE_compfunc_type(cmp: Tsk_ASN1_VALUE_compfunc): TOPENSSL_sk_compfunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_compfunc(cmp);
end;

function ossl_check_ASN1_VALUE_copyfunc_type(cpy: Tsk_ASN1_VALUE_copyfunc): TOPENSSL_sk_copyfunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_copyfunc(cpy);
end;

function ossl_check_ASN1_VALUE_freefunc_type(fr: Tsk_ASN1_VALUE_freefunc): TOPENSSL_sk_freefunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_freefunc(fr);
end;

{$ifndef OPENSSL_STATIC_LINK_MODEL}
function Load_ASN1_BOOLEAN_it: PASN1_ITEM; cdecl;
begin
  ASN1_BOOLEAN_it := LoadLibCryptoFunction('ASN1_BOOLEAN_it');
  if not assigned(ASN1_BOOLEAN_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ASN1_BOOLEAN_it');
  Result := ASN1_BOOLEAN_it;
end;

function Load_ASN1_TBOOLEAN_it: PASN1_ITEM; cdecl;
begin
  ASN1_TBOOLEAN_it := LoadLibCryptoFunction('ASN1_TBOOLEAN_it');
  if not assigned(ASN1_TBOOLEAN_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ASN1_TBOOLEAN_it');
  Result := ASN1_TBOOLEAN_it;
end;

function Load_ASN1_FBOOLEAN_it: PASN1_ITEM; cdecl;
begin
  ASN1_FBOOLEAN_it := LoadLibCryptoFunction('ASN1_FBOOLEAN_it');
  if not assigned(ASN1_FBOOLEAN_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ASN1_FBOOLEAN_it');
  Result := ASN1_FBOOLEAN_it;
end;

function Load_ASN1_SEQUENCE_it: PASN1_ITEM; cdecl;
begin
  ASN1_SEQUENCE_it := LoadLibCryptoFunction('ASN1_SEQUENCE_it');
  if not assigned(ASN1_SEQUENCE_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ASN1_SEQUENCE_it');
  Result := ASN1_SEQUENCE_it;
end;

function Load_CBIGNUM_it: PASN1_ITEM; cdecl;
begin
  CBIGNUM_it := LoadLibCryptoFunction('CBIGNUM_it');
  if not assigned(CBIGNUM_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CBIGNUM_it');
  Result := CBIGNUM_it;
end;

function Load_BIGNUM_it: PASN1_ITEM; cdecl;
begin
  BIGNUM_it := LoadLibCryptoFunction('BIGNUM_it');
  if not assigned(BIGNUM_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('BIGNUM_it');
  Result := BIGNUM_it;
end;

function Load_INT32_it: PASN1_ITEM; cdecl;
begin
  INT32_it := LoadLibCryptoFunction('INT32_it');
  if not assigned(INT32_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('INT32_it');
  Result := INT32_it;
end;

function Load_ZINT32_it: PASN1_ITEM; cdecl;
begin
  ZINT32_it := LoadLibCryptoFunction('ZINT32_it');
  if not assigned(ZINT32_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ZINT32_it');
  Result := ZINT32_it;
end;

function Load_UINT32_it: PASN1_ITEM; cdecl;
begin
  UINT32_it := LoadLibCryptoFunction('UINT32_it');
  if not assigned(UINT32_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('UINT32_it');
  Result := UINT32_it;
end;

function Load_ZUINT32_it: PASN1_ITEM; cdecl;
begin
  ZUINT32_it := LoadLibCryptoFunction('ZUINT32_it');
  if not assigned(ZUINT32_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ZUINT32_it');
  Result := ZUINT32_it;
end;

function Load_INT64_it: PASN1_ITEM; cdecl;
begin
  INT64_it := LoadLibCryptoFunction('INT64_it');
  if not assigned(INT64_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('INT64_it');
  Result := INT64_it;
end;

function Load_ZINT64_it: PASN1_ITEM; cdecl;
begin
  ZINT64_it := LoadLibCryptoFunction('ZINT64_it');
  if not assigned(ZINT64_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ZINT64_it');
  Result := ZINT64_it;
end;

function Load_UINT64_it: PASN1_ITEM; cdecl;
begin
  UINT64_it := LoadLibCryptoFunction('UINT64_it');
  if not assigned(UINT64_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('UINT64_it');
  Result := UINT64_it;
end;

function Load_ZUINT64_it: PASN1_ITEM; cdecl;
begin
  ZUINT64_it := LoadLibCryptoFunction('ZUINT64_it');
  if not assigned(ZUINT64_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ZUINT64_it');
  Result := ZUINT64_it;
end;

{$ifndef  OPENSSL_NO_DEPRECATED_3_0}
function Load_LONG_it: PASN1_ITEM; cdecl;
begin
  LONG_it := LoadLibCryptoFunction('LONG_it');
  if not assigned(LONG_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('LONG_it');
  Result := LONG_it;
end;

function Load_ZLONG_it: PASN1_ITEM; cdecl;
begin
  ZLONG_it := LoadLibCryptoFunction('ZLONG_it');
  if not assigned(ZLONG_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ZLONG_it');
  Result := ZLONG_it;
end;

{$endif} { OPENSSL_NO_DEPRECATED_3_0}
function Load_sk_ASN1_VALUE_num(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl;
begin
  sk_ASN1_VALUE_num := LoadLibCryptoFunction('OPENSSL_sk_num');
  if not assigned(sk_ASN1_VALUE_num) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_num');
  Result := sk_ASN1_VALUE_num(_para);
end;

function Load_sk_ASN1_VALUE_value(_para: Pstack_st_ASN1_VALUE; _para2: TOpenSSL_C_INT): Pstack_st_ASN1_VALUE; cdecl;
begin
  sk_ASN1_VALUE_value := LoadLibCryptoFunction('OPENSSL_sk_value');
  if not assigned(sk_ASN1_VALUE_value) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_value');
  Result := sk_ASN1_VALUE_value(_para, _para2);
end;

function Load_sk_ASN1_VALUE_new(cmp: Tsk_ASN1_VALUE_compfunc): Pstack_st_ASN1_VALUE; cdecl;
begin
  sk_ASN1_VALUE_new := LoadLibCryptoFunction('OPENSSL_sk_new');
  if not assigned(sk_ASN1_VALUE_new) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new');
  Result := sk_ASN1_VALUE_new(cmp);
end;

function Load_sk_ASN1_VALUE_new_null: Pstack_st_ASN1_VALUE; cdecl;
begin
  sk_ASN1_VALUE_new_null := LoadLibCryptoFunction('OPENSSL_sk_new_null');
  if not assigned(sk_ASN1_VALUE_new_null) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new_null');
  Result := sk_ASN1_VALUE_new_null;
end;

function Load_sk_ASN1_VALUE_new_reserve(cmp: Tsk_ASN1_VALUE_compfunc; n: TOpenSSL_C_INT): Pstack_st_ASN1_VALUE; cdecl;
begin
  sk_ASN1_VALUE_new_reserve := LoadLibCryptoFunction('OPENSSL_sk_new_reserve');
  if not assigned(sk_ASN1_VALUE_new_reserve) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new_reserve');
  Result := sk_ASN1_VALUE_new_reserve(cmp, n);
end;

function Load_sk_ASN1_VALUE_reserve(_para: Pstack_st_ASN1_VALUE; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_ASN1_VALUE_reserve := LoadLibCryptoFunction('OPENSSL_sk_reserve');
  if not assigned(sk_ASN1_VALUE_reserve) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_reserve');
  Result := sk_ASN1_VALUE_reserve(_para, n);
end;

function Load_sk_ASN1_VALUE_free(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl;
begin
  sk_ASN1_VALUE_free := LoadLibCryptoFunction('OPENSSL_sk_free');
  if not assigned(sk_ASN1_VALUE_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_free');
  Result := sk_ASN1_VALUE_free(_para);
end;

function Load_sk_ASN1_VALUE_zero(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl;
begin
  sk_ASN1_VALUE_zero := LoadLibCryptoFunction('OPENSSL_sk_zero');
  if not assigned(sk_ASN1_VALUE_zero) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_zero');
  Result := sk_ASN1_VALUE_zero(_para);
end;

function Load_sk_ASN1_VALUE_delete(st: Pstack_st_ASN1_VALUE; loc: TOpenSSL_C_INT): Pstack_st_ASN1_VALUE; cdecl;
begin
  sk_ASN1_VALUE_delete := LoadLibCryptoFunction('OPENSSL_sk_delete');
  if not assigned(sk_ASN1_VALUE_delete) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_delete');
  Result := sk_ASN1_VALUE_delete(st, loc);
end;

function Load_sk_ASN1_VALUE_delete_ptr(st: Pstack_st_ASN1_VALUE; ptr: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl;
begin
  sk_ASN1_VALUE_delete_ptr := LoadLibCryptoFunction('OPENSSL_sk_delete_ptr');
  if not assigned(sk_ASN1_VALUE_delete_ptr) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_delete_ptr');
  Result := sk_ASN1_VALUE_delete_ptr(st, ptr);
end;

function Load_sk_ASN1_VALUE_push(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_ASN1_VALUE_push := LoadLibCryptoFunction('OPENSSL_sk_push');
  if not assigned(sk_ASN1_VALUE_push) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_push');
  Result := sk_ASN1_VALUE_push(st, data);
end;

function Load_sk_ASN1_VALUE_unshift(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_ASN1_VALUE_unshift := LoadLibCryptoFunction('OPENSSL_sk_unshift');
  if not assigned(sk_ASN1_VALUE_unshift) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_unshift');
  Result := sk_ASN1_VALUE_unshift(st, data);
end;

function Load_sk_ASN1_VALUE_pop(_para: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl;
begin
  sk_ASN1_VALUE_pop := LoadLibCryptoFunction('OPENSSL_sk_pop');
  if not assigned(sk_ASN1_VALUE_pop) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_pop');
  Result := sk_ASN1_VALUE_pop(_para);
end;

function Load_sk_ASN1_VALUE_shift(_para: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl;
begin
  sk_ASN1_VALUE_shift := LoadLibCryptoFunction('OPENSSL_sk_shift');
  if not assigned(sk_ASN1_VALUE_shift) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_shift');
  Result := sk_ASN1_VALUE_shift(_para);
end;

procedure Load_sk_ASN1_VALUE_pop_free(st: Pstack_st_ASN1_VALUE; func: Tsk_ASN1_VALUE_freefunc); cdecl;
begin
  sk_ASN1_VALUE_pop_free := LoadLibCryptoFunction('OPENSSL_sk_pop_free');
  if not assigned(sk_ASN1_VALUE_pop_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_pop_free');
  sk_ASN1_VALUE_pop_free(st, func);
end;

function Load_sk_ASN1_VALUE_insert(st: Pstack_st_ASN1_VALUE; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_ASN1_VALUE_insert := LoadLibCryptoFunction('OPENSSL_sk_insert');
  if not assigned(sk_ASN1_VALUE_insert) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_insert');
  Result := sk_ASN1_VALUE_insert(st, data, where);
end;

function Load_sk_ASN1_VALUE_set(st: Pstack_st_ASN1_VALUE; i: TOpenSSL_C_INT; data: pointer): Pstack_st_ASN1_VALUE; cdecl;
begin
  sk_ASN1_VALUE_set := LoadLibCryptoFunction('OPENSSL_sk_set');
  if not assigned(sk_ASN1_VALUE_set) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_set');
  Result := sk_ASN1_VALUE_set(st, i, data);
end;

function Load_sk_ASN1_VALUE_find(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_ASN1_VALUE_find := LoadLibCryptoFunction('OPENSSL_sk_find');
  if not assigned(sk_ASN1_VALUE_find) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find');
  Result := sk_ASN1_VALUE_find(st, data);
end;

function Load_sk_ASN1_VALUE_find_ex(st: Pstack_st_ASN1_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_ASN1_VALUE_find_ex := LoadLibCryptoFunction('OPENSSL_sk_find_ex');
  if not assigned(sk_ASN1_VALUE_find_ex) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find_ex');
  Result := sk_ASN1_VALUE_find_ex(st, data);
end;

function Load_sk_ASN1_VALUE_find_all(st: Pstack_st_ASN1_VALUE; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_ASN1_VALUE_find_all := LoadLibCryptoFunction('OPENSSL_sk_find_all');
  if not assigned(sk_ASN1_VALUE_find_all) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find_all');
  Result := sk_ASN1_VALUE_find_all(st, data, pnum);
end;

function Load_sk_ASN1_VALUE_sort(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl;
begin
  sk_ASN1_VALUE_sort := LoadLibCryptoFunction('OPENSSL_sk_sort');
  if not assigned(sk_ASN1_VALUE_sort) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_sort');
  Result := sk_ASN1_VALUE_sort(_para);
end;

function Load_sk_ASN1_VALUE_is_sorted(_para: Pstack_st_ASN1_VALUE): TOpenSSL_C_INT; cdecl;
begin
  sk_ASN1_VALUE_is_sorted := LoadLibCryptoFunction('OPENSSL_sk_is_sorted');
  if not assigned(sk_ASN1_VALUE_is_sorted) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_is_sorted');
  Result := sk_ASN1_VALUE_is_sorted(_para);
end;

function Load_sk_ASN1_VALUE_dup(st: Pstack_st_ASN1_VALUE): Pstack_st_ASN1_VALUE; cdecl;
begin
  sk_ASN1_VALUE_dup := LoadLibCryptoFunction('OPENSSL_sk_dup');
  if not assigned(sk_ASN1_VALUE_dup) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_dup');
  Result := sk_ASN1_VALUE_dup(st);
end;

function Load_sk_ASN1_VALUE_deep_copy(st: Pstack_st_ASN1_VALUE; c: Tsk_ASN1_VALUE_compfunc; f: Tsk_ASN1_VALUE_freefunc): Pstack_st_ASN1_VALUE; cdecl;
begin
  sk_ASN1_VALUE_deep_copy := LoadLibCryptoFunction('OPENSSL_sk_deep_copy');
  if not assigned(sk_ASN1_VALUE_deep_copy) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_deep_copy');
  Result := sk_ASN1_VALUE_deep_copy(st, c, f);
end;

function Load_sk_ASN1_VALUE_set_cmp_func(st: Pstack_st_ASN1_VALUE; cmp: Tsk_ASN1_VALUE_compfunc): Tsk_ASN1_VALUE_compfunc; cdecl;
begin
  sk_ASN1_VALUE_set_cmp_func := LoadLibCryptoFunction('OPENSSL_sk_set_cmp_func');
  if not assigned(sk_ASN1_VALUE_set_cmp_func) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_set_cmp_func');
  Result := sk_ASN1_VALUE_set_cmp_func(st, cmp);
end;

function Load_ASN1_item_ex_new(pval: PPASN1_VALUE; it: PASN1_ITEM): TOpenSSL_C_INT; cdecl;
begin
  ASN1_item_ex_new := LoadLibCryptoFunction('ASN1_item_ex_new');
  if not assigned(ASN1_item_ex_new) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ASN1_item_ex_new');
  Result := ASN1_item_ex_new(pval, it);
end;

procedure Load_ASN1_item_ex_free(pval: PPASN1_VALUE; it: PASN1_ITEM); cdecl;
begin
  ASN1_item_ex_free := LoadLibCryptoFunction('ASN1_item_ex_free');
  if not assigned(ASN1_item_ex_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ASN1_item_ex_free');
  ASN1_item_ex_free(pval, it);
end;

function Load_ASN1_item_ex_d2i(pval: PPASN1_VALUE; in_: PPbyte; len: TOpenSSL_C_INT; it: PASN1_ITEM; tag: TOpenSSL_C_INT; aclass: TOpenSSL_C_INT; opt: ansichar; ctx: PASN1_TLC): TOpenSSL_C_INT; cdecl;
begin
  ASN1_item_ex_d2i := LoadLibCryptoFunction('ASN1_item_ex_d2i');
  if not assigned(ASN1_item_ex_d2i) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ASN1_item_ex_d2i');
  Result := ASN1_item_ex_d2i(pval, in_, len, it, tag, aclass, opt, ctx);
end;

function Load_ASN1_item_ex_i2d(pval: PPASN1_VALUE; out_: PPbyte; it: PASN1_ITEM; tag: TOpenSSL_C_INT; aclass: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  ASN1_item_ex_i2d := LoadLibCryptoFunction('ASN1_item_ex_i2d');
  if not assigned(ASN1_item_ex_i2d) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ASN1_item_ex_i2d');
  Result := ASN1_item_ex_i2d(pval, out_, it, tag, aclass);
end;

procedure Load;
begin
  {$define EMPTY_LOAD_FUNCTION}
end;

procedure Unload;
begin
  ASN1_BOOLEAN_it := Load_ASN1_BOOLEAN_it;
  ASN1_TBOOLEAN_it := Load_ASN1_TBOOLEAN_it;
  ASN1_FBOOLEAN_it := Load_ASN1_FBOOLEAN_it;
  ASN1_SEQUENCE_it := Load_ASN1_SEQUENCE_it;
  CBIGNUM_it := Load_CBIGNUM_it;
  BIGNUM_it := Load_BIGNUM_it;
  INT32_it := Load_INT32_it;
  ZINT32_it := Load_ZINT32_it;
  UINT32_it := Load_UINT32_it;
  ZUINT32_it := Load_ZUINT32_it;
  INT64_it := Load_INT64_it;
  ZINT64_it := Load_ZINT64_it;
  UINT64_it := Load_UINT64_it;
  ZUINT64_it := Load_ZUINT64_it;
{$ifndef  OPENSSL_NO_DEPRECATED_3_0}
  LONG_it := Load_LONG_it;
  ZLONG_it := Load_ZLONG_it;
{$endif} { OPENSSL_NO_DEPRECATED_3_0}
  sk_ASN1_VALUE_num := Load_sk_ASN1_VALUE_num;
  sk_ASN1_VALUE_value := Load_sk_ASN1_VALUE_value;
  sk_ASN1_VALUE_new := Load_sk_ASN1_VALUE_new;
  sk_ASN1_VALUE_new_null := Load_sk_ASN1_VALUE_new_null;
  sk_ASN1_VALUE_new_reserve := Load_sk_ASN1_VALUE_new_reserve;
  sk_ASN1_VALUE_reserve := Load_sk_ASN1_VALUE_reserve;
  sk_ASN1_VALUE_free := Load_sk_ASN1_VALUE_free;
  sk_ASN1_VALUE_zero := Load_sk_ASN1_VALUE_zero;
  sk_ASN1_VALUE_delete := Load_sk_ASN1_VALUE_delete;
  sk_ASN1_VALUE_delete_ptr := Load_sk_ASN1_VALUE_delete_ptr;
  sk_ASN1_VALUE_push := Load_sk_ASN1_VALUE_push;
  sk_ASN1_VALUE_unshift := Load_sk_ASN1_VALUE_unshift;
  sk_ASN1_VALUE_pop := Load_sk_ASN1_VALUE_pop;
  sk_ASN1_VALUE_shift := Load_sk_ASN1_VALUE_shift;
  sk_ASN1_VALUE_pop_free := Load_sk_ASN1_VALUE_pop_free;
  sk_ASN1_VALUE_insert := Load_sk_ASN1_VALUE_insert;
  sk_ASN1_VALUE_set := Load_sk_ASN1_VALUE_set;
  sk_ASN1_VALUE_find := Load_sk_ASN1_VALUE_find;
  sk_ASN1_VALUE_find_ex := Load_sk_ASN1_VALUE_find_ex;
  sk_ASN1_VALUE_find_all := Load_sk_ASN1_VALUE_find_all;
  sk_ASN1_VALUE_sort := Load_sk_ASN1_VALUE_sort;
  sk_ASN1_VALUE_is_sorted := Load_sk_ASN1_VALUE_is_sorted;
  sk_ASN1_VALUE_dup := Load_sk_ASN1_VALUE_dup;
  sk_ASN1_VALUE_deep_copy := Load_sk_ASN1_VALUE_deep_copy;
  sk_ASN1_VALUE_set_cmp_func := Load_sk_ASN1_VALUE_set_cmp_func;
  ASN1_item_ex_new := Load_ASN1_item_ex_new;
  ASN1_item_ex_free := Load_ASN1_item_ex_free;
  ASN1_item_ex_d2i := Load_ASN1_item_ex_d2i;
  ASN1_item_ex_i2d := Load_ASN1_item_ex_i2d;
end;

{$endif} {OPENSSL_STATIC_LINK_MODEL}

initialization

{$ifndef OPENSSL_STATIC_LINK_MODEL}
{$ifndef EMPTY_LOAD_FUNCTION}
Register_SSLloader(@Load);
{$endif}
Register_SSLUnloader(@Unload);
{$endif}
{$if declared(LegacySupport_Initialization)}
LegacySupport_Initialization;
{$ifend}

finalization

{$if declared(LegacySupport_Finalization)}
LegacySupport_Finalization;
{$ifend}

end.



