{
    This file is part of the MWA Software Pascal API for OpenSSL .

    The MWA Software Pascal API for OpenSSL is free software: you can redistribute it
    and/or modify it under the terms of the Apache License Version 2.0 (the "License"), and as
    a derived work of the OpenSSL Project (see below for the original licence text).

    You may not use this file except in compliance with the License.  You can obtain a copy
    in the file LICENSE.txt in the source distribution or at https://www.openssl.org/source/license.html.

    The MWA Software Pascal API for OpenSSL is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the License for more details.
}

{$include openssl_defines.inc}

unit openssl_cmperr;

{
  Generated from OpenSSL 3.6.2 Header File cmperr.h - Tue 19 May 14:29:30 BST 2026
}

{$IFNDEF FPC}
{$IFDEF OPENSSL_USE_STATIC_LIBRARY}
{$LINK openssl_cmperr.obj}
{$ENDIF}
{$ENDIF}

interface

uses OpenSSLAPI,openssl_symhacks,openssl_cryptoerr_legacy;


{* Generated by util/mkerr.pl DO NOT EDIT
* Copyright 1995-2025 The OpenSSL Project Authors. All Rights Reserved.
*
* Licensed under the Apache License 2.0 (the "License").  You may not use
* this file except in compliance with the License.  You can obtain a copy
* in the file LICENSE in the source distribution or at
* https://www.openssl.org/source/license.html
}
{$ifndef  OPENSSL_CMPERR_H}
  {$define OPENSSL_CMPERR_H}
  {$include openssl_opensslconf.inc}
  {$ifndef  OPENSSL_NO_CMP}

const
    
    {* CMP reason codes.
    }
  CMP_R_ALGORITHM_NOT_SUPPORTED = 139;
  CMP_R_BAD_CHECKAFTER_IN_POLLREP = 167;
  CMP_R_BAD_REQUEST_ID = 108;
  CMP_R_CERTHASH_UNMATCHED = 156;
  CMP_R_CERTID_NOT_FOUND = 109;
  CMP_R_CERTIFICATE_NOT_ACCEPTED = 169;
  CMP_R_CERTIFICATE_NOT_FOUND = 112;
  CMP_R_CERTREQMSG_NOT_FOUND = 157;
  CMP_R_CERTRESPONSE_NOT_FOUND = 113;
  CMP_R_CERT_AND_KEY_DO_NOT_MATCH = 114;
  CMP_R_CHECKAFTER_OUT_OF_RANGE = 181;
  CMP_R_ENCOUNTERED_KEYUPDATEWARNING = 176;
  CMP_R_ENCOUNTERED_WAITING = 162;
  CMP_R_ERROR_CALCULATING_PROTECTION = 115;
  CMP_R_ERROR_CREATING_CERTCONF = 116;
  CMP_R_ERROR_CREATING_CERTREP = 117;
  CMP_R_ERROR_CREATING_CERTREQ = 163;
  CMP_R_ERROR_CREATING_ERROR = 118;
  CMP_R_ERROR_CREATING_GENM = 119;
  CMP_R_ERROR_CREATING_GENP = 120;
  CMP_R_ERROR_CREATING_PKICONF = 122;
  CMP_R_ERROR_CREATING_POLLREP = 123;
  CMP_R_ERROR_CREATING_POLLREQ = 124;
  CMP_R_ERROR_CREATING_RP = 125;
  CMP_R_ERROR_CREATING_RR = 126;
  CMP_R_ERROR_PARSING_PKISTATUS = 107;
  CMP_R_ERROR_PROCESSING_MESSAGE = 158;
  CMP_R_ERROR_PROTECTING_MESSAGE = 127;
  CMP_R_ERROR_SETTING_CERTHASH = 128;
  CMP_R_ERROR_UNEXPECTED_CERTCONF = 160;
  CMP_R_ERROR_VALIDATING_PROTECTION = 140;
  CMP_R_ERROR_VALIDATING_SIGNATURE = 171;
  CMP_R_EXPECTED_POLLREQ = 104;
  CMP_R_FAILED_BUILDING_OWN_CHAIN = 164;
  CMP_R_FAILED_EXTRACTING_CENTRAL_GEN_KEY = 203;
  CMP_R_FAILED_EXTRACTING_PUBKEY = 141;
  CMP_R_FAILURE_OBTAINING_RANDOM = 110;
  CMP_R_FAIL_INFO_OUT_OF_RANGE = 129;
  CMP_R_GENERATE_CERTREQTEMPLATE = 197;
  CMP_R_GENERATE_CRLSTATUS = 198;
  CMP_R_GETTING_GENP = 192;
  CMP_R_GET_ITAV = 199;
  CMP_R_INVALID_ARGS = 100;
  CMP_R_INVALID_GENP = 193;
  CMP_R_INVALID_KEYSPEC = 202;
  CMP_R_INVALID_OPTION = 174;
  CMP_R_INVALID_ROOTCAKEYUPDATE = 195;
  CMP_R_MISSING_CENTRAL_GEN_KEY = 204;
  CMP_R_MISSING_CERTID = 165;
  CMP_R_MISSING_KEY_INPUT_FOR_CREATING_PROTECTION = 130;
  CMP_R_MISSING_KEY_USAGE_DIGITALSIGNATURE = 142;
  CMP_R_MISSING_P10CSR = 121;
  CMP_R_MISSING_PBM_SECRET = 166;
  CMP_R_MISSING_PRIVATE_KEY = 131;
  CMP_R_MISSING_PRIVATE_KEY_FOR_POPO = 190;
  CMP_R_MISSING_PROTECTION = 143;
  CMP_R_MISSING_PUBLIC_KEY = 183;
  CMP_R_MISSING_REFERENCE_CERT = 168;
  CMP_R_MISSING_SECRET = 178;
  CMP_R_MISSING_SENDER_IDENTIFICATION = 111;
  CMP_R_MISSING_TRUST_ANCHOR = 179;
  CMP_R_MISSING_TRUST_STORE = 144;
  CMP_R_MULTIPLE_REQUESTS_NOT_SUPPORTED = 161;
  CMP_R_MULTIPLE_RESPONSES_NOT_SUPPORTED = 170;
  CMP_R_MULTIPLE_SAN_SOURCES = 102;
  CMP_R_NO_STDIO = 194;
  CMP_R_NO_SUITABLE_SENDER_CERT = 145;
  CMP_R_NULL_ARGUMENT = 103;
  CMP_R_PKIBODY_ERROR = 146;
  CMP_R_PKISTATUSINFO_NOT_FOUND = 132;
  CMP_R_POLLING_FAILED = 172;
  CMP_R_POTENTIALLY_INVALID_CERTIFICATE = 147;
  CMP_R_RECEIVED_ERROR = 180;
  CMP_R_RECIPNONCE_UNMATCHED = 148;
  CMP_R_REQUEST_NOT_ACCEPTED = 149;
  CMP_R_REQUEST_REJECTED_BY_SERVER = 182;
  CMP_R_SENDER_GENERALNAME_TYPE_NOT_SUPPORTED = 150;
  CMP_R_SRVCERT_DOES_NOT_VALIDATE_MSG = 151;
  CMP_R_TOTAL_TIMEOUT = 184;
  CMP_R_TRANSACTIONID_UNMATCHED = 152;
  CMP_R_TRANSFER_ERROR = 159;
  CMP_R_UNCLEAN_CTX = 191;
  CMP_R_UNEXPECTED_CENTRAL_GEN_KEY = 205;
  CMP_R_UNEXPECTED_CERTPROFILE = 196;
  CMP_R_UNEXPECTED_CRLSTATUSLIST = 201;
  CMP_R_UNEXPECTED_PKIBODY = 133;
  CMP_R_UNEXPECTED_PKISTATUS = 185;
  CMP_R_UNEXPECTED_POLLREQ = 105;
  CMP_R_UNEXPECTED_PVNO = 153;
  CMP_R_UNEXPECTED_SENDER = 106;
  CMP_R_UNKNOWN_ALGORITHM_ID = 134;
  CMP_R_UNKNOWN_CERT_TYPE = 135;
  CMP_R_UNKNOWN_CRL_ISSUER = 200;
  CMP_R_UNKNOWN_PKISTATUS = 186;
  CMP_R_UNSUPPORTED_ALGORITHM = 136;
  CMP_R_UNSUPPORTED_KEY_TYPE = 137;
  CMP_R_UNSUPPORTED_PKIBODY = 101;
  CMP_R_UNSUPPORTED_PROTECTION_ALG_DHBASEDMAC = 154;
  CMP_R_VALUE_TOO_LARGE = 175;
  CMP_R_VALUE_TOO_SMALL = 177;
  CMP_R_WRONG_ALGORITHM_OID = 138;
  CMP_R_WRONG_CERTID = 189;
  CMP_R_WRONG_CERTID_IN_RP = 187;
  CMP_R_WRONG_PBM_VALUE = 155;
  CMP_R_WRONG_RP_COMPONENT_COUNT = 188;
  CMP_R_WRONG_SERIAL_IN_RP = 173;
  {$endif}
{$endif}

implementation

uses Sysutils, variants
  {$ifdef OPENSSL_INTERNAL_NEED_THREADS}
   {$IFNDEF FPC}
     ,System.SyncObjs
     {$IFDEF POSIX}
       ,Posix.Pthread
     {$ELSE}
       ,Windows
     {$ENDIF}
   {$ELSE}
     ,SyncObjs
   {$ENDIF}
  {$endif}
  ,Classes, OpenSSLExceptionHandlers;

  {$if not declared(__FILE__)}
  const
    {$ifdef FPC}
    __FILE__ = {$include %FILE%};
    {$else}
    __FILE__ = '$(INPUTFILENAME)';
    {$endif}
  {$ifend}
  {$if not declared(__LINE__)}
  const
    __LINE__ = 0;
  {$ifend}
  {$if not declared(OPENSSL_FILE)}
  const
    OPENSSL_FILE = __FILE__;
  {$ifend}
  {$if not declared(OPENSSL_LINE)}
  const
    OPENSSL_LINE  = 0;
  {$ifend}

{$ifndef OPENSSL_STATIC_LINK_MODEL}
procedure Load;
begin
  {$define EMPTY_LOAD_FUNCTION}
end;

procedure Unload;
begin
end;

{$endif} {OPENSSL_STATIC_LINK_MODEL}

initialization

{$ifndef OPENSSL_STATIC_LINK_MODEL}
{$ifndef EMPTY_LOAD_FUNCTION}
Register_SSLloader(@Load);
{$endif}
Register_SSLUnloader(@Unload);
{$endif}
{$if declared(LegacySupport_Initialization)}
LegacySupport_Initialization;
{$ifend}

finalization

{$if declared(LegacySupport_Finalization)}
LegacySupport_Finalization;
{$ifend}

end.



