{
    This file is part of the MWA Software Pascal API for OpenSSL .

    The MWA Software Pascal API for OpenSSL is free software: you can redistribute it
    and/or modify it under the terms of the Apache License Version 2.0 (the "License"), and as
    a derived work of the OpenSSL Project (see below for the original licence text).

    You may not use this file except in compliance with the License.  You can obtain a copy
    in the file LICENSE.txt in the source distribution or at https://www.openssl.org/source/license.html.

    The MWA Software Pascal API for OpenSSL is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the License for more details.
}

{$include openssl_defines.inc}

unit openssl_ess;

{
  Generated from OpenSSL 3.6.2 Header File ess.h - Tue 19 May 14:30:05 BST 2026
}

{$IFNDEF FPC}
{$IFDEF OPENSSL_USE_STATIC_LIBRARY}
{$LINK openssl_ess.obj}
{$ENDIF}
{$ENDIF}

interface

uses OpenSSLAPI,openssl_stack,openssl_types,openssl_safestack,openssl_x509,
     openssl_esserr;


{* WARNING: do not edit!
* Generated by Makefile from include/openssl/ess.h.in
*
* Copyright 2019-2021 The OpenSSL Project Authors. All Rights Reserved.
*
* Licensed under the Apache License 2.0 (the "License").  You may not use
* this file except in compliance with the License.  You can obtain a copy
* in the file LICENSE in the source distribution or at
* https://www.openssl.org/source/license.html
}
{ clang-format off }
{ clang-format on }
{$ifndef  OPENSSL_ESS_H}
  {$define OPENSSL_ESS_H}
  {$include openssl_opensslconf.inc}

type
  {Auto-generated forward references}
  PESS_ISSUER_SERIAL = ^TESS_ISSUER_SERIAL;
  PPESS_ISSUER_SERIAL = ^PESS_ISSUER_SERIAL;
  PESS_CERT_ID = ^TESS_CERT_ID;
  PPESS_CERT_ID = ^PESS_CERT_ID;
  PESS_SIGNING_CERT = ^TESS_SIGNING_CERT;
  PPESS_SIGNING_CERT = ^PESS_SIGNING_CERT;
  Pstack_st_ESS_CERT_ID = ^Tstack_st_ESS_CERT_ID;
  PPstack_st_ESS_CERT_ID = ^Pstack_st_ESS_CERT_ID;
  Psk_ESS_CERT_ID_compfunc = ^Tsk_ESS_CERT_ID_compfunc;
  PPsk_ESS_CERT_ID_compfunc = ^Psk_ESS_CERT_ID_compfunc;
  Psk_ESS_CERT_ID_freefunc = ^Tsk_ESS_CERT_ID_freefunc;
  PPsk_ESS_CERT_ID_freefunc = ^Psk_ESS_CERT_ID_freefunc;
  Psk_ESS_CERT_ID_copyfunc = ^Tsk_ESS_CERT_ID_copyfunc;
  PPsk_ESS_CERT_ID_copyfunc = ^Psk_ESS_CERT_ID_copyfunc;
  {end of auto-generated forward references}

  TESS_ISSUER_SERIAL = record end;

  TESS_CERT_ID = record end;

  TESS_SIGNING_CERT = record end;

  { clang-format off }
  Tstack_st_ESS_CERT_ID = record 
  end;
  Tsk_ESS_CERT_ID_compfunc = function(a: PPESS_CERT_ID; b: PPESS_CERT_ID): TOpenSSL_C_INT; cdecl;
  Tsk_ESS_CERT_ID_freefunc = procedure(a: PESS_CERT_ID); cdecl;
  Tsk_ESS_CERT_ID_copyfunc = function(a: PESS_CERT_ID): PESS_CERT_ID; cdecl;


  procedure sk_ESS_CERT_ID_freefunc_thunk(freefunc_arg: TOPENSSL_sk_freefunc; ptr: pointer); inline;
  function ossl_check_ESS_CERT_ID_type(ptr: PESS_CERT_ID): PESS_CERT_ID{Has C Attribute: unused}; inline;
  function ossl_check_const_ESS_CERT_ID_sk_type(sk: Pstack_st_ESS_CERT_ID): POPENSSL_STACK{Has C Attribute: unused}; inline;
  function ossl_check_ESS_CERT_ID_sk_type(sk: Pstack_st_ESS_CERT_ID): POPENSSL_STACK{Has C Attribute: unused}; inline;
  function ossl_check_ESS_CERT_ID_compfunc_type(cmp: Tsk_ESS_CERT_ID_compfunc): TOPENSSL_sk_compfunc{Has C Attribute: unused}; inline;
  function ossl_check_ESS_CERT_ID_copyfunc_type(cpy: Tsk_ESS_CERT_ID_copyfunc): TOPENSSL_sk_copyfunc{Has C Attribute: unused}; inline;
  function ossl_check_ESS_CERT_ID_freefunc_type(fr: Tsk_ESS_CERT_ID_freefunc): TOPENSSL_sk_freefunc{Has C Attribute: unused}; inline;
  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function sk_ESS_CERT_ID_num(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_num';
  function sk_ESS_CERT_ID_value(_para: Pstack_st_ESS_CERT_ID; _para2: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID; cdecl; external CLibCrypto name 'OPENSSL_sk_value';
  function sk_ESS_CERT_ID_new(cmp: Tsk_ESS_CERT_ID_compfunc): Pstack_st_ESS_CERT_ID; cdecl; external CLibCrypto name 'OPENSSL_sk_new';
  function sk_ESS_CERT_ID_new_null: Pstack_st_ESS_CERT_ID; cdecl; external CLibCrypto name 'OPENSSL_sk_new_null';
  function sk_ESS_CERT_ID_new_reserve(cmp: Tsk_ESS_CERT_ID_compfunc; n: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID; cdecl; external CLibCrypto name 'OPENSSL_sk_new_reserve';
  function sk_ESS_CERT_ID_reserve(_para: Pstack_st_ESS_CERT_ID; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_reserve';
  function sk_ESS_CERT_ID_free(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_free';
  function sk_ESS_CERT_ID_zero(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_zero';
  function sk_ESS_CERT_ID_delete(st: Pstack_st_ESS_CERT_ID; loc: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID; cdecl; external CLibCrypto name 'OPENSSL_sk_delete';
  function sk_ESS_CERT_ID_delete_ptr(st: Pstack_st_ESS_CERT_ID; ptr: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl; external CLibCrypto name 'OPENSSL_sk_delete_ptr';
  function sk_ESS_CERT_ID_push(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_push';
  function sk_ESS_CERT_ID_unshift(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_unshift';
  function sk_ESS_CERT_ID_pop(_para: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl; external CLibCrypto name 'OPENSSL_sk_pop';
  function sk_ESS_CERT_ID_shift(_para: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl; external CLibCrypto name 'OPENSSL_sk_shift';
  procedure sk_ESS_CERT_ID_pop_free(st: Pstack_st_ESS_CERT_ID; func: Tsk_ESS_CERT_ID_freefunc); cdecl; external CLibCrypto name 'OPENSSL_sk_pop_free';
  function sk_ESS_CERT_ID_insert(st: Pstack_st_ESS_CERT_ID; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_insert';
  function sk_ESS_CERT_ID_set(st: Pstack_st_ESS_CERT_ID; i: TOpenSSL_C_INT; data: pointer): Pstack_st_ESS_CERT_ID; cdecl; external CLibCrypto name 'OPENSSL_sk_set';
  function sk_ESS_CERT_ID_find(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find';
  function sk_ESS_CERT_ID_find_ex(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find_ex';
  function sk_ESS_CERT_ID_find_all(st: Pstack_st_ESS_CERT_ID; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find_all';
  function sk_ESS_CERT_ID_sort(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_sort';
  function sk_ESS_CERT_ID_is_sorted(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_is_sorted';
  function sk_ESS_CERT_ID_dup(st: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl; external CLibCrypto name 'OPENSSL_sk_dup';
  function sk_ESS_CERT_ID_deep_copy(st: Pstack_st_ESS_CERT_ID; c: Tsk_ESS_CERT_ID_compfunc; f: Tsk_ESS_CERT_ID_freefunc): Pstack_st_ESS_CERT_ID; cdecl; external CLibCrypto name 'OPENSSL_sk_deep_copy';
  function sk_ESS_CERT_ID_set_cmp_func(st: Pstack_st_ESS_CERT_ID; cmp: Tsk_ESS_CERT_ID_compfunc): Tsk_ESS_CERT_ID_compfunc; cdecl; external CLibCrypto name 'OPENSSL_sk_set_cmp_func';
  { clang-format on }
  {$else}
  { The EXTERNALSYM directive is ignored by FPC, however, it is used by Delphi as follows:

  The EXTERNALSYM directive prevents the specified Delphi symbol from appearing in header
  files generated for C++. }
  {$EXTERNALSYM sk_ESS_CERT_ID_num}
  {$EXTERNALSYM sk_ESS_CERT_ID_value}
  {$EXTERNALSYM sk_ESS_CERT_ID_new}
  {$EXTERNALSYM sk_ESS_CERT_ID_new_null}
  {$EXTERNALSYM sk_ESS_CERT_ID_new_reserve}
  {$EXTERNALSYM sk_ESS_CERT_ID_reserve}
  {$EXTERNALSYM sk_ESS_CERT_ID_free}
  {$EXTERNALSYM sk_ESS_CERT_ID_zero}
  {$EXTERNALSYM sk_ESS_CERT_ID_delete}
  {$EXTERNALSYM sk_ESS_CERT_ID_delete_ptr}
  {$EXTERNALSYM sk_ESS_CERT_ID_push}
  {$EXTERNALSYM sk_ESS_CERT_ID_unshift}
  {$EXTERNALSYM sk_ESS_CERT_ID_pop}
  {$EXTERNALSYM sk_ESS_CERT_ID_shift}
  {$EXTERNALSYM sk_ESS_CERT_ID_pop_free}
  {$EXTERNALSYM sk_ESS_CERT_ID_insert}
  {$EXTERNALSYM sk_ESS_CERT_ID_set}
  {$EXTERNALSYM sk_ESS_CERT_ID_find}
  {$EXTERNALSYM sk_ESS_CERT_ID_find_ex}
  {$EXTERNALSYM sk_ESS_CERT_ID_find_all}
  {$EXTERNALSYM sk_ESS_CERT_ID_sort}
  {$EXTERNALSYM sk_ESS_CERT_ID_is_sorted}
  {$EXTERNALSYM sk_ESS_CERT_ID_dup}
  {$EXTERNALSYM sk_ESS_CERT_ID_deep_copy}
  {$EXTERNALSYM sk_ESS_CERT_ID_set_cmp_func}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_sk_ESS_CERT_ID_num(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_value(_para: Pstack_st_ESS_CERT_ID; _para2: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID; cdecl;
  function Load_sk_ESS_CERT_ID_new(cmp: Tsk_ESS_CERT_ID_compfunc): Pstack_st_ESS_CERT_ID; cdecl;
  function Load_sk_ESS_CERT_ID_new_null: Pstack_st_ESS_CERT_ID; cdecl;
  function Load_sk_ESS_CERT_ID_new_reserve(cmp: Tsk_ESS_CERT_ID_compfunc; n: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID; cdecl;
  function Load_sk_ESS_CERT_ID_reserve(_para: Pstack_st_ESS_CERT_ID; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_free(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_zero(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_delete(st: Pstack_st_ESS_CERT_ID; loc: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID; cdecl;
  function Load_sk_ESS_CERT_ID_delete_ptr(st: Pstack_st_ESS_CERT_ID; ptr: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl;
  function Load_sk_ESS_CERT_ID_push(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_unshift(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_pop(_para: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl;
  function Load_sk_ESS_CERT_ID_shift(_para: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl;
  procedure Load_sk_ESS_CERT_ID_pop_free(st: Pstack_st_ESS_CERT_ID; func: Tsk_ESS_CERT_ID_freefunc); cdecl;
  function Load_sk_ESS_CERT_ID_insert(st: Pstack_st_ESS_CERT_ID; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_set(st: Pstack_st_ESS_CERT_ID; i: TOpenSSL_C_INT; data: pointer): Pstack_st_ESS_CERT_ID; cdecl;
  function Load_sk_ESS_CERT_ID_find(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_find_ex(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_find_all(st: Pstack_st_ESS_CERT_ID; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_sort(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_is_sorted(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_dup(st: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl;
  function Load_sk_ESS_CERT_ID_deep_copy(st: Pstack_st_ESS_CERT_ID; c: Tsk_ESS_CERT_ID_compfunc; f: Tsk_ESS_CERT_ID_freefunc): Pstack_st_ESS_CERT_ID; cdecl;
  function Load_sk_ESS_CERT_ID_set_cmp_func(st: Pstack_st_ESS_CERT_ID; cmp: Tsk_ESS_CERT_ID_compfunc): Tsk_ESS_CERT_ID_compfunc; cdecl;

var
  sk_ESS_CERT_ID_num: function(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_num;
  sk_ESS_CERT_ID_value: function(_para: Pstack_st_ESS_CERT_ID; _para2: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID; cdecl = Load_sk_ESS_CERT_ID_value;
  sk_ESS_CERT_ID_new: function(cmp: Tsk_ESS_CERT_ID_compfunc): Pstack_st_ESS_CERT_ID; cdecl = Load_sk_ESS_CERT_ID_new;
  sk_ESS_CERT_ID_new_null: function: Pstack_st_ESS_CERT_ID; cdecl = Load_sk_ESS_CERT_ID_new_null;
  sk_ESS_CERT_ID_new_reserve: function(cmp: Tsk_ESS_CERT_ID_compfunc; n: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID; cdecl = Load_sk_ESS_CERT_ID_new_reserve;
  sk_ESS_CERT_ID_reserve: function(_para: Pstack_st_ESS_CERT_ID; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_reserve;
  sk_ESS_CERT_ID_free: function(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_free;
  sk_ESS_CERT_ID_zero: function(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_zero;
  sk_ESS_CERT_ID_delete: function(st: Pstack_st_ESS_CERT_ID; loc: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID; cdecl = Load_sk_ESS_CERT_ID_delete;
  sk_ESS_CERT_ID_delete_ptr: function(st: Pstack_st_ESS_CERT_ID; ptr: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl = Load_sk_ESS_CERT_ID_delete_ptr;
  sk_ESS_CERT_ID_push: function(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_push;
  sk_ESS_CERT_ID_unshift: function(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_unshift;
  sk_ESS_CERT_ID_pop: function(_para: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl = Load_sk_ESS_CERT_ID_pop;
  sk_ESS_CERT_ID_shift: function(_para: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl = Load_sk_ESS_CERT_ID_shift;
  sk_ESS_CERT_ID_pop_free: procedure(st: Pstack_st_ESS_CERT_ID; func: Tsk_ESS_CERT_ID_freefunc); cdecl = Load_sk_ESS_CERT_ID_pop_free;
  sk_ESS_CERT_ID_insert: function(st: Pstack_st_ESS_CERT_ID; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_insert;
  sk_ESS_CERT_ID_set: function(st: Pstack_st_ESS_CERT_ID; i: TOpenSSL_C_INT; data: pointer): Pstack_st_ESS_CERT_ID; cdecl = Load_sk_ESS_CERT_ID_set;
  sk_ESS_CERT_ID_find: function(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_find;
  sk_ESS_CERT_ID_find_ex: function(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_find_ex;
  sk_ESS_CERT_ID_find_all: function(st: Pstack_st_ESS_CERT_ID; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_find_all;
  sk_ESS_CERT_ID_sort: function(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_sort;
  sk_ESS_CERT_ID_is_sorted: function(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_is_sorted;
  sk_ESS_CERT_ID_dup: function(st: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl = Load_sk_ESS_CERT_ID_dup;
  sk_ESS_CERT_ID_deep_copy: function(st: Pstack_st_ESS_CERT_ID; c: Tsk_ESS_CERT_ID_compfunc; f: Tsk_ESS_CERT_ID_freefunc): Pstack_st_ESS_CERT_ID; cdecl = Load_sk_ESS_CERT_ID_deep_copy;
  sk_ESS_CERT_ID_set_cmp_func: function(st: Pstack_st_ESS_CERT_ID; cmp: Tsk_ESS_CERT_ID_compfunc): Tsk_ESS_CERT_ID_compfunc; cdecl = Load_sk_ESS_CERT_ID_set_cmp_func;
  { clang-format on }
  {$endif} {OPENSSL_STATIC_LINK_MODEL}

type
  {Auto-generated forward references}
  PESS_signing_cert_v2_st = ^TESS_SIGNING_CERT_V2;
  PPESS_signing_cert_v2_st = ^PESS_signing_cert_v2_st;
  PESS_SIGNING_CERT_V2 = ^TESS_SIGNING_CERT_V2;
  PPESS_SIGNING_CERT_V2 = ^PESS_SIGNING_CERT_V2;
  PESS_cert_id_v2_st = ^TESS_CERT_ID_V2;
  PPESS_cert_id_v2_st = ^PESS_cert_id_v2_st;
  PESS_CERT_ID_V2 = ^TESS_CERT_ID_V2;
  PPESS_CERT_ID_V2 = ^PESS_CERT_ID_V2;
  Pstack_st_ESS_CERT_ID_V2 = ^Tstack_st_ESS_CERT_ID_V2;
  PPstack_st_ESS_CERT_ID_V2 = ^Pstack_st_ESS_CERT_ID_V2;
  Psk_ESS_CERT_ID_V2_compfunc = ^Tsk_ESS_CERT_ID_V2_compfunc;
  PPsk_ESS_CERT_ID_V2_compfunc = ^Psk_ESS_CERT_ID_V2_compfunc;
  Psk_ESS_CERT_ID_V2_freefunc = ^Tsk_ESS_CERT_ID_V2_freefunc;
  PPsk_ESS_CERT_ID_V2_freefunc = ^Psk_ESS_CERT_ID_V2_freefunc;
  Psk_ESS_CERT_ID_V2_copyfunc = ^Tsk_ESS_CERT_ID_V2_copyfunc;
  PPsk_ESS_CERT_ID_V2_copyfunc = ^Psk_ESS_CERT_ID_V2_copyfunc;
  {end of auto-generated forward references}

  TESS_signing_cert_v2_st = record end;
  TESS_SIGNING_CERT_V2 = TESS_signing_cert_v2_st;
  TESS_cert_id_v2_st = record end;
  TESS_CERT_ID_V2 = TESS_cert_id_v2_st;
  { clang-format off }
  Tstack_st_ESS_CERT_ID_V2 = record 
  end;
  Tsk_ESS_CERT_ID_V2_compfunc = function(a: PPESS_CERT_ID_V2; b: PPESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl;
  Tsk_ESS_CERT_ID_V2_freefunc = procedure(a: PESS_CERT_ID_V2); cdecl;
  Tsk_ESS_CERT_ID_V2_copyfunc = function(a: PESS_CERT_ID_V2): PESS_CERT_ID_V2; cdecl;


  procedure sk_ESS_CERT_ID_V2_freefunc_thunk(freefunc_arg: TOPENSSL_sk_freefunc; ptr: pointer); inline;
  function ossl_check_ESS_CERT_ID_V2_type(ptr: PESS_CERT_ID_V2): PESS_CERT_ID_V2{Has C Attribute: unused}; inline;
  function ossl_check_const_ESS_CERT_ID_V2_sk_type(sk: Pstack_st_ESS_CERT_ID_V2): POPENSSL_STACK{Has C Attribute: unused}; inline;
  function ossl_check_ESS_CERT_ID_V2_sk_type(sk: Pstack_st_ESS_CERT_ID_V2): POPENSSL_STACK{Has C Attribute: unused}; inline;
  function ossl_check_ESS_CERT_ID_V2_compfunc_type(cmp: Tsk_ESS_CERT_ID_V2_compfunc): TOPENSSL_sk_compfunc{Has C Attribute: unused}; inline;
  function ossl_check_ESS_CERT_ID_V2_copyfunc_type(cpy: Tsk_ESS_CERT_ID_V2_copyfunc): TOPENSSL_sk_copyfunc{Has C Attribute: unused}; inline;
  function ossl_check_ESS_CERT_ID_V2_freefunc_type(fr: Tsk_ESS_CERT_ID_V2_freefunc): TOPENSSL_sk_freefunc{Has C Attribute: unused}; inline;
  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function sk_ESS_CERT_ID_V2_num(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_num';
  function sk_ESS_CERT_ID_V2_value(_para: Pstack_st_ESS_CERT_ID_V2; _para2: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID_V2; cdecl; external CLibCrypto name 'OPENSSL_sk_value';
  function sk_ESS_CERT_ID_V2_new(cmp: Tsk_ESS_CERT_ID_V2_compfunc): Pstack_st_ESS_CERT_ID_V2; cdecl; external CLibCrypto name 'OPENSSL_sk_new';
  function sk_ESS_CERT_ID_V2_new_null: Pstack_st_ESS_CERT_ID_V2; cdecl; external CLibCrypto name 'OPENSSL_sk_new_null';
  function sk_ESS_CERT_ID_V2_new_reserve(cmp: Tsk_ESS_CERT_ID_V2_compfunc; n: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID_V2; cdecl; external CLibCrypto name 'OPENSSL_sk_new_reserve';
  function sk_ESS_CERT_ID_V2_reserve(_para: Pstack_st_ESS_CERT_ID_V2; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_reserve';
  function sk_ESS_CERT_ID_V2_free(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_free';
  function sk_ESS_CERT_ID_V2_zero(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_zero';
  function sk_ESS_CERT_ID_V2_delete(st: Pstack_st_ESS_CERT_ID_V2; loc: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID_V2; cdecl; external CLibCrypto name 'OPENSSL_sk_delete';
  function sk_ESS_CERT_ID_V2_delete_ptr(st: Pstack_st_ESS_CERT_ID_V2; ptr: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl; external CLibCrypto name 'OPENSSL_sk_delete_ptr';
  function sk_ESS_CERT_ID_V2_push(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_push';
  function sk_ESS_CERT_ID_V2_unshift(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_unshift';
  function sk_ESS_CERT_ID_V2_pop(_para: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl; external CLibCrypto name 'OPENSSL_sk_pop';
  function sk_ESS_CERT_ID_V2_shift(_para: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl; external CLibCrypto name 'OPENSSL_sk_shift';
  procedure sk_ESS_CERT_ID_V2_pop_free(st: Pstack_st_ESS_CERT_ID_V2; func: Tsk_ESS_CERT_ID_V2_freefunc); cdecl; external CLibCrypto name 'OPENSSL_sk_pop_free';
  function sk_ESS_CERT_ID_V2_insert(st: Pstack_st_ESS_CERT_ID_V2; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_insert';
  function sk_ESS_CERT_ID_V2_set(st: Pstack_st_ESS_CERT_ID_V2; i: TOpenSSL_C_INT; data: pointer): Pstack_st_ESS_CERT_ID_V2; cdecl; external CLibCrypto name 'OPENSSL_sk_set';
  function sk_ESS_CERT_ID_V2_find(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find';
  function sk_ESS_CERT_ID_V2_find_ex(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find_ex';
  function sk_ESS_CERT_ID_V2_find_all(st: Pstack_st_ESS_CERT_ID_V2; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find_all';
  function sk_ESS_CERT_ID_V2_sort(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_sort';
  function sk_ESS_CERT_ID_V2_is_sorted(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_is_sorted';
  function sk_ESS_CERT_ID_V2_dup(st: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl; external CLibCrypto name 'OPENSSL_sk_dup';
  function sk_ESS_CERT_ID_V2_deep_copy(st: Pstack_st_ESS_CERT_ID_V2; c: Tsk_ESS_CERT_ID_V2_compfunc; f: Tsk_ESS_CERT_ID_V2_freefunc): Pstack_st_ESS_CERT_ID_V2; cdecl; external CLibCrypto name 'OPENSSL_sk_deep_copy';
  function sk_ESS_CERT_ID_V2_set_cmp_func(st: Pstack_st_ESS_CERT_ID_V2; cmp: Tsk_ESS_CERT_ID_V2_compfunc): Tsk_ESS_CERT_ID_V2_compfunc; cdecl; external CLibCrypto name 'OPENSSL_sk_set_cmp_func';
  { clang-format on }
  function ESS_ISSUER_SERIAL_new: PESS_ISSUER_SERIAL; cdecl; external CLibCrypto name 'ESS_ISSUER_SERIAL_new';
  procedure ESS_ISSUER_SERIAL_free(a: PESS_ISSUER_SERIAL); cdecl; external CLibCrypto name 'ESS_ISSUER_SERIAL_free';
  function d2i_ESS_ISSUER_SERIAL(a: PPESS_ISSUER_SERIAL; in_: PPbyte; len: TOpenSSL_C_INT): PESS_ISSUER_SERIAL; cdecl; external CLibCrypto name 'd2i_ESS_ISSUER_SERIAL';
  function i2d_ESS_ISSUER_SERIAL(a: PESS_ISSUER_SERIAL; out_: PPbyte): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'i2d_ESS_ISSUER_SERIAL';
  function ESS_ISSUER_SERIAL_dup(a: PESS_ISSUER_SERIAL): PESS_ISSUER_SERIAL; cdecl; external CLibCrypto name 'ESS_ISSUER_SERIAL_dup';
  function ESS_CERT_ID_new: PESS_CERT_ID; cdecl; external CLibCrypto name 'ESS_CERT_ID_new';
  procedure ESS_CERT_ID_free(a: PESS_CERT_ID); cdecl; external CLibCrypto name 'ESS_CERT_ID_free';
  function d2i_ESS_CERT_ID(a: PPESS_CERT_ID; in_: PPbyte; len: TOpenSSL_C_INT): PESS_CERT_ID; cdecl; external CLibCrypto name 'd2i_ESS_CERT_ID';
  function i2d_ESS_CERT_ID(a: PESS_CERT_ID; out_: PPbyte): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'i2d_ESS_CERT_ID';
  function ESS_CERT_ID_dup(a: PESS_CERT_ID): PESS_CERT_ID; cdecl; external CLibCrypto name 'ESS_CERT_ID_dup';
  function ESS_SIGNING_CERT_new: PESS_SIGNING_CERT; cdecl; external CLibCrypto name 'ESS_SIGNING_CERT_new';
  procedure ESS_SIGNING_CERT_free(a: PESS_SIGNING_CERT); cdecl; external CLibCrypto name 'ESS_SIGNING_CERT_free';
  function d2i_ESS_SIGNING_CERT(a: PPESS_SIGNING_CERT; in_: PPbyte; len: TOpenSSL_C_INT): PESS_SIGNING_CERT; cdecl; external CLibCrypto name 'd2i_ESS_SIGNING_CERT';
  function i2d_ESS_SIGNING_CERT(a: PESS_SIGNING_CERT; out_: PPbyte): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'i2d_ESS_SIGNING_CERT';
  function ESS_SIGNING_CERT_it: PASN1_ITEM; cdecl; external CLibCrypto name 'ESS_SIGNING_CERT_it';
  function ESS_SIGNING_CERT_dup(a: PESS_SIGNING_CERT): PESS_SIGNING_CERT; cdecl; external CLibCrypto name 'ESS_SIGNING_CERT_dup';
  function ESS_CERT_ID_V2_new: PESS_CERT_ID_V2; cdecl; external CLibCrypto name 'ESS_CERT_ID_V2_new';
  procedure ESS_CERT_ID_V2_free(a: PESS_CERT_ID_V2); cdecl; external CLibCrypto name 'ESS_CERT_ID_V2_free';
  function d2i_ESS_CERT_ID_V2(a: PPESS_CERT_ID_V2; in_: PPbyte; len: TOpenSSL_C_INT): PESS_CERT_ID_V2; cdecl; external CLibCrypto name 'd2i_ESS_CERT_ID_V2';
  function i2d_ESS_CERT_ID_V2(a: PESS_CERT_ID_V2; out_: PPbyte): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'i2d_ESS_CERT_ID_V2';
  function ESS_CERT_ID_V2_dup(a: PESS_CERT_ID_V2): PESS_CERT_ID_V2; cdecl; external CLibCrypto name 'ESS_CERT_ID_V2_dup';
  function ESS_SIGNING_CERT_V2_new: PESS_SIGNING_CERT_V2; cdecl; external CLibCrypto name 'ESS_SIGNING_CERT_V2_new';
  procedure ESS_SIGNING_CERT_V2_free(a: PESS_SIGNING_CERT_V2); cdecl; external CLibCrypto name 'ESS_SIGNING_CERT_V2_free';
  function d2i_ESS_SIGNING_CERT_V2(a: PPESS_SIGNING_CERT_V2; in_: PPbyte; len: TOpenSSL_C_INT): PESS_SIGNING_CERT_V2; cdecl; external CLibCrypto name 'd2i_ESS_SIGNING_CERT_V2';
  function i2d_ESS_SIGNING_CERT_V2(a: PESS_SIGNING_CERT_V2; out_: PPbyte): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'i2d_ESS_SIGNING_CERT_V2';
  function ESS_SIGNING_CERT_V2_it: PASN1_ITEM; cdecl; external CLibCrypto name 'ESS_SIGNING_CERT_V2_it';
  function ESS_SIGNING_CERT_V2_dup(a: PESS_SIGNING_CERT_V2): PESS_SIGNING_CERT_V2; cdecl; external CLibCrypto name 'ESS_SIGNING_CERT_V2_dup';
  function OSSL_ESS_signing_cert_new_init(signcert: PX509; certs: Pstack_st_X509; set_issuer_serial: TOpenSSL_C_INT): PESS_SIGNING_CERT; cdecl; external CLibCrypto name 'OSSL_ESS_signing_cert_new_init';
  function OSSL_ESS_signing_cert_v2_new_init(hash_alg: PEVP_MD; signcert: PX509; certs: Pstack_st_X509; set_issuer_serial: TOpenSSL_C_INT): PESS_SIGNING_CERT_V2; cdecl; external CLibCrypto name 'OSSL_ESS_signing_cert_v2_new_init';
  function OSSL_ESS_check_signing_certs(ss: PESS_SIGNING_CERT; ssv2: PESS_SIGNING_CERT_V2; chain: Pstack_st_X509; require_signing_cert: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OSSL_ESS_check_signing_certs';
  {$else}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_num}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_value}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_new}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_new_null}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_new_reserve}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_reserve}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_free}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_zero}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_delete}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_delete_ptr}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_push}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_unshift}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_pop}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_shift}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_pop_free}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_insert}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_set}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_find}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_find_ex}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_find_all}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_sort}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_is_sorted}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_dup}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_deep_copy}
  {$EXTERNALSYM sk_ESS_CERT_ID_V2_set_cmp_func}
  {$EXTERNALSYM ESS_ISSUER_SERIAL_new}
  {$EXTERNALSYM ESS_ISSUER_SERIAL_free}
  {$EXTERNALSYM d2i_ESS_ISSUER_SERIAL}
  {$EXTERNALSYM i2d_ESS_ISSUER_SERIAL}
  {$EXTERNALSYM ESS_ISSUER_SERIAL_dup}
  {$EXTERNALSYM ESS_CERT_ID_new}
  {$EXTERNALSYM ESS_CERT_ID_free}
  {$EXTERNALSYM d2i_ESS_CERT_ID}
  {$EXTERNALSYM i2d_ESS_CERT_ID}
  {$EXTERNALSYM ESS_CERT_ID_dup}
  {$EXTERNALSYM ESS_SIGNING_CERT_new}
  {$EXTERNALSYM ESS_SIGNING_CERT_free}
  {$EXTERNALSYM d2i_ESS_SIGNING_CERT}
  {$EXTERNALSYM i2d_ESS_SIGNING_CERT}
  {$EXTERNALSYM ESS_SIGNING_CERT_it}
  {$EXTERNALSYM ESS_SIGNING_CERT_dup}
  {$EXTERNALSYM ESS_CERT_ID_V2_new}
  {$EXTERNALSYM ESS_CERT_ID_V2_free}
  {$EXTERNALSYM d2i_ESS_CERT_ID_V2}
  {$EXTERNALSYM i2d_ESS_CERT_ID_V2}
  {$EXTERNALSYM ESS_CERT_ID_V2_dup}
  {$EXTERNALSYM ESS_SIGNING_CERT_V2_new}
  {$EXTERNALSYM ESS_SIGNING_CERT_V2_free}
  {$EXTERNALSYM d2i_ESS_SIGNING_CERT_V2}
  {$EXTERNALSYM i2d_ESS_SIGNING_CERT_V2}
  {$EXTERNALSYM ESS_SIGNING_CERT_V2_it}
  {$EXTERNALSYM ESS_SIGNING_CERT_V2_dup}
  {$EXTERNALSYM OSSL_ESS_signing_cert_new_init}
  {$EXTERNALSYM OSSL_ESS_signing_cert_v2_new_init}
  {$EXTERNALSYM OSSL_ESS_check_signing_certs}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_sk_ESS_CERT_ID_V2_num(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_V2_value(_para: Pstack_st_ESS_CERT_ID_V2; _para2: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID_V2; cdecl;
  function Load_sk_ESS_CERT_ID_V2_new(cmp: Tsk_ESS_CERT_ID_V2_compfunc): Pstack_st_ESS_CERT_ID_V2; cdecl;
  function Load_sk_ESS_CERT_ID_V2_new_null: Pstack_st_ESS_CERT_ID_V2; cdecl;
  function Load_sk_ESS_CERT_ID_V2_new_reserve(cmp: Tsk_ESS_CERT_ID_V2_compfunc; n: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID_V2; cdecl;
  function Load_sk_ESS_CERT_ID_V2_reserve(_para: Pstack_st_ESS_CERT_ID_V2; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_V2_free(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_V2_zero(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_V2_delete(st: Pstack_st_ESS_CERT_ID_V2; loc: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID_V2; cdecl;
  function Load_sk_ESS_CERT_ID_V2_delete_ptr(st: Pstack_st_ESS_CERT_ID_V2; ptr: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl;
  function Load_sk_ESS_CERT_ID_V2_push(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_V2_unshift(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_V2_pop(_para: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl;
  function Load_sk_ESS_CERT_ID_V2_shift(_para: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl;
  procedure Load_sk_ESS_CERT_ID_V2_pop_free(st: Pstack_st_ESS_CERT_ID_V2; func: Tsk_ESS_CERT_ID_V2_freefunc); cdecl;
  function Load_sk_ESS_CERT_ID_V2_insert(st: Pstack_st_ESS_CERT_ID_V2; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_V2_set(st: Pstack_st_ESS_CERT_ID_V2; i: TOpenSSL_C_INT; data: pointer): Pstack_st_ESS_CERT_ID_V2; cdecl;
  function Load_sk_ESS_CERT_ID_V2_find(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_V2_find_ex(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_V2_find_all(st: Pstack_st_ESS_CERT_ID_V2; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_V2_sort(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_V2_is_sorted(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl;
  function Load_sk_ESS_CERT_ID_V2_dup(st: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl;
  function Load_sk_ESS_CERT_ID_V2_deep_copy(st: Pstack_st_ESS_CERT_ID_V2; c: Tsk_ESS_CERT_ID_V2_compfunc; f: Tsk_ESS_CERT_ID_V2_freefunc): Pstack_st_ESS_CERT_ID_V2; cdecl;
  function Load_sk_ESS_CERT_ID_V2_set_cmp_func(st: Pstack_st_ESS_CERT_ID_V2; cmp: Tsk_ESS_CERT_ID_V2_compfunc): Tsk_ESS_CERT_ID_V2_compfunc; cdecl;
  function Load_ESS_ISSUER_SERIAL_new: PESS_ISSUER_SERIAL; cdecl;
  procedure Load_ESS_ISSUER_SERIAL_free(a: PESS_ISSUER_SERIAL); cdecl;
  function Load_d2i_ESS_ISSUER_SERIAL(a: PPESS_ISSUER_SERIAL; in_: PPbyte; len: TOpenSSL_C_INT): PESS_ISSUER_SERIAL; cdecl;
  function Load_i2d_ESS_ISSUER_SERIAL(a: PESS_ISSUER_SERIAL; out_: PPbyte): TOpenSSL_C_INT; cdecl;
  function Load_ESS_ISSUER_SERIAL_dup(a: PESS_ISSUER_SERIAL): PESS_ISSUER_SERIAL; cdecl;
  function Load_ESS_CERT_ID_new: PESS_CERT_ID; cdecl;
  procedure Load_ESS_CERT_ID_free(a: PESS_CERT_ID); cdecl;
  function Load_d2i_ESS_CERT_ID(a: PPESS_CERT_ID; in_: PPbyte; len: TOpenSSL_C_INT): PESS_CERT_ID; cdecl;
  function Load_i2d_ESS_CERT_ID(a: PESS_CERT_ID; out_: PPbyte): TOpenSSL_C_INT; cdecl;
  function Load_ESS_CERT_ID_dup(a: PESS_CERT_ID): PESS_CERT_ID; cdecl;
  function Load_ESS_SIGNING_CERT_new: PESS_SIGNING_CERT; cdecl;
  procedure Load_ESS_SIGNING_CERT_free(a: PESS_SIGNING_CERT); cdecl;
  function Load_d2i_ESS_SIGNING_CERT(a: PPESS_SIGNING_CERT; in_: PPbyte; len: TOpenSSL_C_INT): PESS_SIGNING_CERT; cdecl;
  function Load_i2d_ESS_SIGNING_CERT(a: PESS_SIGNING_CERT; out_: PPbyte): TOpenSSL_C_INT; cdecl;
  function Load_ESS_SIGNING_CERT_it: PASN1_ITEM; cdecl;
  function Load_ESS_SIGNING_CERT_dup(a: PESS_SIGNING_CERT): PESS_SIGNING_CERT; cdecl;
  function Load_ESS_CERT_ID_V2_new: PESS_CERT_ID_V2; cdecl;
  procedure Load_ESS_CERT_ID_V2_free(a: PESS_CERT_ID_V2); cdecl;
  function Load_d2i_ESS_CERT_ID_V2(a: PPESS_CERT_ID_V2; in_: PPbyte; len: TOpenSSL_C_INT): PESS_CERT_ID_V2; cdecl;
  function Load_i2d_ESS_CERT_ID_V2(a: PESS_CERT_ID_V2; out_: PPbyte): TOpenSSL_C_INT; cdecl;
  function Load_ESS_CERT_ID_V2_dup(a: PESS_CERT_ID_V2): PESS_CERT_ID_V2; cdecl;
  function Load_ESS_SIGNING_CERT_V2_new: PESS_SIGNING_CERT_V2; cdecl;
  procedure Load_ESS_SIGNING_CERT_V2_free(a: PESS_SIGNING_CERT_V2); cdecl;
  function Load_d2i_ESS_SIGNING_CERT_V2(a: PPESS_SIGNING_CERT_V2; in_: PPbyte; len: TOpenSSL_C_INT): PESS_SIGNING_CERT_V2; cdecl;
  function Load_i2d_ESS_SIGNING_CERT_V2(a: PESS_SIGNING_CERT_V2; out_: PPbyte): TOpenSSL_C_INT; cdecl;
  function Load_ESS_SIGNING_CERT_V2_it: PASN1_ITEM; cdecl;
  function Load_ESS_SIGNING_CERT_V2_dup(a: PESS_SIGNING_CERT_V2): PESS_SIGNING_CERT_V2; cdecl;
  function Load_OSSL_ESS_signing_cert_new_init(signcert: PX509; certs: Pstack_st_X509; set_issuer_serial: TOpenSSL_C_INT): PESS_SIGNING_CERT; cdecl;
  function Load_OSSL_ESS_signing_cert_v2_new_init(hash_alg: PEVP_MD; signcert: PX509; certs: Pstack_st_X509; set_issuer_serial: TOpenSSL_C_INT): PESS_SIGNING_CERT_V2; cdecl;
  function Load_OSSL_ESS_check_signing_certs(ss: PESS_SIGNING_CERT; ssv2: PESS_SIGNING_CERT_V2; chain: Pstack_st_X509; require_signing_cert: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;

var
  sk_ESS_CERT_ID_V2_num: function(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_V2_num;
  sk_ESS_CERT_ID_V2_value: function(_para: Pstack_st_ESS_CERT_ID_V2; _para2: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID_V2; cdecl = Load_sk_ESS_CERT_ID_V2_value;
  sk_ESS_CERT_ID_V2_new: function(cmp: Tsk_ESS_CERT_ID_V2_compfunc): Pstack_st_ESS_CERT_ID_V2; cdecl = Load_sk_ESS_CERT_ID_V2_new;
  sk_ESS_CERT_ID_V2_new_null: function: Pstack_st_ESS_CERT_ID_V2; cdecl = Load_sk_ESS_CERT_ID_V2_new_null;
  sk_ESS_CERT_ID_V2_new_reserve: function(cmp: Tsk_ESS_CERT_ID_V2_compfunc; n: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID_V2; cdecl = Load_sk_ESS_CERT_ID_V2_new_reserve;
  sk_ESS_CERT_ID_V2_reserve: function(_para: Pstack_st_ESS_CERT_ID_V2; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_V2_reserve;
  sk_ESS_CERT_ID_V2_free: function(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_V2_free;
  sk_ESS_CERT_ID_V2_zero: function(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_V2_zero;
  sk_ESS_CERT_ID_V2_delete: function(st: Pstack_st_ESS_CERT_ID_V2; loc: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID_V2; cdecl = Load_sk_ESS_CERT_ID_V2_delete;
  sk_ESS_CERT_ID_V2_delete_ptr: function(st: Pstack_st_ESS_CERT_ID_V2; ptr: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl = Load_sk_ESS_CERT_ID_V2_delete_ptr;
  sk_ESS_CERT_ID_V2_push: function(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_V2_push;
  sk_ESS_CERT_ID_V2_unshift: function(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_V2_unshift;
  sk_ESS_CERT_ID_V2_pop: function(_para: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl = Load_sk_ESS_CERT_ID_V2_pop;
  sk_ESS_CERT_ID_V2_shift: function(_para: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl = Load_sk_ESS_CERT_ID_V2_shift;
  sk_ESS_CERT_ID_V2_pop_free: procedure(st: Pstack_st_ESS_CERT_ID_V2; func: Tsk_ESS_CERT_ID_V2_freefunc); cdecl = Load_sk_ESS_CERT_ID_V2_pop_free;
  sk_ESS_CERT_ID_V2_insert: function(st: Pstack_st_ESS_CERT_ID_V2; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_V2_insert;
  sk_ESS_CERT_ID_V2_set: function(st: Pstack_st_ESS_CERT_ID_V2; i: TOpenSSL_C_INT; data: pointer): Pstack_st_ESS_CERT_ID_V2; cdecl = Load_sk_ESS_CERT_ID_V2_set;
  sk_ESS_CERT_ID_V2_find: function(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_V2_find;
  sk_ESS_CERT_ID_V2_find_ex: function(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_V2_find_ex;
  sk_ESS_CERT_ID_V2_find_all: function(st: Pstack_st_ESS_CERT_ID_V2; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_V2_find_all;
  sk_ESS_CERT_ID_V2_sort: function(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_V2_sort;
  sk_ESS_CERT_ID_V2_is_sorted: function(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl = Load_sk_ESS_CERT_ID_V2_is_sorted;
  sk_ESS_CERT_ID_V2_dup: function(st: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl = Load_sk_ESS_CERT_ID_V2_dup;
  sk_ESS_CERT_ID_V2_deep_copy: function(st: Pstack_st_ESS_CERT_ID_V2; c: Tsk_ESS_CERT_ID_V2_compfunc; f: Tsk_ESS_CERT_ID_V2_freefunc): Pstack_st_ESS_CERT_ID_V2; cdecl = Load_sk_ESS_CERT_ID_V2_deep_copy;
  sk_ESS_CERT_ID_V2_set_cmp_func: function(st: Pstack_st_ESS_CERT_ID_V2; cmp: Tsk_ESS_CERT_ID_V2_compfunc): Tsk_ESS_CERT_ID_V2_compfunc; cdecl = Load_sk_ESS_CERT_ID_V2_set_cmp_func;
  { clang-format on }
  ESS_ISSUER_SERIAL_new: function: PESS_ISSUER_SERIAL; cdecl = Load_ESS_ISSUER_SERIAL_new;
  ESS_ISSUER_SERIAL_free: procedure(a: PESS_ISSUER_SERIAL); cdecl = Load_ESS_ISSUER_SERIAL_free;
  d2i_ESS_ISSUER_SERIAL: function(a: PPESS_ISSUER_SERIAL; in_: PPbyte; len: TOpenSSL_C_INT): PESS_ISSUER_SERIAL; cdecl = Load_d2i_ESS_ISSUER_SERIAL;
  i2d_ESS_ISSUER_SERIAL: function(a: PESS_ISSUER_SERIAL; out_: PPbyte): TOpenSSL_C_INT; cdecl = Load_i2d_ESS_ISSUER_SERIAL;
  ESS_ISSUER_SERIAL_dup: function(a: PESS_ISSUER_SERIAL): PESS_ISSUER_SERIAL; cdecl = Load_ESS_ISSUER_SERIAL_dup;
  ESS_CERT_ID_new: function: PESS_CERT_ID; cdecl = Load_ESS_CERT_ID_new;
  ESS_CERT_ID_free: procedure(a: PESS_CERT_ID); cdecl = Load_ESS_CERT_ID_free;
  d2i_ESS_CERT_ID: function(a: PPESS_CERT_ID; in_: PPbyte; len: TOpenSSL_C_INT): PESS_CERT_ID; cdecl = Load_d2i_ESS_CERT_ID;
  i2d_ESS_CERT_ID: function(a: PESS_CERT_ID; out_: PPbyte): TOpenSSL_C_INT; cdecl = Load_i2d_ESS_CERT_ID;
  ESS_CERT_ID_dup: function(a: PESS_CERT_ID): PESS_CERT_ID; cdecl = Load_ESS_CERT_ID_dup;
  ESS_SIGNING_CERT_new: function: PESS_SIGNING_CERT; cdecl = Load_ESS_SIGNING_CERT_new;
  ESS_SIGNING_CERT_free: procedure(a: PESS_SIGNING_CERT); cdecl = Load_ESS_SIGNING_CERT_free;
  d2i_ESS_SIGNING_CERT: function(a: PPESS_SIGNING_CERT; in_: PPbyte; len: TOpenSSL_C_INT): PESS_SIGNING_CERT; cdecl = Load_d2i_ESS_SIGNING_CERT;
  i2d_ESS_SIGNING_CERT: function(a: PESS_SIGNING_CERT; out_: PPbyte): TOpenSSL_C_INT; cdecl = Load_i2d_ESS_SIGNING_CERT;
  ESS_SIGNING_CERT_it: function: PASN1_ITEM; cdecl = Load_ESS_SIGNING_CERT_it;
  ESS_SIGNING_CERT_dup: function(a: PESS_SIGNING_CERT): PESS_SIGNING_CERT; cdecl = Load_ESS_SIGNING_CERT_dup;
  ESS_CERT_ID_V2_new: function: PESS_CERT_ID_V2; cdecl = Load_ESS_CERT_ID_V2_new;
  ESS_CERT_ID_V2_free: procedure(a: PESS_CERT_ID_V2); cdecl = Load_ESS_CERT_ID_V2_free;
  d2i_ESS_CERT_ID_V2: function(a: PPESS_CERT_ID_V2; in_: PPbyte; len: TOpenSSL_C_INT): PESS_CERT_ID_V2; cdecl = Load_d2i_ESS_CERT_ID_V2;
  i2d_ESS_CERT_ID_V2: function(a: PESS_CERT_ID_V2; out_: PPbyte): TOpenSSL_C_INT; cdecl = Load_i2d_ESS_CERT_ID_V2;
  ESS_CERT_ID_V2_dup: function(a: PESS_CERT_ID_V2): PESS_CERT_ID_V2; cdecl = Load_ESS_CERT_ID_V2_dup;
  ESS_SIGNING_CERT_V2_new: function: PESS_SIGNING_CERT_V2; cdecl = Load_ESS_SIGNING_CERT_V2_new;
  ESS_SIGNING_CERT_V2_free: procedure(a: PESS_SIGNING_CERT_V2); cdecl = Load_ESS_SIGNING_CERT_V2_free;
  d2i_ESS_SIGNING_CERT_V2: function(a: PPESS_SIGNING_CERT_V2; in_: PPbyte; len: TOpenSSL_C_INT): PESS_SIGNING_CERT_V2; cdecl = Load_d2i_ESS_SIGNING_CERT_V2;
  i2d_ESS_SIGNING_CERT_V2: function(a: PESS_SIGNING_CERT_V2; out_: PPbyte): TOpenSSL_C_INT; cdecl = Load_i2d_ESS_SIGNING_CERT_V2;
  ESS_SIGNING_CERT_V2_it: function: PASN1_ITEM; cdecl = Load_ESS_SIGNING_CERT_V2_it;
  ESS_SIGNING_CERT_V2_dup: function(a: PESS_SIGNING_CERT_V2): PESS_SIGNING_CERT_V2; cdecl = Load_ESS_SIGNING_CERT_V2_dup;
  OSSL_ESS_signing_cert_new_init: function(signcert: PX509; certs: Pstack_st_X509; set_issuer_serial: TOpenSSL_C_INT): PESS_SIGNING_CERT; cdecl = Load_OSSL_ESS_signing_cert_new_init;
  OSSL_ESS_signing_cert_v2_new_init: function(hash_alg: PEVP_MD; signcert: PX509; certs: Pstack_st_X509; set_issuer_serial: TOpenSSL_C_INT): PESS_SIGNING_CERT_V2; cdecl = Load_OSSL_ESS_signing_cert_v2_new_init;
  OSSL_ESS_check_signing_certs: function(ss: PESS_SIGNING_CERT; ssv2: PESS_SIGNING_CERT_V2; chain: Pstack_st_X509; require_signing_cert: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_OSSL_ESS_check_signing_certs;
  {$endif} {OPENSSL_STATIC_LINK_MODEL}
{$endif}

implementation

uses Sysutils, variants
  {$ifdef OPENSSL_INTERNAL_NEED_THREADS}
   {$IFNDEF FPC}
     ,System.SyncObjs
     {$IFDEF POSIX}
       ,Posix.Pthread
     {$ELSE}
       ,Windows
     {$ENDIF}
   {$ELSE}
     ,SyncObjs
   {$ENDIF}
  {$endif}
  ,Classes, OpenSSLExceptionHandlers;

  {$if not declared(__FILE__)}
  const
    {$ifdef FPC}
    __FILE__ = {$include %FILE%};
    {$else}
    __FILE__ = '$(INPUTFILENAME)';
    {$endif}
  {$ifend}
  {$if not declared(__LINE__)}
  const
    __LINE__ = 0;
  {$ifend}
  {$if not declared(OPENSSL_FILE)}
  const
    OPENSSL_FILE = __FILE__;
  {$ifend}
  {$if not declared(OPENSSL_LINE)}
  const
    OPENSSL_LINE  = 0;
  {$ifend}

procedure sk_ESS_CERT_ID_freefunc_thunk(freefunc_arg: TOPENSSL_sk_freefunc; ptr: pointer); inline;
begin
  raise Exception.Create('Unable to translate C Function "sk_ESS_CERT_ID_freefunc_thunk"');

{Error: Line 35: Syntax Error parsing " sk_ESS_CERT_ID_freefunc freefunc = (sk_ESS_CERT_ID_freefunc)freefunc_arg; freefunc((ESS_CERT_ID 
*)ptr); "

 sk_ESS_CERT_ID_freefunc freefunc = (sk_ESS_CERT_ID_freefunc)freefunc_arg; freefunc((ESS_CERT_ID *)ptr); }
end;

function ossl_check_ESS_CERT_ID_type(ptr: PESS_CERT_ID): PESS_CERT_ID{Has C Attribute: unused}; inline;
begin
   Result := ptr;
end;

function ossl_check_const_ESS_CERT_ID_sk_type(sk: Pstack_st_ESS_CERT_ID): POPENSSL_STACK{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_STACK(sk);
end;

function ossl_check_ESS_CERT_ID_sk_type(sk: Pstack_st_ESS_CERT_ID): POPENSSL_STACK{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_STACK(sk);
end;

function ossl_check_ESS_CERT_ID_compfunc_type(cmp: Tsk_ESS_CERT_ID_compfunc): TOPENSSL_sk_compfunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_compfunc(cmp);
end;

function ossl_check_ESS_CERT_ID_copyfunc_type(cpy: Tsk_ESS_CERT_ID_copyfunc): TOPENSSL_sk_copyfunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_copyfunc(cpy);
end;

function ossl_check_ESS_CERT_ID_freefunc_type(fr: Tsk_ESS_CERT_ID_freefunc): TOPENSSL_sk_freefunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_freefunc(fr);
end;

procedure sk_ESS_CERT_ID_V2_freefunc_thunk(freefunc_arg: TOPENSSL_sk_freefunc; ptr: pointer); inline;
begin
  raise Exception.Create('Unable to translate C Function "sk_ESS_CERT_ID_V2_freefunc_thunk"');

{Error: Line 68: Syntax Error parsing " sk_ESS_CERT_ID_V2_freefunc freefunc = (sk_ESS_CERT_ID_V2_freefunc)freefunc_arg; freefunc((ESS_CERT_ID_V2 
*)ptr); "

 sk_ESS_CERT_ID_V2_freefunc freefunc = (sk_ESS_CERT_ID_V2_freefunc)freefunc_arg; freefunc((ESS_CERT_ID_V2 *)ptr); }
end;

function ossl_check_ESS_CERT_ID_V2_type(ptr: PESS_CERT_ID_V2): PESS_CERT_ID_V2{Has C Attribute: unused}; inline;
begin
   Result := ptr;
end;

function ossl_check_const_ESS_CERT_ID_V2_sk_type(sk: Pstack_st_ESS_CERT_ID_V2): POPENSSL_STACK{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_STACK(sk);
end;

function ossl_check_ESS_CERT_ID_V2_sk_type(sk: Pstack_st_ESS_CERT_ID_V2): POPENSSL_STACK{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_STACK(sk);
end;

function ossl_check_ESS_CERT_ID_V2_compfunc_type(cmp: Tsk_ESS_CERT_ID_V2_compfunc): TOPENSSL_sk_compfunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_compfunc(cmp);
end;

function ossl_check_ESS_CERT_ID_V2_copyfunc_type(cpy: Tsk_ESS_CERT_ID_V2_copyfunc): TOPENSSL_sk_copyfunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_copyfunc(cpy);
end;

function ossl_check_ESS_CERT_ID_V2_freefunc_type(fr: Tsk_ESS_CERT_ID_V2_freefunc): TOPENSSL_sk_freefunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_freefunc(fr);
end;

{$ifndef OPENSSL_STATIC_LINK_MODEL}
function Load_sk_ESS_CERT_ID_num(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_num := LoadLibCryptoFunction('OPENSSL_sk_num');
  if not assigned(sk_ESS_CERT_ID_num) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_num');
  Result := sk_ESS_CERT_ID_num(_para);
end;

function Load_sk_ESS_CERT_ID_value(_para: Pstack_st_ESS_CERT_ID; _para2: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID; cdecl;
begin
  sk_ESS_CERT_ID_value := LoadLibCryptoFunction('OPENSSL_sk_value');
  if not assigned(sk_ESS_CERT_ID_value) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_value');
  Result := sk_ESS_CERT_ID_value(_para, _para2);
end;

function Load_sk_ESS_CERT_ID_new(cmp: Tsk_ESS_CERT_ID_compfunc): Pstack_st_ESS_CERT_ID; cdecl;
begin
  sk_ESS_CERT_ID_new := LoadLibCryptoFunction('OPENSSL_sk_new');
  if not assigned(sk_ESS_CERT_ID_new) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new');
  Result := sk_ESS_CERT_ID_new(cmp);
end;

function Load_sk_ESS_CERT_ID_new_null: Pstack_st_ESS_CERT_ID; cdecl;
begin
  sk_ESS_CERT_ID_new_null := LoadLibCryptoFunction('OPENSSL_sk_new_null');
  if not assigned(sk_ESS_CERT_ID_new_null) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new_null');
  Result := sk_ESS_CERT_ID_new_null;
end;

function Load_sk_ESS_CERT_ID_new_reserve(cmp: Tsk_ESS_CERT_ID_compfunc; n: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID; cdecl;
begin
  sk_ESS_CERT_ID_new_reserve := LoadLibCryptoFunction('OPENSSL_sk_new_reserve');
  if not assigned(sk_ESS_CERT_ID_new_reserve) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new_reserve');
  Result := sk_ESS_CERT_ID_new_reserve(cmp, n);
end;

function Load_sk_ESS_CERT_ID_reserve(_para: Pstack_st_ESS_CERT_ID; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_reserve := LoadLibCryptoFunction('OPENSSL_sk_reserve');
  if not assigned(sk_ESS_CERT_ID_reserve) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_reserve');
  Result := sk_ESS_CERT_ID_reserve(_para, n);
end;

function Load_sk_ESS_CERT_ID_free(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_free := LoadLibCryptoFunction('OPENSSL_sk_free');
  if not assigned(sk_ESS_CERT_ID_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_free');
  Result := sk_ESS_CERT_ID_free(_para);
end;

function Load_sk_ESS_CERT_ID_zero(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_zero := LoadLibCryptoFunction('OPENSSL_sk_zero');
  if not assigned(sk_ESS_CERT_ID_zero) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_zero');
  Result := sk_ESS_CERT_ID_zero(_para);
end;

function Load_sk_ESS_CERT_ID_delete(st: Pstack_st_ESS_CERT_ID; loc: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID; cdecl;
begin
  sk_ESS_CERT_ID_delete := LoadLibCryptoFunction('OPENSSL_sk_delete');
  if not assigned(sk_ESS_CERT_ID_delete) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_delete');
  Result := sk_ESS_CERT_ID_delete(st, loc);
end;

function Load_sk_ESS_CERT_ID_delete_ptr(st: Pstack_st_ESS_CERT_ID; ptr: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl;
begin
  sk_ESS_CERT_ID_delete_ptr := LoadLibCryptoFunction('OPENSSL_sk_delete_ptr');
  if not assigned(sk_ESS_CERT_ID_delete_ptr) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_delete_ptr');
  Result := sk_ESS_CERT_ID_delete_ptr(st, ptr);
end;

function Load_sk_ESS_CERT_ID_push(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_push := LoadLibCryptoFunction('OPENSSL_sk_push');
  if not assigned(sk_ESS_CERT_ID_push) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_push');
  Result := sk_ESS_CERT_ID_push(st, data);
end;

function Load_sk_ESS_CERT_ID_unshift(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_unshift := LoadLibCryptoFunction('OPENSSL_sk_unshift');
  if not assigned(sk_ESS_CERT_ID_unshift) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_unshift');
  Result := sk_ESS_CERT_ID_unshift(st, data);
end;

function Load_sk_ESS_CERT_ID_pop(_para: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl;
begin
  sk_ESS_CERT_ID_pop := LoadLibCryptoFunction('OPENSSL_sk_pop');
  if not assigned(sk_ESS_CERT_ID_pop) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_pop');
  Result := sk_ESS_CERT_ID_pop(_para);
end;

function Load_sk_ESS_CERT_ID_shift(_para: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl;
begin
  sk_ESS_CERT_ID_shift := LoadLibCryptoFunction('OPENSSL_sk_shift');
  if not assigned(sk_ESS_CERT_ID_shift) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_shift');
  Result := sk_ESS_CERT_ID_shift(_para);
end;

procedure Load_sk_ESS_CERT_ID_pop_free(st: Pstack_st_ESS_CERT_ID; func: Tsk_ESS_CERT_ID_freefunc); cdecl;
begin
  sk_ESS_CERT_ID_pop_free := LoadLibCryptoFunction('OPENSSL_sk_pop_free');
  if not assigned(sk_ESS_CERT_ID_pop_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_pop_free');
  sk_ESS_CERT_ID_pop_free(st, func);
end;

function Load_sk_ESS_CERT_ID_insert(st: Pstack_st_ESS_CERT_ID; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_insert := LoadLibCryptoFunction('OPENSSL_sk_insert');
  if not assigned(sk_ESS_CERT_ID_insert) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_insert');
  Result := sk_ESS_CERT_ID_insert(st, data, where);
end;

function Load_sk_ESS_CERT_ID_set(st: Pstack_st_ESS_CERT_ID; i: TOpenSSL_C_INT; data: pointer): Pstack_st_ESS_CERT_ID; cdecl;
begin
  sk_ESS_CERT_ID_set := LoadLibCryptoFunction('OPENSSL_sk_set');
  if not assigned(sk_ESS_CERT_ID_set) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_set');
  Result := sk_ESS_CERT_ID_set(st, i, data);
end;

function Load_sk_ESS_CERT_ID_find(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_find := LoadLibCryptoFunction('OPENSSL_sk_find');
  if not assigned(sk_ESS_CERT_ID_find) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find');
  Result := sk_ESS_CERT_ID_find(st, data);
end;

function Load_sk_ESS_CERT_ID_find_ex(st: Pstack_st_ESS_CERT_ID; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_find_ex := LoadLibCryptoFunction('OPENSSL_sk_find_ex');
  if not assigned(sk_ESS_CERT_ID_find_ex) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find_ex');
  Result := sk_ESS_CERT_ID_find_ex(st, data);
end;

function Load_sk_ESS_CERT_ID_find_all(st: Pstack_st_ESS_CERT_ID; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_find_all := LoadLibCryptoFunction('OPENSSL_sk_find_all');
  if not assigned(sk_ESS_CERT_ID_find_all) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find_all');
  Result := sk_ESS_CERT_ID_find_all(st, data, pnum);
end;

function Load_sk_ESS_CERT_ID_sort(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_sort := LoadLibCryptoFunction('OPENSSL_sk_sort');
  if not assigned(sk_ESS_CERT_ID_sort) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_sort');
  Result := sk_ESS_CERT_ID_sort(_para);
end;

function Load_sk_ESS_CERT_ID_is_sorted(_para: Pstack_st_ESS_CERT_ID): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_is_sorted := LoadLibCryptoFunction('OPENSSL_sk_is_sorted');
  if not assigned(sk_ESS_CERT_ID_is_sorted) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_is_sorted');
  Result := sk_ESS_CERT_ID_is_sorted(_para);
end;

function Load_sk_ESS_CERT_ID_dup(st: Pstack_st_ESS_CERT_ID): Pstack_st_ESS_CERT_ID; cdecl;
begin
  sk_ESS_CERT_ID_dup := LoadLibCryptoFunction('OPENSSL_sk_dup');
  if not assigned(sk_ESS_CERT_ID_dup) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_dup');
  Result := sk_ESS_CERT_ID_dup(st);
end;

function Load_sk_ESS_CERT_ID_deep_copy(st: Pstack_st_ESS_CERT_ID; c: Tsk_ESS_CERT_ID_compfunc; f: Tsk_ESS_CERT_ID_freefunc): Pstack_st_ESS_CERT_ID; cdecl;
begin
  sk_ESS_CERT_ID_deep_copy := LoadLibCryptoFunction('OPENSSL_sk_deep_copy');
  if not assigned(sk_ESS_CERT_ID_deep_copy) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_deep_copy');
  Result := sk_ESS_CERT_ID_deep_copy(st, c, f);
end;

function Load_sk_ESS_CERT_ID_set_cmp_func(st: Pstack_st_ESS_CERT_ID; cmp: Tsk_ESS_CERT_ID_compfunc): Tsk_ESS_CERT_ID_compfunc; cdecl;
begin
  sk_ESS_CERT_ID_set_cmp_func := LoadLibCryptoFunction('OPENSSL_sk_set_cmp_func');
  if not assigned(sk_ESS_CERT_ID_set_cmp_func) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_set_cmp_func');
  Result := sk_ESS_CERT_ID_set_cmp_func(st, cmp);
end;

function Load_sk_ESS_CERT_ID_V2_num(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_V2_num := LoadLibCryptoFunction('OPENSSL_sk_num');
  if not assigned(sk_ESS_CERT_ID_V2_num) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_num');
  Result := sk_ESS_CERT_ID_V2_num(_para);
end;

function Load_sk_ESS_CERT_ID_V2_value(_para: Pstack_st_ESS_CERT_ID_V2; _para2: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID_V2; cdecl;
begin
  sk_ESS_CERT_ID_V2_value := LoadLibCryptoFunction('OPENSSL_sk_value');
  if not assigned(sk_ESS_CERT_ID_V2_value) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_value');
  Result := sk_ESS_CERT_ID_V2_value(_para, _para2);
end;

function Load_sk_ESS_CERT_ID_V2_new(cmp: Tsk_ESS_CERT_ID_V2_compfunc): Pstack_st_ESS_CERT_ID_V2; cdecl;
begin
  sk_ESS_CERT_ID_V2_new := LoadLibCryptoFunction('OPENSSL_sk_new');
  if not assigned(sk_ESS_CERT_ID_V2_new) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new');
  Result := sk_ESS_CERT_ID_V2_new(cmp);
end;

function Load_sk_ESS_CERT_ID_V2_new_null: Pstack_st_ESS_CERT_ID_V2; cdecl;
begin
  sk_ESS_CERT_ID_V2_new_null := LoadLibCryptoFunction('OPENSSL_sk_new_null');
  if not assigned(sk_ESS_CERT_ID_V2_new_null) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new_null');
  Result := sk_ESS_CERT_ID_V2_new_null;
end;

function Load_sk_ESS_CERT_ID_V2_new_reserve(cmp: Tsk_ESS_CERT_ID_V2_compfunc; n: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID_V2; cdecl;
begin
  sk_ESS_CERT_ID_V2_new_reserve := LoadLibCryptoFunction('OPENSSL_sk_new_reserve');
  if not assigned(sk_ESS_CERT_ID_V2_new_reserve) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new_reserve');
  Result := sk_ESS_CERT_ID_V2_new_reserve(cmp, n);
end;

function Load_sk_ESS_CERT_ID_V2_reserve(_para: Pstack_st_ESS_CERT_ID_V2; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_V2_reserve := LoadLibCryptoFunction('OPENSSL_sk_reserve');
  if not assigned(sk_ESS_CERT_ID_V2_reserve) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_reserve');
  Result := sk_ESS_CERT_ID_V2_reserve(_para, n);
end;

function Load_sk_ESS_CERT_ID_V2_free(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_V2_free := LoadLibCryptoFunction('OPENSSL_sk_free');
  if not assigned(sk_ESS_CERT_ID_V2_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_free');
  Result := sk_ESS_CERT_ID_V2_free(_para);
end;

function Load_sk_ESS_CERT_ID_V2_zero(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_V2_zero := LoadLibCryptoFunction('OPENSSL_sk_zero');
  if not assigned(sk_ESS_CERT_ID_V2_zero) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_zero');
  Result := sk_ESS_CERT_ID_V2_zero(_para);
end;

function Load_sk_ESS_CERT_ID_V2_delete(st: Pstack_st_ESS_CERT_ID_V2; loc: TOpenSSL_C_INT): Pstack_st_ESS_CERT_ID_V2; cdecl;
begin
  sk_ESS_CERT_ID_V2_delete := LoadLibCryptoFunction('OPENSSL_sk_delete');
  if not assigned(sk_ESS_CERT_ID_V2_delete) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_delete');
  Result := sk_ESS_CERT_ID_V2_delete(st, loc);
end;

function Load_sk_ESS_CERT_ID_V2_delete_ptr(st: Pstack_st_ESS_CERT_ID_V2; ptr: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl;
begin
  sk_ESS_CERT_ID_V2_delete_ptr := LoadLibCryptoFunction('OPENSSL_sk_delete_ptr');
  if not assigned(sk_ESS_CERT_ID_V2_delete_ptr) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_delete_ptr');
  Result := sk_ESS_CERT_ID_V2_delete_ptr(st, ptr);
end;

function Load_sk_ESS_CERT_ID_V2_push(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_V2_push := LoadLibCryptoFunction('OPENSSL_sk_push');
  if not assigned(sk_ESS_CERT_ID_V2_push) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_push');
  Result := sk_ESS_CERT_ID_V2_push(st, data);
end;

function Load_sk_ESS_CERT_ID_V2_unshift(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_V2_unshift := LoadLibCryptoFunction('OPENSSL_sk_unshift');
  if not assigned(sk_ESS_CERT_ID_V2_unshift) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_unshift');
  Result := sk_ESS_CERT_ID_V2_unshift(st, data);
end;

function Load_sk_ESS_CERT_ID_V2_pop(_para: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl;
begin
  sk_ESS_CERT_ID_V2_pop := LoadLibCryptoFunction('OPENSSL_sk_pop');
  if not assigned(sk_ESS_CERT_ID_V2_pop) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_pop');
  Result := sk_ESS_CERT_ID_V2_pop(_para);
end;

function Load_sk_ESS_CERT_ID_V2_shift(_para: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl;
begin
  sk_ESS_CERT_ID_V2_shift := LoadLibCryptoFunction('OPENSSL_sk_shift');
  if not assigned(sk_ESS_CERT_ID_V2_shift) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_shift');
  Result := sk_ESS_CERT_ID_V2_shift(_para);
end;

procedure Load_sk_ESS_CERT_ID_V2_pop_free(st: Pstack_st_ESS_CERT_ID_V2; func: Tsk_ESS_CERT_ID_V2_freefunc); cdecl;
begin
  sk_ESS_CERT_ID_V2_pop_free := LoadLibCryptoFunction('OPENSSL_sk_pop_free');
  if not assigned(sk_ESS_CERT_ID_V2_pop_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_pop_free');
  sk_ESS_CERT_ID_V2_pop_free(st, func);
end;

function Load_sk_ESS_CERT_ID_V2_insert(st: Pstack_st_ESS_CERT_ID_V2; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_V2_insert := LoadLibCryptoFunction('OPENSSL_sk_insert');
  if not assigned(sk_ESS_CERT_ID_V2_insert) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_insert');
  Result := sk_ESS_CERT_ID_V2_insert(st, data, where);
end;

function Load_sk_ESS_CERT_ID_V2_set(st: Pstack_st_ESS_CERT_ID_V2; i: TOpenSSL_C_INT; data: pointer): Pstack_st_ESS_CERT_ID_V2; cdecl;
begin
  sk_ESS_CERT_ID_V2_set := LoadLibCryptoFunction('OPENSSL_sk_set');
  if not assigned(sk_ESS_CERT_ID_V2_set) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_set');
  Result := sk_ESS_CERT_ID_V2_set(st, i, data);
end;

function Load_sk_ESS_CERT_ID_V2_find(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_V2_find := LoadLibCryptoFunction('OPENSSL_sk_find');
  if not assigned(sk_ESS_CERT_ID_V2_find) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find');
  Result := sk_ESS_CERT_ID_V2_find(st, data);
end;

function Load_sk_ESS_CERT_ID_V2_find_ex(st: Pstack_st_ESS_CERT_ID_V2; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_V2_find_ex := LoadLibCryptoFunction('OPENSSL_sk_find_ex');
  if not assigned(sk_ESS_CERT_ID_V2_find_ex) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find_ex');
  Result := sk_ESS_CERT_ID_V2_find_ex(st, data);
end;

function Load_sk_ESS_CERT_ID_V2_find_all(st: Pstack_st_ESS_CERT_ID_V2; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_V2_find_all := LoadLibCryptoFunction('OPENSSL_sk_find_all');
  if not assigned(sk_ESS_CERT_ID_V2_find_all) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find_all');
  Result := sk_ESS_CERT_ID_V2_find_all(st, data, pnum);
end;

function Load_sk_ESS_CERT_ID_V2_sort(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_V2_sort := LoadLibCryptoFunction('OPENSSL_sk_sort');
  if not assigned(sk_ESS_CERT_ID_V2_sort) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_sort');
  Result := sk_ESS_CERT_ID_V2_sort(_para);
end;

function Load_sk_ESS_CERT_ID_V2_is_sorted(_para: Pstack_st_ESS_CERT_ID_V2): TOpenSSL_C_INT; cdecl;
begin
  sk_ESS_CERT_ID_V2_is_sorted := LoadLibCryptoFunction('OPENSSL_sk_is_sorted');
  if not assigned(sk_ESS_CERT_ID_V2_is_sorted) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_is_sorted');
  Result := sk_ESS_CERT_ID_V2_is_sorted(_para);
end;

function Load_sk_ESS_CERT_ID_V2_dup(st: Pstack_st_ESS_CERT_ID_V2): Pstack_st_ESS_CERT_ID_V2; cdecl;
begin
  sk_ESS_CERT_ID_V2_dup := LoadLibCryptoFunction('OPENSSL_sk_dup');
  if not assigned(sk_ESS_CERT_ID_V2_dup) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_dup');
  Result := sk_ESS_CERT_ID_V2_dup(st);
end;

function Load_sk_ESS_CERT_ID_V2_deep_copy(st: Pstack_st_ESS_CERT_ID_V2; c: Tsk_ESS_CERT_ID_V2_compfunc; f: Tsk_ESS_CERT_ID_V2_freefunc): Pstack_st_ESS_CERT_ID_V2; cdecl;
begin
  sk_ESS_CERT_ID_V2_deep_copy := LoadLibCryptoFunction('OPENSSL_sk_deep_copy');
  if not assigned(sk_ESS_CERT_ID_V2_deep_copy) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_deep_copy');
  Result := sk_ESS_CERT_ID_V2_deep_copy(st, c, f);
end;

function Load_sk_ESS_CERT_ID_V2_set_cmp_func(st: Pstack_st_ESS_CERT_ID_V2; cmp: Tsk_ESS_CERT_ID_V2_compfunc): Tsk_ESS_CERT_ID_V2_compfunc; cdecl;
begin
  sk_ESS_CERT_ID_V2_set_cmp_func := LoadLibCryptoFunction('OPENSSL_sk_set_cmp_func');
  if not assigned(sk_ESS_CERT_ID_V2_set_cmp_func) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_set_cmp_func');
  Result := sk_ESS_CERT_ID_V2_set_cmp_func(st, cmp);
end;

function Load_ESS_ISSUER_SERIAL_new: PESS_ISSUER_SERIAL; cdecl;
begin
  ESS_ISSUER_SERIAL_new := LoadLibCryptoFunction('ESS_ISSUER_SERIAL_new');
  if not assigned(ESS_ISSUER_SERIAL_new) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_ISSUER_SERIAL_new');
  Result := ESS_ISSUER_SERIAL_new;
end;

procedure Load_ESS_ISSUER_SERIAL_free(a: PESS_ISSUER_SERIAL); cdecl;
begin
  ESS_ISSUER_SERIAL_free := LoadLibCryptoFunction('ESS_ISSUER_SERIAL_free');
  if not assigned(ESS_ISSUER_SERIAL_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_ISSUER_SERIAL_free');
  ESS_ISSUER_SERIAL_free(a);
end;

function Load_d2i_ESS_ISSUER_SERIAL(a: PPESS_ISSUER_SERIAL; in_: PPbyte; len: TOpenSSL_C_INT): PESS_ISSUER_SERIAL; cdecl;
begin
  d2i_ESS_ISSUER_SERIAL := LoadLibCryptoFunction('d2i_ESS_ISSUER_SERIAL');
  if not assigned(d2i_ESS_ISSUER_SERIAL) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('d2i_ESS_ISSUER_SERIAL');
  Result := d2i_ESS_ISSUER_SERIAL(a, in_, len);
end;

function Load_i2d_ESS_ISSUER_SERIAL(a: PESS_ISSUER_SERIAL; out_: PPbyte): TOpenSSL_C_INT; cdecl;
begin
  i2d_ESS_ISSUER_SERIAL := LoadLibCryptoFunction('i2d_ESS_ISSUER_SERIAL');
  if not assigned(i2d_ESS_ISSUER_SERIAL) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('i2d_ESS_ISSUER_SERIAL');
  Result := i2d_ESS_ISSUER_SERIAL(a, out_);
end;

function Load_ESS_ISSUER_SERIAL_dup(a: PESS_ISSUER_SERIAL): PESS_ISSUER_SERIAL; cdecl;
begin
  ESS_ISSUER_SERIAL_dup := LoadLibCryptoFunction('ESS_ISSUER_SERIAL_dup');
  if not assigned(ESS_ISSUER_SERIAL_dup) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_ISSUER_SERIAL_dup');
  Result := ESS_ISSUER_SERIAL_dup(a);
end;

function Load_ESS_CERT_ID_new: PESS_CERT_ID; cdecl;
begin
  ESS_CERT_ID_new := LoadLibCryptoFunction('ESS_CERT_ID_new');
  if not assigned(ESS_CERT_ID_new) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_CERT_ID_new');
  Result := ESS_CERT_ID_new;
end;

procedure Load_ESS_CERT_ID_free(a: PESS_CERT_ID); cdecl;
begin
  ESS_CERT_ID_free := LoadLibCryptoFunction('ESS_CERT_ID_free');
  if not assigned(ESS_CERT_ID_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_CERT_ID_free');
  ESS_CERT_ID_free(a);
end;

function Load_d2i_ESS_CERT_ID(a: PPESS_CERT_ID; in_: PPbyte; len: TOpenSSL_C_INT): PESS_CERT_ID; cdecl;
begin
  d2i_ESS_CERT_ID := LoadLibCryptoFunction('d2i_ESS_CERT_ID');
  if not assigned(d2i_ESS_CERT_ID) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('d2i_ESS_CERT_ID');
  Result := d2i_ESS_CERT_ID(a, in_, len);
end;

function Load_i2d_ESS_CERT_ID(a: PESS_CERT_ID; out_: PPbyte): TOpenSSL_C_INT; cdecl;
begin
  i2d_ESS_CERT_ID := LoadLibCryptoFunction('i2d_ESS_CERT_ID');
  if not assigned(i2d_ESS_CERT_ID) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('i2d_ESS_CERT_ID');
  Result := i2d_ESS_CERT_ID(a, out_);
end;

function Load_ESS_CERT_ID_dup(a: PESS_CERT_ID): PESS_CERT_ID; cdecl;
begin
  ESS_CERT_ID_dup := LoadLibCryptoFunction('ESS_CERT_ID_dup');
  if not assigned(ESS_CERT_ID_dup) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_CERT_ID_dup');
  Result := ESS_CERT_ID_dup(a);
end;

function Load_ESS_SIGNING_CERT_new: PESS_SIGNING_CERT; cdecl;
begin
  ESS_SIGNING_CERT_new := LoadLibCryptoFunction('ESS_SIGNING_CERT_new');
  if not assigned(ESS_SIGNING_CERT_new) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_SIGNING_CERT_new');
  Result := ESS_SIGNING_CERT_new;
end;

procedure Load_ESS_SIGNING_CERT_free(a: PESS_SIGNING_CERT); cdecl;
begin
  ESS_SIGNING_CERT_free := LoadLibCryptoFunction('ESS_SIGNING_CERT_free');
  if not assigned(ESS_SIGNING_CERT_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_SIGNING_CERT_free');
  ESS_SIGNING_CERT_free(a);
end;

function Load_d2i_ESS_SIGNING_CERT(a: PPESS_SIGNING_CERT; in_: PPbyte; len: TOpenSSL_C_INT): PESS_SIGNING_CERT; cdecl;
begin
  d2i_ESS_SIGNING_CERT := LoadLibCryptoFunction('d2i_ESS_SIGNING_CERT');
  if not assigned(d2i_ESS_SIGNING_CERT) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('d2i_ESS_SIGNING_CERT');
  Result := d2i_ESS_SIGNING_CERT(a, in_, len);
end;

function Load_i2d_ESS_SIGNING_CERT(a: PESS_SIGNING_CERT; out_: PPbyte): TOpenSSL_C_INT; cdecl;
begin
  i2d_ESS_SIGNING_CERT := LoadLibCryptoFunction('i2d_ESS_SIGNING_CERT');
  if not assigned(i2d_ESS_SIGNING_CERT) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('i2d_ESS_SIGNING_CERT');
  Result := i2d_ESS_SIGNING_CERT(a, out_);
end;

function Load_ESS_SIGNING_CERT_it: PASN1_ITEM; cdecl;
begin
  ESS_SIGNING_CERT_it := LoadLibCryptoFunction('ESS_SIGNING_CERT_it');
  if not assigned(ESS_SIGNING_CERT_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_SIGNING_CERT_it');
  Result := ESS_SIGNING_CERT_it;
end;

function Load_ESS_SIGNING_CERT_dup(a: PESS_SIGNING_CERT): PESS_SIGNING_CERT; cdecl;
begin
  ESS_SIGNING_CERT_dup := LoadLibCryptoFunction('ESS_SIGNING_CERT_dup');
  if not assigned(ESS_SIGNING_CERT_dup) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_SIGNING_CERT_dup');
  Result := ESS_SIGNING_CERT_dup(a);
end;

function Load_ESS_CERT_ID_V2_new: PESS_CERT_ID_V2; cdecl;
begin
  ESS_CERT_ID_V2_new := LoadLibCryptoFunction('ESS_CERT_ID_V2_new');
  if not assigned(ESS_CERT_ID_V2_new) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_CERT_ID_V2_new');
  Result := ESS_CERT_ID_V2_new;
end;

procedure Load_ESS_CERT_ID_V2_free(a: PESS_CERT_ID_V2); cdecl;
begin
  ESS_CERT_ID_V2_free := LoadLibCryptoFunction('ESS_CERT_ID_V2_free');
  if not assigned(ESS_CERT_ID_V2_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_CERT_ID_V2_free');
  ESS_CERT_ID_V2_free(a);
end;

function Load_d2i_ESS_CERT_ID_V2(a: PPESS_CERT_ID_V2; in_: PPbyte; len: TOpenSSL_C_INT): PESS_CERT_ID_V2; cdecl;
begin
  d2i_ESS_CERT_ID_V2 := LoadLibCryptoFunction('d2i_ESS_CERT_ID_V2');
  if not assigned(d2i_ESS_CERT_ID_V2) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('d2i_ESS_CERT_ID_V2');
  Result := d2i_ESS_CERT_ID_V2(a, in_, len);
end;

function Load_i2d_ESS_CERT_ID_V2(a: PESS_CERT_ID_V2; out_: PPbyte): TOpenSSL_C_INT; cdecl;
begin
  i2d_ESS_CERT_ID_V2 := LoadLibCryptoFunction('i2d_ESS_CERT_ID_V2');
  if not assigned(i2d_ESS_CERT_ID_V2) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('i2d_ESS_CERT_ID_V2');
  Result := i2d_ESS_CERT_ID_V2(a, out_);
end;

function Load_ESS_CERT_ID_V2_dup(a: PESS_CERT_ID_V2): PESS_CERT_ID_V2; cdecl;
begin
  ESS_CERT_ID_V2_dup := LoadLibCryptoFunction('ESS_CERT_ID_V2_dup');
  if not assigned(ESS_CERT_ID_V2_dup) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_CERT_ID_V2_dup');
  Result := ESS_CERT_ID_V2_dup(a);
end;

function Load_ESS_SIGNING_CERT_V2_new: PESS_SIGNING_CERT_V2; cdecl;
begin
  ESS_SIGNING_CERT_V2_new := LoadLibCryptoFunction('ESS_SIGNING_CERT_V2_new');
  if not assigned(ESS_SIGNING_CERT_V2_new) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_SIGNING_CERT_V2_new');
  Result := ESS_SIGNING_CERT_V2_new;
end;

procedure Load_ESS_SIGNING_CERT_V2_free(a: PESS_SIGNING_CERT_V2); cdecl;
begin
  ESS_SIGNING_CERT_V2_free := LoadLibCryptoFunction('ESS_SIGNING_CERT_V2_free');
  if not assigned(ESS_SIGNING_CERT_V2_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_SIGNING_CERT_V2_free');
  ESS_SIGNING_CERT_V2_free(a);
end;

function Load_d2i_ESS_SIGNING_CERT_V2(a: PPESS_SIGNING_CERT_V2; in_: PPbyte; len: TOpenSSL_C_INT): PESS_SIGNING_CERT_V2; cdecl;
begin
  d2i_ESS_SIGNING_CERT_V2 := LoadLibCryptoFunction('d2i_ESS_SIGNING_CERT_V2');
  if not assigned(d2i_ESS_SIGNING_CERT_V2) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('d2i_ESS_SIGNING_CERT_V2');
  Result := d2i_ESS_SIGNING_CERT_V2(a, in_, len);
end;

function Load_i2d_ESS_SIGNING_CERT_V2(a: PESS_SIGNING_CERT_V2; out_: PPbyte): TOpenSSL_C_INT; cdecl;
begin
  i2d_ESS_SIGNING_CERT_V2 := LoadLibCryptoFunction('i2d_ESS_SIGNING_CERT_V2');
  if not assigned(i2d_ESS_SIGNING_CERT_V2) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('i2d_ESS_SIGNING_CERT_V2');
  Result := i2d_ESS_SIGNING_CERT_V2(a, out_);
end;

function Load_ESS_SIGNING_CERT_V2_it: PASN1_ITEM; cdecl;
begin
  ESS_SIGNING_CERT_V2_it := LoadLibCryptoFunction('ESS_SIGNING_CERT_V2_it');
  if not assigned(ESS_SIGNING_CERT_V2_it) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_SIGNING_CERT_V2_it');
  Result := ESS_SIGNING_CERT_V2_it;
end;

function Load_ESS_SIGNING_CERT_V2_dup(a: PESS_SIGNING_CERT_V2): PESS_SIGNING_CERT_V2; cdecl;
begin
  ESS_SIGNING_CERT_V2_dup := LoadLibCryptoFunction('ESS_SIGNING_CERT_V2_dup');
  if not assigned(ESS_SIGNING_CERT_V2_dup) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('ESS_SIGNING_CERT_V2_dup');
  Result := ESS_SIGNING_CERT_V2_dup(a);
end;

function Load_OSSL_ESS_signing_cert_new_init(signcert: PX509; certs: Pstack_st_X509; set_issuer_serial: TOpenSSL_C_INT): PESS_SIGNING_CERT; cdecl;
begin
  OSSL_ESS_signing_cert_new_init := LoadLibCryptoFunction('OSSL_ESS_signing_cert_new_init');
  if not assigned(OSSL_ESS_signing_cert_new_init) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OSSL_ESS_signing_cert_new_init');
  Result := OSSL_ESS_signing_cert_new_init(signcert, certs, set_issuer_serial);
end;

function Load_OSSL_ESS_signing_cert_v2_new_init(hash_alg: PEVP_MD; signcert: PX509; certs: Pstack_st_X509; set_issuer_serial: TOpenSSL_C_INT): PESS_SIGNING_CERT_V2; cdecl;
begin
  OSSL_ESS_signing_cert_v2_new_init := LoadLibCryptoFunction('OSSL_ESS_signing_cert_v2_new_init');
  if not assigned(OSSL_ESS_signing_cert_v2_new_init) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OSSL_ESS_signing_cert_v2_new_init');
  Result := OSSL_ESS_signing_cert_v2_new_init(hash_alg, signcert, certs, set_issuer_serial);
end;

function Load_OSSL_ESS_check_signing_certs(ss: PESS_SIGNING_CERT; ssv2: PESS_SIGNING_CERT_V2; chain: Pstack_st_X509; require_signing_cert: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  OSSL_ESS_check_signing_certs := LoadLibCryptoFunction('OSSL_ESS_check_signing_certs');
  if not assigned(OSSL_ESS_check_signing_certs) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OSSL_ESS_check_signing_certs');
  Result := OSSL_ESS_check_signing_certs(ss, ssv2, chain, require_signing_cert);
end;

procedure Load;
begin
  {$define EMPTY_LOAD_FUNCTION}
end;

procedure Unload;
begin
  sk_ESS_CERT_ID_num := Load_sk_ESS_CERT_ID_num;
  sk_ESS_CERT_ID_value := Load_sk_ESS_CERT_ID_value;
  sk_ESS_CERT_ID_new := Load_sk_ESS_CERT_ID_new;
  sk_ESS_CERT_ID_new_null := Load_sk_ESS_CERT_ID_new_null;
  sk_ESS_CERT_ID_new_reserve := Load_sk_ESS_CERT_ID_new_reserve;
  sk_ESS_CERT_ID_reserve := Load_sk_ESS_CERT_ID_reserve;
  sk_ESS_CERT_ID_free := Load_sk_ESS_CERT_ID_free;
  sk_ESS_CERT_ID_zero := Load_sk_ESS_CERT_ID_zero;
  sk_ESS_CERT_ID_delete := Load_sk_ESS_CERT_ID_delete;
  sk_ESS_CERT_ID_delete_ptr := Load_sk_ESS_CERT_ID_delete_ptr;
  sk_ESS_CERT_ID_push := Load_sk_ESS_CERT_ID_push;
  sk_ESS_CERT_ID_unshift := Load_sk_ESS_CERT_ID_unshift;
  sk_ESS_CERT_ID_pop := Load_sk_ESS_CERT_ID_pop;
  sk_ESS_CERT_ID_shift := Load_sk_ESS_CERT_ID_shift;
  sk_ESS_CERT_ID_pop_free := Load_sk_ESS_CERT_ID_pop_free;
  sk_ESS_CERT_ID_insert := Load_sk_ESS_CERT_ID_insert;
  sk_ESS_CERT_ID_set := Load_sk_ESS_CERT_ID_set;
  sk_ESS_CERT_ID_find := Load_sk_ESS_CERT_ID_find;
  sk_ESS_CERT_ID_find_ex := Load_sk_ESS_CERT_ID_find_ex;
  sk_ESS_CERT_ID_find_all := Load_sk_ESS_CERT_ID_find_all;
  sk_ESS_CERT_ID_sort := Load_sk_ESS_CERT_ID_sort;
  sk_ESS_CERT_ID_is_sorted := Load_sk_ESS_CERT_ID_is_sorted;
  sk_ESS_CERT_ID_dup := Load_sk_ESS_CERT_ID_dup;
  sk_ESS_CERT_ID_deep_copy := Load_sk_ESS_CERT_ID_deep_copy;
  sk_ESS_CERT_ID_set_cmp_func := Load_sk_ESS_CERT_ID_set_cmp_func;
  sk_ESS_CERT_ID_V2_num := Load_sk_ESS_CERT_ID_V2_num;
  sk_ESS_CERT_ID_V2_value := Load_sk_ESS_CERT_ID_V2_value;
  sk_ESS_CERT_ID_V2_new := Load_sk_ESS_CERT_ID_V2_new;
  sk_ESS_CERT_ID_V2_new_null := Load_sk_ESS_CERT_ID_V2_new_null;
  sk_ESS_CERT_ID_V2_new_reserve := Load_sk_ESS_CERT_ID_V2_new_reserve;
  sk_ESS_CERT_ID_V2_reserve := Load_sk_ESS_CERT_ID_V2_reserve;
  sk_ESS_CERT_ID_V2_free := Load_sk_ESS_CERT_ID_V2_free;
  sk_ESS_CERT_ID_V2_zero := Load_sk_ESS_CERT_ID_V2_zero;
  sk_ESS_CERT_ID_V2_delete := Load_sk_ESS_CERT_ID_V2_delete;
  sk_ESS_CERT_ID_V2_delete_ptr := Load_sk_ESS_CERT_ID_V2_delete_ptr;
  sk_ESS_CERT_ID_V2_push := Load_sk_ESS_CERT_ID_V2_push;
  sk_ESS_CERT_ID_V2_unshift := Load_sk_ESS_CERT_ID_V2_unshift;
  sk_ESS_CERT_ID_V2_pop := Load_sk_ESS_CERT_ID_V2_pop;
  sk_ESS_CERT_ID_V2_shift := Load_sk_ESS_CERT_ID_V2_shift;
  sk_ESS_CERT_ID_V2_pop_free := Load_sk_ESS_CERT_ID_V2_pop_free;
  sk_ESS_CERT_ID_V2_insert := Load_sk_ESS_CERT_ID_V2_insert;
  sk_ESS_CERT_ID_V2_set := Load_sk_ESS_CERT_ID_V2_set;
  sk_ESS_CERT_ID_V2_find := Load_sk_ESS_CERT_ID_V2_find;
  sk_ESS_CERT_ID_V2_find_ex := Load_sk_ESS_CERT_ID_V2_find_ex;
  sk_ESS_CERT_ID_V2_find_all := Load_sk_ESS_CERT_ID_V2_find_all;
  sk_ESS_CERT_ID_V2_sort := Load_sk_ESS_CERT_ID_V2_sort;
  sk_ESS_CERT_ID_V2_is_sorted := Load_sk_ESS_CERT_ID_V2_is_sorted;
  sk_ESS_CERT_ID_V2_dup := Load_sk_ESS_CERT_ID_V2_dup;
  sk_ESS_CERT_ID_V2_deep_copy := Load_sk_ESS_CERT_ID_V2_deep_copy;
  sk_ESS_CERT_ID_V2_set_cmp_func := Load_sk_ESS_CERT_ID_V2_set_cmp_func;
  ESS_ISSUER_SERIAL_new := Load_ESS_ISSUER_SERIAL_new;
  ESS_ISSUER_SERIAL_free := Load_ESS_ISSUER_SERIAL_free;
  d2i_ESS_ISSUER_SERIAL := Load_d2i_ESS_ISSUER_SERIAL;
  i2d_ESS_ISSUER_SERIAL := Load_i2d_ESS_ISSUER_SERIAL;
  ESS_ISSUER_SERIAL_dup := Load_ESS_ISSUER_SERIAL_dup;
  ESS_CERT_ID_new := Load_ESS_CERT_ID_new;
  ESS_CERT_ID_free := Load_ESS_CERT_ID_free;
  d2i_ESS_CERT_ID := Load_d2i_ESS_CERT_ID;
  i2d_ESS_CERT_ID := Load_i2d_ESS_CERT_ID;
  ESS_CERT_ID_dup := Load_ESS_CERT_ID_dup;
  ESS_SIGNING_CERT_new := Load_ESS_SIGNING_CERT_new;
  ESS_SIGNING_CERT_free := Load_ESS_SIGNING_CERT_free;
  d2i_ESS_SIGNING_CERT := Load_d2i_ESS_SIGNING_CERT;
  i2d_ESS_SIGNING_CERT := Load_i2d_ESS_SIGNING_CERT;
  ESS_SIGNING_CERT_it := Load_ESS_SIGNING_CERT_it;
  ESS_SIGNING_CERT_dup := Load_ESS_SIGNING_CERT_dup;
  ESS_CERT_ID_V2_new := Load_ESS_CERT_ID_V2_new;
  ESS_CERT_ID_V2_free := Load_ESS_CERT_ID_V2_free;
  d2i_ESS_CERT_ID_V2 := Load_d2i_ESS_CERT_ID_V2;
  i2d_ESS_CERT_ID_V2 := Load_i2d_ESS_CERT_ID_V2;
  ESS_CERT_ID_V2_dup := Load_ESS_CERT_ID_V2_dup;
  ESS_SIGNING_CERT_V2_new := Load_ESS_SIGNING_CERT_V2_new;
  ESS_SIGNING_CERT_V2_free := Load_ESS_SIGNING_CERT_V2_free;
  d2i_ESS_SIGNING_CERT_V2 := Load_d2i_ESS_SIGNING_CERT_V2;
  i2d_ESS_SIGNING_CERT_V2 := Load_i2d_ESS_SIGNING_CERT_V2;
  ESS_SIGNING_CERT_V2_it := Load_ESS_SIGNING_CERT_V2_it;
  ESS_SIGNING_CERT_V2_dup := Load_ESS_SIGNING_CERT_V2_dup;
  OSSL_ESS_signing_cert_new_init := Load_OSSL_ESS_signing_cert_new_init;
  OSSL_ESS_signing_cert_v2_new_init := Load_OSSL_ESS_signing_cert_v2_new_init;
  OSSL_ESS_check_signing_certs := Load_OSSL_ESS_check_signing_certs;
end;

{$endif} {OPENSSL_STATIC_LINK_MODEL}

initialization

{$ifndef OPENSSL_STATIC_LINK_MODEL}
{$ifndef EMPTY_LOAD_FUNCTION}
Register_SSLloader(@Load);
{$endif}
Register_SSLUnloader(@Unload);
{$endif}
{$if declared(LegacySupport_Initialization)}
LegacySupport_Initialization;
{$ifend}

finalization

{$if declared(LegacySupport_Finalization)}
LegacySupport_Finalization;
{$ifend}

end.



