{
    This file is part of the MWA Software Pascal API for OpenSSL .

    The MWA Software Pascal API for OpenSSL is free software: you can redistribute it
    and/or modify it under the terms of the Apache License Version 2.0 (the "License"), and as
    a derived work of the OpenSSL Project (see below for the original licence text).

    You may not use this file except in compliance with the License.  You can obtain a copy
    in the file LICENSE.txt in the source distribution or at https://www.openssl.org/source/license.html.

    The MWA Software Pascal API for OpenSSL is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the License for more details.
}

{$include openssl_defines.inc}

unit openssl_fipskey;

{
  Generated from OpenSSL 3.5.6 Header File fipskey.h - Tue 19 May 14:27:47 BST 2026
}

{$IFNDEF FPC}
{$IFDEF OPENSSL_USE_STATIC_LIBRARY}
{$LINK openssl_fipskey.obj}
{$ENDIF}
{$ENDIF}

interface

uses OpenSSLAPI;


{* WARNING: do not edit!
* Generated by Makefile from include/openssl/fipskey.h.in
*
* Copyright 2020-2024 The OpenSSL Project Authors. All Rights Reserved.
*
* Licensed under the Apache License 2.0 (the "License").  You may not use
* this file except in compliance with the License.  You can obtain a copy
* in the file LICENSE in the source distribution or at
* https://www.openssl.org/source/license.html
}
{$ifndef  OPENSSL_FIPSKEY_H}
  {$define OPENSSL_FIPSKEY_H}

const
  
  {* The FIPS validation HMAC key, usable as an array initializer.
  }
  { clang-format off }
  FIPS_KEY_ELEMENTS = '$f4' + ',' + '$55' + ',' + '$66' + ',' + '$50' + ',' + '$ac' + ',' + '$31' + ',' + '$d3' + ',' + '$54' + ',' + '$61' + ',' + '$61' + ',' + '$0b' + ',' + '$ac' + ',' + '$4e' + ',' + '$d8' + ',' + '$1b' + ',' + '$1a' + ',' + '$18' + ',' + '$1b' + ',' + '$2d' + ',' + '$8a' + ',' + '$43' + ',' + '$ea' + ',' + '$28' + ',' + '$54' + ',' + '$cb' + ',' + '$ae' + ',' + '$22' + ',' + '$ca' + ',' + '$74' + ',' + '$56' + ',' + '$08' + ',' + '$13';
  { clang-format on }
  
  {* The FIPS validation key, as a string.
  }
  { clang-format off }
  FIPS_KEY_STRING = 'f4556650ac31d35461610bac4ed81b1a181b2d8a43ea2854cbae22ca74560813';
  { clang-format on }
  
  {* The FIPS provider vendor name, as a string.
  }
  { clang-format off }
  FIPS_VENDOR = 'OpenSSL non-compliant FIPS Provider';
  { clang-format on }
{$endif}

implementation

uses Sysutils, variants
  {$ifdef OPENSSL_INTERNAL_NEED_THREADS}
   {$IFNDEF FPC}
     ,System.SyncObjs
     {$IFDEF POSIX}
       ,Posix.Pthread
     {$ELSE}
       ,Windows
     {$ENDIF}
   {$ELSE}
     ,SyncObjs
   {$ENDIF}
  {$endif}
  ,Classes, OpenSSLExceptionHandlers;

  {$if not declared(__FILE__)}
  const
    {$ifdef FPC}
    __FILE__ = {$include %FILE%};
    {$else}
    __FILE__ = '$(INPUTFILENAME)';
    {$endif}
  {$ifend}
  {$if not declared(__LINE__)}
  const
    __LINE__ = 0;
  {$ifend}
  {$if not declared(OPENSSL_FILE)}
  const
    OPENSSL_FILE = __FILE__;
  {$ifend}
  {$if not declared(OPENSSL_LINE)}
  const
    OPENSSL_LINE  = 0;
  {$ifend}

{$ifndef OPENSSL_STATIC_LINK_MODEL}
procedure Load;
begin
  {$define EMPTY_LOAD_FUNCTION}
end;

procedure Unload;
begin
end;

{$endif} {OPENSSL_STATIC_LINK_MODEL}

initialization

{$ifndef OPENSSL_STATIC_LINK_MODEL}
{$ifndef EMPTY_LOAD_FUNCTION}
Register_SSLloader(@Load);
{$endif}
Register_SSLUnloader(@Unload);
{$endif}
{$if declared(LegacySupport_Initialization)}
LegacySupport_Initialization;
{$ifend}

finalization

{$if declared(LegacySupport_Finalization)}
LegacySupport_Finalization;
{$ifend}

end.



