{
    This file is part of the MWA Software Pascal API for OpenSSL .

    The MWA Software Pascal API for OpenSSL is free software: you can redistribute it
    and/or modify it under the terms of the Apache License Version 2.0 (the "License"), and as
    a derived work of the OpenSSL Project (see below for the original licence text).

    You may not use this file except in compliance with the License.  You can obtain a copy
    in the file LICENSE.txt in the source distribution or at https://www.openssl.org/source/license.html.

    The MWA Software Pascal API for OpenSSL is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the License for more details.
}

{$include openssl_defines.inc}

unit openssl_cryptoerr;

{
  Generated from OpenSSL 3.5.6 Header File cryptoerr.h - Tue 19 May 14:27:26 BST 2026
}

{$IFNDEF FPC}
{$IFDEF OPENSSL_USE_STATIC_LIBRARY}
{$LINK openssl_cryptoerr.obj}
{$ENDIF}
{$ENDIF}

interface

uses OpenSSLAPI,openssl_symhacks,openssl_cryptoerr_legacy;


{* Generated by util/mkerr.pl DO NOT EDIT
* Copyright 1995-2024 The OpenSSL Project Authors. All Rights Reserved.
*
* Licensed under the Apache License 2.0 (the "License").  You may not use
* this file except in compliance with the License.  You can obtain a copy
* in the file LICENSE in the source distribution or at
* https://www.openssl.org/source/license.html
}
{$ifndef  OPENSSL_CRYPTOERR_H}
  {$define OPENSSL_CRYPTOERR_H}
  {$include openssl_opensslconf.inc}

const
  
  {* CRYPTO reason codes.
  }
  CRYPTO_R_BAD_ALGORITHM_NAME = 117;
  CRYPTO_R_CONFLICTING_NAMES = 118;
  CRYPTO_R_HEX_STRING_TOO_SHORT = 121;
  CRYPTO_R_ILLEGAL_HEX_DIGIT = 102;
  CRYPTO_R_INSUFFICIENT_DATA_SPACE = 106;
  CRYPTO_R_INSUFFICIENT_PARAM_SIZE = 107;
  CRYPTO_R_INSUFFICIENT_SECURE_DATA_SPACE = 108;
  CRYPTO_R_INTEGER_OVERFLOW = 127;
  CRYPTO_R_INVALID_NEGATIVE_VALUE = 122;
  CRYPTO_R_INVALID_NULL_ARGUMENT = 109;
  CRYPTO_R_INVALID_OSSL_PARAM_TYPE = 110;
  CRYPTO_R_NO_PARAMS_TO_MERGE = 131;
  CRYPTO_R_NO_SPACE_FOR_TERMINATING_NULL = 128;
  CRYPTO_R_ODD_NUMBER_OF_DIGITS = 103;
  CRYPTO_R_PARAM_CANNOT_BE_REPRESENTED_EXACTLY = 123;
  CRYPTO_R_PARAM_NOT_INTEGER_TYPE = 124;
  CRYPTO_R_PARAM_OF_INCOMPATIBLE_TYPE = 129;
  CRYPTO_R_PARAM_UNSIGNED_INTEGER_NEGATIVE_VALUE_UNSUPPORTED = 125;
  CRYPTO_R_PARAM_UNSUPPORTED_FLOATING_POINT_FORMAT = 130;
  CRYPTO_R_PARAM_VALUE_TOO_LARGE_FOR_DESTINATION = 126;
  CRYPTO_R_PROVIDER_ALREADY_EXISTS = 104;
  CRYPTO_R_PROVIDER_SECTION_ERROR = 105;
  CRYPTO_R_RANDOM_SECTION_ERROR = 119;
  CRYPTO_R_SECURE_MALLOC_FAILURE = 111;
  CRYPTO_R_STRING_TOO_LONG = 112;
  CRYPTO_R_TOO_MANY_BYTES = 113;
  CRYPTO_R_TOO_MANY_NAMES = 132;
  CRYPTO_R_TOO_MANY_RECORDS = 114;
  CRYPTO_R_TOO_SMALL_BUFFER = 116;
  CRYPTO_R_UNKNOWN_NAME_IN_RANDOM_SECTION = 120;
  CRYPTO_R_ZERO_LENGTH_NUMBER = 115;
{$endif}

implementation

uses Sysutils, variants
  {$ifdef OPENSSL_INTERNAL_NEED_THREADS}
   {$IFNDEF FPC}
     ,System.SyncObjs
     {$IFDEF POSIX}
       ,Posix.Pthread
     {$ELSE}
       ,Windows
     {$ENDIF}
   {$ELSE}
     ,SyncObjs
   {$ENDIF}
  {$endif}
  ,Classes, OpenSSLExceptionHandlers;

  {$if not declared(__FILE__)}
  const
    {$ifdef FPC}
    __FILE__ = {$include %FILE%};
    {$else}
    __FILE__ = '$(INPUTFILENAME)';
    {$endif}
  {$ifend}
  {$if not declared(__LINE__)}
  const
    __LINE__ = 0;
  {$ifend}
  {$if not declared(OPENSSL_FILE)}
  const
    OPENSSL_FILE = __FILE__;
  {$ifend}
  {$if not declared(OPENSSL_LINE)}
  const
    OPENSSL_LINE  = 0;
  {$ifend}

{$ifndef OPENSSL_STATIC_LINK_MODEL}
procedure Load;
begin
  {$define EMPTY_LOAD_FUNCTION}
end;

procedure Unload;
begin
end;

{$endif} {OPENSSL_STATIC_LINK_MODEL}

initialization

{$ifndef OPENSSL_STATIC_LINK_MODEL}
{$ifndef EMPTY_LOAD_FUNCTION}
Register_SSLloader(@Load);
{$endif}
Register_SSLUnloader(@Unload);
{$endif}
{$if declared(LegacySupport_Initialization)}
LegacySupport_Initialization;
{$ifend}

finalization

{$if declared(LegacySupport_Finalization)}
LegacySupport_Finalization;
{$ifend}

end.



