{
    This file is part of the MWA Software Pascal API for OpenSSL .

    The MWA Software Pascal API for OpenSSL is free software: you can redistribute it
    and/or modify it under the terms of the Apache License Version 2.0 (the "License"), and as
    a derived work of the OpenSSL Project (see below for the original licence text).

    You may not use this file except in compliance with the License.  You can obtain a copy
    in the file LICENSE.txt in the source distribution or at https://www.openssl.org/source/license.html.

    The MWA Software Pascal API for OpenSSL is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the License for more details.
}

{$include openssl_defines.inc}

unit openssl_conf;

{
  Generated from OpenSSL 3.5.6 Header File conf.h - Tue 19 May 14:27:20 BST 2026
}

{$IFNDEF FPC}
{$IFDEF OPENSSL_USE_STATIC_LIBRARY}
{$LINK openssl_conf.obj}
{$ENDIF}
{$ENDIF}

interface

uses OpenSSLAPI,openssl_stack,openssl_bio,openssl_lhash,openssl_safestack,
     openssl_e_os2,openssl_types,openssl_conferr;


{* WARNING: do not edit!
* Generated by Makefile from include/openssl/conf.h.in
*
* Copyright 1995-2021 The OpenSSL Project Authors. All Rights Reserved.
*
* Licensed under the Apache License 2.0 (the "License").  You may not use
* this file except in compliance with the License.  You can obtain a copy
* in the file LICENSE in the source distribution or at
* https://www.openssl.org/source/license.html
}
{ clang-format off }
{ clang-format on }
{$ifndef  OPENSSL_CONF_H}
  {$define OPENSSL_CONF_H}
  {$include openssl_macros.inc}
  {$ifndef  OPENSSL_NO_DEPRECATED_3_0}
    {$define HEADER_CONF_H}
  {$endif}
  {$ifndef  OPENSSL_NO_STDIO}
  {$endif}

type
  {Auto-generated forward references}
  PCONF_VALUE = ^TCONF_VALUE;
  PPCONF_VALUE = ^PCONF_VALUE;
  Pstack_st_CONF_VALUE = ^Tstack_st_CONF_VALUE;
  PPstack_st_CONF_VALUE = ^Pstack_st_CONF_VALUE;
  Psk_CONF_VALUE_compfunc = ^Tsk_CONF_VALUE_compfunc;
  PPsk_CONF_VALUE_compfunc = ^Psk_CONF_VALUE_compfunc;
  Psk_CONF_VALUE_freefunc = ^Tsk_CONF_VALUE_freefunc;
  PPsk_CONF_VALUE_freefunc = ^Psk_CONF_VALUE_freefunc;
  Psk_CONF_VALUE_copyfunc = ^Tsk_CONF_VALUE_copyfunc;
  PPsk_CONF_VALUE_copyfunc = ^Psk_CONF_VALUE_copyfunc;
  {end of auto-generated forward references}

  TCONF_VALUE = record 
    section: PAnsiChar;
    name: PAnsiChar;
    value: PAnsiChar;
  end;
  { clang-format off }
  Tstack_st_CONF_VALUE = record 
  end;
  Tsk_CONF_VALUE_compfunc = function(a: PPCONF_VALUE; b: PPCONF_VALUE): TOpenSSL_C_INT; cdecl;
  Tsk_CONF_VALUE_freefunc = procedure(a: PCONF_VALUE); cdecl;
  Tsk_CONF_VALUE_copyfunc = function(a: PCONF_VALUE): PCONF_VALUE; cdecl;


  function ossl_check_CONF_VALUE_type(ptr: PCONF_VALUE): PCONF_VALUE{Has C Attribute: unused}; inline;
  function ossl_check_const_CONF_VALUE_sk_type(sk: Pstack_st_CONF_VALUE): POPENSSL_STACK{Has C Attribute: unused}; inline;
  function ossl_check_CONF_VALUE_sk_type(sk: Pstack_st_CONF_VALUE): POPENSSL_STACK{Has C Attribute: unused}; inline;
  function ossl_check_CONF_VALUE_compfunc_type(cmp: Tsk_CONF_VALUE_compfunc): TOPENSSL_sk_compfunc{Has C Attribute: unused}; inline;
  function ossl_check_CONF_VALUE_copyfunc_type(cpy: Tsk_CONF_VALUE_copyfunc): TOPENSSL_sk_copyfunc{Has C Attribute: unused}; inline;
  function ossl_check_CONF_VALUE_freefunc_type(fr: Tsk_CONF_VALUE_freefunc): TOPENSSL_sk_freefunc{Has C Attribute: unused}; inline;
  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function sk_CONF_VALUE_num(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_num';
  function sk_CONF_VALUE_value(_para: Pstack_st_CONF_VALUE; _para2: TOpenSSL_C_INT): Pstack_st_CONF_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_value';
  function sk_CONF_VALUE_new(cmp: Tsk_CONF_VALUE_compfunc): Pstack_st_CONF_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_new';
  function sk_CONF_VALUE_new_null: Pstack_st_CONF_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_new_null';
  function sk_CONF_VALUE_new_reserve(cmp: Tsk_CONF_VALUE_compfunc; n: TOpenSSL_C_INT): Pstack_st_CONF_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_new_reserve';
  function sk_CONF_VALUE_reserve(_para: Pstack_st_CONF_VALUE; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_reserve';
  function sk_CONF_VALUE_free(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_free';
  function sk_CONF_VALUE_zero(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_zero';
  function sk_CONF_VALUE_delete(st: Pstack_st_CONF_VALUE; loc: TOpenSSL_C_INT): Pstack_st_CONF_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_delete';
  function sk_CONF_VALUE_delete_ptr(st: Pstack_st_CONF_VALUE; ptr: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_delete_ptr';
  function sk_CONF_VALUE_push(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_push';
  function sk_CONF_VALUE_unshift(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_unshift';
  function sk_CONF_VALUE_pop(_para: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_pop';
  function sk_CONF_VALUE_shift(_para: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_shift';
  procedure sk_CONF_VALUE_pop_free(st: Pstack_st_CONF_VALUE; func: Tsk_CONF_VALUE_freefunc); cdecl; external CLibCrypto name 'OPENSSL_sk_pop_free';
  function sk_CONF_VALUE_insert(st: Pstack_st_CONF_VALUE; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_insert';
  function sk_CONF_VALUE_set(st: Pstack_st_CONF_VALUE; i: TOpenSSL_C_INT; data: pointer): Pstack_st_CONF_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_set';
  function sk_CONF_VALUE_find(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find';
  function sk_CONF_VALUE_find_ex(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find_ex';
  function sk_CONF_VALUE_find_all(st: Pstack_st_CONF_VALUE; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find_all';
  function sk_CONF_VALUE_sort(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_sort';
  function sk_CONF_VALUE_is_sorted(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_is_sorted';
  function sk_CONF_VALUE_dup(st: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_dup';
  function sk_CONF_VALUE_deep_copy(st: Pstack_st_CONF_VALUE; c: Tsk_CONF_VALUE_compfunc; f: Tsk_CONF_VALUE_freefunc): Pstack_st_CONF_VALUE; cdecl; external CLibCrypto name 'OPENSSL_sk_deep_copy';
  function sk_CONF_VALUE_set_cmp_func(st: Pstack_st_CONF_VALUE; cmp: Tsk_CONF_VALUE_compfunc): Tsk_CONF_VALUE_compfunc; cdecl; external CLibCrypto name 'OPENSSL_sk_set_cmp_func';
  {$else}
  { The EXTERNALSYM directive is ignored by FPC, however, it is used by Delphi as follows:

  The EXTERNALSYM directive prevents the specified Delphi symbol from appearing in header
  files generated for C++. }
  {$EXTERNALSYM sk_CONF_VALUE_num}
  {$EXTERNALSYM sk_CONF_VALUE_value}
  {$EXTERNALSYM sk_CONF_VALUE_new}
  {$EXTERNALSYM sk_CONF_VALUE_new_null}
  {$EXTERNALSYM sk_CONF_VALUE_new_reserve}
  {$EXTERNALSYM sk_CONF_VALUE_reserve}
  {$EXTERNALSYM sk_CONF_VALUE_free}
  {$EXTERNALSYM sk_CONF_VALUE_zero}
  {$EXTERNALSYM sk_CONF_VALUE_delete}
  {$EXTERNALSYM sk_CONF_VALUE_delete_ptr}
  {$EXTERNALSYM sk_CONF_VALUE_push}
  {$EXTERNALSYM sk_CONF_VALUE_unshift}
  {$EXTERNALSYM sk_CONF_VALUE_pop}
  {$EXTERNALSYM sk_CONF_VALUE_shift}
  {$EXTERNALSYM sk_CONF_VALUE_pop_free}
  {$EXTERNALSYM sk_CONF_VALUE_insert}
  {$EXTERNALSYM sk_CONF_VALUE_set}
  {$EXTERNALSYM sk_CONF_VALUE_find}
  {$EXTERNALSYM sk_CONF_VALUE_find_ex}
  {$EXTERNALSYM sk_CONF_VALUE_find_all}
  {$EXTERNALSYM sk_CONF_VALUE_sort}
  {$EXTERNALSYM sk_CONF_VALUE_is_sorted}
  {$EXTERNALSYM sk_CONF_VALUE_dup}
  {$EXTERNALSYM sk_CONF_VALUE_deep_copy}
  {$EXTERNALSYM sk_CONF_VALUE_set_cmp_func}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_sk_CONF_VALUE_num(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl;
  function Load_sk_CONF_VALUE_value(_para: Pstack_st_CONF_VALUE; _para2: TOpenSSL_C_INT): Pstack_st_CONF_VALUE; cdecl;
  function Load_sk_CONF_VALUE_new(cmp: Tsk_CONF_VALUE_compfunc): Pstack_st_CONF_VALUE; cdecl;
  function Load_sk_CONF_VALUE_new_null: Pstack_st_CONF_VALUE; cdecl;
  function Load_sk_CONF_VALUE_new_reserve(cmp: Tsk_CONF_VALUE_compfunc; n: TOpenSSL_C_INT): Pstack_st_CONF_VALUE; cdecl;
  function Load_sk_CONF_VALUE_reserve(_para: Pstack_st_CONF_VALUE; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_CONF_VALUE_free(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl;
  function Load_sk_CONF_VALUE_zero(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl;
  function Load_sk_CONF_VALUE_delete(st: Pstack_st_CONF_VALUE; loc: TOpenSSL_C_INT): Pstack_st_CONF_VALUE; cdecl;
  function Load_sk_CONF_VALUE_delete_ptr(st: Pstack_st_CONF_VALUE; ptr: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl;
  function Load_sk_CONF_VALUE_push(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_CONF_VALUE_unshift(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_CONF_VALUE_pop(_para: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl;
  function Load_sk_CONF_VALUE_shift(_para: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl;
  procedure Load_sk_CONF_VALUE_pop_free(st: Pstack_st_CONF_VALUE; func: Tsk_CONF_VALUE_freefunc); cdecl;
  function Load_sk_CONF_VALUE_insert(st: Pstack_st_CONF_VALUE; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_CONF_VALUE_set(st: Pstack_st_CONF_VALUE; i: TOpenSSL_C_INT; data: pointer): Pstack_st_CONF_VALUE; cdecl;
  function Load_sk_CONF_VALUE_find(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_CONF_VALUE_find_ex(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_CONF_VALUE_find_all(st: Pstack_st_CONF_VALUE; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_CONF_VALUE_sort(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl;
  function Load_sk_CONF_VALUE_is_sorted(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl;
  function Load_sk_CONF_VALUE_dup(st: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl;
  function Load_sk_CONF_VALUE_deep_copy(st: Pstack_st_CONF_VALUE; c: Tsk_CONF_VALUE_compfunc; f: Tsk_CONF_VALUE_freefunc): Pstack_st_CONF_VALUE; cdecl;
  function Load_sk_CONF_VALUE_set_cmp_func(st: Pstack_st_CONF_VALUE; cmp: Tsk_CONF_VALUE_compfunc): Tsk_CONF_VALUE_compfunc; cdecl;

var
  sk_CONF_VALUE_num: function(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl = Load_sk_CONF_VALUE_num;
  sk_CONF_VALUE_value: function(_para: Pstack_st_CONF_VALUE; _para2: TOpenSSL_C_INT): Pstack_st_CONF_VALUE; cdecl = Load_sk_CONF_VALUE_value;
  sk_CONF_VALUE_new: function(cmp: Tsk_CONF_VALUE_compfunc): Pstack_st_CONF_VALUE; cdecl = Load_sk_CONF_VALUE_new;
  sk_CONF_VALUE_new_null: function: Pstack_st_CONF_VALUE; cdecl = Load_sk_CONF_VALUE_new_null;
  sk_CONF_VALUE_new_reserve: function(cmp: Tsk_CONF_VALUE_compfunc; n: TOpenSSL_C_INT): Pstack_st_CONF_VALUE; cdecl = Load_sk_CONF_VALUE_new_reserve;
  sk_CONF_VALUE_reserve: function(_para: Pstack_st_CONF_VALUE; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_CONF_VALUE_reserve;
  sk_CONF_VALUE_free: function(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl = Load_sk_CONF_VALUE_free;
  sk_CONF_VALUE_zero: function(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl = Load_sk_CONF_VALUE_zero;
  sk_CONF_VALUE_delete: function(st: Pstack_st_CONF_VALUE; loc: TOpenSSL_C_INT): Pstack_st_CONF_VALUE; cdecl = Load_sk_CONF_VALUE_delete;
  sk_CONF_VALUE_delete_ptr: function(st: Pstack_st_CONF_VALUE; ptr: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl = Load_sk_CONF_VALUE_delete_ptr;
  sk_CONF_VALUE_push: function(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_CONF_VALUE_push;
  sk_CONF_VALUE_unshift: function(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_CONF_VALUE_unshift;
  sk_CONF_VALUE_pop: function(_para: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl = Load_sk_CONF_VALUE_pop;
  sk_CONF_VALUE_shift: function(_para: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl = Load_sk_CONF_VALUE_shift;
  sk_CONF_VALUE_pop_free: procedure(st: Pstack_st_CONF_VALUE; func: Tsk_CONF_VALUE_freefunc); cdecl = Load_sk_CONF_VALUE_pop_free;
  sk_CONF_VALUE_insert: function(st: Pstack_st_CONF_VALUE; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_CONF_VALUE_insert;
  sk_CONF_VALUE_set: function(st: Pstack_st_CONF_VALUE; i: TOpenSSL_C_INT; data: pointer): Pstack_st_CONF_VALUE; cdecl = Load_sk_CONF_VALUE_set;
  sk_CONF_VALUE_find: function(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_CONF_VALUE_find;
  sk_CONF_VALUE_find_ex: function(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_CONF_VALUE_find_ex;
  sk_CONF_VALUE_find_all: function(st: Pstack_st_CONF_VALUE; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_CONF_VALUE_find_all;
  sk_CONF_VALUE_sort: function(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl = Load_sk_CONF_VALUE_sort;
  sk_CONF_VALUE_is_sorted: function(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl = Load_sk_CONF_VALUE_is_sorted;
  sk_CONF_VALUE_dup: function(st: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl = Load_sk_CONF_VALUE_dup;
  sk_CONF_VALUE_deep_copy: function(st: Pstack_st_CONF_VALUE; c: Tsk_CONF_VALUE_compfunc; f: Tsk_CONF_VALUE_freefunc): Pstack_st_CONF_VALUE; cdecl = Load_sk_CONF_VALUE_deep_copy;
  sk_CONF_VALUE_set_cmp_func: function(st: Pstack_st_CONF_VALUE; cmp: Tsk_CONF_VALUE_compfunc): Tsk_CONF_VALUE_compfunc; cdecl = Load_sk_CONF_VALUE_set_cmp_func;
  {$endif} {OPENSSL_STATIC_LINK_MODEL}

type
  {Auto-generated forward references}
  Plh_CONF_VALUE_dummy = ^Tlh_CONF_VALUE_dummy;
  PPlh_CONF_VALUE_dummy = ^Plh_CONF_VALUE_dummy;
  Plhash_st_CONF_VALUE = ^Tlhash_st_CONF_VALUE;
  PPlhash_st_CONF_VALUE = ^Plhash_st_CONF_VALUE;
  Plh_CONF_VALUE_compfunc = ^Tlh_CONF_VALUE_compfunc;
  PPlh_CONF_VALUE_compfunc = ^Plh_CONF_VALUE_compfunc;
  Plh_CONF_VALUE_hashfunc = ^Tlh_CONF_VALUE_hashfunc;
  PPlh_CONF_VALUE_hashfunc = ^Plh_CONF_VALUE_hashfunc;
  Plh_CONF_VALUE_doallfunc = ^Tlh_CONF_VALUE_doallfunc;
  PPlh_CONF_VALUE_doallfunc = ^Plh_CONF_VALUE_doallfunc;
  {end of auto-generated forward references}

  Tlh_CONF_VALUE_dummy = record 
    case integer of 
      0: (d1: pointer);
      1: (d2: TOpenSSL_C_UINT);
      2: (d3: TOpenSSL_C_INT);
  end;
  Tlhash_st_CONF_VALUE = record 
    dummy: Tlh_CONF_VALUE_dummy;
  end;
  Tlh_CONF_VALUE_compfunc = function(a: PCONF_VALUE; b: PCONF_VALUE): TOpenSSL_C_INT; cdecl;
  Tlh_CONF_VALUE_hashfunc = function(a: PCONF_VALUE): TOpenSSL_C_UINT; cdecl;
  Tlh_CONF_VALUE_doallfunc = procedure(a: PCONF_VALUE); cdecl;


  function lh_CONF_VALUE_hash_thunk(data: pointer; hfn: TOPENSSL_LH_HASHFUNC): TOpenSSL_C_UINT; inline;
  function lh_CONF_VALUE_comp_thunk(da: pointer; db: pointer; cfn: TOPENSSL_LH_COMPFUNC): TOpenSSL_C_INT; inline;
  procedure lh_CONF_VALUE_doall_thunk(node: pointer; doall: TOPENSSL_LH_DOALL_FUNC); inline;
  procedure lh_CONF_VALUE_doall_arg_thunk(node: pointer; arg: pointer; doall: TOPENSSL_LH_DOALL_FUNCARG); inline;
  function ossl_check_CONF_VALUE_lh_plain_type(ptr: PCONF_VALUE): PCONF_VALUE{Has C Attribute: unused}; inline;
  function ossl_check_const_CONF_VALUE_lh_plain_type(ptr: PCONF_VALUE): PCONF_VALUE{Has C Attribute: unused}; inline;
  function ossl_check_const_CONF_VALUE_lh_type(lh: Plhash_st_CONF_VALUE): POPENSSL_LHASH{Has C Attribute: unused}; inline;
  function ossl_check_CONF_VALUE_lh_type(lh: Plhash_st_CONF_VALUE): POPENSSL_LHASH{Has C Attribute: unused}; inline;
  function ossl_check_CONF_VALUE_lh_compfunc_type(cmp: Tlh_CONF_VALUE_compfunc): TOPENSSL_LH_COMPFUNC{Has C Attribute: unused}; inline;
  function ossl_check_CONF_VALUE_lh_hashfunc_type(hfn: Tlh_CONF_VALUE_hashfunc): TOPENSSL_LH_HASHFUNC{Has C Attribute: unused}; inline;
  function ossl_check_CONF_VALUE_lh_doallfunc_type(dfn: Tlh_CONF_VALUE_doallfunc): TOPENSSL_LH_DOALL_FUNC{Has C Attribute: unused}; inline;
  {# define  lh_CONF_VALUE_new(hfn,cmp) ((LHASH_OF(CONF_VALUE) *)OPENSSL_LH_set_thunks(OPENSSL_LH_new(ossl_check_CONF_VALUE_lh_hashfunc_type(hfn),
 ossl_check_CONF_VALUE_lh_compfunc_type(cmp)), lh_CONF_VALUE_hash_thunk, lh_CONF_VALUE_comp_thunk, lh_CONF_VALUE_doall_thunk, lh_CONF_VALUE_doall_arg_thunk))}
  {# define  lh_CONF_VALUE_free(lh) OPENSSL_LH_free(ossl_check_CONF_VALUE_lh_type(lh))} {Macro Return Type unknown at line no 77}
  {# define  lh_CONF_VALUE_flush(lh) OPENSSL_LH_flush(ossl_check_CONF_VALUE_lh_type(lh))} {Macro Return Type unknown at line no 78}
  function lh_CONF_VALUE_insert(lh:Plhash_st_CONF_VALUE; ptr:PCONF_VALUE): PCONF_VALUE; inline;
  function lh_CONF_VALUE_delete(lh:Plhash_st_CONF_VALUE; ptr:PCONF_VALUE): PCONF_VALUE; inline;
  function lh_CONF_VALUE_retrieve(lh:Plhash_st_CONF_VALUE; ptr:PCONF_VALUE): PCONF_VALUE; inline;
  {# define  lh_CONF_VALUE_error(lh) OPENSSL_LH_error(ossl_check_CONF_VALUE_lh_type(lh))} {Macro Return Type unknown at line no 82}
  {# define  lh_CONF_VALUE_num_items(lh) OPENSSL_LH_num_items(ossl_check_CONF_VALUE_lh_type(lh))} {Macro Return Type unknown at line no 83}
  {# define  lh_CONF_VALUE_node_stats_bio(lh,out) OPENSSL_LH_node_stats_bio(ossl_check_const_CONF_VALUE_lh_type(lh), out)} {Function argument out of range at line no 84}
  {# define  lh_CONF_VALUE_node_usage_stats_bio(lh,out) OPENSSL_LH_node_usage_stats_bio(ossl_check_const_CONF_VALUE_lh_type(lh), out)} {Function argument out of range at line no 85}
  {# define  lh_CONF_VALUE_stats_bio(lh,out) OPENSSL_LH_stats_bio(ossl_check_const_CONF_VALUE_lh_type(lh), out)} {Function argument out of range at line no 86}
  {# define  lh_CONF_VALUE_get_down_load(lh) OPENSSL_LH_get_down_load(ossl_check_CONF_VALUE_lh_type(lh))} {Macro Return Type unknown at line no 87}
  {# define  lh_CONF_VALUE_set_down_load(lh,dl) OPENSSL_LH_set_down_load(ossl_check_CONF_VALUE_lh_type(lh), dl)} {Function argument out of range at line no 88}
  {# define  lh_CONF_VALUE_doall(lh,dfn) OPENSSL_LH_doall(ossl_check_CONF_VALUE_lh_type(lh), ossl_check_CONF_VALUE_lh_doallfunc_type(dfn))} {Macro Return Type unknown at line no 89}

type
  {Auto-generated forward references}
  Pconf_st = ^Tconf_st;
  PPconf_st = ^Pconf_st;
  Pconf_method_st = ^Tconf_method_st;
  PPconf_method_st = ^Pconf_method_st;
  PCONF_METHOD = ^TCONF_METHOD;
  PPCONF_METHOD = ^PCONF_METHOD;
  {end of auto-generated forward references}

  { clang-format on }
  Tconf_st = record 
  end;
  Tconf_method_st = record 
  end;
  TCONF_METHOD = Tconf_method_st;
  {$ifndef  OPENSSL_NO_DEPRECATED_3_0}
  {$endif}

type
  {Auto-generated forward references}
  Pconf_imodule_st = ^TCONF_IMODULE;
  PPconf_imodule_st = ^Pconf_imodule_st;
  PCONF_IMODULE = ^TCONF_IMODULE;
  PPCONF_IMODULE = ^PCONF_IMODULE;
  Pconf_module_st = ^TCONF_MODULE;
  PPconf_module_st = ^Pconf_module_st;
  PCONF_MODULE = ^TCONF_MODULE;
  PPCONF_MODULE = ^PCONF_MODULE;
  Pstack_st_CONF_MODULE = ^Tstack_st_CONF_MODULE;
  PPstack_st_CONF_MODULE = ^Pstack_st_CONF_MODULE;
  Pstack_st_CONF_IMODULE = ^Tstack_st_CONF_IMODULE;
  PPstack_st_CONF_IMODULE = ^Pstack_st_CONF_IMODULE;
  Pconf_init_func = ^Tconf_init_func;
  PPconf_init_func = ^Pconf_init_func;
  Pconf_finish_func = ^Tconf_finish_func;
  PPconf_finish_func = ^Pconf_finish_func;
  {end of auto-generated forward references}

  { Module definitions }
  Tconf_imodule_st = record end;
  TCONF_IMODULE = Tconf_imodule_st;
  Tconf_module_st = record end;
  TCONF_MODULE = Tconf_module_st;
  Tstack_st_CONF_MODULE = record 
  end;
  Tstack_st_CONF_IMODULE = record 
  end;
  { DSO module function typedefs }
  Tconf_init_func = function(md: PCONF_IMODULE; cnf: PCONF): TOpenSSL_C_INT; cdecl;
  Tconf_finish_func = procedure(md: PCONF_IMODULE); cdecl;

const
  CONF_MFLAGS_IGNORE_ERRORS = $1;
  CONF_MFLAGS_IGNORE_RETURN_CODES = $2;
  CONF_MFLAGS_SILENT = $4;
  CONF_MFLAGS_NO_DSO = $8;
  CONF_MFLAGS_IGNORE_MISSING_FILE = $10;
  CONF_MFLAGS_DEFAULT_SECTION = $20;


  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function CONF_set_default_method(meth: PCONF_METHOD): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'CONF_set_default_method';
  procedure CONF_set_nconf(conf: PCONF; hash: Plhash_st_CONF_VALUE); cdecl; external CLibCrypto name 'CONF_set_nconf';
  function CONF_load(conf: Plhash_st_CONF_VALUE; file_: PAnsiChar; eline: POpenSSL_C_INT): Plhash_st_CONF_VALUE; cdecl; external CLibCrypto name 'CONF_load';
  {$else}
  {$EXTERNALSYM CONF_set_default_method}
  {$EXTERNALSYM CONF_set_nconf}
  {$EXTERNALSYM CONF_load}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_CONF_set_default_method(meth: PCONF_METHOD): TOpenSSL_C_INT; cdecl;
  procedure Load_CONF_set_nconf(conf: PCONF; hash: Plhash_st_CONF_VALUE); cdecl;
  function Load_CONF_load(conf: Plhash_st_CONF_VALUE; file_: PAnsiChar; eline: POpenSSL_C_INT): Plhash_st_CONF_VALUE; cdecl;

var
  CONF_set_default_method: function(meth: PCONF_METHOD): TOpenSSL_C_INT; cdecl = Load_CONF_set_default_method;
  CONF_set_nconf: procedure(conf: PCONF; hash: Plhash_st_CONF_VALUE); cdecl = Load_CONF_set_nconf;
  CONF_load: function(conf: Plhash_st_CONF_VALUE; file_: PAnsiChar; eline: POpenSSL_C_INT): Plhash_st_CONF_VALUE; cdecl = Load_CONF_load;
  {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$ifndef  OPENSSL_NO_STDIO}


    {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function CONF_load_fp(conf: Plhash_st_CONF_VALUE; fp: PFILE; eline: POpenSSL_C_INT): Plhash_st_CONF_VALUE; cdecl; external CLibCrypto name 'CONF_load_fp';
    {$else}
  {$EXTERNALSYM CONF_load_fp}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_CONF_load_fp(conf: Plhash_st_CONF_VALUE; fp: PFILE; eline: POpenSSL_C_INT): Plhash_st_CONF_VALUE; cdecl;

var
  CONF_load_fp: function(conf: Plhash_st_CONF_VALUE; fp: PFILE; eline: POpenSSL_C_INT): Plhash_st_CONF_VALUE; cdecl = Load_CONF_load_fp;
    {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$endif}


  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function CONF_load_bio(conf: Plhash_st_CONF_VALUE; bp: PBIO; eline: POpenSSL_C_INT): Plhash_st_CONF_VALUE; cdecl; external CLibCrypto name 'CONF_load_bio';
  function CONF_get_section(conf: Plhash_st_CONF_VALUE; section: PAnsiChar): Pstack_st_CONF_VALUE; cdecl; external CLibCrypto name 'CONF_get_section';
  function CONF_get_string(conf: Plhash_st_CONF_VALUE; group: PAnsiChar; name: PAnsiChar): PAnsiChar; cdecl; external CLibCrypto name 'CONF_get_string';
  function CONF_get_number(conf: Plhash_st_CONF_VALUE; group: PAnsiChar; name: PAnsiChar): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'CONF_get_number';
  procedure CONF_free(conf: Plhash_st_CONF_VALUE); cdecl; external CLibCrypto name 'CONF_free';
  {$else}
  {$EXTERNALSYM CONF_load_bio}
  {$EXTERNALSYM CONF_get_section}
  {$EXTERNALSYM CONF_get_string}
  {$EXTERNALSYM CONF_get_number}
  {$EXTERNALSYM CONF_free}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_CONF_load_bio(conf: Plhash_st_CONF_VALUE; bp: PBIO; eline: POpenSSL_C_INT): Plhash_st_CONF_VALUE; cdecl;
  function Load_CONF_get_section(conf: Plhash_st_CONF_VALUE; section: PAnsiChar): Pstack_st_CONF_VALUE; cdecl;
  function Load_CONF_get_string(conf: Plhash_st_CONF_VALUE; group: PAnsiChar; name: PAnsiChar): PAnsiChar; cdecl;
  function Load_CONF_get_number(conf: Plhash_st_CONF_VALUE; group: PAnsiChar; name: PAnsiChar): TOpenSSL_C_INT; cdecl;
  procedure Load_CONF_free(conf: Plhash_st_CONF_VALUE); cdecl;

var
  CONF_load_bio: function(conf: Plhash_st_CONF_VALUE; bp: PBIO; eline: POpenSSL_C_INT): Plhash_st_CONF_VALUE; cdecl = Load_CONF_load_bio;
  CONF_get_section: function(conf: Plhash_st_CONF_VALUE; section: PAnsiChar): Pstack_st_CONF_VALUE; cdecl = Load_CONF_get_section;
  CONF_get_string: function(conf: Plhash_st_CONF_VALUE; group: PAnsiChar; name: PAnsiChar): PAnsiChar; cdecl = Load_CONF_get_string;
  CONF_get_number: function(conf: Plhash_st_CONF_VALUE; group: PAnsiChar; name: PAnsiChar): TOpenSSL_C_INT; cdecl = Load_CONF_get_number;
  CONF_free: procedure(conf: Plhash_st_CONF_VALUE); cdecl = Load_CONF_free;
  {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$ifndef  OPENSSL_NO_STDIO}


    {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function CONF_dump_fp(conf: Plhash_st_CONF_VALUE; out_: PFILE): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'CONF_dump_fp';
    {$else}
  {$EXTERNALSYM CONF_dump_fp}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_CONF_dump_fp(conf: Plhash_st_CONF_VALUE; out_: PFILE): TOpenSSL_C_INT; cdecl;

var
  CONF_dump_fp: function(conf: Plhash_st_CONF_VALUE; out_: PFILE): TOpenSSL_C_INT; cdecl = Load_CONF_dump_fp;
    {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$endif}


  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function CONF_dump_bio(conf: Plhash_st_CONF_VALUE; out_: PBIO): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'CONF_dump_bio';
  {$else}
  {$EXTERNALSYM CONF_dump_bio}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_CONF_dump_bio(conf: Plhash_st_CONF_VALUE; out_: PBIO): TOpenSSL_C_INT; cdecl;

var
  CONF_dump_bio: function(conf: Plhash_st_CONF_VALUE; out_: PBIO): TOpenSSL_C_INT; cdecl = Load_CONF_dump_bio;
  {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$ifndef  OPENSSL_NO_DEPRECATED_1_1_0}


    {$ifdef OPENSSL_STATIC_LINK_MODEL}
  procedure OPENSSL_config(config_name: PAnsiChar); cdecl; external CLibCrypto name 'OPENSSL_config'; deprecated 'Since OpenSSL 1.1.0';
    {$else}
  {$EXTERNALSYM OPENSSL_config}
  {Do not call Function LoadDeclarations. Internal use only}
  procedure Load_OPENSSL_config(config_name: PAnsiChar); cdecl;

var
  OPENSSL_config: procedure(config_name: PAnsiChar); cdecl = Load_OPENSSL_config;
    {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$endif}
  {$ifndef  OPENSSL_NO_DEPRECATED_1_1_0}
{# define  OPENSSL_no_config() OPENSSL_init_crypto(OPENSSL_INIT_NO_LOAD_CONFIG, NULL)} {Macro Return Type unknown at line no 145}
  {$endif}


  
  {* New conf code.  The semantics are different from the functions above. If
  * that wasn't the case, the above functions would have been replaced
  }
  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function NCONF_new_ex(libctx: POSSL_LIB_CTX; meth: PCONF_METHOD): PCONF; cdecl; external CLibCrypto name 'NCONF_new_ex';
  function NCONF_get0_libctx(conf: PCONF): POSSL_LIB_CTX; cdecl; external CLibCrypto name 'NCONF_get0_libctx';
  function NCONF_new(meth: PCONF_METHOD): PCONF; cdecl; external CLibCrypto name 'NCONF_new';
  function NCONF_default: PCONF_METHOD; cdecl; external CLibCrypto name 'NCONF_default';
  {$else}
  {$EXTERNALSYM NCONF_new_ex}
  {$EXTERNALSYM NCONF_get0_libctx}
  {$EXTERNALSYM NCONF_new}
  {$EXTERNALSYM NCONF_default}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_NCONF_new_ex(libctx: POSSL_LIB_CTX; meth: PCONF_METHOD): PCONF; cdecl;
  function Load_NCONF_get0_libctx(conf: PCONF): POSSL_LIB_CTX; cdecl;
  function Load_NCONF_new(meth: PCONF_METHOD): PCONF; cdecl;
  function Load_NCONF_default: PCONF_METHOD; cdecl;

var
  NCONF_new_ex: function(libctx: POSSL_LIB_CTX; meth: PCONF_METHOD): PCONF; cdecl = Load_NCONF_new_ex;
  NCONF_get0_libctx: function(conf: PCONF): POSSL_LIB_CTX; cdecl = Load_NCONF_get0_libctx;
  NCONF_new: function(meth: PCONF_METHOD): PCONF; cdecl = Load_NCONF_new;
  NCONF_default: function: PCONF_METHOD; cdecl = Load_NCONF_default;
  {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$ifndef  OPENSSL_NO_DEPRECATED_3_0}


    {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function NCONF_WIN32: PCONF_METHOD; cdecl; external CLibCrypto name 'NCONF_WIN32'; deprecated 'Since OpenSSL 3.0';
    {$else}
  {$EXTERNALSYM NCONF_WIN32}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_NCONF_WIN32: PCONF_METHOD; cdecl;

var
  NCONF_WIN32: function: PCONF_METHOD; cdecl = Load_NCONF_WIN32;
    {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$endif}


  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  procedure NCONF_free(conf: PCONF); cdecl; external CLibCrypto name 'NCONF_free';
  procedure NCONF_free_data(conf: PCONF); cdecl; external CLibCrypto name 'NCONF_free_data';
  function NCONF_load(conf: PCONF; file_: PAnsiChar; eline: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'NCONF_load';
  {$else}
  {$EXTERNALSYM NCONF_free}
  {$EXTERNALSYM NCONF_free_data}
  {$EXTERNALSYM NCONF_load}
  {Do not call Function LoadDeclarations. Internal use only}
  procedure Load_NCONF_free(conf: PCONF); cdecl;
  procedure Load_NCONF_free_data(conf: PCONF); cdecl;
  function Load_NCONF_load(conf: PCONF; file_: PAnsiChar; eline: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;

var
  NCONF_free: procedure(conf: PCONF); cdecl = Load_NCONF_free;
  NCONF_free_data: procedure(conf: PCONF); cdecl = Load_NCONF_free_data;
  NCONF_load: function(conf: PCONF; file_: PAnsiChar; eline: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_NCONF_load;
  {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$ifndef  OPENSSL_NO_STDIO}


    {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function NCONF_load_fp(conf: PCONF; fp: PFILE; eline: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'NCONF_load_fp';
    {$else}
  {$EXTERNALSYM NCONF_load_fp}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_NCONF_load_fp(conf: PCONF; fp: PFILE; eline: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;

var
  NCONF_load_fp: function(conf: PCONF; fp: PFILE; eline: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_NCONF_load_fp;
    {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$endif}


  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function NCONF_load_bio(conf: PCONF; bp: PBIO; eline: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'NCONF_load_bio';
  function NCONF_get_section_names(conf: PCONF): Pstack_st_OPENSSL_CSTRING; cdecl; external CLibCrypto name 'NCONF_get_section_names';
  function NCONF_get_section(conf: PCONF; section: PAnsiChar): Pstack_st_CONF_VALUE; cdecl; external CLibCrypto name 'NCONF_get_section';
  function NCONF_get_string(conf: PCONF; group: PAnsiChar; name: PAnsiChar): PAnsiChar; cdecl; external CLibCrypto name 'NCONF_get_string';
  function NCONF_get_number_e(conf: PCONF; group: PAnsiChar; name: PAnsiChar; result_: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'NCONF_get_number_e';
  {$else}
  {$EXTERNALSYM NCONF_load_bio}
  {$EXTERNALSYM NCONF_get_section_names}
  {$EXTERNALSYM NCONF_get_section}
  {$EXTERNALSYM NCONF_get_string}
  {$EXTERNALSYM NCONF_get_number_e}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_NCONF_load_bio(conf: PCONF; bp: PBIO; eline: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_NCONF_get_section_names(conf: PCONF): Pstack_st_OPENSSL_CSTRING; cdecl;
  function Load_NCONF_get_section(conf: PCONF; section: PAnsiChar): Pstack_st_CONF_VALUE; cdecl;
  function Load_NCONF_get_string(conf: PCONF; group: PAnsiChar; name: PAnsiChar): PAnsiChar; cdecl;
  function Load_NCONF_get_number_e(conf: PCONF; group: PAnsiChar; name: PAnsiChar; result_: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;

var
  NCONF_load_bio: function(conf: PCONF; bp: PBIO; eline: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_NCONF_load_bio;
  NCONF_get_section_names: function(conf: PCONF): Pstack_st_OPENSSL_CSTRING; cdecl = Load_NCONF_get_section_names;
  NCONF_get_section: function(conf: PCONF; section: PAnsiChar): Pstack_st_CONF_VALUE; cdecl = Load_NCONF_get_section;
  NCONF_get_string: function(conf: PCONF; group: PAnsiChar; name: PAnsiChar): PAnsiChar; cdecl = Load_NCONF_get_string;
  NCONF_get_number_e: function(conf: PCONF; group: PAnsiChar; name: PAnsiChar; result_: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_NCONF_get_number_e;
  {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$ifndef  OPENSSL_NO_STDIO}


    {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function NCONF_dump_fp(conf: PCONF; out_: PFILE): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'NCONF_dump_fp';
    {$else}
  {$EXTERNALSYM NCONF_dump_fp}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_NCONF_dump_fp(conf: PCONF; out_: PFILE): TOpenSSL_C_INT; cdecl;

var
  NCONF_dump_fp: function(conf: PCONF; out_: PFILE): TOpenSSL_C_INT; cdecl = Load_NCONF_dump_fp;
    {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$endif}


  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function NCONF_dump_bio(conf: PCONF; out_: PBIO): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'NCONF_dump_bio';
  {$else}
  {$EXTERNALSYM NCONF_dump_bio}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_NCONF_dump_bio(conf: PCONF; out_: PBIO): TOpenSSL_C_INT; cdecl;

var
  NCONF_dump_bio: function(conf: PCONF; out_: PBIO): TOpenSSL_C_INT; cdecl = Load_NCONF_dump_bio;
  {$endif} {OPENSSL_STATIC_LINK_MODEL}


  function NCONF_get_number(c:PCONF; g:PAnsiChar; n:PAnsiChar; r:POpenSSL_C_INT): TOpenSSL_C_INT; inline;
  { Module functions }
  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function CONF_modules_load(cnf: PCONF; appname: PAnsiChar; flags: TOpenSSL_C_UINT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'CONF_modules_load';
  function CONF_modules_load_file_ex(libctx: POSSL_LIB_CTX; filename: PAnsiChar; appname: PAnsiChar; flags: TOpenSSL_C_UINT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'CONF_modules_load_file_ex';
  function CONF_modules_load_file(filename: PAnsiChar; appname: PAnsiChar; flags: TOpenSSL_C_UINT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'CONF_modules_load_file';
  procedure CONF_modules_unload(all: TOpenSSL_C_INT); cdecl; external CLibCrypto name 'CONF_modules_unload';
  procedure CONF_modules_finish; cdecl; external CLibCrypto name 'CONF_modules_finish';
  {$else}
  {$EXTERNALSYM CONF_modules_load}
  {$EXTERNALSYM CONF_modules_load_file_ex}
  {$EXTERNALSYM CONF_modules_load_file}
  {$EXTERNALSYM CONF_modules_unload}
  {$EXTERNALSYM CONF_modules_finish}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_CONF_modules_load(cnf: PCONF; appname: PAnsiChar; flags: TOpenSSL_C_UINT): TOpenSSL_C_INT; cdecl;
  function Load_CONF_modules_load_file_ex(libctx: POSSL_LIB_CTX; filename: PAnsiChar; appname: PAnsiChar; flags: TOpenSSL_C_UINT): TOpenSSL_C_INT; cdecl;
  function Load_CONF_modules_load_file(filename: PAnsiChar; appname: PAnsiChar; flags: TOpenSSL_C_UINT): TOpenSSL_C_INT; cdecl;
  procedure Load_CONF_modules_unload(all: TOpenSSL_C_INT); cdecl;
  procedure Load_CONF_modules_finish; cdecl;

var
  CONF_modules_load: function(cnf: PCONF; appname: PAnsiChar; flags: TOpenSSL_C_UINT): TOpenSSL_C_INT; cdecl = Load_CONF_modules_load;
  CONF_modules_load_file_ex: function(libctx: POSSL_LIB_CTX; filename: PAnsiChar; appname: PAnsiChar; flags: TOpenSSL_C_UINT): TOpenSSL_C_INT; cdecl = Load_CONF_modules_load_file_ex;
  CONF_modules_load_file: function(filename: PAnsiChar; appname: PAnsiChar; flags: TOpenSSL_C_UINT): TOpenSSL_C_INT; cdecl = Load_CONF_modules_load_file;
  CONF_modules_unload: procedure(all: TOpenSSL_C_INT); cdecl = Load_CONF_modules_unload;
  CONF_modules_finish: procedure; cdecl = Load_CONF_modules_finish;
  {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$ifndef  OPENSSL_NO_DEPRECATED_1_1_0}
{# define  CONF_modules_free() while (0) continue}
  {$endif}


  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function CONF_module_add(name: PAnsiChar; ifunc: Pconf_init_func; ffunc: Pconf_finish_func): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'CONF_module_add';
  function CONF_imodule_get_name(md: PCONF_IMODULE): PAnsiChar; cdecl; external CLibCrypto name 'CONF_imodule_get_name';
  function CONF_imodule_get_value(md: PCONF_IMODULE): PAnsiChar; cdecl; external CLibCrypto name 'CONF_imodule_get_value';
  function CONF_imodule_get_usr_data(md: PCONF_IMODULE): pointer; cdecl; external CLibCrypto name 'CONF_imodule_get_usr_data';
  procedure CONF_imodule_set_usr_data(md: PCONF_IMODULE; usr_data: pointer); cdecl; external CLibCrypto name 'CONF_imodule_set_usr_data';
  function CONF_imodule_get_module(md: PCONF_IMODULE): PCONF_MODULE; cdecl; external CLibCrypto name 'CONF_imodule_get_module';
  function CONF_imodule_get_flags(md: PCONF_IMODULE): TOpenSSL_C_UINT; cdecl; external CLibCrypto name 'CONF_imodule_get_flags';
  procedure CONF_imodule_set_flags(md: PCONF_IMODULE; flags: TOpenSSL_C_UINT); cdecl; external CLibCrypto name 'CONF_imodule_set_flags';
  function CONF_module_get_usr_data(pmod: PCONF_MODULE): pointer; cdecl; external CLibCrypto name 'CONF_module_get_usr_data';
  procedure CONF_module_set_usr_data(pmod: PCONF_MODULE; usr_data: pointer); cdecl; external CLibCrypto name 'CONF_module_set_usr_data';
  function CONF_get1_default_config_file: PAnsiChar; cdecl; external CLibCrypto name 'CONF_get1_default_config_file';
  {$else}
  {$EXTERNALSYM CONF_module_add}
  {$EXTERNALSYM CONF_imodule_get_name}
  {$EXTERNALSYM CONF_imodule_get_value}
  {$EXTERNALSYM CONF_imodule_get_usr_data}
  {$EXTERNALSYM CONF_imodule_set_usr_data}
  {$EXTERNALSYM CONF_imodule_get_module}
  {$EXTERNALSYM CONF_imodule_get_flags}
  {$EXTERNALSYM CONF_imodule_set_flags}
  {$EXTERNALSYM CONF_module_get_usr_data}
  {$EXTERNALSYM CONF_module_set_usr_data}
  {$EXTERNALSYM CONF_get1_default_config_file}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_CONF_module_add(name: PAnsiChar; ifunc: Pconf_init_func; ffunc: Pconf_finish_func): TOpenSSL_C_INT; cdecl;
  function Load_CONF_imodule_get_name(md: PCONF_IMODULE): PAnsiChar; cdecl;
  function Load_CONF_imodule_get_value(md: PCONF_IMODULE): PAnsiChar; cdecl;
  function Load_CONF_imodule_get_usr_data(md: PCONF_IMODULE): pointer; cdecl;
  procedure Load_CONF_imodule_set_usr_data(md: PCONF_IMODULE; usr_data: pointer); cdecl;
  function Load_CONF_imodule_get_module(md: PCONF_IMODULE): PCONF_MODULE; cdecl;
  function Load_CONF_imodule_get_flags(md: PCONF_IMODULE): TOpenSSL_C_UINT; cdecl;
  procedure Load_CONF_imodule_set_flags(md: PCONF_IMODULE; flags: TOpenSSL_C_UINT); cdecl;
  function Load_CONF_module_get_usr_data(pmod: PCONF_MODULE): pointer; cdecl;
  procedure Load_CONF_module_set_usr_data(pmod: PCONF_MODULE; usr_data: pointer); cdecl;
  function Load_CONF_get1_default_config_file: PAnsiChar; cdecl;

var
  CONF_module_add: function(name: PAnsiChar; ifunc: Pconf_init_func; ffunc: Pconf_finish_func): TOpenSSL_C_INT; cdecl = Load_CONF_module_add;
  CONF_imodule_get_name: function(md: PCONF_IMODULE): PAnsiChar; cdecl = Load_CONF_imodule_get_name;
  CONF_imodule_get_value: function(md: PCONF_IMODULE): PAnsiChar; cdecl = Load_CONF_imodule_get_value;
  CONF_imodule_get_usr_data: function(md: PCONF_IMODULE): pointer; cdecl = Load_CONF_imodule_get_usr_data;
  CONF_imodule_set_usr_data: procedure(md: PCONF_IMODULE; usr_data: pointer); cdecl = Load_CONF_imodule_set_usr_data;
  CONF_imodule_get_module: function(md: PCONF_IMODULE): PCONF_MODULE; cdecl = Load_CONF_imodule_get_module;
  CONF_imodule_get_flags: function(md: PCONF_IMODULE): TOpenSSL_C_UINT; cdecl = Load_CONF_imodule_get_flags;
  CONF_imodule_set_flags: procedure(md: PCONF_IMODULE; flags: TOpenSSL_C_UINT); cdecl = Load_CONF_imodule_set_flags;
  CONF_module_get_usr_data: function(pmod: PCONF_MODULE): pointer; cdecl = Load_CONF_module_get_usr_data;
  CONF_module_set_usr_data: procedure(pmod: PCONF_MODULE; usr_data: pointer); cdecl = Load_CONF_module_set_usr_data;
  CONF_get1_default_config_file: function: PAnsiChar; cdecl = Load_CONF_get1_default_config_file;
  {$endif} {OPENSSL_STATIC_LINK_MODEL}

type
  {Auto-generated forward references}
  PFuncType000 = ^TFuncType000;
  PPFuncType000 = ^PFuncType000;
  {end of auto-generated forward references}

  TFuncType000 = function(elem: PAnsiChar; len: TOpenSSL_C_INT; usr: pointer): TOpenSSL_C_INT; cdecl;


  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function CONF_parse_list(list: PAnsiChar; sep: TOpenSSL_C_INT; nospc: TOpenSSL_C_INT; list_cb: TFuncType000; arg: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'CONF_parse_list';
  procedure OPENSSL_load_builtin_modules; cdecl; external CLibCrypto name 'OPENSSL_load_builtin_modules';
  {$else}
  {$EXTERNALSYM CONF_parse_list}
  {$EXTERNALSYM OPENSSL_load_builtin_modules}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_CONF_parse_list(list: PAnsiChar; sep: TOpenSSL_C_INT; nospc: TOpenSSL_C_INT; list_cb: TFuncType000; arg: pointer): TOpenSSL_C_INT; cdecl;
  procedure Load_OPENSSL_load_builtin_modules; cdecl;

var
  CONF_parse_list: function(list: PAnsiChar; sep: TOpenSSL_C_INT; nospc: TOpenSSL_C_INT; list_cb: TFuncType000; arg: pointer): TOpenSSL_C_INT; cdecl = Load_CONF_parse_list;
  OPENSSL_load_builtin_modules: procedure; cdecl = Load_OPENSSL_load_builtin_modules;
  {$endif} {OPENSSL_STATIC_LINK_MODEL}
{$endif}

implementation

uses Sysutils, variants
  {$ifdef OPENSSL_INTERNAL_NEED_THREADS}
   {$IFNDEF FPC}
     ,System.SyncObjs
     {$IFDEF POSIX}
       ,Posix.Pthread
     {$ELSE}
       ,Windows
     {$ENDIF}
   {$ELSE}
     ,SyncObjs
   {$ENDIF}
  {$endif}
  ,Classes, OpenSSLExceptionHandlers;

  {$if not declared(__FILE__)}
  const
    {$ifdef FPC}
    __FILE__ = {$include %FILE%};
    {$else}
    __FILE__ = '$(INPUTFILENAME)';
    {$endif}
  {$ifend}
  {$if not declared(__LINE__)}
  const
    __LINE__ = 0;
  {$ifend}
  {$if not declared(OPENSSL_FILE)}
  const
    OPENSSL_FILE = __FILE__;
  {$ifend}
  {$if not declared(OPENSSL_LINE)}
  const
    OPENSSL_LINE  = 0;
  {$ifend}

function ossl_check_CONF_VALUE_type(ptr: PCONF_VALUE): PCONF_VALUE{Has C Attribute: unused}; inline;
begin
   Result := ptr;
end;

function ossl_check_const_CONF_VALUE_sk_type(sk: Pstack_st_CONF_VALUE): POPENSSL_STACK{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_STACK(sk);
end;

function ossl_check_CONF_VALUE_sk_type(sk: Pstack_st_CONF_VALUE): POPENSSL_STACK{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_STACK(sk);
end;

function ossl_check_CONF_VALUE_compfunc_type(cmp: Tsk_CONF_VALUE_compfunc): TOPENSSL_sk_compfunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_compfunc(cmp);
end;

function ossl_check_CONF_VALUE_copyfunc_type(cpy: Tsk_CONF_VALUE_copyfunc): TOPENSSL_sk_copyfunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_copyfunc(cpy);
end;

function ossl_check_CONF_VALUE_freefunc_type(fr: Tsk_CONF_VALUE_freefunc): TOPENSSL_sk_freefunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_freefunc(fr);
end;

function lh_CONF_VALUE_hash_thunk(data: pointer; hfn: TOPENSSL_LH_HASHFUNC): TOpenSSL_C_UINT; inline;
begin
  raise Exception.Create('Unable to translate C Function "lh_CONF_VALUE_hash_thunk"');

{Error: Line 75: Syntax Error parsing " unsigned long (*hfn_conv)(const CONF_VALUE *) = (unsigned long (*)(const CONF_VALUE *))hfn; 
return hfn_conv((const CONF_VALUE *)data); "

 unsigned long (*hfn_conv)(const CONF_VALUE *) = (unsigned long (*)(const CONF_VALUE *))hfn; return hfn_conv((const CONF_VALUE 
*)data); }
end;

function lh_CONF_VALUE_comp_thunk(da: pointer; db: pointer; cfn: TOPENSSL_LH_COMPFUNC): TOpenSSL_C_INT; inline;
begin
  raise Exception.Create('Unable to translate C Function "lh_CONF_VALUE_comp_thunk"');

{Error: Line 75: Syntax Error parsing " int (*cfn_conv)(const CONF_VALUE *, const CONF_VALUE *) = (int (*)(const CONF_VALUE *, const 
CONF_VALUE *))cfn; return cfn_conv((const CONF_VALUE *)da, (const CONF_VALUE *)db); "

 int (*cfn_conv)(const CONF_VALUE *, const CONF_VALUE *) = (int (*)(const CONF_VALUE *, const CONF_VALUE *))cfn; return cfn_conv((const 
CONF_VALUE *)da, (const CONF_VALUE *)db); }
end;

procedure lh_CONF_VALUE_doall_thunk(node: pointer; doall: TOPENSSL_LH_DOALL_FUNC); inline;
begin
  raise Exception.Create('Unable to translate C Function "lh_CONF_VALUE_doall_thunk"');

{Error: Line 75: Syntax Error parsing " void (*doall_conv)(CONF_VALUE *) = (void (*)(CONF_VALUE *))doall; doall_conv((CONF_VALUE 
*)node); "

 void (*doall_conv)(CONF_VALUE *) = (void (*)(CONF_VALUE *))doall; doall_conv((CONF_VALUE *)node); }
end;

procedure lh_CONF_VALUE_doall_arg_thunk(node: pointer; arg: pointer; doall: TOPENSSL_LH_DOALL_FUNCARG); inline;
begin
  raise Exception.Create('Unable to translate C Function "lh_CONF_VALUE_doall_arg_thunk"');

{Error: Line 75: Syntax Error parsing " void (*doall_conv)(CONF_VALUE *, void *) = (void (*)(CONF_VALUE *, void *))doall; doall_conv((CONF_VALUE 
*)node, arg); "

 void (*doall_conv)(CONF_VALUE *, void *) = (void (*)(CONF_VALUE *, void *))doall; doall_conv((CONF_VALUE *)node, arg); }
end;

function ossl_check_CONF_VALUE_lh_plain_type(ptr: PCONF_VALUE): PCONF_VALUE{Has C Attribute: unused}; inline;
begin
   Result := ptr;
end;

function ossl_check_const_CONF_VALUE_lh_plain_type(ptr: PCONF_VALUE): PCONF_VALUE{Has C Attribute: unused}; inline;
begin
   Result := ptr;
end;

function ossl_check_const_CONF_VALUE_lh_type(lh: Plhash_st_CONF_VALUE): POPENSSL_LHASH{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_LHASH(lh);
end;

function ossl_check_CONF_VALUE_lh_type(lh: Plhash_st_CONF_VALUE): POPENSSL_LHASH{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_LHASH(lh);
end;

function ossl_check_CONF_VALUE_lh_compfunc_type(cmp: Tlh_CONF_VALUE_compfunc): TOPENSSL_LH_COMPFUNC{Has C Attribute: unused}; inline;
begin
  raise Exception.Create('Unable to translate C Function "ossl_check_CONF_VALUE_lh_compfunc_type"');

{Error: Line 75: Syntax Error parsing " return (OPENSSL_LH_COMPFUNC)cmp; "

 return (OPENSSL_LH_COMPFUNC)cmp; }
end;

function ossl_check_CONF_VALUE_lh_hashfunc_type(hfn: Tlh_CONF_VALUE_hashfunc): TOPENSSL_LH_HASHFUNC{Has C Attribute: unused}; inline;
begin
  raise Exception.Create('Unable to translate C Function "ossl_check_CONF_VALUE_lh_hashfunc_type"');

{Error: Line 75: Syntax Error parsing " return (OPENSSL_LH_HASHFUNC)hfn; "

 return (OPENSSL_LH_HASHFUNC)hfn; }
end;

function ossl_check_CONF_VALUE_lh_doallfunc_type(dfn: Tlh_CONF_VALUE_doallfunc): TOPENSSL_LH_DOALL_FUNC{Has C Attribute: unused}; inline;
begin
  raise Exception.Create('Unable to translate C Function "ossl_check_CONF_VALUE_lh_doallfunc_type"');

{Error: Line 75: Syntax Error parsing " return (OPENSSL_LH_DOALL_FUNC)dfn; "

 return (OPENSSL_LH_DOALL_FUNC)dfn; }
end;


{# define  lh_CONF_VALUE_insert(lh,ptr) ((CONF_VALUE *)OPENSSL_LH_insert(ossl_check_CONF_VALUE_lh_type(lh), ossl_check_CONF_VALUE_lh_plain_type(ptr)))}

function lh_CONF_VALUE_insert(lh:Plhash_st_CONF_VALUE; ptr:PCONF_VALUE): PCONF_VALUE;
begin
  Result := PCONF_VALUE(PCONF_VALUE(OPENSSL_LH_insert(ossl_check_CONF_VALUE_lh_type(lh),ossl_check_CONF_VALUE_lh_plain_type(ptr))));
end;

{# define  lh_CONF_VALUE_delete(lh,ptr) ((CONF_VALUE *)OPENSSL_LH_delete(ossl_check_CONF_VALUE_lh_type(lh), ossl_check_const_CONF_VALUE_lh_plain_type(ptr)))}

function lh_CONF_VALUE_delete(lh:Plhash_st_CONF_VALUE; ptr:PCONF_VALUE): PCONF_VALUE;
begin
  Result := PCONF_VALUE(PCONF_VALUE(OPENSSL_LH_delete(ossl_check_CONF_VALUE_lh_type(lh),ossl_check_const_CONF_VALUE_lh_plain_type(ptr))));
end;

{# define  lh_CONF_VALUE_retrieve(lh,ptr) ((CONF_VALUE *)OPENSSL_LH_retrieve(ossl_check_CONF_VALUE_lh_type(lh), ossl_check_const_CONF_VALUE_lh_plain_type(ptr)))}

function lh_CONF_VALUE_retrieve(lh:Plhash_st_CONF_VALUE; ptr:PCONF_VALUE): PCONF_VALUE;
begin
  Result := PCONF_VALUE(PCONF_VALUE(OPENSSL_LH_retrieve(ossl_check_CONF_VALUE_lh_type(lh),ossl_check_const_CONF_VALUE_lh_plain_type(ptr))));
end;

{# define  NCONF_get_number(c,g,n,r) NCONF_get_number_e(c, g, n, r)}

function NCONF_get_number(c:PCONF; g:PAnsiChar; n:PAnsiChar; r:POpenSSL_C_INT): TOpenSSL_C_INT;
begin
  Result := TOpenSSL_C_INT(NCONF_get_number_e(c,g,n,r));
end;
{$ifndef OPENSSL_STATIC_LINK_MODEL}
function Load_sk_CONF_VALUE_num(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl;
begin
  sk_CONF_VALUE_num := LoadLibCryptoFunction('OPENSSL_sk_num');
  if not assigned(sk_CONF_VALUE_num) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_num');
  Result := sk_CONF_VALUE_num(_para);
end;

function Load_sk_CONF_VALUE_value(_para: Pstack_st_CONF_VALUE; _para2: TOpenSSL_C_INT): Pstack_st_CONF_VALUE; cdecl;
begin
  sk_CONF_VALUE_value := LoadLibCryptoFunction('OPENSSL_sk_value');
  if not assigned(sk_CONF_VALUE_value) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_value');
  Result := sk_CONF_VALUE_value(_para, _para2);
end;

function Load_sk_CONF_VALUE_new(cmp: Tsk_CONF_VALUE_compfunc): Pstack_st_CONF_VALUE; cdecl;
begin
  sk_CONF_VALUE_new := LoadLibCryptoFunction('OPENSSL_sk_new');
  if not assigned(sk_CONF_VALUE_new) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new');
  Result := sk_CONF_VALUE_new(cmp);
end;

function Load_sk_CONF_VALUE_new_null: Pstack_st_CONF_VALUE; cdecl;
begin
  sk_CONF_VALUE_new_null := LoadLibCryptoFunction('OPENSSL_sk_new_null');
  if not assigned(sk_CONF_VALUE_new_null) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new_null');
  Result := sk_CONF_VALUE_new_null;
end;

function Load_sk_CONF_VALUE_new_reserve(cmp: Tsk_CONF_VALUE_compfunc; n: TOpenSSL_C_INT): Pstack_st_CONF_VALUE; cdecl;
begin
  sk_CONF_VALUE_new_reserve := LoadLibCryptoFunction('OPENSSL_sk_new_reserve');
  if not assigned(sk_CONF_VALUE_new_reserve) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new_reserve');
  Result := sk_CONF_VALUE_new_reserve(cmp, n);
end;

function Load_sk_CONF_VALUE_reserve(_para: Pstack_st_CONF_VALUE; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_CONF_VALUE_reserve := LoadLibCryptoFunction('OPENSSL_sk_reserve');
  if not assigned(sk_CONF_VALUE_reserve) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_reserve');
  Result := sk_CONF_VALUE_reserve(_para, n);
end;

function Load_sk_CONF_VALUE_free(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl;
begin
  sk_CONF_VALUE_free := LoadLibCryptoFunction('OPENSSL_sk_free');
  if not assigned(sk_CONF_VALUE_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_free');
  Result := sk_CONF_VALUE_free(_para);
end;

function Load_sk_CONF_VALUE_zero(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl;
begin
  sk_CONF_VALUE_zero := LoadLibCryptoFunction('OPENSSL_sk_zero');
  if not assigned(sk_CONF_VALUE_zero) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_zero');
  Result := sk_CONF_VALUE_zero(_para);
end;

function Load_sk_CONF_VALUE_delete(st: Pstack_st_CONF_VALUE; loc: TOpenSSL_C_INT): Pstack_st_CONF_VALUE; cdecl;
begin
  sk_CONF_VALUE_delete := LoadLibCryptoFunction('OPENSSL_sk_delete');
  if not assigned(sk_CONF_VALUE_delete) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_delete');
  Result := sk_CONF_VALUE_delete(st, loc);
end;

function Load_sk_CONF_VALUE_delete_ptr(st: Pstack_st_CONF_VALUE; ptr: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl;
begin
  sk_CONF_VALUE_delete_ptr := LoadLibCryptoFunction('OPENSSL_sk_delete_ptr');
  if not assigned(sk_CONF_VALUE_delete_ptr) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_delete_ptr');
  Result := sk_CONF_VALUE_delete_ptr(st, ptr);
end;

function Load_sk_CONF_VALUE_push(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_CONF_VALUE_push := LoadLibCryptoFunction('OPENSSL_sk_push');
  if not assigned(sk_CONF_VALUE_push) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_push');
  Result := sk_CONF_VALUE_push(st, data);
end;

function Load_sk_CONF_VALUE_unshift(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_CONF_VALUE_unshift := LoadLibCryptoFunction('OPENSSL_sk_unshift');
  if not assigned(sk_CONF_VALUE_unshift) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_unshift');
  Result := sk_CONF_VALUE_unshift(st, data);
end;

function Load_sk_CONF_VALUE_pop(_para: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl;
begin
  sk_CONF_VALUE_pop := LoadLibCryptoFunction('OPENSSL_sk_pop');
  if not assigned(sk_CONF_VALUE_pop) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_pop');
  Result := sk_CONF_VALUE_pop(_para);
end;

function Load_sk_CONF_VALUE_shift(_para: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl;
begin
  sk_CONF_VALUE_shift := LoadLibCryptoFunction('OPENSSL_sk_shift');
  if not assigned(sk_CONF_VALUE_shift) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_shift');
  Result := sk_CONF_VALUE_shift(_para);
end;

procedure Load_sk_CONF_VALUE_pop_free(st: Pstack_st_CONF_VALUE; func: Tsk_CONF_VALUE_freefunc); cdecl;
begin
  sk_CONF_VALUE_pop_free := LoadLibCryptoFunction('OPENSSL_sk_pop_free');
  if not assigned(sk_CONF_VALUE_pop_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_pop_free');
  sk_CONF_VALUE_pop_free(st, func);
end;

function Load_sk_CONF_VALUE_insert(st: Pstack_st_CONF_VALUE; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_CONF_VALUE_insert := LoadLibCryptoFunction('OPENSSL_sk_insert');
  if not assigned(sk_CONF_VALUE_insert) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_insert');
  Result := sk_CONF_VALUE_insert(st, data, where);
end;

function Load_sk_CONF_VALUE_set(st: Pstack_st_CONF_VALUE; i: TOpenSSL_C_INT; data: pointer): Pstack_st_CONF_VALUE; cdecl;
begin
  sk_CONF_VALUE_set := LoadLibCryptoFunction('OPENSSL_sk_set');
  if not assigned(sk_CONF_VALUE_set) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_set');
  Result := sk_CONF_VALUE_set(st, i, data);
end;

function Load_sk_CONF_VALUE_find(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_CONF_VALUE_find := LoadLibCryptoFunction('OPENSSL_sk_find');
  if not assigned(sk_CONF_VALUE_find) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find');
  Result := sk_CONF_VALUE_find(st, data);
end;

function Load_sk_CONF_VALUE_find_ex(st: Pstack_st_CONF_VALUE; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_CONF_VALUE_find_ex := LoadLibCryptoFunction('OPENSSL_sk_find_ex');
  if not assigned(sk_CONF_VALUE_find_ex) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find_ex');
  Result := sk_CONF_VALUE_find_ex(st, data);
end;

function Load_sk_CONF_VALUE_find_all(st: Pstack_st_CONF_VALUE; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_CONF_VALUE_find_all := LoadLibCryptoFunction('OPENSSL_sk_find_all');
  if not assigned(sk_CONF_VALUE_find_all) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find_all');
  Result := sk_CONF_VALUE_find_all(st, data, pnum);
end;

function Load_sk_CONF_VALUE_sort(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl;
begin
  sk_CONF_VALUE_sort := LoadLibCryptoFunction('OPENSSL_sk_sort');
  if not assigned(sk_CONF_VALUE_sort) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_sort');
  Result := sk_CONF_VALUE_sort(_para);
end;

function Load_sk_CONF_VALUE_is_sorted(_para: Pstack_st_CONF_VALUE): TOpenSSL_C_INT; cdecl;
begin
  sk_CONF_VALUE_is_sorted := LoadLibCryptoFunction('OPENSSL_sk_is_sorted');
  if not assigned(sk_CONF_VALUE_is_sorted) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_is_sorted');
  Result := sk_CONF_VALUE_is_sorted(_para);
end;

function Load_sk_CONF_VALUE_dup(st: Pstack_st_CONF_VALUE): Pstack_st_CONF_VALUE; cdecl;
begin
  sk_CONF_VALUE_dup := LoadLibCryptoFunction('OPENSSL_sk_dup');
  if not assigned(sk_CONF_VALUE_dup) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_dup');
  Result := sk_CONF_VALUE_dup(st);
end;

function Load_sk_CONF_VALUE_deep_copy(st: Pstack_st_CONF_VALUE; c: Tsk_CONF_VALUE_compfunc; f: Tsk_CONF_VALUE_freefunc): Pstack_st_CONF_VALUE; cdecl;
begin
  sk_CONF_VALUE_deep_copy := LoadLibCryptoFunction('OPENSSL_sk_deep_copy');
  if not assigned(sk_CONF_VALUE_deep_copy) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_deep_copy');
  Result := sk_CONF_VALUE_deep_copy(st, c, f);
end;

function Load_sk_CONF_VALUE_set_cmp_func(st: Pstack_st_CONF_VALUE; cmp: Tsk_CONF_VALUE_compfunc): Tsk_CONF_VALUE_compfunc; cdecl;
begin
  sk_CONF_VALUE_set_cmp_func := LoadLibCryptoFunction('OPENSSL_sk_set_cmp_func');
  if not assigned(sk_CONF_VALUE_set_cmp_func) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_set_cmp_func');
  Result := sk_CONF_VALUE_set_cmp_func(st, cmp);
end;

function Load_CONF_set_default_method(meth: PCONF_METHOD): TOpenSSL_C_INT; cdecl;
begin
  CONF_set_default_method := LoadLibCryptoFunction('CONF_set_default_method');
  if not assigned(CONF_set_default_method) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_set_default_method');
  Result := CONF_set_default_method(meth);
end;

procedure Load_CONF_set_nconf(conf: PCONF; hash: Plhash_st_CONF_VALUE); cdecl;
begin
  CONF_set_nconf := LoadLibCryptoFunction('CONF_set_nconf');
  if not assigned(CONF_set_nconf) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_set_nconf');
  CONF_set_nconf(conf, hash);
end;

function Load_CONF_load(conf: Plhash_st_CONF_VALUE; file_: PAnsiChar; eline: POpenSSL_C_INT): Plhash_st_CONF_VALUE; cdecl;
begin
  CONF_load := LoadLibCryptoFunction('CONF_load');
  if not assigned(CONF_load) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_load');
  Result := CONF_load(conf, file_, eline);
end;

{$ifndef  OPENSSL_NO_STDIO}
function Load_CONF_load_fp(conf: Plhash_st_CONF_VALUE; fp: PFILE; eline: POpenSSL_C_INT): Plhash_st_CONF_VALUE; cdecl;
begin
  CONF_load_fp := LoadLibCryptoFunction('CONF_load_fp');
  if not assigned(CONF_load_fp) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_load_fp');
  Result := CONF_load_fp(conf, fp, eline);
end;

{$endif} { OPENSSL_NO_STDIO}
function Load_CONF_load_bio(conf: Plhash_st_CONF_VALUE; bp: PBIO; eline: POpenSSL_C_INT): Plhash_st_CONF_VALUE; cdecl;
begin
  CONF_load_bio := LoadLibCryptoFunction('CONF_load_bio');
  if not assigned(CONF_load_bio) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_load_bio');
  Result := CONF_load_bio(conf, bp, eline);
end;

function Load_CONF_get_section(conf: Plhash_st_CONF_VALUE; section: PAnsiChar): Pstack_st_CONF_VALUE; cdecl;
begin
  CONF_get_section := LoadLibCryptoFunction('CONF_get_section');
  if not assigned(CONF_get_section) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_get_section');
  Result := CONF_get_section(conf, section);
end;

function Load_CONF_get_string(conf: Plhash_st_CONF_VALUE; group: PAnsiChar; name: PAnsiChar): PAnsiChar; cdecl;
begin
  CONF_get_string := LoadLibCryptoFunction('CONF_get_string');
  if not assigned(CONF_get_string) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_get_string');
  Result := CONF_get_string(conf, group, name);
end;

function Load_CONF_get_number(conf: Plhash_st_CONF_VALUE; group: PAnsiChar; name: PAnsiChar): TOpenSSL_C_INT; cdecl;
begin
  CONF_get_number := LoadLibCryptoFunction('CONF_get_number');
  if not assigned(CONF_get_number) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_get_number');
  Result := CONF_get_number(conf, group, name);
end;

procedure Load_CONF_free(conf: Plhash_st_CONF_VALUE); cdecl;
begin
  CONF_free := LoadLibCryptoFunction('CONF_free');
  if not assigned(CONF_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_free');
  CONF_free(conf);
end;

{$ifndef  OPENSSL_NO_STDIO}
function Load_CONF_dump_fp(conf: Plhash_st_CONF_VALUE; out_: PFILE): TOpenSSL_C_INT; cdecl;
begin
  CONF_dump_fp := LoadLibCryptoFunction('CONF_dump_fp');
  if not assigned(CONF_dump_fp) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_dump_fp');
  Result := CONF_dump_fp(conf, out_);
end;

{$endif} { OPENSSL_NO_STDIO}
function Load_CONF_dump_bio(conf: Plhash_st_CONF_VALUE; out_: PBIO): TOpenSSL_C_INT; cdecl;
begin
  CONF_dump_bio := LoadLibCryptoFunction('CONF_dump_bio');
  if not assigned(CONF_dump_bio) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_dump_bio');
  Result := CONF_dump_bio(conf, out_);
end;

{$ifndef  OPENSSL_NO_DEPRECATED_1_1_0}
procedure Load_OPENSSL_config(config_name: PAnsiChar); cdecl;
begin
  OPENSSL_config := LoadLibCryptoFunction('OPENSSL_config');
  if not assigned(OPENSSL_config) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_config');
  OPENSSL_config(config_name);
end;

{$endif} { OPENSSL_NO_DEPRECATED_1_1_0}
function Load_NCONF_new_ex(libctx: POSSL_LIB_CTX; meth: PCONF_METHOD): PCONF; cdecl;
begin
  NCONF_new_ex := LoadLibCryptoFunction('NCONF_new_ex');
  if not assigned(NCONF_new_ex) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_new_ex');
  Result := NCONF_new_ex(libctx, meth);
end;

function Load_NCONF_get0_libctx(conf: PCONF): POSSL_LIB_CTX; cdecl;
begin
  NCONF_get0_libctx := LoadLibCryptoFunction('NCONF_get0_libctx');
  if not assigned(NCONF_get0_libctx) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_get0_libctx');
  Result := NCONF_get0_libctx(conf);
end;

function Load_NCONF_new(meth: PCONF_METHOD): PCONF; cdecl;
begin
  NCONF_new := LoadLibCryptoFunction('NCONF_new');
  if not assigned(NCONF_new) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_new');
  Result := NCONF_new(meth);
end;

function Load_NCONF_default: PCONF_METHOD; cdecl;
begin
  NCONF_default := LoadLibCryptoFunction('NCONF_default');
  if not assigned(NCONF_default) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_default');
  Result := NCONF_default;
end;

{$ifndef  OPENSSL_NO_DEPRECATED_3_0}
function Load_NCONF_WIN32: PCONF_METHOD; cdecl;
begin
  NCONF_WIN32 := LoadLibCryptoFunction('NCONF_WIN32');
  if not assigned(NCONF_WIN32) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_WIN32');
  Result := NCONF_WIN32;
end;

{$endif} { OPENSSL_NO_DEPRECATED_3_0}
procedure Load_NCONF_free(conf: PCONF); cdecl;
begin
  NCONF_free := LoadLibCryptoFunction('NCONF_free');
  if not assigned(NCONF_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_free');
  NCONF_free(conf);
end;

procedure Load_NCONF_free_data(conf: PCONF); cdecl;
begin
  NCONF_free_data := LoadLibCryptoFunction('NCONF_free_data');
  if not assigned(NCONF_free_data) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_free_data');
  NCONF_free_data(conf);
end;

function Load_NCONF_load(conf: PCONF; file_: PAnsiChar; eline: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  NCONF_load := LoadLibCryptoFunction('NCONF_load');
  if not assigned(NCONF_load) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_load');
  Result := NCONF_load(conf, file_, eline);
end;

{$ifndef  OPENSSL_NO_STDIO}
function Load_NCONF_load_fp(conf: PCONF; fp: PFILE; eline: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  NCONF_load_fp := LoadLibCryptoFunction('NCONF_load_fp');
  if not assigned(NCONF_load_fp) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_load_fp');
  Result := NCONF_load_fp(conf, fp, eline);
end;

{$endif} { OPENSSL_NO_STDIO}
function Load_NCONF_load_bio(conf: PCONF; bp: PBIO; eline: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  NCONF_load_bio := LoadLibCryptoFunction('NCONF_load_bio');
  if not assigned(NCONF_load_bio) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_load_bio');
  Result := NCONF_load_bio(conf, bp, eline);
end;

function Load_NCONF_get_section_names(conf: PCONF): Pstack_st_OPENSSL_CSTRING; cdecl;
begin
  NCONF_get_section_names := LoadLibCryptoFunction('NCONF_get_section_names');
  if not assigned(NCONF_get_section_names) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_get_section_names');
  Result := NCONF_get_section_names(conf);
end;

function Load_NCONF_get_section(conf: PCONF; section: PAnsiChar): Pstack_st_CONF_VALUE; cdecl;
begin
  NCONF_get_section := LoadLibCryptoFunction('NCONF_get_section');
  if not assigned(NCONF_get_section) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_get_section');
  Result := NCONF_get_section(conf, section);
end;

function Load_NCONF_get_string(conf: PCONF; group: PAnsiChar; name: PAnsiChar): PAnsiChar; cdecl;
begin
  NCONF_get_string := LoadLibCryptoFunction('NCONF_get_string');
  if not assigned(NCONF_get_string) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_get_string');
  Result := NCONF_get_string(conf, group, name);
end;

function Load_NCONF_get_number_e(conf: PCONF; group: PAnsiChar; name: PAnsiChar; result_: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  NCONF_get_number_e := LoadLibCryptoFunction('NCONF_get_number_e');
  if not assigned(NCONF_get_number_e) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_get_number_e');
  Result := NCONF_get_number_e(conf, group, name, result_);
end;

{$ifndef  OPENSSL_NO_STDIO}
function Load_NCONF_dump_fp(conf: PCONF; out_: PFILE): TOpenSSL_C_INT; cdecl;
begin
  NCONF_dump_fp := LoadLibCryptoFunction('NCONF_dump_fp');
  if not assigned(NCONF_dump_fp) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_dump_fp');
  Result := NCONF_dump_fp(conf, out_);
end;

{$endif} { OPENSSL_NO_STDIO}
function Load_NCONF_dump_bio(conf: PCONF; out_: PBIO): TOpenSSL_C_INT; cdecl;
begin
  NCONF_dump_bio := LoadLibCryptoFunction('NCONF_dump_bio');
  if not assigned(NCONF_dump_bio) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('NCONF_dump_bio');
  Result := NCONF_dump_bio(conf, out_);
end;

function Load_CONF_modules_load(cnf: PCONF; appname: PAnsiChar; flags: TOpenSSL_C_UINT): TOpenSSL_C_INT; cdecl;
begin
  CONF_modules_load := LoadLibCryptoFunction('CONF_modules_load');
  if not assigned(CONF_modules_load) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_modules_load');
  Result := CONF_modules_load(cnf, appname, flags);
end;

function Load_CONF_modules_load_file_ex(libctx: POSSL_LIB_CTX; filename: PAnsiChar; appname: PAnsiChar; flags: TOpenSSL_C_UINT): TOpenSSL_C_INT; cdecl;
begin
  CONF_modules_load_file_ex := LoadLibCryptoFunction('CONF_modules_load_file_ex');
  if not assigned(CONF_modules_load_file_ex) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_modules_load_file_ex');
  Result := CONF_modules_load_file_ex(libctx, filename, appname, flags);
end;

function Load_CONF_modules_load_file(filename: PAnsiChar; appname: PAnsiChar; flags: TOpenSSL_C_UINT): TOpenSSL_C_INT; cdecl;
begin
  CONF_modules_load_file := LoadLibCryptoFunction('CONF_modules_load_file');
  if not assigned(CONF_modules_load_file) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_modules_load_file');
  Result := CONF_modules_load_file(filename, appname, flags);
end;

procedure Load_CONF_modules_unload(all: TOpenSSL_C_INT); cdecl;
begin
  CONF_modules_unload := LoadLibCryptoFunction('CONF_modules_unload');
  if not assigned(CONF_modules_unload) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_modules_unload');
  CONF_modules_unload(all);
end;

procedure Load_CONF_modules_finish; cdecl;
begin
  CONF_modules_finish := LoadLibCryptoFunction('CONF_modules_finish');
  if not assigned(CONF_modules_finish) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_modules_finish');
  CONF_modules_finish;
end;

function Load_CONF_module_add(name: PAnsiChar; ifunc: Pconf_init_func; ffunc: Pconf_finish_func): TOpenSSL_C_INT; cdecl;
begin
  CONF_module_add := LoadLibCryptoFunction('CONF_module_add');
  if not assigned(CONF_module_add) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_module_add');
  Result := CONF_module_add(name, ifunc, ffunc);
end;

function Load_CONF_imodule_get_name(md: PCONF_IMODULE): PAnsiChar; cdecl;
begin
  CONF_imodule_get_name := LoadLibCryptoFunction('CONF_imodule_get_name');
  if not assigned(CONF_imodule_get_name) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_imodule_get_name');
  Result := CONF_imodule_get_name(md);
end;

function Load_CONF_imodule_get_value(md: PCONF_IMODULE): PAnsiChar; cdecl;
begin
  CONF_imodule_get_value := LoadLibCryptoFunction('CONF_imodule_get_value');
  if not assigned(CONF_imodule_get_value) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_imodule_get_value');
  Result := CONF_imodule_get_value(md);
end;

function Load_CONF_imodule_get_usr_data(md: PCONF_IMODULE): pointer; cdecl;
begin
  CONF_imodule_get_usr_data := LoadLibCryptoFunction('CONF_imodule_get_usr_data');
  if not assigned(CONF_imodule_get_usr_data) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_imodule_get_usr_data');
  Result := CONF_imodule_get_usr_data(md);
end;

procedure Load_CONF_imodule_set_usr_data(md: PCONF_IMODULE; usr_data: pointer); cdecl;
begin
  CONF_imodule_set_usr_data := LoadLibCryptoFunction('CONF_imodule_set_usr_data');
  if not assigned(CONF_imodule_set_usr_data) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_imodule_set_usr_data');
  CONF_imodule_set_usr_data(md, usr_data);
end;

function Load_CONF_imodule_get_module(md: PCONF_IMODULE): PCONF_MODULE; cdecl;
begin
  CONF_imodule_get_module := LoadLibCryptoFunction('CONF_imodule_get_module');
  if not assigned(CONF_imodule_get_module) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_imodule_get_module');
  Result := CONF_imodule_get_module(md);
end;

function Load_CONF_imodule_get_flags(md: PCONF_IMODULE): TOpenSSL_C_UINT; cdecl;
begin
  CONF_imodule_get_flags := LoadLibCryptoFunction('CONF_imodule_get_flags');
  if not assigned(CONF_imodule_get_flags) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_imodule_get_flags');
  Result := CONF_imodule_get_flags(md);
end;

procedure Load_CONF_imodule_set_flags(md: PCONF_IMODULE; flags: TOpenSSL_C_UINT); cdecl;
begin
  CONF_imodule_set_flags := LoadLibCryptoFunction('CONF_imodule_set_flags');
  if not assigned(CONF_imodule_set_flags) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_imodule_set_flags');
  CONF_imodule_set_flags(md, flags);
end;

function Load_CONF_module_get_usr_data(pmod: PCONF_MODULE): pointer; cdecl;
begin
  CONF_module_get_usr_data := LoadLibCryptoFunction('CONF_module_get_usr_data');
  if not assigned(CONF_module_get_usr_data) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_module_get_usr_data');
  Result := CONF_module_get_usr_data(pmod);
end;

procedure Load_CONF_module_set_usr_data(pmod: PCONF_MODULE; usr_data: pointer); cdecl;
begin
  CONF_module_set_usr_data := LoadLibCryptoFunction('CONF_module_set_usr_data');
  if not assigned(CONF_module_set_usr_data) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_module_set_usr_data');
  CONF_module_set_usr_data(pmod, usr_data);
end;

function Load_CONF_get1_default_config_file: PAnsiChar; cdecl;
begin
  CONF_get1_default_config_file := LoadLibCryptoFunction('CONF_get1_default_config_file');
  if not assigned(CONF_get1_default_config_file) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_get1_default_config_file');
  Result := CONF_get1_default_config_file;
end;

function Load_CONF_parse_list(list: PAnsiChar; sep: TOpenSSL_C_INT; nospc: TOpenSSL_C_INT; list_cb: TFuncType000; arg: pointer): TOpenSSL_C_INT; cdecl;
begin
  CONF_parse_list := LoadLibCryptoFunction('CONF_parse_list');
  if not assigned(CONF_parse_list) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('CONF_parse_list');
  Result := CONF_parse_list(list, sep, nospc, list_cb, arg);
end;

procedure Load_OPENSSL_load_builtin_modules; cdecl;
begin
  OPENSSL_load_builtin_modules := LoadLibCryptoFunction('OPENSSL_load_builtin_modules');
  if not assigned(OPENSSL_load_builtin_modules) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_load_builtin_modules');
  OPENSSL_load_builtin_modules;
end;

procedure Load;
begin
  {$define EMPTY_LOAD_FUNCTION}
end;

procedure Unload;
begin
  sk_CONF_VALUE_num := Load_sk_CONF_VALUE_num;
  sk_CONF_VALUE_value := Load_sk_CONF_VALUE_value;
  sk_CONF_VALUE_new := Load_sk_CONF_VALUE_new;
  sk_CONF_VALUE_new_null := Load_sk_CONF_VALUE_new_null;
  sk_CONF_VALUE_new_reserve := Load_sk_CONF_VALUE_new_reserve;
  sk_CONF_VALUE_reserve := Load_sk_CONF_VALUE_reserve;
  sk_CONF_VALUE_free := Load_sk_CONF_VALUE_free;
  sk_CONF_VALUE_zero := Load_sk_CONF_VALUE_zero;
  sk_CONF_VALUE_delete := Load_sk_CONF_VALUE_delete;
  sk_CONF_VALUE_delete_ptr := Load_sk_CONF_VALUE_delete_ptr;
  sk_CONF_VALUE_push := Load_sk_CONF_VALUE_push;
  sk_CONF_VALUE_unshift := Load_sk_CONF_VALUE_unshift;
  sk_CONF_VALUE_pop := Load_sk_CONF_VALUE_pop;
  sk_CONF_VALUE_shift := Load_sk_CONF_VALUE_shift;
  sk_CONF_VALUE_pop_free := Load_sk_CONF_VALUE_pop_free;
  sk_CONF_VALUE_insert := Load_sk_CONF_VALUE_insert;
  sk_CONF_VALUE_set := Load_sk_CONF_VALUE_set;
  sk_CONF_VALUE_find := Load_sk_CONF_VALUE_find;
  sk_CONF_VALUE_find_ex := Load_sk_CONF_VALUE_find_ex;
  sk_CONF_VALUE_find_all := Load_sk_CONF_VALUE_find_all;
  sk_CONF_VALUE_sort := Load_sk_CONF_VALUE_sort;
  sk_CONF_VALUE_is_sorted := Load_sk_CONF_VALUE_is_sorted;
  sk_CONF_VALUE_dup := Load_sk_CONF_VALUE_dup;
  sk_CONF_VALUE_deep_copy := Load_sk_CONF_VALUE_deep_copy;
  sk_CONF_VALUE_set_cmp_func := Load_sk_CONF_VALUE_set_cmp_func;
  CONF_set_default_method := Load_CONF_set_default_method;
  CONF_set_nconf := Load_CONF_set_nconf;
  CONF_load := Load_CONF_load;
{$ifndef  OPENSSL_NO_STDIO}
  CONF_load_fp := Load_CONF_load_fp;
{$endif} { OPENSSL_NO_STDIO}
  CONF_load_bio := Load_CONF_load_bio;
  CONF_get_section := Load_CONF_get_section;
  CONF_get_string := Load_CONF_get_string;
  CONF_get_number := Load_CONF_get_number;
  CONF_free := Load_CONF_free;
{$ifndef  OPENSSL_NO_STDIO}
  CONF_dump_fp := Load_CONF_dump_fp;
{$endif} { OPENSSL_NO_STDIO}
  CONF_dump_bio := Load_CONF_dump_bio;
{$ifndef  OPENSSL_NO_DEPRECATED_1_1_0}
  OPENSSL_config := Load_OPENSSL_config;
{$endif} { OPENSSL_NO_DEPRECATED_1_1_0}
  NCONF_new_ex := Load_NCONF_new_ex;
  NCONF_get0_libctx := Load_NCONF_get0_libctx;
  NCONF_new := Load_NCONF_new;
  NCONF_default := Load_NCONF_default;
{$ifndef  OPENSSL_NO_DEPRECATED_3_0}
  NCONF_WIN32 := Load_NCONF_WIN32;
{$endif} { OPENSSL_NO_DEPRECATED_3_0}
  NCONF_free := Load_NCONF_free;
  NCONF_free_data := Load_NCONF_free_data;
  NCONF_load := Load_NCONF_load;
{$ifndef  OPENSSL_NO_STDIO}
  NCONF_load_fp := Load_NCONF_load_fp;
{$endif} { OPENSSL_NO_STDIO}
  NCONF_load_bio := Load_NCONF_load_bio;
  NCONF_get_section_names := Load_NCONF_get_section_names;
  NCONF_get_section := Load_NCONF_get_section;
  NCONF_get_string := Load_NCONF_get_string;
  NCONF_get_number_e := Load_NCONF_get_number_e;
{$ifndef  OPENSSL_NO_STDIO}
  NCONF_dump_fp := Load_NCONF_dump_fp;
{$endif} { OPENSSL_NO_STDIO}
  NCONF_dump_bio := Load_NCONF_dump_bio;
  CONF_modules_load := Load_CONF_modules_load;
  CONF_modules_load_file_ex := Load_CONF_modules_load_file_ex;
  CONF_modules_load_file := Load_CONF_modules_load_file;
  CONF_modules_unload := Load_CONF_modules_unload;
  CONF_modules_finish := Load_CONF_modules_finish;
  CONF_module_add := Load_CONF_module_add;
  CONF_imodule_get_name := Load_CONF_imodule_get_name;
  CONF_imodule_get_value := Load_CONF_imodule_get_value;
  CONF_imodule_get_usr_data := Load_CONF_imodule_get_usr_data;
  CONF_imodule_set_usr_data := Load_CONF_imodule_set_usr_data;
  CONF_imodule_get_module := Load_CONF_imodule_get_module;
  CONF_imodule_get_flags := Load_CONF_imodule_get_flags;
  CONF_imodule_set_flags := Load_CONF_imodule_set_flags;
  CONF_module_get_usr_data := Load_CONF_module_get_usr_data;
  CONF_module_set_usr_data := Load_CONF_module_set_usr_data;
  CONF_get1_default_config_file := Load_CONF_get1_default_config_file;
  CONF_parse_list := Load_CONF_parse_list;
  OPENSSL_load_builtin_modules := Load_OPENSSL_load_builtin_modules;
end;

{$endif} {OPENSSL_STATIC_LINK_MODEL}

initialization

{$ifndef OPENSSL_STATIC_LINK_MODEL}
{$ifndef EMPTY_LOAD_FUNCTION}
Register_SSLloader(@Load);
{$endif}
Register_SSLUnloader(@Unload);
{$endif}
{$if declared(LegacySupport_Initialization)}
LegacySupport_Initialization;
{$ifend}

finalization

{$if declared(LegacySupport_Finalization)}
LegacySupport_Finalization;
{$ifend}

end.



