{
    This file is part of the MWA Software Pascal API for OpenSSL .

    The MWA Software Pascal API for OpenSSL is free software: you can redistribute it
    and/or modify it under the terms of the Apache License Version 2.0 (the "License"), and as
    a derived work of the OpenSSL Project (see below for the original licence text).

    You may not use this file except in compliance with the License.  You can obtain a copy
    in the file LICENSE.txt in the source distribution or at https://www.openssl.org/source/license.html.

    The MWA Software Pascal API for OpenSSL is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the License for more details.
}

{$include openssl_defines.inc}

unit openssl_httperr;

{
  Generated from OpenSSL 3.5.6 Header File httperr.h - Tue 19 May 14:27:49 BST 2026
}

{$IFNDEF FPC}
{$IFDEF OPENSSL_USE_STATIC_LIBRARY}
{$LINK openssl_httperr.obj}
{$ENDIF}
{$ENDIF}

interface

uses OpenSSLAPI,openssl_symhacks,openssl_cryptoerr_legacy;


{* Generated by util/mkerr.pl DO NOT EDIT
* Copyright 1995-2026 The OpenSSL Project Authors. All Rights Reserved.
*
* Licensed under the Apache License 2.0 (the "License").  You may not use
* this file except in compliance with the License.  You can obtain a copy
* in the file LICENSE in the source distribution or at
* https://www.openssl.org/source/license.html
}
{$ifndef  OPENSSL_HTTPERR_H}
  {$define OPENSSL_HTTPERR_H}
  {$include openssl_opensslconf.inc}

const
  
  {* HTTP reason codes.
  }
  HTTP_R_ASN1_LEN_EXCEEDS_MAX_RESP_LEN = 108;
  HTTP_R_CONNECT_FAILURE = 100;
  HTTP_R_CONTENT_TYPE_MISMATCH = 131;
  HTTP_R_ERROR_PARSING_ASN1_LENGTH = 109;
  HTTP_R_ERROR_PARSING_CONTENT_LENGTH = 119;
  HTTP_R_ERROR_PARSING_URL = 101;
  HTTP_R_ERROR_RECEIVING = 103;
  HTTP_R_ERROR_SENDING = 102;
  HTTP_R_FAILED_READING_DATA = 128;
  HTTP_R_HEADER_PARSE_ERROR = 126;
  HTTP_R_INCONSISTENT_CONTENT_LENGTH = 120;
  HTTP_R_INVALID_PORT_NUMBER = 123;
  HTTP_R_INVALID_URL_PATH = 125;
  HTTP_R_INVALID_URL_SCHEME = 124;
  HTTP_R_MAX_RESP_LEN_EXCEEDED = 117;
  HTTP_R_MISSING_ASN1_ENCODING = 110;
  HTTP_R_MISSING_CONTENT_TYPE = 121;
  HTTP_R_MISSING_REDIRECT_LOCATION = 111;
  HTTP_R_RECEIVED_ERROR = 105;
  HTTP_R_RECEIVED_WRONG_HTTP_VERSION = 106;
  HTTP_R_REDIRECTION_FROM_HTTPS_TO_HTTP = 112;
  HTTP_R_REDIRECTION_NOT_ENABLED = 116;
  HTTP_R_RESPONSE_LINE_TOO_LONG = 113;
  HTTP_R_RESPONSE_PARSE_ERROR = 104;
  HTTP_R_RESPONSE_TOO_MANY_HDRLINES = 130;
  HTTP_R_RETRY_TIMEOUT = 129;
  HTTP_R_SERVER_CANCELED_CONNECTION = 127;
  HTTP_R_SOCK_NOT_SUPPORTED = 122;
  HTTP_R_STATUS_CODE_UNSUPPORTED = 114;
  HTTP_R_TLS_NOT_ENABLED = 107;
  HTTP_R_TOO_MANY_REDIRECTIONS = 115;
  HTTP_R_UNEXPECTED_CONTENT_TYPE = 118;
{$endif}

implementation

uses Sysutils, variants
  {$ifdef OPENSSL_INTERNAL_NEED_THREADS}
   {$IFNDEF FPC}
     ,System.SyncObjs
     {$IFDEF POSIX}
       ,Posix.Pthread
     {$ELSE}
       ,Windows
     {$ENDIF}
   {$ELSE}
     ,SyncObjs
   {$ENDIF}
  {$endif}
  ,Classes, OpenSSLExceptionHandlers;

  {$if not declared(__FILE__)}
  const
    {$ifdef FPC}
    __FILE__ = {$include %FILE%};
    {$else}
    __FILE__ = '$(INPUTFILENAME)';
    {$endif}
  {$ifend}
  {$if not declared(__LINE__)}
  const
    __LINE__ = 0;
  {$ifend}
  {$if not declared(OPENSSL_FILE)}
  const
    OPENSSL_FILE = __FILE__;
  {$ifend}
  {$if not declared(OPENSSL_LINE)}
  const
    OPENSSL_LINE  = 0;
  {$ifend}

{$ifndef OPENSSL_STATIC_LINK_MODEL}
procedure Load;
begin
  {$define EMPTY_LOAD_FUNCTION}
end;

procedure Unload;
begin
end;

{$endif} {OPENSSL_STATIC_LINK_MODEL}

initialization

{$ifndef OPENSSL_STATIC_LINK_MODEL}
{$ifndef EMPTY_LOAD_FUNCTION}
Register_SSLloader(@Load);
{$endif}
Register_SSLUnloader(@Unload);
{$endif}
{$if declared(LegacySupport_Initialization)}
LegacySupport_Initialization;
{$ifend}

finalization

{$if declared(LegacySupport_Finalization)}
LegacySupport_Finalization;
{$ifend}

end.



