{
    This file is part of the MWA Software Pascal API for OpenSSL .

    The MWA Software Pascal API for OpenSSL is free software: you can redistribute it
    and/or modify it under the terms of the Apache License Version 2.0 (the "License"), and as
    a derived work of the OpenSSL Project (see below for the original licence text).

    You may not use this file except in compliance with the License.  You can obtain a copy
    in the file LICENSE.txt in the source distribution or at https://www.openssl.org/source/license.html.

    The MWA Software Pascal API for OpenSSL is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the License for more details.
}

{$include openssl_defines.inc}

unit openssl_safestack;

{
  Generated from OpenSSL 3.5.6 Header File safestack.h - Tue 19 May 14:28:16 BST 2026
}

{$IFNDEF FPC}
{$IFDEF OPENSSL_USE_STATIC_LIBRARY}
{$LINK openssl_safestack.obj}
{$ENDIF}
{$ENDIF}

interface

uses OpenSSLAPI,openssl_stack,openssl_e_os2;


{* WARNING: do not edit!
* Generated by Makefile from include/openssl/safestack.h.in
*
* Copyright 1999-2021 The OpenSSL Project Authors. All Rights Reserved.
*
* Licensed under the Apache License 2.0 (the "License").  You may not use
* this file except in compliance with the License.  You can obtain a copy
* in the file LICENSE in the source distribution or at
* https://www.openssl.org/source/license.html
}
{ clang-format off }
{ clang-format on }
{$ifndef  OPENSSL_SAFESTACK_H}
  {$define OPENSSL_SAFESTACK_H}
  {$include openssl_macros.inc}
  {$ifndef  OPENSSL_NO_DEPRECATED_3_0}
    {$define HEADER_SAFESTACK_H}
  {$endif}
{# define  STACK_OF(type) struct stack_st_ ##type}
(*# define  SKM_DEFINE_STACK_OF_INTERNAL(t1,t2,t3) STACK_OF(t1); typedef int ( *sk_ ##t1 ##_compfunc)(const t3 *const *a, const 
t3 *const *b); typedef void ( *sk_ ##t1 ##_freefunc)(t3 * a); typedef t3 *( *sk_ ##t1 ##_copyfunc)(const t3 *a); static ossl_unused 
ossl_inline t2 *ossl_check_ ##t1 ##_type(t2 *ptr) { return ptr; } static ossl_unused ossl_inline const OPENSSL_STACK *ossl_check_const_ 
##t1 ##_sk_type(const STACK_OF(t1) *sk) { return (const OPENSSL_STACK * )sk; } static ossl_unused ossl_inline OPENSSL_STACK *ossl_check_ 
##t1 ##_sk_type(STACK_OF(t1) *sk) { return (OPENSSL_STACK * )sk; } static ossl_unused ossl_inline OPENSSL_sk_compfunc ossl_check_ 
##t1 ##_compfunc_type(sk_ ##t1 ##_compfunc cmp) { return (OPENSSL_sk_compfunc)cmp; } static ossl_unused ossl_inline OPENSSL_sk_copyfunc 
ossl_check_ ##t1 ##_copyfunc_type(sk_ ##t1 ##_copyfunc cpy) { return (OPENSSL_sk_copyfunc)cpy; } static ossl_unused ossl_inline 
OPENSSL_sk_freefunc ossl_check_ ##t1 ##_freefunc_type(sk_ ##t1 ##_freefunc fr) { return (OPENSSL_sk_freefunc)fr; }*)
(*# define  SKM_DEFINE_STACK_OF(t1,t2,t3) STACK_OF(t1); typedef int ( *sk_ ##t1 ##_compfunc)(const t3 *const *a, const t3 *const 
*b); typedef void ( *sk_ ##t1 ##_freefunc)(t3 * a); typedef t3 *( *sk_ ##t1 ##_copyfunc)(const t3 *a); static ossl_unused ossl_inline 
int sk_ ##t1 ##_num(const STACK_OF(t1) *sk) { return OPENSSL_sk_num((const OPENSSL_STACK * )sk); } static ossl_unused ossl_inline 
t2 *sk_ ##t1 ##_value(const STACK_OF(t1) *sk, int idx) { return (t2 * )OPENSSL_sk_value((const OPENSSL_STACK * )sk, idx); } static 
ossl_unused ossl_inline STACK_OF(t1) *sk_ ##t1 ##_new(sk_ ##t1 ##_compfunc compare) { return (STACK_OF(t1) * )OPENSSL_sk_new((OPENSSL_sk_compfunc)compare); 
} static ossl_unused ossl_inline STACK_OF(t1) *sk_ ##t1 ##_new_null(void) { return (STACK_OF(t1) * )OPENSSL_sk_new_null(); } static 
ossl_unused ossl_inline STACK_OF(t1) *sk_ ##t1 ##_new_reserve(sk_ ##t1 ##_compfunc compare, int n) { return (STACK_OF(t1) * )OPENSSL_sk_new_reserve((OPENSSL_sk_compfunc)compare,
 n); } static ossl_unused ossl_inline int sk_ ##t1 ##_reserve(STACK_OF(t1) *sk, int n) { return OPENSSL_sk_reserve((OPENSSL_STACK 
* )sk, n); } static ossl_unused ossl_inline void sk_ ##t1 ##_free(STACK_OF(t1) *sk) { OPENSSL_sk_free((OPENSSL_STACK * )sk); } static 
ossl_unused ossl_inline void sk_ ##t1 ##_zero(STACK_OF(t1) *sk) { OPENSSL_sk_zero((OPENSSL_STACK * )sk); } static ossl_unused ossl_inline 
t2 *sk_ ##t1 ##_delete(STACK_OF(t1) *sk, int i) { return (t2 * )OPENSSL_sk_delete((OPENSSL_STACK * )sk, i); } static ossl_unused 
ossl_inline t2 *sk_ ##t1 ##_delete_ptr(STACK_OF(t1) *sk, t2 *ptr) { return (t2 * )OPENSSL_sk_delete_ptr((OPENSSL_STACK * )sk, (const 
void * )ptr); } static ossl_unused ossl_inline int sk_ ##t1 ##_push(STACK_OF(t1) *sk, t2 *ptr) { return OPENSSL_sk_push((OPENSSL_STACK 
* )sk, (const void * )ptr); } static ossl_unused ossl_inline int sk_ ##t1 ##_unshift(STACK_OF(t1) *sk, t2 *ptr) { return OPENSSL_sk_unshift((OPENSSL_STACK 
* )sk, (const void * )ptr); } static ossl_unused ossl_inline t2 *sk_ ##t1 ##_pop(STACK_OF(t1) *sk) { return (t2 * )OPENSSL_sk_pop((OPENSSL_STACK 
* )sk); } static ossl_unused ossl_inline t2 *sk_ ##t1 ##_shift(STACK_OF(t1) *sk) { return (t2 * )OPENSSL_sk_shift((OPENSSL_STACK 
* )sk); } static ossl_unused ossl_inline void sk_ ##t1 ##_pop_free(STACK_OF(t1) *sk, sk_ ##t1 ##_freefunc freefunc) { OPENSSL_sk_pop_free((OPENSSL_STACK 
* )sk, (OPENSSL_sk_freefunc)freefunc); } static ossl_unused ossl_inline int sk_ ##t1 ##_insert(STACK_OF(t1) *sk, t2 *ptr, int idx) 
{ return OPENSSL_sk_insert((OPENSSL_STACK * )sk, (const void * )ptr, idx); } static ossl_unused ossl_inline t2 *sk_ ##t1 ##_set(STACK_OF(t1) 
*sk, int idx, t2 *ptr) { return (t2 * )OPENSSL_sk_set((OPENSSL_STACK * )sk, idx, (const void * )ptr); } static ossl_unused ossl_inline 
int sk_ ##t1 ##_find(STACK_OF(t1) *sk, t2 *ptr) { return OPENSSL_sk_find((OPENSSL_STACK * )sk, (const void * )ptr); } static ossl_unused 
ossl_inline int sk_ ##t1 ##_find_ex(STACK_OF(t1) *sk, t2 *ptr) { return OPENSSL_sk_find_ex((OPENSSL_STACK * )sk, (const void * )ptr); 
} static ossl_unused ossl_inline int sk_ ##t1 ##_find_all(STACK_OF(t1) *sk, t2 *ptr, int *pnum) { return OPENSSL_sk_find_all((OPENSSL_STACK 
* )sk, (const void * )ptr, pnum); } static ossl_unused ossl_inline void sk_ ##t1 ##_sort(STACK_OF(t1) *sk) { OPENSSL_sk_sort((OPENSSL_STACK 
* )sk); } static ossl_unused ossl_inline int sk_ ##t1 ##_is_sorted(const STACK_OF(t1) *sk) { return OPENSSL_sk_is_sorted((const 
OPENSSL_STACK * )sk); } static ossl_unused ossl_inline STACK_OF(t1) *sk_ ##t1 ##_dup(const STACK_OF(t1) *sk) { return (STACK_OF(t1) 
* )OPENSSL_sk_dup((const OPENSSL_STACK * )sk); } static ossl_unused ossl_inline STACK_OF(t1) *sk_ ##t1 ##_deep_copy(const STACK_OF(t1) 
*sk, sk_ ##t1 ##_copyfunc copyfunc, sk_ ##t1 ##_freefunc freefunc) { return (STACK_OF(t1) * )OPENSSL_sk_deep_copy((const OPENSSL_STACK 
* )sk, (OPENSSL_sk_copyfunc)copyfunc, (OPENSSL_sk_freefunc)freefunc); } static ossl_unused ossl_inline sk_ ##t1 ##_compfunc sk_ 
##t1 ##_set_cmp_func(STACK_OF(t1) *sk, sk_ ##t1 ##_compfunc compare) { return (sk_ ##t1 ##_compfunc)OPENSSL_sk_set_cmp_func((OPENSSL_STACK 
* )sk, (OPENSSL_sk_compfunc)compare); }*)
{# define  DEFINE_STACK_OF(t) SKM_DEFINE_STACK_OF(t, t, t)} { Blacklisted Macro}
{# define  DEFINE_STACK_OF_CONST(t) SKM_DEFINE_STACK_OF(t, const t, t)}
{# define  DEFINE_SPECIAL_STACK_OF(t1,t2) SKM_DEFINE_STACK_OF(t1, t2, t2)} { Blacklisted Macro}
{# define  DEFINE_SPECIAL_STACK_OF_CONST(t1,t2) SKM_DEFINE_STACK_OF(t1, const t2, t2)}

type
  {Auto-generated forward references}
  POPENSSL_STRING = ^TOPENSSL_STRING;
  PPOPENSSL_STRING = ^POPENSSL_STRING;
  POPENSSL_CSTRING = ^TOPENSSL_CSTRING;
  PPOPENSSL_CSTRING = ^POPENSSL_CSTRING;
  Pstack_st_char = ^Tstack_st_char;
  PPstack_st_char = ^Pstack_st_char;
  Pstack_st_void = ^Tstack_st_void;
  PPstack_st_void = ^Pstack_st_void;
  Pstack_st_OPENSSL_STRING = ^Tstack_st_OPENSSL_STRING;
  PPstack_st_OPENSSL_STRING = ^Pstack_st_OPENSSL_STRING;
  Psk_OPENSSL_STRING_compfunc = ^Tsk_OPENSSL_STRING_compfunc;
  PPsk_OPENSSL_STRING_compfunc = ^Psk_OPENSSL_STRING_compfunc;
  Psk_OPENSSL_STRING_freefunc = ^Tsk_OPENSSL_STRING_freefunc;
  PPsk_OPENSSL_STRING_freefunc = ^Psk_OPENSSL_STRING_freefunc;
  Psk_OPENSSL_STRING_copyfunc = ^Tsk_OPENSSL_STRING_copyfunc;
  PPsk_OPENSSL_STRING_copyfunc = ^Psk_OPENSSL_STRING_copyfunc;
  {end of auto-generated forward references}

  { Helper macro for internal use }
  {-
  * Strings are special: normally an lhash entry will point to a single
  * (somewhat) mutable object. In the case of strings:
  *
  * a) Instead of a single char, there is an array of chars, NUL-terminated.
  * b) The string may have be immutable.
  *
  * So, they need their own declarations. Especially important for
  * type-checking tools, such as Deputy.
  *
  * In practice, however, it appears to be hard to have a const
  * string. For now, I'm settling for dealing with the fact it is a
  * string at all.
  }
  TOPENSSL_STRING = PAnsiChar;
  TOPENSSL_CSTRING = PAnsiChar;
  {-
  * Confusingly, LHASH_OF(STRING) deals with char ** throughout, but
  * STACK_OF(STRING) is really more like STACK_OF(char), only, as mentioned
  * above, instead of a single char each entry is a NUL-terminated array of
  * chars. So, we have to implement STRING specially for STACK_OF. This is
  * dealt with in the autogenerated macros below.
  }
  Tstack_st_char = record 
  end;
  Tstack_st_void = record 
  end;
  { clang-format off }
  Tstack_st_OPENSSL_STRING = record 
  end;
  Tsk_OPENSSL_STRING_compfunc = function(a: PPAnsiChar; b: PPAnsiChar): TOpenSSL_C_INT; cdecl;
  Tsk_OPENSSL_STRING_freefunc = procedure(a: PAnsiChar); cdecl;
  Tsk_OPENSSL_STRING_copyfunc = function(a: PAnsiChar): PAnsiChar; cdecl;


  function ossl_check_OPENSSL_STRING_type(ptr: PAnsiChar): PAnsiChar{Has C Attribute: unused}; inline;
  function ossl_check_const_OPENSSL_STRING_sk_type(sk: Pstack_st_OPENSSL_STRING): POPENSSL_STACK{Has C Attribute: unused}; inline;
  function ossl_check_OPENSSL_STRING_sk_type(sk: Pstack_st_OPENSSL_STRING): POPENSSL_STACK{Has C Attribute: unused}; inline;
  function ossl_check_OPENSSL_STRING_compfunc_type(cmp: Tsk_OPENSSL_STRING_compfunc): TOPENSSL_sk_compfunc{Has C Attribute: unused}; inline;
  function ossl_check_OPENSSL_STRING_copyfunc_type(cpy: Tsk_OPENSSL_STRING_copyfunc): TOPENSSL_sk_copyfunc{Has C Attribute: unused}; inline;
  function ossl_check_OPENSSL_STRING_freefunc_type(fr: Tsk_OPENSSL_STRING_freefunc): TOPENSSL_sk_freefunc{Has C Attribute: unused}; inline;
  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function sk_OPENSSL_STRING_num(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_num';
  function sk_OPENSSL_STRING_value(_para: Pstack_st_OPENSSL_STRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl; external CLibCrypto name 'OPENSSL_sk_value';
  function sk_OPENSSL_STRING_new(cmp: Tsk_OPENSSL_STRING_compfunc): Pstack_st_OPENSSL_STRING; cdecl; external CLibCrypto name 'OPENSSL_sk_new';
  function sk_OPENSSL_STRING_new_null: Pstack_st_OPENSSL_STRING; cdecl; external CLibCrypto name 'OPENSSL_sk_new_null';
  function sk_OPENSSL_STRING_new_reserve(cmp: Tsk_OPENSSL_STRING_compfunc; n: TOpenSSL_C_INT): Pstack_st_OPENSSL_STRING; cdecl; external CLibCrypto name 'OPENSSL_sk_new_reserve';
  function sk_OPENSSL_STRING_reserve(_para: Pstack_st_OPENSSL_STRING; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_reserve';
  function sk_OPENSSL_STRING_free(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_free';
  function sk_OPENSSL_STRING_zero(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_zero';
  function sk_OPENSSL_STRING_delete(st: Pstack_st_OPENSSL_STRING; loc: TOpenSSL_C_INT): Pstack_st_char; cdecl; external CLibCrypto name 'OPENSSL_sk_delete';
  function sk_OPENSSL_STRING_delete_ptr(st: Pstack_st_OPENSSL_STRING; ptr: Pstack_st_OPENSSL_STRING): Pstack_st_char; cdecl; external CLibCrypto name 'OPENSSL_sk_delete_ptr';
  function sk_OPENSSL_STRING_push(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_push';
  function sk_OPENSSL_STRING_unshift(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_unshift';
  function sk_OPENSSL_STRING_pop(_para: Pstack_st_OPENSSL_STRING): Pstack_st_char; cdecl; external CLibCrypto name 'OPENSSL_sk_pop';
  function sk_OPENSSL_STRING_shift(_para: Pstack_st_OPENSSL_STRING): Pstack_st_char; cdecl; external CLibCrypto name 'OPENSSL_sk_shift';
  procedure sk_OPENSSL_STRING_pop_free(st: Pstack_st_OPENSSL_STRING; func: Tsk_OPENSSL_STRING_freefunc); cdecl; external CLibCrypto name 'OPENSSL_sk_pop_free';
  function sk_OPENSSL_STRING_insert(st: Pstack_st_OPENSSL_STRING; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_insert';
  function sk_OPENSSL_STRING_set(st: Pstack_st_OPENSSL_STRING; i: TOpenSSL_C_INT; data: pointer): Pstack_st_char; cdecl; external CLibCrypto name 'OPENSSL_sk_set';
  function sk_OPENSSL_STRING_find(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find';
  function sk_OPENSSL_STRING_find_ex(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find_ex';
  function sk_OPENSSL_STRING_find_all(st: Pstack_st_OPENSSL_STRING; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find_all';
  function sk_OPENSSL_STRING_sort(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_sort';
  function sk_OPENSSL_STRING_is_sorted(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_is_sorted';
  function sk_OPENSSL_STRING_dup(st: Pstack_st_OPENSSL_STRING): Pstack_st_OPENSSL_STRING; cdecl; external CLibCrypto name 'OPENSSL_sk_dup';
  function sk_OPENSSL_STRING_deep_copy(st: Pstack_st_OPENSSL_STRING; c: Tsk_OPENSSL_STRING_compfunc; f: Tsk_OPENSSL_STRING_freefunc): Pstack_st_OPENSSL_STRING; cdecl; external CLibCrypto name 'OPENSSL_sk_deep_copy';
  function sk_OPENSSL_STRING_set_cmp_func(st: Pstack_st_OPENSSL_STRING; cmp: Tsk_OPENSSL_STRING_compfunc): Tsk_OPENSSL_STRING_compfunc; cdecl; external CLibCrypto name 'OPENSSL_sk_set_cmp_func';
  {$else}
  { The EXTERNALSYM directive is ignored by FPC, however, it is used by Delphi as follows:

  The EXTERNALSYM directive prevents the specified Delphi symbol from appearing in header
  files generated for C++. }
  {$EXTERNALSYM sk_OPENSSL_STRING_num}
  {$EXTERNALSYM sk_OPENSSL_STRING_value}
  {$EXTERNALSYM sk_OPENSSL_STRING_new}
  {$EXTERNALSYM sk_OPENSSL_STRING_new_null}
  {$EXTERNALSYM sk_OPENSSL_STRING_new_reserve}
  {$EXTERNALSYM sk_OPENSSL_STRING_reserve}
  {$EXTERNALSYM sk_OPENSSL_STRING_free}
  {$EXTERNALSYM sk_OPENSSL_STRING_zero}
  {$EXTERNALSYM sk_OPENSSL_STRING_delete}
  {$EXTERNALSYM sk_OPENSSL_STRING_delete_ptr}
  {$EXTERNALSYM sk_OPENSSL_STRING_push}
  {$EXTERNALSYM sk_OPENSSL_STRING_unshift}
  {$EXTERNALSYM sk_OPENSSL_STRING_pop}
  {$EXTERNALSYM sk_OPENSSL_STRING_shift}
  {$EXTERNALSYM sk_OPENSSL_STRING_pop_free}
  {$EXTERNALSYM sk_OPENSSL_STRING_insert}
  {$EXTERNALSYM sk_OPENSSL_STRING_set}
  {$EXTERNALSYM sk_OPENSSL_STRING_find}
  {$EXTERNALSYM sk_OPENSSL_STRING_find_ex}
  {$EXTERNALSYM sk_OPENSSL_STRING_find_all}
  {$EXTERNALSYM sk_OPENSSL_STRING_sort}
  {$EXTERNALSYM sk_OPENSSL_STRING_is_sorted}
  {$EXTERNALSYM sk_OPENSSL_STRING_dup}
  {$EXTERNALSYM sk_OPENSSL_STRING_deep_copy}
  {$EXTERNALSYM sk_OPENSSL_STRING_set_cmp_func}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_sk_OPENSSL_STRING_num(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_STRING_value(_para: Pstack_st_OPENSSL_STRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl;
  function Load_sk_OPENSSL_STRING_new(cmp: Tsk_OPENSSL_STRING_compfunc): Pstack_st_OPENSSL_STRING; cdecl;
  function Load_sk_OPENSSL_STRING_new_null: Pstack_st_OPENSSL_STRING; cdecl;
  function Load_sk_OPENSSL_STRING_new_reserve(cmp: Tsk_OPENSSL_STRING_compfunc; n: TOpenSSL_C_INT): Pstack_st_OPENSSL_STRING; cdecl;
  function Load_sk_OPENSSL_STRING_reserve(_para: Pstack_st_OPENSSL_STRING; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_STRING_free(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_STRING_zero(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_STRING_delete(st: Pstack_st_OPENSSL_STRING; loc: TOpenSSL_C_INT): Pstack_st_char; cdecl;
  function Load_sk_OPENSSL_STRING_delete_ptr(st: Pstack_st_OPENSSL_STRING; ptr: Pstack_st_OPENSSL_STRING): Pstack_st_char; cdecl;
  function Load_sk_OPENSSL_STRING_push(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_STRING_unshift(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_STRING_pop(_para: Pstack_st_OPENSSL_STRING): Pstack_st_char; cdecl;
  function Load_sk_OPENSSL_STRING_shift(_para: Pstack_st_OPENSSL_STRING): Pstack_st_char; cdecl;
  procedure Load_sk_OPENSSL_STRING_pop_free(st: Pstack_st_OPENSSL_STRING; func: Tsk_OPENSSL_STRING_freefunc); cdecl;
  function Load_sk_OPENSSL_STRING_insert(st: Pstack_st_OPENSSL_STRING; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_STRING_set(st: Pstack_st_OPENSSL_STRING; i: TOpenSSL_C_INT; data: pointer): Pstack_st_char; cdecl;
  function Load_sk_OPENSSL_STRING_find(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_STRING_find_ex(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_STRING_find_all(st: Pstack_st_OPENSSL_STRING; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_STRING_sort(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_STRING_is_sorted(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_STRING_dup(st: Pstack_st_OPENSSL_STRING): Pstack_st_OPENSSL_STRING; cdecl;
  function Load_sk_OPENSSL_STRING_deep_copy(st: Pstack_st_OPENSSL_STRING; c: Tsk_OPENSSL_STRING_compfunc; f: Tsk_OPENSSL_STRING_freefunc): Pstack_st_OPENSSL_STRING; cdecl;
  function Load_sk_OPENSSL_STRING_set_cmp_func(st: Pstack_st_OPENSSL_STRING; cmp: Tsk_OPENSSL_STRING_compfunc): Tsk_OPENSSL_STRING_compfunc; cdecl;

var
  sk_OPENSSL_STRING_num: function(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_STRING_num;
  sk_OPENSSL_STRING_value: function(_para: Pstack_st_OPENSSL_STRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl = Load_sk_OPENSSL_STRING_value;
  sk_OPENSSL_STRING_new: function(cmp: Tsk_OPENSSL_STRING_compfunc): Pstack_st_OPENSSL_STRING; cdecl = Load_sk_OPENSSL_STRING_new;
  sk_OPENSSL_STRING_new_null: function: Pstack_st_OPENSSL_STRING; cdecl = Load_sk_OPENSSL_STRING_new_null;
  sk_OPENSSL_STRING_new_reserve: function(cmp: Tsk_OPENSSL_STRING_compfunc; n: TOpenSSL_C_INT): Pstack_st_OPENSSL_STRING; cdecl = Load_sk_OPENSSL_STRING_new_reserve;
  sk_OPENSSL_STRING_reserve: function(_para: Pstack_st_OPENSSL_STRING; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_STRING_reserve;
  sk_OPENSSL_STRING_free: function(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_STRING_free;
  sk_OPENSSL_STRING_zero: function(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_STRING_zero;
  sk_OPENSSL_STRING_delete: function(st: Pstack_st_OPENSSL_STRING; loc: TOpenSSL_C_INT): Pstack_st_char; cdecl = Load_sk_OPENSSL_STRING_delete;
  sk_OPENSSL_STRING_delete_ptr: function(st: Pstack_st_OPENSSL_STRING; ptr: Pstack_st_OPENSSL_STRING): Pstack_st_char; cdecl = Load_sk_OPENSSL_STRING_delete_ptr;
  sk_OPENSSL_STRING_push: function(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_STRING_push;
  sk_OPENSSL_STRING_unshift: function(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_STRING_unshift;
  sk_OPENSSL_STRING_pop: function(_para: Pstack_st_OPENSSL_STRING): Pstack_st_char; cdecl = Load_sk_OPENSSL_STRING_pop;
  sk_OPENSSL_STRING_shift: function(_para: Pstack_st_OPENSSL_STRING): Pstack_st_char; cdecl = Load_sk_OPENSSL_STRING_shift;
  sk_OPENSSL_STRING_pop_free: procedure(st: Pstack_st_OPENSSL_STRING; func: Tsk_OPENSSL_STRING_freefunc); cdecl = Load_sk_OPENSSL_STRING_pop_free;
  sk_OPENSSL_STRING_insert: function(st: Pstack_st_OPENSSL_STRING; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_STRING_insert;
  sk_OPENSSL_STRING_set: function(st: Pstack_st_OPENSSL_STRING; i: TOpenSSL_C_INT; data: pointer): Pstack_st_char; cdecl = Load_sk_OPENSSL_STRING_set;
  sk_OPENSSL_STRING_find: function(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_STRING_find;
  sk_OPENSSL_STRING_find_ex: function(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_STRING_find_ex;
  sk_OPENSSL_STRING_find_all: function(st: Pstack_st_OPENSSL_STRING; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_STRING_find_all;
  sk_OPENSSL_STRING_sort: function(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_STRING_sort;
  sk_OPENSSL_STRING_is_sorted: function(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_STRING_is_sorted;
  sk_OPENSSL_STRING_dup: function(st: Pstack_st_OPENSSL_STRING): Pstack_st_OPENSSL_STRING; cdecl = Load_sk_OPENSSL_STRING_dup;
  sk_OPENSSL_STRING_deep_copy: function(st: Pstack_st_OPENSSL_STRING; c: Tsk_OPENSSL_STRING_compfunc; f: Tsk_OPENSSL_STRING_freefunc): Pstack_st_OPENSSL_STRING; cdecl = Load_sk_OPENSSL_STRING_deep_copy;
  sk_OPENSSL_STRING_set_cmp_func: function(st: Pstack_st_OPENSSL_STRING; cmp: Tsk_OPENSSL_STRING_compfunc): Tsk_OPENSSL_STRING_compfunc; cdecl = Load_sk_OPENSSL_STRING_set_cmp_func;
  {$endif} {OPENSSL_STATIC_LINK_MODEL}

type
  {Auto-generated forward references}
  Pstack_st_OPENSSL_CSTRING = ^Tstack_st_OPENSSL_CSTRING;
  PPstack_st_OPENSSL_CSTRING = ^Pstack_st_OPENSSL_CSTRING;
  Psk_OPENSSL_CSTRING_compfunc = ^Tsk_OPENSSL_CSTRING_compfunc;
  PPsk_OPENSSL_CSTRING_compfunc = ^Psk_OPENSSL_CSTRING_compfunc;
  Psk_OPENSSL_CSTRING_freefunc = ^Tsk_OPENSSL_CSTRING_freefunc;
  PPsk_OPENSSL_CSTRING_freefunc = ^Psk_OPENSSL_CSTRING_freefunc;
  Psk_OPENSSL_CSTRING_copyfunc = ^Tsk_OPENSSL_CSTRING_copyfunc;
  PPsk_OPENSSL_CSTRING_copyfunc = ^Psk_OPENSSL_CSTRING_copyfunc;
  {end of auto-generated forward references}

  Tstack_st_OPENSSL_CSTRING = record 
  end;
  Tsk_OPENSSL_CSTRING_compfunc = function(a: PPAnsiChar; b: PPAnsiChar): TOpenSSL_C_INT; cdecl;
  Tsk_OPENSSL_CSTRING_freefunc = procedure(a: PAnsiChar); cdecl;
  Tsk_OPENSSL_CSTRING_copyfunc = function(a: PAnsiChar): PAnsiChar; cdecl;


  function ossl_check_OPENSSL_CSTRING_type(ptr: PAnsiChar): PAnsiChar{Has C Attribute: unused}; inline;
  function ossl_check_const_OPENSSL_CSTRING_sk_type(sk: Pstack_st_OPENSSL_CSTRING): POPENSSL_STACK{Has C Attribute: unused}; inline;
  function ossl_check_OPENSSL_CSTRING_sk_type(sk: Pstack_st_OPENSSL_CSTRING): POPENSSL_STACK{Has C Attribute: unused}; inline;
  function ossl_check_OPENSSL_CSTRING_compfunc_type(cmp: Tsk_OPENSSL_CSTRING_compfunc): TOPENSSL_sk_compfunc{Has C Attribute: unused}; inline;
  function ossl_check_OPENSSL_CSTRING_copyfunc_type(cpy: Tsk_OPENSSL_CSTRING_copyfunc): TOPENSSL_sk_copyfunc{Has C Attribute: unused}; inline;
  function ossl_check_OPENSSL_CSTRING_freefunc_type(fr: Tsk_OPENSSL_CSTRING_freefunc): TOPENSSL_sk_freefunc{Has C Attribute: unused}; inline;
  {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function sk_OPENSSL_CSTRING_num(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_num';
  function sk_OPENSSL_CSTRING_value(_para: Pstack_st_OPENSSL_CSTRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl; external CLibCrypto name 'OPENSSL_sk_value';
  function sk_OPENSSL_CSTRING_new(cmp: Tsk_OPENSSL_CSTRING_compfunc): Pstack_st_OPENSSL_CSTRING; cdecl; external CLibCrypto name 'OPENSSL_sk_new';
  function sk_OPENSSL_CSTRING_new_null: Pstack_st_OPENSSL_CSTRING; cdecl; external CLibCrypto name 'OPENSSL_sk_new_null';
  function sk_OPENSSL_CSTRING_new_reserve(cmp: Tsk_OPENSSL_CSTRING_compfunc; n: TOpenSSL_C_INT): Pstack_st_OPENSSL_CSTRING; cdecl; external CLibCrypto name 'OPENSSL_sk_new_reserve';
  function sk_OPENSSL_CSTRING_reserve(_para: Pstack_st_OPENSSL_CSTRING; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_reserve';
  function sk_OPENSSL_CSTRING_free(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_free';
  function sk_OPENSSL_CSTRING_zero(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_zero';
  function sk_OPENSSL_CSTRING_delete(_para: Pstack_st_OPENSSL_CSTRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl; external CLibCrypto name 'OPENSSL_sk_delete';
  function sk_OPENSSL_CSTRING_delete_ptr(_para: Pstack_st_OPENSSL_CSTRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl; external CLibCrypto name 'OPENSSL_sk_delete_ptr';
  function sk_OPENSSL_CSTRING_push(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_push';
  function sk_OPENSSL_CSTRING_unshift(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_unshift';
  function sk_OPENSSL_CSTRING_pop(_para: Pstack_st_OPENSSL_CSTRING): Pstack_st_char; cdecl; external CLibCrypto name 'OPENSSL_sk_pop';
  function sk_OPENSSL_CSTRING_shift(_para: Pstack_st_OPENSSL_CSTRING): Pstack_st_char; cdecl; external CLibCrypto name 'OPENSSL_sk_shift';
  procedure sk_OPENSSL_CSTRING_pop_free(st: Pstack_st_OPENSSL_CSTRING; func: Tsk_OPENSSL_CSTRING_freefunc); cdecl; external CLibCrypto name 'OPENSSL_sk_pop_free';
  function sk_OPENSSL_CSTRING_insert(st: Pstack_st_OPENSSL_CSTRING; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_insert';
  function sk_OPENSSL_CSTRING_set(st: Pstack_st_OPENSSL_CSTRING; i: TOpenSSL_C_INT; data: pointer): Pstack_st_char; cdecl; external CLibCrypto name 'OPENSSL_sk_set';
  function sk_OPENSSL_CSTRING_find(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find';
  function sk_OPENSSL_CSTRING_find_ex(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find_ex';
  function sk_OPENSSL_CSTRING_find_all(st: Pstack_st_OPENSSL_CSTRING; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find_all';
  function sk_OPENSSL_CSTRING_sort(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_sort';
  function sk_OPENSSL_CSTRING_is_sorted(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_is_sorted';
  function sk_OPENSSL_CSTRING_dup(st: Pstack_st_OPENSSL_CSTRING): Pstack_st_OPENSSL_CSTRING; cdecl; external CLibCrypto name 'OPENSSL_sk_dup';
  function sk_OPENSSL_CSTRING_deep_copy(st: Pstack_st_OPENSSL_CSTRING; c: Tsk_OPENSSL_CSTRING_compfunc; f: Tsk_OPENSSL_CSTRING_freefunc): Pstack_st_OPENSSL_CSTRING; cdecl; external CLibCrypto name 'OPENSSL_sk_deep_copy';
  function sk_OPENSSL_CSTRING_set_cmp_func(st: Pstack_st_OPENSSL_CSTRING; cmp: Tsk_OPENSSL_CSTRING_compfunc): Tsk_OPENSSL_CSTRING_compfunc; cdecl; external CLibCrypto name 'OPENSSL_sk_set_cmp_func';
  { clang-format on }
  {$else}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_num}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_value}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_new}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_new_null}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_new_reserve}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_reserve}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_free}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_zero}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_delete}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_delete_ptr}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_push}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_unshift}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_pop}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_shift}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_pop_free}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_insert}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_set}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_find}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_find_ex}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_find_all}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_sort}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_is_sorted}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_dup}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_deep_copy}
  {$EXTERNALSYM sk_OPENSSL_CSTRING_set_cmp_func}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_sk_OPENSSL_CSTRING_num(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_CSTRING_value(_para: Pstack_st_OPENSSL_CSTRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl;
  function Load_sk_OPENSSL_CSTRING_new(cmp: Tsk_OPENSSL_CSTRING_compfunc): Pstack_st_OPENSSL_CSTRING; cdecl;
  function Load_sk_OPENSSL_CSTRING_new_null: Pstack_st_OPENSSL_CSTRING; cdecl;
  function Load_sk_OPENSSL_CSTRING_new_reserve(cmp: Tsk_OPENSSL_CSTRING_compfunc; n: TOpenSSL_C_INT): Pstack_st_OPENSSL_CSTRING; cdecl;
  function Load_sk_OPENSSL_CSTRING_reserve(_para: Pstack_st_OPENSSL_CSTRING; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_CSTRING_free(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_CSTRING_zero(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_CSTRING_delete(_para: Pstack_st_OPENSSL_CSTRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl;
  function Load_sk_OPENSSL_CSTRING_delete_ptr(_para: Pstack_st_OPENSSL_CSTRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl;
  function Load_sk_OPENSSL_CSTRING_push(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_CSTRING_unshift(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_CSTRING_pop(_para: Pstack_st_OPENSSL_CSTRING): Pstack_st_char; cdecl;
  function Load_sk_OPENSSL_CSTRING_shift(_para: Pstack_st_OPENSSL_CSTRING): Pstack_st_char; cdecl;
  procedure Load_sk_OPENSSL_CSTRING_pop_free(st: Pstack_st_OPENSSL_CSTRING; func: Tsk_OPENSSL_CSTRING_freefunc); cdecl;
  function Load_sk_OPENSSL_CSTRING_insert(st: Pstack_st_OPENSSL_CSTRING; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_CSTRING_set(st: Pstack_st_OPENSSL_CSTRING; i: TOpenSSL_C_INT; data: pointer): Pstack_st_char; cdecl;
  function Load_sk_OPENSSL_CSTRING_find(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_CSTRING_find_ex(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_CSTRING_find_all(st: Pstack_st_OPENSSL_CSTRING; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_CSTRING_sort(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_CSTRING_is_sorted(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_CSTRING_dup(st: Pstack_st_OPENSSL_CSTRING): Pstack_st_OPENSSL_CSTRING; cdecl;
  function Load_sk_OPENSSL_CSTRING_deep_copy(st: Pstack_st_OPENSSL_CSTRING; c: Tsk_OPENSSL_CSTRING_compfunc; f: Tsk_OPENSSL_CSTRING_freefunc): Pstack_st_OPENSSL_CSTRING; cdecl;
  function Load_sk_OPENSSL_CSTRING_set_cmp_func(st: Pstack_st_OPENSSL_CSTRING; cmp: Tsk_OPENSSL_CSTRING_compfunc): Tsk_OPENSSL_CSTRING_compfunc; cdecl;

var
  sk_OPENSSL_CSTRING_num: function(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_CSTRING_num;
  sk_OPENSSL_CSTRING_value: function(_para: Pstack_st_OPENSSL_CSTRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl = Load_sk_OPENSSL_CSTRING_value;
  sk_OPENSSL_CSTRING_new: function(cmp: Tsk_OPENSSL_CSTRING_compfunc): Pstack_st_OPENSSL_CSTRING; cdecl = Load_sk_OPENSSL_CSTRING_new;
  sk_OPENSSL_CSTRING_new_null: function: Pstack_st_OPENSSL_CSTRING; cdecl = Load_sk_OPENSSL_CSTRING_new_null;
  sk_OPENSSL_CSTRING_new_reserve: function(cmp: Tsk_OPENSSL_CSTRING_compfunc; n: TOpenSSL_C_INT): Pstack_st_OPENSSL_CSTRING; cdecl = Load_sk_OPENSSL_CSTRING_new_reserve;
  sk_OPENSSL_CSTRING_reserve: function(_para: Pstack_st_OPENSSL_CSTRING; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_CSTRING_reserve;
  sk_OPENSSL_CSTRING_free: function(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_CSTRING_free;
  sk_OPENSSL_CSTRING_zero: function(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_CSTRING_zero;
  sk_OPENSSL_CSTRING_delete: function(_para: Pstack_st_OPENSSL_CSTRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl = Load_sk_OPENSSL_CSTRING_delete;
  sk_OPENSSL_CSTRING_delete_ptr: function(_para: Pstack_st_OPENSSL_CSTRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl = Load_sk_OPENSSL_CSTRING_delete_ptr;
  sk_OPENSSL_CSTRING_push: function(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_CSTRING_push;
  sk_OPENSSL_CSTRING_unshift: function(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_CSTRING_unshift;
  sk_OPENSSL_CSTRING_pop: function(_para: Pstack_st_OPENSSL_CSTRING): Pstack_st_char; cdecl = Load_sk_OPENSSL_CSTRING_pop;
  sk_OPENSSL_CSTRING_shift: function(_para: Pstack_st_OPENSSL_CSTRING): Pstack_st_char; cdecl = Load_sk_OPENSSL_CSTRING_shift;
  sk_OPENSSL_CSTRING_pop_free: procedure(st: Pstack_st_OPENSSL_CSTRING; func: Tsk_OPENSSL_CSTRING_freefunc); cdecl = Load_sk_OPENSSL_CSTRING_pop_free;
  sk_OPENSSL_CSTRING_insert: function(st: Pstack_st_OPENSSL_CSTRING; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_CSTRING_insert;
  sk_OPENSSL_CSTRING_set: function(st: Pstack_st_OPENSSL_CSTRING; i: TOpenSSL_C_INT; data: pointer): Pstack_st_char; cdecl = Load_sk_OPENSSL_CSTRING_set;
  sk_OPENSSL_CSTRING_find: function(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_CSTRING_find;
  sk_OPENSSL_CSTRING_find_ex: function(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_CSTRING_find_ex;
  sk_OPENSSL_CSTRING_find_all: function(st: Pstack_st_OPENSSL_CSTRING; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_CSTRING_find_all;
  sk_OPENSSL_CSTRING_sort: function(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_CSTRING_sort;
  sk_OPENSSL_CSTRING_is_sorted: function(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_CSTRING_is_sorted;
  sk_OPENSSL_CSTRING_dup: function(st: Pstack_st_OPENSSL_CSTRING): Pstack_st_OPENSSL_CSTRING; cdecl = Load_sk_OPENSSL_CSTRING_dup;
  sk_OPENSSL_CSTRING_deep_copy: function(st: Pstack_st_OPENSSL_CSTRING; c: Tsk_OPENSSL_CSTRING_compfunc; f: Tsk_OPENSSL_CSTRING_freefunc): Pstack_st_OPENSSL_CSTRING; cdecl = Load_sk_OPENSSL_CSTRING_deep_copy;
  sk_OPENSSL_CSTRING_set_cmp_func: function(st: Pstack_st_OPENSSL_CSTRING; cmp: Tsk_OPENSSL_CSTRING_compfunc): Tsk_OPENSSL_CSTRING_compfunc; cdecl = Load_sk_OPENSSL_CSTRING_set_cmp_func;
  { clang-format on }
  {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$if  not defined(OPENSSL_NO_DEPRECATED_3_0)}

type
  {Auto-generated forward references}
  POPENSSL_BLOCK = ^TOPENSSL_BLOCK;
  PPOPENSSL_BLOCK = ^POPENSSL_BLOCK;
  Pstack_st_OPENSSL_BLOCK = ^Tstack_st_OPENSSL_BLOCK;
  PPstack_st_OPENSSL_BLOCK = ^Pstack_st_OPENSSL_BLOCK;
  Psk_OPENSSL_BLOCK_compfunc = ^Tsk_OPENSSL_BLOCK_compfunc;
  PPsk_OPENSSL_BLOCK_compfunc = ^Psk_OPENSSL_BLOCK_compfunc;
  Psk_OPENSSL_BLOCK_freefunc = ^Tsk_OPENSSL_BLOCK_freefunc;
  PPsk_OPENSSL_BLOCK_freefunc = ^Psk_OPENSSL_BLOCK_freefunc;
  Psk_OPENSSL_BLOCK_copyfunc = ^Tsk_OPENSSL_BLOCK_copyfunc;
  PPsk_OPENSSL_BLOCK_copyfunc = ^Psk_OPENSSL_BLOCK_copyfunc;
  {end of auto-generated forward references}

    
    {* This is not used by OpenSSL.  A block of bytes,  NOT nul-terminated.
    * These should also be distinguished from "normal" stacks.
    }
  TOPENSSL_BLOCK = pointer;
    { clang-format off }
  Tstack_st_OPENSSL_BLOCK = record 
  end;
  Tsk_OPENSSL_BLOCK_compfunc = function(a: Ppointer; b: Ppointer): TOpenSSL_C_INT; cdecl;
  Tsk_OPENSSL_BLOCK_freefunc = procedure(a: pointer); cdecl;
  Tsk_OPENSSL_BLOCK_copyfunc = function(a: pointer): pointer; cdecl;


  function ossl_check_OPENSSL_BLOCK_type(ptr: pointer): pointer{Has C Attribute: unused}; inline;
  function ossl_check_const_OPENSSL_BLOCK_sk_type(sk: Pstack_st_OPENSSL_BLOCK): POPENSSL_STACK{Has C Attribute: unused}; inline;
  function ossl_check_OPENSSL_BLOCK_sk_type(sk: Pstack_st_OPENSSL_BLOCK): POPENSSL_STACK{Has C Attribute: unused}; inline;
  function ossl_check_OPENSSL_BLOCK_compfunc_type(cmp: Tsk_OPENSSL_BLOCK_compfunc): TOPENSSL_sk_compfunc{Has C Attribute: unused}; inline;
  function ossl_check_OPENSSL_BLOCK_copyfunc_type(cpy: Tsk_OPENSSL_BLOCK_copyfunc): TOPENSSL_sk_copyfunc{Has C Attribute: unused}; inline;
  function ossl_check_OPENSSL_BLOCK_freefunc_type(fr: Tsk_OPENSSL_BLOCK_freefunc): TOPENSSL_sk_freefunc{Has C Attribute: unused}; inline;
    {$ifdef OPENSSL_STATIC_LINK_MODEL}
  function sk_OPENSSL_BLOCK_num(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_num';
  function sk_OPENSSL_BLOCK_value(_para: Pstack_st_OPENSSL_BLOCK; _para2: TOpenSSL_C_INT): Pstack_st_void; cdecl; external CLibCrypto name 'OPENSSL_sk_value';
  function sk_OPENSSL_BLOCK_new(cmp: Tsk_OPENSSL_BLOCK_compfunc): Pstack_st_OPENSSL_BLOCK; cdecl; external CLibCrypto name 'OPENSSL_sk_new';
  function sk_OPENSSL_BLOCK_new_null: Pstack_st_OPENSSL_BLOCK; cdecl; external CLibCrypto name 'OPENSSL_sk_new_null';
  function sk_OPENSSL_BLOCK_new_reserve(cmp: Tsk_OPENSSL_BLOCK_compfunc; n: TOpenSSL_C_INT): Pstack_st_OPENSSL_BLOCK; cdecl; external CLibCrypto name 'OPENSSL_sk_new_reserve';
  function sk_OPENSSL_BLOCK_reserve(_para: Pstack_st_OPENSSL_BLOCK; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_reserve';
  function sk_OPENSSL_BLOCK_free(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_free';
  function sk_OPENSSL_BLOCK_zero(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_zero';
  function sk_OPENSSL_BLOCK_delete(st: Pstack_st_OPENSSL_BLOCK; loc: TOpenSSL_C_INT): Pstack_st_void; cdecl; external CLibCrypto name 'OPENSSL_sk_delete';
  function sk_OPENSSL_BLOCK_delete_ptr(st: Pstack_st_OPENSSL_BLOCK; ptr: Pstack_st_OPENSSL_BLOCK): Pstack_st_void; cdecl; external CLibCrypto name 'OPENSSL_sk_delete_ptr';
  function sk_OPENSSL_BLOCK_push(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_push';
  function sk_OPENSSL_BLOCK_unshift(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_unshift';
  function sk_OPENSSL_BLOCK_pop(_para: Pstack_st_OPENSSL_BLOCK): Pstack_st_void; cdecl; external CLibCrypto name 'OPENSSL_sk_pop';
  function sk_OPENSSL_BLOCK_shift(_para: Pstack_st_OPENSSL_BLOCK): Pstack_st_void; cdecl; external CLibCrypto name 'OPENSSL_sk_shift';
  procedure sk_OPENSSL_BLOCK_pop_free(st: Pstack_st_OPENSSL_BLOCK; func: Tsk_OPENSSL_BLOCK_freefunc); cdecl; external CLibCrypto name 'OPENSSL_sk_pop_free';
  function sk_OPENSSL_BLOCK_insert(st: Pstack_st_OPENSSL_BLOCK; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_insert';
  function sk_OPENSSL_BLOCK_set(st: Pstack_st_OPENSSL_BLOCK; i: TOpenSSL_C_INT; data: pointer): Pstack_st_void; cdecl; external CLibCrypto name 'OPENSSL_sk_set';
  function sk_OPENSSL_BLOCK_find(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find';
  function sk_OPENSSL_BLOCK_find_ex(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find_ex';
  function sk_OPENSSL_BLOCK_find_all(st: Pstack_st_OPENSSL_BLOCK; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_find_all';
  function sk_OPENSSL_BLOCK_sort(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_sort';
  function sk_OPENSSL_BLOCK_is_sorted(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl; external CLibCrypto name 'OPENSSL_sk_is_sorted';
  function sk_OPENSSL_BLOCK_dup(st: Pstack_st_OPENSSL_BLOCK): Pstack_st_OPENSSL_BLOCK; cdecl; external CLibCrypto name 'OPENSSL_sk_dup';
  function sk_OPENSSL_BLOCK_deep_copy(st: Pstack_st_OPENSSL_BLOCK; c: Tsk_OPENSSL_BLOCK_compfunc; f: Tsk_OPENSSL_BLOCK_freefunc): Pstack_st_OPENSSL_BLOCK; cdecl; external CLibCrypto name 'OPENSSL_sk_deep_copy';
  function sk_OPENSSL_BLOCK_set_cmp_func(st: Pstack_st_OPENSSL_BLOCK; cmp: Tsk_OPENSSL_BLOCK_compfunc): Tsk_OPENSSL_BLOCK_compfunc; cdecl; external CLibCrypto name 'OPENSSL_sk_set_cmp_func';
  { clang-format on }
    {$else}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_num}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_value}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_new}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_new_null}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_new_reserve}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_reserve}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_free}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_zero}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_delete}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_delete_ptr}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_push}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_unshift}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_pop}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_shift}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_pop_free}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_insert}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_set}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_find}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_find_ex}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_find_all}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_sort}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_is_sorted}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_dup}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_deep_copy}
  {$EXTERNALSYM sk_OPENSSL_BLOCK_set_cmp_func}
  {Do not call Function LoadDeclarations. Internal use only}
  function Load_sk_OPENSSL_BLOCK_num(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_BLOCK_value(_para: Pstack_st_OPENSSL_BLOCK; _para2: TOpenSSL_C_INT): Pstack_st_void; cdecl;
  function Load_sk_OPENSSL_BLOCK_new(cmp: Tsk_OPENSSL_BLOCK_compfunc): Pstack_st_OPENSSL_BLOCK; cdecl;
  function Load_sk_OPENSSL_BLOCK_new_null: Pstack_st_OPENSSL_BLOCK; cdecl;
  function Load_sk_OPENSSL_BLOCK_new_reserve(cmp: Tsk_OPENSSL_BLOCK_compfunc; n: TOpenSSL_C_INT): Pstack_st_OPENSSL_BLOCK; cdecl;
  function Load_sk_OPENSSL_BLOCK_reserve(_para: Pstack_st_OPENSSL_BLOCK; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_BLOCK_free(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_BLOCK_zero(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_BLOCK_delete(st: Pstack_st_OPENSSL_BLOCK; loc: TOpenSSL_C_INT): Pstack_st_void; cdecl;
  function Load_sk_OPENSSL_BLOCK_delete_ptr(st: Pstack_st_OPENSSL_BLOCK; ptr: Pstack_st_OPENSSL_BLOCK): Pstack_st_void; cdecl;
  function Load_sk_OPENSSL_BLOCK_push(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_BLOCK_unshift(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_BLOCK_pop(_para: Pstack_st_OPENSSL_BLOCK): Pstack_st_void; cdecl;
  function Load_sk_OPENSSL_BLOCK_shift(_para: Pstack_st_OPENSSL_BLOCK): Pstack_st_void; cdecl;
  procedure Load_sk_OPENSSL_BLOCK_pop_free(st: Pstack_st_OPENSSL_BLOCK; func: Tsk_OPENSSL_BLOCK_freefunc); cdecl;
  function Load_sk_OPENSSL_BLOCK_insert(st: Pstack_st_OPENSSL_BLOCK; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_BLOCK_set(st: Pstack_st_OPENSSL_BLOCK; i: TOpenSSL_C_INT; data: pointer): Pstack_st_void; cdecl;
  function Load_sk_OPENSSL_BLOCK_find(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_BLOCK_find_ex(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_BLOCK_find_all(st: Pstack_st_OPENSSL_BLOCK; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_BLOCK_sort(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_BLOCK_is_sorted(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl;
  function Load_sk_OPENSSL_BLOCK_dup(st: Pstack_st_OPENSSL_BLOCK): Pstack_st_OPENSSL_BLOCK; cdecl;
  function Load_sk_OPENSSL_BLOCK_deep_copy(st: Pstack_st_OPENSSL_BLOCK; c: Tsk_OPENSSL_BLOCK_compfunc; f: Tsk_OPENSSL_BLOCK_freefunc): Pstack_st_OPENSSL_BLOCK; cdecl;
  function Load_sk_OPENSSL_BLOCK_set_cmp_func(st: Pstack_st_OPENSSL_BLOCK; cmp: Tsk_OPENSSL_BLOCK_compfunc): Tsk_OPENSSL_BLOCK_compfunc; cdecl;

var
  sk_OPENSSL_BLOCK_num: function(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_BLOCK_num;
  sk_OPENSSL_BLOCK_value: function(_para: Pstack_st_OPENSSL_BLOCK; _para2: TOpenSSL_C_INT): Pstack_st_void; cdecl = Load_sk_OPENSSL_BLOCK_value;
  sk_OPENSSL_BLOCK_new: function(cmp: Tsk_OPENSSL_BLOCK_compfunc): Pstack_st_OPENSSL_BLOCK; cdecl = Load_sk_OPENSSL_BLOCK_new;
  sk_OPENSSL_BLOCK_new_null: function: Pstack_st_OPENSSL_BLOCK; cdecl = Load_sk_OPENSSL_BLOCK_new_null;
  sk_OPENSSL_BLOCK_new_reserve: function(cmp: Tsk_OPENSSL_BLOCK_compfunc; n: TOpenSSL_C_INT): Pstack_st_OPENSSL_BLOCK; cdecl = Load_sk_OPENSSL_BLOCK_new_reserve;
  sk_OPENSSL_BLOCK_reserve: function(_para: Pstack_st_OPENSSL_BLOCK; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_BLOCK_reserve;
  sk_OPENSSL_BLOCK_free: function(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_BLOCK_free;
  sk_OPENSSL_BLOCK_zero: function(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_BLOCK_zero;
  sk_OPENSSL_BLOCK_delete: function(st: Pstack_st_OPENSSL_BLOCK; loc: TOpenSSL_C_INT): Pstack_st_void; cdecl = Load_sk_OPENSSL_BLOCK_delete;
  sk_OPENSSL_BLOCK_delete_ptr: function(st: Pstack_st_OPENSSL_BLOCK; ptr: Pstack_st_OPENSSL_BLOCK): Pstack_st_void; cdecl = Load_sk_OPENSSL_BLOCK_delete_ptr;
  sk_OPENSSL_BLOCK_push: function(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_BLOCK_push;
  sk_OPENSSL_BLOCK_unshift: function(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_BLOCK_unshift;
  sk_OPENSSL_BLOCK_pop: function(_para: Pstack_st_OPENSSL_BLOCK): Pstack_st_void; cdecl = Load_sk_OPENSSL_BLOCK_pop;
  sk_OPENSSL_BLOCK_shift: function(_para: Pstack_st_OPENSSL_BLOCK): Pstack_st_void; cdecl = Load_sk_OPENSSL_BLOCK_shift;
  sk_OPENSSL_BLOCK_pop_free: procedure(st: Pstack_st_OPENSSL_BLOCK; func: Tsk_OPENSSL_BLOCK_freefunc); cdecl = Load_sk_OPENSSL_BLOCK_pop_free;
  sk_OPENSSL_BLOCK_insert: function(st: Pstack_st_OPENSSL_BLOCK; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_BLOCK_insert;
  sk_OPENSSL_BLOCK_set: function(st: Pstack_st_OPENSSL_BLOCK; i: TOpenSSL_C_INT; data: pointer): Pstack_st_void; cdecl = Load_sk_OPENSSL_BLOCK_set;
  sk_OPENSSL_BLOCK_find: function(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_BLOCK_find;
  sk_OPENSSL_BLOCK_find_ex: function(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_BLOCK_find_ex;
  sk_OPENSSL_BLOCK_find_all: function(st: Pstack_st_OPENSSL_BLOCK; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_BLOCK_find_all;
  sk_OPENSSL_BLOCK_sort: function(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_BLOCK_sort;
  sk_OPENSSL_BLOCK_is_sorted: function(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl = Load_sk_OPENSSL_BLOCK_is_sorted;
  sk_OPENSSL_BLOCK_dup: function(st: Pstack_st_OPENSSL_BLOCK): Pstack_st_OPENSSL_BLOCK; cdecl = Load_sk_OPENSSL_BLOCK_dup;
  sk_OPENSSL_BLOCK_deep_copy: function(st: Pstack_st_OPENSSL_BLOCK; c: Tsk_OPENSSL_BLOCK_compfunc; f: Tsk_OPENSSL_BLOCK_freefunc): Pstack_st_OPENSSL_BLOCK; cdecl = Load_sk_OPENSSL_BLOCK_deep_copy;
  sk_OPENSSL_BLOCK_set_cmp_func: function(st: Pstack_st_OPENSSL_BLOCK; cmp: Tsk_OPENSSL_BLOCK_compfunc): Tsk_OPENSSL_BLOCK_compfunc; cdecl = Load_sk_OPENSSL_BLOCK_set_cmp_func;
  { clang-format on }
    {$endif} {OPENSSL_STATIC_LINK_MODEL}
  {$endif}
{$endif}

implementation

uses Sysutils, variants
  {$ifdef OPENSSL_INTERNAL_NEED_THREADS}
   {$IFNDEF FPC}
     ,System.SyncObjs
     {$IFDEF POSIX}
       ,Posix.Pthread
     {$ELSE}
       ,Windows
     {$ENDIF}
   {$ELSE}
     ,SyncObjs
   {$ENDIF}
  {$endif}
  ,Classes, OpenSSLExceptionHandlers;

  {$if not declared(__FILE__)}
  const
    {$ifdef FPC}
    __FILE__ = {$include %FILE%};
    {$else}
    __FILE__ = '$(INPUTFILENAME)';
    {$endif}
  {$ifend}
  {$if not declared(__LINE__)}
  const
    __LINE__ = 0;
  {$ifend}
  {$if not declared(OPENSSL_FILE)}
  const
    OPENSSL_FILE = __FILE__;
  {$ifend}
  {$if not declared(OPENSSL_LINE)}
  const
    OPENSSL_LINE  = 0;
  {$ifend}

function ossl_check_OPENSSL_STRING_type(ptr: PAnsiChar): PAnsiChar{Has C Attribute: unused}; inline;
begin
   Result := ptr;
end;

function ossl_check_const_OPENSSL_STRING_sk_type(sk: Pstack_st_OPENSSL_STRING): POPENSSL_STACK{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_STACK(sk);
end;

function ossl_check_OPENSSL_STRING_sk_type(sk: Pstack_st_OPENSSL_STRING): POPENSSL_STACK{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_STACK(sk);
end;

function ossl_check_OPENSSL_STRING_compfunc_type(cmp: Tsk_OPENSSL_STRING_compfunc): TOPENSSL_sk_compfunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_compfunc(cmp);
end;

function ossl_check_OPENSSL_STRING_copyfunc_type(cpy: Tsk_OPENSSL_STRING_copyfunc): TOPENSSL_sk_copyfunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_copyfunc(cpy);
end;

function ossl_check_OPENSSL_STRING_freefunc_type(fr: Tsk_OPENSSL_STRING_freefunc): TOPENSSL_sk_freefunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_freefunc(fr);
end;

function ossl_check_OPENSSL_CSTRING_type(ptr: PAnsiChar): PAnsiChar{Has C Attribute: unused}; inline;
begin
   Result := ptr;
end;

function ossl_check_const_OPENSSL_CSTRING_sk_type(sk: Pstack_st_OPENSSL_CSTRING): POPENSSL_STACK{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_STACK(sk);
end;

function ossl_check_OPENSSL_CSTRING_sk_type(sk: Pstack_st_OPENSSL_CSTRING): POPENSSL_STACK{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_STACK(sk);
end;

function ossl_check_OPENSSL_CSTRING_compfunc_type(cmp: Tsk_OPENSSL_CSTRING_compfunc): TOPENSSL_sk_compfunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_compfunc(cmp);
end;

function ossl_check_OPENSSL_CSTRING_copyfunc_type(cpy: Tsk_OPENSSL_CSTRING_copyfunc): TOPENSSL_sk_copyfunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_copyfunc(cpy);
end;

function ossl_check_OPENSSL_CSTRING_freefunc_type(fr: Tsk_OPENSSL_CSTRING_freefunc): TOPENSSL_sk_freefunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_freefunc(fr);
end;

{$if  not defined(OPENSSL_NO_DEPRECATED_3_0)}
function ossl_check_OPENSSL_BLOCK_type(ptr: pointer): pointer{Has C Attribute: unused}; inline;
begin
   Result := ptr;
end;

function ossl_check_const_OPENSSL_BLOCK_sk_type(sk: Pstack_st_OPENSSL_BLOCK): POPENSSL_STACK{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_STACK(sk);
end;

function ossl_check_OPENSSL_BLOCK_sk_type(sk: Pstack_st_OPENSSL_BLOCK): POPENSSL_STACK{Has C Attribute: unused}; inline;
begin
   Result := POPENSSL_STACK(sk);
end;

function ossl_check_OPENSSL_BLOCK_compfunc_type(cmp: Tsk_OPENSSL_BLOCK_compfunc): TOPENSSL_sk_compfunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_compfunc(cmp);
end;

function ossl_check_OPENSSL_BLOCK_copyfunc_type(cpy: Tsk_OPENSSL_BLOCK_copyfunc): TOPENSSL_sk_copyfunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_copyfunc(cpy);
end;

function ossl_check_OPENSSL_BLOCK_freefunc_type(fr: Tsk_OPENSSL_BLOCK_freefunc): TOPENSSL_sk_freefunc{Has C Attribute: unused}; inline;
begin
   Result := TOPENSSL_sk_freefunc(fr);
end;

{$endif} { not defined(OPENSSL_NO_DEPRECATED_3_0)}
{$ifndef OPENSSL_STATIC_LINK_MODEL}
function Load_sk_OPENSSL_STRING_num(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_STRING_num := LoadLibCryptoFunction('OPENSSL_sk_num');
  if not assigned(sk_OPENSSL_STRING_num) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_num');
  Result := sk_OPENSSL_STRING_num(_para);
end;

function Load_sk_OPENSSL_STRING_value(_para: Pstack_st_OPENSSL_STRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl;
begin
  sk_OPENSSL_STRING_value := LoadLibCryptoFunction('OPENSSL_sk_value');
  if not assigned(sk_OPENSSL_STRING_value) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_value');
  Result := sk_OPENSSL_STRING_value(_para, _para2);
end;

function Load_sk_OPENSSL_STRING_new(cmp: Tsk_OPENSSL_STRING_compfunc): Pstack_st_OPENSSL_STRING; cdecl;
begin
  sk_OPENSSL_STRING_new := LoadLibCryptoFunction('OPENSSL_sk_new');
  if not assigned(sk_OPENSSL_STRING_new) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new');
  Result := sk_OPENSSL_STRING_new(cmp);
end;

function Load_sk_OPENSSL_STRING_new_null: Pstack_st_OPENSSL_STRING; cdecl;
begin
  sk_OPENSSL_STRING_new_null := LoadLibCryptoFunction('OPENSSL_sk_new_null');
  if not assigned(sk_OPENSSL_STRING_new_null) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new_null');
  Result := sk_OPENSSL_STRING_new_null;
end;

function Load_sk_OPENSSL_STRING_new_reserve(cmp: Tsk_OPENSSL_STRING_compfunc; n: TOpenSSL_C_INT): Pstack_st_OPENSSL_STRING; cdecl;
begin
  sk_OPENSSL_STRING_new_reserve := LoadLibCryptoFunction('OPENSSL_sk_new_reserve');
  if not assigned(sk_OPENSSL_STRING_new_reserve) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new_reserve');
  Result := sk_OPENSSL_STRING_new_reserve(cmp, n);
end;

function Load_sk_OPENSSL_STRING_reserve(_para: Pstack_st_OPENSSL_STRING; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_STRING_reserve := LoadLibCryptoFunction('OPENSSL_sk_reserve');
  if not assigned(sk_OPENSSL_STRING_reserve) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_reserve');
  Result := sk_OPENSSL_STRING_reserve(_para, n);
end;

function Load_sk_OPENSSL_STRING_free(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_STRING_free := LoadLibCryptoFunction('OPENSSL_sk_free');
  if not assigned(sk_OPENSSL_STRING_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_free');
  Result := sk_OPENSSL_STRING_free(_para);
end;

function Load_sk_OPENSSL_STRING_zero(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_STRING_zero := LoadLibCryptoFunction('OPENSSL_sk_zero');
  if not assigned(sk_OPENSSL_STRING_zero) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_zero');
  Result := sk_OPENSSL_STRING_zero(_para);
end;

function Load_sk_OPENSSL_STRING_delete(st: Pstack_st_OPENSSL_STRING; loc: TOpenSSL_C_INT): Pstack_st_char; cdecl;
begin
  sk_OPENSSL_STRING_delete := LoadLibCryptoFunction('OPENSSL_sk_delete');
  if not assigned(sk_OPENSSL_STRING_delete) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_delete');
  Result := sk_OPENSSL_STRING_delete(st, loc);
end;

function Load_sk_OPENSSL_STRING_delete_ptr(st: Pstack_st_OPENSSL_STRING; ptr: Pstack_st_OPENSSL_STRING): Pstack_st_char; cdecl;
begin
  sk_OPENSSL_STRING_delete_ptr := LoadLibCryptoFunction('OPENSSL_sk_delete_ptr');
  if not assigned(sk_OPENSSL_STRING_delete_ptr) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_delete_ptr');
  Result := sk_OPENSSL_STRING_delete_ptr(st, ptr);
end;

function Load_sk_OPENSSL_STRING_push(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_STRING_push := LoadLibCryptoFunction('OPENSSL_sk_push');
  if not assigned(sk_OPENSSL_STRING_push) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_push');
  Result := sk_OPENSSL_STRING_push(st, data);
end;

function Load_sk_OPENSSL_STRING_unshift(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_STRING_unshift := LoadLibCryptoFunction('OPENSSL_sk_unshift');
  if not assigned(sk_OPENSSL_STRING_unshift) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_unshift');
  Result := sk_OPENSSL_STRING_unshift(st, data);
end;

function Load_sk_OPENSSL_STRING_pop(_para: Pstack_st_OPENSSL_STRING): Pstack_st_char; cdecl;
begin
  sk_OPENSSL_STRING_pop := LoadLibCryptoFunction('OPENSSL_sk_pop');
  if not assigned(sk_OPENSSL_STRING_pop) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_pop');
  Result := sk_OPENSSL_STRING_pop(_para);
end;

function Load_sk_OPENSSL_STRING_shift(_para: Pstack_st_OPENSSL_STRING): Pstack_st_char; cdecl;
begin
  sk_OPENSSL_STRING_shift := LoadLibCryptoFunction('OPENSSL_sk_shift');
  if not assigned(sk_OPENSSL_STRING_shift) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_shift');
  Result := sk_OPENSSL_STRING_shift(_para);
end;

procedure Load_sk_OPENSSL_STRING_pop_free(st: Pstack_st_OPENSSL_STRING; func: Tsk_OPENSSL_STRING_freefunc); cdecl;
begin
  sk_OPENSSL_STRING_pop_free := LoadLibCryptoFunction('OPENSSL_sk_pop_free');
  if not assigned(sk_OPENSSL_STRING_pop_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_pop_free');
  sk_OPENSSL_STRING_pop_free(st, func);
end;

function Load_sk_OPENSSL_STRING_insert(st: Pstack_st_OPENSSL_STRING; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_STRING_insert := LoadLibCryptoFunction('OPENSSL_sk_insert');
  if not assigned(sk_OPENSSL_STRING_insert) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_insert');
  Result := sk_OPENSSL_STRING_insert(st, data, where);
end;

function Load_sk_OPENSSL_STRING_set(st: Pstack_st_OPENSSL_STRING; i: TOpenSSL_C_INT; data: pointer): Pstack_st_char; cdecl;
begin
  sk_OPENSSL_STRING_set := LoadLibCryptoFunction('OPENSSL_sk_set');
  if not assigned(sk_OPENSSL_STRING_set) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_set');
  Result := sk_OPENSSL_STRING_set(st, i, data);
end;

function Load_sk_OPENSSL_STRING_find(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_STRING_find := LoadLibCryptoFunction('OPENSSL_sk_find');
  if not assigned(sk_OPENSSL_STRING_find) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find');
  Result := sk_OPENSSL_STRING_find(st, data);
end;

function Load_sk_OPENSSL_STRING_find_ex(st: Pstack_st_OPENSSL_STRING; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_STRING_find_ex := LoadLibCryptoFunction('OPENSSL_sk_find_ex');
  if not assigned(sk_OPENSSL_STRING_find_ex) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find_ex');
  Result := sk_OPENSSL_STRING_find_ex(st, data);
end;

function Load_sk_OPENSSL_STRING_find_all(st: Pstack_st_OPENSSL_STRING; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_STRING_find_all := LoadLibCryptoFunction('OPENSSL_sk_find_all');
  if not assigned(sk_OPENSSL_STRING_find_all) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find_all');
  Result := sk_OPENSSL_STRING_find_all(st, data, pnum);
end;

function Load_sk_OPENSSL_STRING_sort(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_STRING_sort := LoadLibCryptoFunction('OPENSSL_sk_sort');
  if not assigned(sk_OPENSSL_STRING_sort) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_sort');
  Result := sk_OPENSSL_STRING_sort(_para);
end;

function Load_sk_OPENSSL_STRING_is_sorted(_para: Pstack_st_OPENSSL_STRING): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_STRING_is_sorted := LoadLibCryptoFunction('OPENSSL_sk_is_sorted');
  if not assigned(sk_OPENSSL_STRING_is_sorted) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_is_sorted');
  Result := sk_OPENSSL_STRING_is_sorted(_para);
end;

function Load_sk_OPENSSL_STRING_dup(st: Pstack_st_OPENSSL_STRING): Pstack_st_OPENSSL_STRING; cdecl;
begin
  sk_OPENSSL_STRING_dup := LoadLibCryptoFunction('OPENSSL_sk_dup');
  if not assigned(sk_OPENSSL_STRING_dup) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_dup');
  Result := sk_OPENSSL_STRING_dup(st);
end;

function Load_sk_OPENSSL_STRING_deep_copy(st: Pstack_st_OPENSSL_STRING; c: Tsk_OPENSSL_STRING_compfunc; f: Tsk_OPENSSL_STRING_freefunc): Pstack_st_OPENSSL_STRING; cdecl;
begin
  sk_OPENSSL_STRING_deep_copy := LoadLibCryptoFunction('OPENSSL_sk_deep_copy');
  if not assigned(sk_OPENSSL_STRING_deep_copy) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_deep_copy');
  Result := sk_OPENSSL_STRING_deep_copy(st, c, f);
end;

function Load_sk_OPENSSL_STRING_set_cmp_func(st: Pstack_st_OPENSSL_STRING; cmp: Tsk_OPENSSL_STRING_compfunc): Tsk_OPENSSL_STRING_compfunc; cdecl;
begin
  sk_OPENSSL_STRING_set_cmp_func := LoadLibCryptoFunction('OPENSSL_sk_set_cmp_func');
  if not assigned(sk_OPENSSL_STRING_set_cmp_func) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_set_cmp_func');
  Result := sk_OPENSSL_STRING_set_cmp_func(st, cmp);
end;

function Load_sk_OPENSSL_CSTRING_num(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_CSTRING_num := LoadLibCryptoFunction('OPENSSL_sk_num');
  if not assigned(sk_OPENSSL_CSTRING_num) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_num');
  Result := sk_OPENSSL_CSTRING_num(_para);
end;

function Load_sk_OPENSSL_CSTRING_value(_para: Pstack_st_OPENSSL_CSTRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl;
begin
  sk_OPENSSL_CSTRING_value := LoadLibCryptoFunction('OPENSSL_sk_value');
  if not assigned(sk_OPENSSL_CSTRING_value) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_value');
  Result := sk_OPENSSL_CSTRING_value(_para, _para2);
end;

function Load_sk_OPENSSL_CSTRING_new(cmp: Tsk_OPENSSL_CSTRING_compfunc): Pstack_st_OPENSSL_CSTRING; cdecl;
begin
  sk_OPENSSL_CSTRING_new := LoadLibCryptoFunction('OPENSSL_sk_new');
  if not assigned(sk_OPENSSL_CSTRING_new) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new');
  Result := sk_OPENSSL_CSTRING_new(cmp);
end;

function Load_sk_OPENSSL_CSTRING_new_null: Pstack_st_OPENSSL_CSTRING; cdecl;
begin
  sk_OPENSSL_CSTRING_new_null := LoadLibCryptoFunction('OPENSSL_sk_new_null');
  if not assigned(sk_OPENSSL_CSTRING_new_null) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new_null');
  Result := sk_OPENSSL_CSTRING_new_null;
end;

function Load_sk_OPENSSL_CSTRING_new_reserve(cmp: Tsk_OPENSSL_CSTRING_compfunc; n: TOpenSSL_C_INT): Pstack_st_OPENSSL_CSTRING; cdecl;
begin
  sk_OPENSSL_CSTRING_new_reserve := LoadLibCryptoFunction('OPENSSL_sk_new_reserve');
  if not assigned(sk_OPENSSL_CSTRING_new_reserve) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new_reserve');
  Result := sk_OPENSSL_CSTRING_new_reserve(cmp, n);
end;

function Load_sk_OPENSSL_CSTRING_reserve(_para: Pstack_st_OPENSSL_CSTRING; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_CSTRING_reserve := LoadLibCryptoFunction('OPENSSL_sk_reserve');
  if not assigned(sk_OPENSSL_CSTRING_reserve) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_reserve');
  Result := sk_OPENSSL_CSTRING_reserve(_para, n);
end;

function Load_sk_OPENSSL_CSTRING_free(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_CSTRING_free := LoadLibCryptoFunction('OPENSSL_sk_free');
  if not assigned(sk_OPENSSL_CSTRING_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_free');
  Result := sk_OPENSSL_CSTRING_free(_para);
end;

function Load_sk_OPENSSL_CSTRING_zero(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_CSTRING_zero := LoadLibCryptoFunction('OPENSSL_sk_zero');
  if not assigned(sk_OPENSSL_CSTRING_zero) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_zero');
  Result := sk_OPENSSL_CSTRING_zero(_para);
end;

function Load_sk_OPENSSL_CSTRING_delete(_para: Pstack_st_OPENSSL_CSTRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl;
begin
  sk_OPENSSL_CSTRING_delete := LoadLibCryptoFunction('OPENSSL_sk_delete');
  if not assigned(sk_OPENSSL_CSTRING_delete) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_delete');
  Result := sk_OPENSSL_CSTRING_delete(_para, _para2);
end;

function Load_sk_OPENSSL_CSTRING_delete_ptr(_para: Pstack_st_OPENSSL_CSTRING; _para2: TOpenSSL_C_INT): Pstack_st_char; cdecl;
begin
  sk_OPENSSL_CSTRING_delete_ptr := LoadLibCryptoFunction('OPENSSL_sk_delete_ptr');
  if not assigned(sk_OPENSSL_CSTRING_delete_ptr) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_delete_ptr');
  Result := sk_OPENSSL_CSTRING_delete_ptr(_para, _para2);
end;

function Load_sk_OPENSSL_CSTRING_push(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_CSTRING_push := LoadLibCryptoFunction('OPENSSL_sk_push');
  if not assigned(sk_OPENSSL_CSTRING_push) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_push');
  Result := sk_OPENSSL_CSTRING_push(st, data);
end;

function Load_sk_OPENSSL_CSTRING_unshift(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_CSTRING_unshift := LoadLibCryptoFunction('OPENSSL_sk_unshift');
  if not assigned(sk_OPENSSL_CSTRING_unshift) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_unshift');
  Result := sk_OPENSSL_CSTRING_unshift(st, data);
end;

function Load_sk_OPENSSL_CSTRING_pop(_para: Pstack_st_OPENSSL_CSTRING): Pstack_st_char; cdecl;
begin
  sk_OPENSSL_CSTRING_pop := LoadLibCryptoFunction('OPENSSL_sk_pop');
  if not assigned(sk_OPENSSL_CSTRING_pop) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_pop');
  Result := sk_OPENSSL_CSTRING_pop(_para);
end;

function Load_sk_OPENSSL_CSTRING_shift(_para: Pstack_st_OPENSSL_CSTRING): Pstack_st_char; cdecl;
begin
  sk_OPENSSL_CSTRING_shift := LoadLibCryptoFunction('OPENSSL_sk_shift');
  if not assigned(sk_OPENSSL_CSTRING_shift) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_shift');
  Result := sk_OPENSSL_CSTRING_shift(_para);
end;

procedure Load_sk_OPENSSL_CSTRING_pop_free(st: Pstack_st_OPENSSL_CSTRING; func: Tsk_OPENSSL_CSTRING_freefunc); cdecl;
begin
  sk_OPENSSL_CSTRING_pop_free := LoadLibCryptoFunction('OPENSSL_sk_pop_free');
  if not assigned(sk_OPENSSL_CSTRING_pop_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_pop_free');
  sk_OPENSSL_CSTRING_pop_free(st, func);
end;

function Load_sk_OPENSSL_CSTRING_insert(st: Pstack_st_OPENSSL_CSTRING; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_CSTRING_insert := LoadLibCryptoFunction('OPENSSL_sk_insert');
  if not assigned(sk_OPENSSL_CSTRING_insert) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_insert');
  Result := sk_OPENSSL_CSTRING_insert(st, data, where);
end;

function Load_sk_OPENSSL_CSTRING_set(st: Pstack_st_OPENSSL_CSTRING; i: TOpenSSL_C_INT; data: pointer): Pstack_st_char; cdecl;
begin
  sk_OPENSSL_CSTRING_set := LoadLibCryptoFunction('OPENSSL_sk_set');
  if not assigned(sk_OPENSSL_CSTRING_set) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_set');
  Result := sk_OPENSSL_CSTRING_set(st, i, data);
end;

function Load_sk_OPENSSL_CSTRING_find(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_CSTRING_find := LoadLibCryptoFunction('OPENSSL_sk_find');
  if not assigned(sk_OPENSSL_CSTRING_find) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find');
  Result := sk_OPENSSL_CSTRING_find(st, data);
end;

function Load_sk_OPENSSL_CSTRING_find_ex(st: Pstack_st_OPENSSL_CSTRING; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_CSTRING_find_ex := LoadLibCryptoFunction('OPENSSL_sk_find_ex');
  if not assigned(sk_OPENSSL_CSTRING_find_ex) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find_ex');
  Result := sk_OPENSSL_CSTRING_find_ex(st, data);
end;

function Load_sk_OPENSSL_CSTRING_find_all(st: Pstack_st_OPENSSL_CSTRING; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_CSTRING_find_all := LoadLibCryptoFunction('OPENSSL_sk_find_all');
  if not assigned(sk_OPENSSL_CSTRING_find_all) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find_all');
  Result := sk_OPENSSL_CSTRING_find_all(st, data, pnum);
end;

function Load_sk_OPENSSL_CSTRING_sort(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_CSTRING_sort := LoadLibCryptoFunction('OPENSSL_sk_sort');
  if not assigned(sk_OPENSSL_CSTRING_sort) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_sort');
  Result := sk_OPENSSL_CSTRING_sort(_para);
end;

function Load_sk_OPENSSL_CSTRING_is_sorted(_para: Pstack_st_OPENSSL_CSTRING): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_CSTRING_is_sorted := LoadLibCryptoFunction('OPENSSL_sk_is_sorted');
  if not assigned(sk_OPENSSL_CSTRING_is_sorted) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_is_sorted');
  Result := sk_OPENSSL_CSTRING_is_sorted(_para);
end;

function Load_sk_OPENSSL_CSTRING_dup(st: Pstack_st_OPENSSL_CSTRING): Pstack_st_OPENSSL_CSTRING; cdecl;
begin
  sk_OPENSSL_CSTRING_dup := LoadLibCryptoFunction('OPENSSL_sk_dup');
  if not assigned(sk_OPENSSL_CSTRING_dup) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_dup');
  Result := sk_OPENSSL_CSTRING_dup(st);
end;

function Load_sk_OPENSSL_CSTRING_deep_copy(st: Pstack_st_OPENSSL_CSTRING; c: Tsk_OPENSSL_CSTRING_compfunc; f: Tsk_OPENSSL_CSTRING_freefunc): Pstack_st_OPENSSL_CSTRING; cdecl;
begin
  sk_OPENSSL_CSTRING_deep_copy := LoadLibCryptoFunction('OPENSSL_sk_deep_copy');
  if not assigned(sk_OPENSSL_CSTRING_deep_copy) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_deep_copy');
  Result := sk_OPENSSL_CSTRING_deep_copy(st, c, f);
end;

function Load_sk_OPENSSL_CSTRING_set_cmp_func(st: Pstack_st_OPENSSL_CSTRING; cmp: Tsk_OPENSSL_CSTRING_compfunc): Tsk_OPENSSL_CSTRING_compfunc; cdecl;
begin
  sk_OPENSSL_CSTRING_set_cmp_func := LoadLibCryptoFunction('OPENSSL_sk_set_cmp_func');
  if not assigned(sk_OPENSSL_CSTRING_set_cmp_func) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_set_cmp_func');
  Result := sk_OPENSSL_CSTRING_set_cmp_func(st, cmp);
end;

{$if  not defined(OPENSSL_NO_DEPRECATED_3_0)}
function Load_sk_OPENSSL_BLOCK_num(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_BLOCK_num := LoadLibCryptoFunction('OPENSSL_sk_num');
  if not assigned(sk_OPENSSL_BLOCK_num) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_num');
  Result := sk_OPENSSL_BLOCK_num(_para);
end;

function Load_sk_OPENSSL_BLOCK_value(_para: Pstack_st_OPENSSL_BLOCK; _para2: TOpenSSL_C_INT): Pstack_st_void; cdecl;
begin
  sk_OPENSSL_BLOCK_value := LoadLibCryptoFunction('OPENSSL_sk_value');
  if not assigned(sk_OPENSSL_BLOCK_value) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_value');
  Result := sk_OPENSSL_BLOCK_value(_para, _para2);
end;

function Load_sk_OPENSSL_BLOCK_new(cmp: Tsk_OPENSSL_BLOCK_compfunc): Pstack_st_OPENSSL_BLOCK; cdecl;
begin
  sk_OPENSSL_BLOCK_new := LoadLibCryptoFunction('OPENSSL_sk_new');
  if not assigned(sk_OPENSSL_BLOCK_new) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new');
  Result := sk_OPENSSL_BLOCK_new(cmp);
end;

function Load_sk_OPENSSL_BLOCK_new_null: Pstack_st_OPENSSL_BLOCK; cdecl;
begin
  sk_OPENSSL_BLOCK_new_null := LoadLibCryptoFunction('OPENSSL_sk_new_null');
  if not assigned(sk_OPENSSL_BLOCK_new_null) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new_null');
  Result := sk_OPENSSL_BLOCK_new_null;
end;

function Load_sk_OPENSSL_BLOCK_new_reserve(cmp: Tsk_OPENSSL_BLOCK_compfunc; n: TOpenSSL_C_INT): Pstack_st_OPENSSL_BLOCK; cdecl;
begin
  sk_OPENSSL_BLOCK_new_reserve := LoadLibCryptoFunction('OPENSSL_sk_new_reserve');
  if not assigned(sk_OPENSSL_BLOCK_new_reserve) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_new_reserve');
  Result := sk_OPENSSL_BLOCK_new_reserve(cmp, n);
end;

function Load_sk_OPENSSL_BLOCK_reserve(_para: Pstack_st_OPENSSL_BLOCK; n: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_BLOCK_reserve := LoadLibCryptoFunction('OPENSSL_sk_reserve');
  if not assigned(sk_OPENSSL_BLOCK_reserve) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_reserve');
  Result := sk_OPENSSL_BLOCK_reserve(_para, n);
end;

function Load_sk_OPENSSL_BLOCK_free(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_BLOCK_free := LoadLibCryptoFunction('OPENSSL_sk_free');
  if not assigned(sk_OPENSSL_BLOCK_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_free');
  Result := sk_OPENSSL_BLOCK_free(_para);
end;

function Load_sk_OPENSSL_BLOCK_zero(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_BLOCK_zero := LoadLibCryptoFunction('OPENSSL_sk_zero');
  if not assigned(sk_OPENSSL_BLOCK_zero) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_zero');
  Result := sk_OPENSSL_BLOCK_zero(_para);
end;

function Load_sk_OPENSSL_BLOCK_delete(st: Pstack_st_OPENSSL_BLOCK; loc: TOpenSSL_C_INT): Pstack_st_void; cdecl;
begin
  sk_OPENSSL_BLOCK_delete := LoadLibCryptoFunction('OPENSSL_sk_delete');
  if not assigned(sk_OPENSSL_BLOCK_delete) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_delete');
  Result := sk_OPENSSL_BLOCK_delete(st, loc);
end;

function Load_sk_OPENSSL_BLOCK_delete_ptr(st: Pstack_st_OPENSSL_BLOCK; ptr: Pstack_st_OPENSSL_BLOCK): Pstack_st_void; cdecl;
begin
  sk_OPENSSL_BLOCK_delete_ptr := LoadLibCryptoFunction('OPENSSL_sk_delete_ptr');
  if not assigned(sk_OPENSSL_BLOCK_delete_ptr) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_delete_ptr');
  Result := sk_OPENSSL_BLOCK_delete_ptr(st, ptr);
end;

function Load_sk_OPENSSL_BLOCK_push(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_BLOCK_push := LoadLibCryptoFunction('OPENSSL_sk_push');
  if not assigned(sk_OPENSSL_BLOCK_push) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_push');
  Result := sk_OPENSSL_BLOCK_push(st, data);
end;

function Load_sk_OPENSSL_BLOCK_unshift(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_BLOCK_unshift := LoadLibCryptoFunction('OPENSSL_sk_unshift');
  if not assigned(sk_OPENSSL_BLOCK_unshift) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_unshift');
  Result := sk_OPENSSL_BLOCK_unshift(st, data);
end;

function Load_sk_OPENSSL_BLOCK_pop(_para: Pstack_st_OPENSSL_BLOCK): Pstack_st_void; cdecl;
begin
  sk_OPENSSL_BLOCK_pop := LoadLibCryptoFunction('OPENSSL_sk_pop');
  if not assigned(sk_OPENSSL_BLOCK_pop) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_pop');
  Result := sk_OPENSSL_BLOCK_pop(_para);
end;

function Load_sk_OPENSSL_BLOCK_shift(_para: Pstack_st_OPENSSL_BLOCK): Pstack_st_void; cdecl;
begin
  sk_OPENSSL_BLOCK_shift := LoadLibCryptoFunction('OPENSSL_sk_shift');
  if not assigned(sk_OPENSSL_BLOCK_shift) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_shift');
  Result := sk_OPENSSL_BLOCK_shift(_para);
end;

procedure Load_sk_OPENSSL_BLOCK_pop_free(st: Pstack_st_OPENSSL_BLOCK; func: Tsk_OPENSSL_BLOCK_freefunc); cdecl;
begin
  sk_OPENSSL_BLOCK_pop_free := LoadLibCryptoFunction('OPENSSL_sk_pop_free');
  if not assigned(sk_OPENSSL_BLOCK_pop_free) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_pop_free');
  sk_OPENSSL_BLOCK_pop_free(st, func);
end;

function Load_sk_OPENSSL_BLOCK_insert(st: Pstack_st_OPENSSL_BLOCK; data: pointer; where: TOpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_BLOCK_insert := LoadLibCryptoFunction('OPENSSL_sk_insert');
  if not assigned(sk_OPENSSL_BLOCK_insert) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_insert');
  Result := sk_OPENSSL_BLOCK_insert(st, data, where);
end;

function Load_sk_OPENSSL_BLOCK_set(st: Pstack_st_OPENSSL_BLOCK; i: TOpenSSL_C_INT; data: pointer): Pstack_st_void; cdecl;
begin
  sk_OPENSSL_BLOCK_set := LoadLibCryptoFunction('OPENSSL_sk_set');
  if not assigned(sk_OPENSSL_BLOCK_set) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_set');
  Result := sk_OPENSSL_BLOCK_set(st, i, data);
end;

function Load_sk_OPENSSL_BLOCK_find(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_BLOCK_find := LoadLibCryptoFunction('OPENSSL_sk_find');
  if not assigned(sk_OPENSSL_BLOCK_find) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find');
  Result := sk_OPENSSL_BLOCK_find(st, data);
end;

function Load_sk_OPENSSL_BLOCK_find_ex(st: Pstack_st_OPENSSL_BLOCK; data: pointer): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_BLOCK_find_ex := LoadLibCryptoFunction('OPENSSL_sk_find_ex');
  if not assigned(sk_OPENSSL_BLOCK_find_ex) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find_ex');
  Result := sk_OPENSSL_BLOCK_find_ex(st, data);
end;

function Load_sk_OPENSSL_BLOCK_find_all(st: Pstack_st_OPENSSL_BLOCK; data: pointer; pnum: POpenSSL_C_INT): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_BLOCK_find_all := LoadLibCryptoFunction('OPENSSL_sk_find_all');
  if not assigned(sk_OPENSSL_BLOCK_find_all) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_find_all');
  Result := sk_OPENSSL_BLOCK_find_all(st, data, pnum);
end;

function Load_sk_OPENSSL_BLOCK_sort(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_BLOCK_sort := LoadLibCryptoFunction('OPENSSL_sk_sort');
  if not assigned(sk_OPENSSL_BLOCK_sort) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_sort');
  Result := sk_OPENSSL_BLOCK_sort(_para);
end;

function Load_sk_OPENSSL_BLOCK_is_sorted(_para: Pstack_st_OPENSSL_BLOCK): TOpenSSL_C_INT; cdecl;
begin
  sk_OPENSSL_BLOCK_is_sorted := LoadLibCryptoFunction('OPENSSL_sk_is_sorted');
  if not assigned(sk_OPENSSL_BLOCK_is_sorted) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_is_sorted');
  Result := sk_OPENSSL_BLOCK_is_sorted(_para);
end;

function Load_sk_OPENSSL_BLOCK_dup(st: Pstack_st_OPENSSL_BLOCK): Pstack_st_OPENSSL_BLOCK; cdecl;
begin
  sk_OPENSSL_BLOCK_dup := LoadLibCryptoFunction('OPENSSL_sk_dup');
  if not assigned(sk_OPENSSL_BLOCK_dup) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_dup');
  Result := sk_OPENSSL_BLOCK_dup(st);
end;

function Load_sk_OPENSSL_BLOCK_deep_copy(st: Pstack_st_OPENSSL_BLOCK; c: Tsk_OPENSSL_BLOCK_compfunc; f: Tsk_OPENSSL_BLOCK_freefunc): Pstack_st_OPENSSL_BLOCK; cdecl;
begin
  sk_OPENSSL_BLOCK_deep_copy := LoadLibCryptoFunction('OPENSSL_sk_deep_copy');
  if not assigned(sk_OPENSSL_BLOCK_deep_copy) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_deep_copy');
  Result := sk_OPENSSL_BLOCK_deep_copy(st, c, f);
end;

function Load_sk_OPENSSL_BLOCK_set_cmp_func(st: Pstack_st_OPENSSL_BLOCK; cmp: Tsk_OPENSSL_BLOCK_compfunc): Tsk_OPENSSL_BLOCK_compfunc; cdecl;
begin
  sk_OPENSSL_BLOCK_set_cmp_func := LoadLibCryptoFunction('OPENSSL_sk_set_cmp_func');
  if not assigned(sk_OPENSSL_BLOCK_set_cmp_func) then
    EOpenSSLAPIFunctionNotPresent.RaiseException('OPENSSL_sk_set_cmp_func');
  Result := sk_OPENSSL_BLOCK_set_cmp_func(st, cmp);
end;

{$endif} { not defined(OPENSSL_NO_DEPRECATED_3_0)}
procedure Load;
begin
  {$define EMPTY_LOAD_FUNCTION}
end;

procedure Unload;
begin
  sk_OPENSSL_STRING_num := Load_sk_OPENSSL_STRING_num;
  sk_OPENSSL_STRING_value := Load_sk_OPENSSL_STRING_value;
  sk_OPENSSL_STRING_new := Load_sk_OPENSSL_STRING_new;
  sk_OPENSSL_STRING_new_null := Load_sk_OPENSSL_STRING_new_null;
  sk_OPENSSL_STRING_new_reserve := Load_sk_OPENSSL_STRING_new_reserve;
  sk_OPENSSL_STRING_reserve := Load_sk_OPENSSL_STRING_reserve;
  sk_OPENSSL_STRING_free := Load_sk_OPENSSL_STRING_free;
  sk_OPENSSL_STRING_zero := Load_sk_OPENSSL_STRING_zero;
  sk_OPENSSL_STRING_delete := Load_sk_OPENSSL_STRING_delete;
  sk_OPENSSL_STRING_delete_ptr := Load_sk_OPENSSL_STRING_delete_ptr;
  sk_OPENSSL_STRING_push := Load_sk_OPENSSL_STRING_push;
  sk_OPENSSL_STRING_unshift := Load_sk_OPENSSL_STRING_unshift;
  sk_OPENSSL_STRING_pop := Load_sk_OPENSSL_STRING_pop;
  sk_OPENSSL_STRING_shift := Load_sk_OPENSSL_STRING_shift;
  sk_OPENSSL_STRING_pop_free := Load_sk_OPENSSL_STRING_pop_free;
  sk_OPENSSL_STRING_insert := Load_sk_OPENSSL_STRING_insert;
  sk_OPENSSL_STRING_set := Load_sk_OPENSSL_STRING_set;
  sk_OPENSSL_STRING_find := Load_sk_OPENSSL_STRING_find;
  sk_OPENSSL_STRING_find_ex := Load_sk_OPENSSL_STRING_find_ex;
  sk_OPENSSL_STRING_find_all := Load_sk_OPENSSL_STRING_find_all;
  sk_OPENSSL_STRING_sort := Load_sk_OPENSSL_STRING_sort;
  sk_OPENSSL_STRING_is_sorted := Load_sk_OPENSSL_STRING_is_sorted;
  sk_OPENSSL_STRING_dup := Load_sk_OPENSSL_STRING_dup;
  sk_OPENSSL_STRING_deep_copy := Load_sk_OPENSSL_STRING_deep_copy;
  sk_OPENSSL_STRING_set_cmp_func := Load_sk_OPENSSL_STRING_set_cmp_func;
  sk_OPENSSL_CSTRING_num := Load_sk_OPENSSL_CSTRING_num;
  sk_OPENSSL_CSTRING_value := Load_sk_OPENSSL_CSTRING_value;
  sk_OPENSSL_CSTRING_new := Load_sk_OPENSSL_CSTRING_new;
  sk_OPENSSL_CSTRING_new_null := Load_sk_OPENSSL_CSTRING_new_null;
  sk_OPENSSL_CSTRING_new_reserve := Load_sk_OPENSSL_CSTRING_new_reserve;
  sk_OPENSSL_CSTRING_reserve := Load_sk_OPENSSL_CSTRING_reserve;
  sk_OPENSSL_CSTRING_free := Load_sk_OPENSSL_CSTRING_free;
  sk_OPENSSL_CSTRING_zero := Load_sk_OPENSSL_CSTRING_zero;
  sk_OPENSSL_CSTRING_delete := Load_sk_OPENSSL_CSTRING_delete;
  sk_OPENSSL_CSTRING_delete_ptr := Load_sk_OPENSSL_CSTRING_delete_ptr;
  sk_OPENSSL_CSTRING_push := Load_sk_OPENSSL_CSTRING_push;
  sk_OPENSSL_CSTRING_unshift := Load_sk_OPENSSL_CSTRING_unshift;
  sk_OPENSSL_CSTRING_pop := Load_sk_OPENSSL_CSTRING_pop;
  sk_OPENSSL_CSTRING_shift := Load_sk_OPENSSL_CSTRING_shift;
  sk_OPENSSL_CSTRING_pop_free := Load_sk_OPENSSL_CSTRING_pop_free;
  sk_OPENSSL_CSTRING_insert := Load_sk_OPENSSL_CSTRING_insert;
  sk_OPENSSL_CSTRING_set := Load_sk_OPENSSL_CSTRING_set;
  sk_OPENSSL_CSTRING_find := Load_sk_OPENSSL_CSTRING_find;
  sk_OPENSSL_CSTRING_find_ex := Load_sk_OPENSSL_CSTRING_find_ex;
  sk_OPENSSL_CSTRING_find_all := Load_sk_OPENSSL_CSTRING_find_all;
  sk_OPENSSL_CSTRING_sort := Load_sk_OPENSSL_CSTRING_sort;
  sk_OPENSSL_CSTRING_is_sorted := Load_sk_OPENSSL_CSTRING_is_sorted;
  sk_OPENSSL_CSTRING_dup := Load_sk_OPENSSL_CSTRING_dup;
  sk_OPENSSL_CSTRING_deep_copy := Load_sk_OPENSSL_CSTRING_deep_copy;
  sk_OPENSSL_CSTRING_set_cmp_func := Load_sk_OPENSSL_CSTRING_set_cmp_func;
{$if  not defined(OPENSSL_NO_DEPRECATED_3_0)}
  sk_OPENSSL_BLOCK_num := Load_sk_OPENSSL_BLOCK_num;
  sk_OPENSSL_BLOCK_value := Load_sk_OPENSSL_BLOCK_value;
  sk_OPENSSL_BLOCK_new := Load_sk_OPENSSL_BLOCK_new;
  sk_OPENSSL_BLOCK_new_null := Load_sk_OPENSSL_BLOCK_new_null;
  sk_OPENSSL_BLOCK_new_reserve := Load_sk_OPENSSL_BLOCK_new_reserve;
  sk_OPENSSL_BLOCK_reserve := Load_sk_OPENSSL_BLOCK_reserve;
  sk_OPENSSL_BLOCK_free := Load_sk_OPENSSL_BLOCK_free;
  sk_OPENSSL_BLOCK_zero := Load_sk_OPENSSL_BLOCK_zero;
  sk_OPENSSL_BLOCK_delete := Load_sk_OPENSSL_BLOCK_delete;
  sk_OPENSSL_BLOCK_delete_ptr := Load_sk_OPENSSL_BLOCK_delete_ptr;
  sk_OPENSSL_BLOCK_push := Load_sk_OPENSSL_BLOCK_push;
  sk_OPENSSL_BLOCK_unshift := Load_sk_OPENSSL_BLOCK_unshift;
  sk_OPENSSL_BLOCK_pop := Load_sk_OPENSSL_BLOCK_pop;
  sk_OPENSSL_BLOCK_shift := Load_sk_OPENSSL_BLOCK_shift;
  sk_OPENSSL_BLOCK_pop_free := Load_sk_OPENSSL_BLOCK_pop_free;
  sk_OPENSSL_BLOCK_insert := Load_sk_OPENSSL_BLOCK_insert;
  sk_OPENSSL_BLOCK_set := Load_sk_OPENSSL_BLOCK_set;
  sk_OPENSSL_BLOCK_find := Load_sk_OPENSSL_BLOCK_find;
  sk_OPENSSL_BLOCK_find_ex := Load_sk_OPENSSL_BLOCK_find_ex;
  sk_OPENSSL_BLOCK_find_all := Load_sk_OPENSSL_BLOCK_find_all;
  sk_OPENSSL_BLOCK_sort := Load_sk_OPENSSL_BLOCK_sort;
  sk_OPENSSL_BLOCK_is_sorted := Load_sk_OPENSSL_BLOCK_is_sorted;
  sk_OPENSSL_BLOCK_dup := Load_sk_OPENSSL_BLOCK_dup;
  sk_OPENSSL_BLOCK_deep_copy := Load_sk_OPENSSL_BLOCK_deep_copy;
  sk_OPENSSL_BLOCK_set_cmp_func := Load_sk_OPENSSL_BLOCK_set_cmp_func;
{$endif} { not defined(OPENSSL_NO_DEPRECATED_3_0)}
end;

{$endif} {OPENSSL_STATIC_LINK_MODEL}

initialization

{$ifndef OPENSSL_STATIC_LINK_MODEL}
{$ifndef EMPTY_LOAD_FUNCTION}
Register_SSLloader(@Load);
{$endif}
Register_SSLUnloader(@Unload);
{$endif}
{$if declared(LegacySupport_Initialization)}
LegacySupport_Initialization;
{$ifend}

finalization

{$if declared(LegacySupport_Finalization)}
LegacySupport_Finalization;
{$ifend}

end.



